#!/usr/bin/env bash
# convert.sh: how root/cert-manager.tf was made, and how to remake it.
#
# The estate is named `reference-` and not `corpus-` because cert-manager
# ships YAML, not Terraform: the bundle is theirs, the conversion is
# mechanical, and the root is ours (#1174). Everything that makes the root
# ours is in this file or in root/custom-resources.tf; nothing here is
# hand-edited output.
#
# Provenance, all four facts re-verified on 2026-09-16 before this file was
# written and asserted below rather than trusted:
#
#   source   https://github.com/cert-manager/cert-manager/releases/download/v1.21.2/cert-manager.yaml
#   tag      v1.21.2, published 2026-09-11
#   size     1,034,400 bytes
#   sha256   e03b668ec8675214af6b0a671699d088f2601fa3878e0dbe1b41d3feafd1879f
#   licence  Apache-2.0. The bundle's own first line is
#            "# Copyright 2022 The cert-manager Authors." followed by the
#            Apache-2.0 grant, so the copied artifact carries its own
#            licence header; tfk8s drops comments, which is why
#            root/cert-manager.tf carries the same notice re-stated at the
#            top by this script.
#   tool     tfk8s v0.1.10 (go install github.com/jrhouston/tfk8s@v0.1.10)
#
# Needs network and tfk8s. The run script does NOT call this: root/ is
# committed, so a run is offline and reproducible, and this file exists so
# that "converted mechanically" is a claim someone can check rather than
# one they have to take.
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
URL="https://github.com/cert-manager/cert-manager/releases/download/v1.21.2/cert-manager.yaml"
WANT_SHA="e03b668ec8675214af6b0a671699d088f2601fa3878e0dbe1b41d3feafd1879f"
WANT_BYTES=1034400
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

command -v tfk8s >/dev/null 2>&1 || { echo "convert.sh: tfk8s is not on PATH (go install github.com/jrhouston/tfk8s@v0.1.10)" >&2; exit 1; }

echo "fetching $URL"
curl -fsSL -o "$WORK/cert-manager.yaml" "$URL" || { echo "convert.sh: fetch failed" >&2; exit 1; }

got_sha="$(shasum -a 256 "$WORK/cert-manager.yaml" | awk '{print $1}')"
got_bytes="$(wc -c < "$WORK/cert-manager.yaml" | tr -d ' ')"
[ "$got_sha" = "$WANT_SHA" ] || { echo "convert.sh: sha256 is $got_sha, want $WANT_SHA - the release artifact moved, which is a fact worth an issue, not a pin to update quietly" >&2; exit 1; }
[ "$got_bytes" = "$WANT_BYTES" ] || { echo "convert.sh: $got_bytes bytes, want $WANT_BYTES" >&2; exit 1; }
echo "  $got_bytes bytes, sha256 $got_sha - matches the pin"

# tfk8s turns each YAML document into one kubernetes_manifest block and
# drops every comment, licence header included.
tfk8s -f "$WORK/cert-manager.yaml" -o "$WORK/cert-manager.tf" || { echo "convert.sh: tfk8s failed" >&2; exit 1; }
n="$(grep -c '^resource "kubernetes_manifest"' "$WORK/cert-manager.tf")"
[ "$n" = "47" ] || { echo "convert.sh: the conversion produced $n blocks, want 47" >&2; exit 1; }

# ...and emits no dependencies at all, so the converted bundle races its own
# Namespace: measured on kind, 46 of 47 objects apply and the 47th fails
# "NotFound namespaces [cert-manager]". order.py restores exactly that
# dependency and nothing else. It is a property of the CONVERTED ROOT and
# is deliberately NOT solved with #1173's pre-apply mechanism, which is
# about the CRD/webhook ordering the pre-apply exists for.
python3 "$HERE/order.py" "$WORK/cert-manager.tf" || exit 1

{
  cat <<'HDR'
# Copyright 2022 The cert-manager Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# ---------------------------------------------------------------------
# GENERATED by live/e2e/reference-k8s-cert-manager/convert.sh from
# cert-manager v1.21.2's own install bundle (cert-manager.yaml at the
# release, 1,034,400 bytes, sha256
# e03b668ec8675214af6b0a671699d088f2601fa3878e0dbe1b41d3feafd1879f) with
# tfk8s v0.1.10, then order.py for the one dependency tfk8s drops. Do not
# hand-edit: rerun convert.sh. The licence notice above is the bundle's
# own, restated here because tfk8s does not carry comments across.
# ---------------------------------------------------------------------
HDR
  cat "$WORK/cert-manager.tf"
} > "$HERE/root/cert-manager.tf"

echo "wrote $HERE/root/cert-manager.tf ($(wc -c < "$HERE/root/cert-manager.tf" | tr -d ' ') bytes, $n blocks)"
echo
echo "If the block NAMES changed, live/gauntlet/estates.json's pre_apply list is now stale."
echo "The declared list must be exactly these 47 addresses:"
grep -o '^resource "kubernetes_manifest" "[^"]*"' "$HERE/root/cert-manager.tf" | sed 's/.*"kubernetes_manifest" "/  kubernetes_manifest./; s/"$//'
