// Copyright (c) The OpenTofu Authors
// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2023 HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by tools/row-gen -emit. DO NOT EDIT.

package identity

// ContentMatchTypes is every provider resource type issue #272's two-source
// rule qualifies for content-match discovery - see [ContentMatchBinding].
//
// The set is derived on every generator run from live/import-grammar.json's
// and live/registry-schema-facts.json's own DeclaredUnique signals, joined
// by the property name both sources describe. Nothing here is maintained by
// hand.
var ContentMatchTypes = map[string]ContentMatchBinding{
	"aws_alb": {
		Argument:     "name",
		CFNType:      "AWS::ElasticLoadBalancingV2::LoadBalancer",
		PropertyPath: []string{"Name"},
	},
	"aws_athena_data_catalog": {
		Argument:     "name",
		CFNType:      "AWS::Athena::DataCatalog",
		PropertyPath: []string{"Name"},
	},
	"aws_cloudfront_cache_policy": {
		Argument:     "name",
		CFNType:      "AWS::CloudFront::CachePolicy",
		PropertyPath: []string{"CachePolicyConfig", "Name"},
	},
	"aws_cloudfront_origin_request_policy": {
		Argument:     "name",
		CFNType:      "AWS::CloudFront::OriginRequestPolicy",
		PropertyPath: []string{"OriginRequestPolicyConfig", "Name"},
	},
	"aws_cloudfront_realtime_log_config": {
		Argument:     "name",
		CFNType:      "AWS::CloudFront::RealtimeLogConfig",
		PropertyPath: []string{"Name"},
	},
	"aws_cloudfront_response_headers_policy": {
		Argument:     "name",
		CFNType:      "AWS::CloudFront::ResponseHeadersPolicy",
		PropertyPath: []string{"ResponseHeadersPolicyConfig", "Name"},
	},
	"aws_lb": {
		Argument:     "name",
		CFNType:      "AWS::ElasticLoadBalancingV2::LoadBalancer",
		PropertyPath: []string{"Name"},
	},
	"aws_route53_cidr_collection": {
		Argument:     "name",
		CFNType:      "AWS::Route53::CidrCollection",
		PropertyPath: []string{"Name"},
	},
	"aws_route53_key_signing_key": {
		Argument:     "name",
		CFNType:      "AWS::Route53::KeySigningKey",
		PropertyPath: []string{"Name"},
	},
	"aws_timestreaminfluxdb_db_cluster": {
		Argument:     "name",
		CFNType:      "AWS::Timestream::InfluxDBCluster",
		PropertyPath: []string{"Name"},
	},
	"aws_timestreaminfluxdb_db_instance": {
		Argument:     "name",
		CFNType:      "AWS::Timestream::InfluxDBInstance",
		PropertyPath: []string{"Name"},
	},
}
