# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: training_specification is a required block the schema leaves entirely optional-shaped (validate: "Block training_specification must have a configuration value as the provider has marked it as required"); filled with the provider docs' own minimal worked example (one training channel, one supported instance type, a training image)
resource "aws_sagemaker_algorithm" "app" {
  algorithm_name = "tofu-sagemaker-cohort-algorithm"
  training_specification {
    supported_training_instance_types = ["ml.m5.large"]
    training_image                    = "123456789012.dkr.ecr.us-east-1.amazonaws.com/tofu-sagemaker-cohort-training:latest"
    training_channels {
      name                    = "train"
      supported_content_types = ["text/csv"]
      supported_input_modes   = ["File"]
    }
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_sagemaker_algorithm.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: schema marks both user_profile_name and space_name Optional, but the provider requires exactly one (validate: "one of `space_name,user_profile_name` must be specified"); app_type is Required and validated against a closed enum (validate: "expected app_type to be one of [...]"), and the generic placeholder string is not a member. domain_id is also wired to this cohort's own aws_sagemaker_domain.app.id and user_profile_name to aws_sagemaker_user_profile.app.user_profile_name in place of the generic placeholder strings - not required by validate (domain_id and user_profile_name carry no format check of their own), but the same cross-resource-reference improvement aws_eip_association's entry above makes: both sibling resources exist in this same cohort, so pointing at them is more real than an orphaned placeholder.
resource "aws_sagemaker_app" "app" {
  domain_id         = aws_sagemaker_domain.app.id
  app_name          = "tofu-sagemaker-cohort-app"
  app_type          = "JupyterServer"
  user_profile_name = aws_sagemaker_user_profile.app.user_profile_name
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_sagemaker_app.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: every image-config block is Optional in the wire schema, but the provider requires exactly one of code_editor_app_image_config, jupyter_lab_image_config or kernel_gateway_image_config (apply: "exactly one ... block must be configured") - found by the #108 acceptance tier; validate never runs this check
resource "aws_sagemaker_app_image_config" "app" {
  app_image_config_name = "tofu-sagemaker-cohort-app-image-config"
  kernel_gateway_image_config {
    kernel_spec {
      name = "tofu-sagemaker-cohort-kernel"
    }
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_sagemaker_app_image_config.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: git_config.repository_url
resource "aws_sagemaker_code_repository" "app" {
  code_repository_name = "tofu-sagemaker-cohort-code-repository"
  git_config {
    repository_url = "https://github.com/hashicorp/terraform-provider-aws.git"
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_sagemaker_code_repository.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: role_arn is Required and the provider validates it is a well-formed ARN (validate: "is an invalid ARN"), the same shape as aws_db_proxy's role_arn above - wired to the shared aws_iam_role instead. The s3_output.s3_uri leaf is Required and validated against a "^(https|s3)://..." pattern (validate: "expected value ... to match regular expression"); cluster_config.instance_count is Required and validated at least 1 (validate: "expected ... to be at least (1), got 0"); cluster_config.volume_size_in_gb is Required and validated 1-512 (validate: "expected ... to be in the range (1 - 512), got 0"); cluster_config.instance_type is Required and validated against a closed enum (validate: "expected instance_type to be one of [...]")
resource "aws_sagemaker_data_quality_job_definition" "app" {
  name     = "tofu-sagemaker-cohort-data-quality-job-definition"
  role_arn = aws_iam_role.sagemaker.arn
  data_quality_app_specification {
    image_uri = "placeholder"
  }
  data_quality_job_input {
  }
  data_quality_job_output_config {
    monitoring_outputs {
      s3_output {
        s3_uri = "s3://tofu-sagemaker-cohort-bucket/data-quality-output"
      }
    }
  }
  job_resources {
    cluster_config {
      instance_count    = 1
      instance_type     = "ml.t3.medium"
      volume_size_in_gb = 20
    }
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_sagemaker_data_quality_job_definition.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: role_arn is Required and the provider validates it is a well-formed ARN (validate: "is an invalid ARN"); wired to the shared aws_iam_role
resource "aws_sagemaker_device_fleet" "app" {
  device_fleet_name = "tofu-sagemaker-cohort-device-fleet"
  role_arn          = aws_iam_role.sagemaker.arn
  output_config {
    s3_output_location = "placeholder"
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_sagemaker_device_fleet.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: auth_mode is Required and the provider validates it against a closed enum (validate: "expected auth_mode to be one of [...]"); default_user_settings.execution_role is Required and the provider validates it is a well-formed ARN (validate: "is an invalid ARN") - wired to the shared aws_iam_role
resource "aws_sagemaker_domain" "app" {
  auth_mode   = "IAM"
  domain_name = "tofu-sagemaker-cohort-domain"
  subnet_ids  = ["placeholder"]
  vpc_id      = "placeholder"
  default_user_settings {
    execution_role = aws_iam_role.sagemaker.arn
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_sagemaker_domain.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: endpoint_config_name is Required but a generic-string placeholder, not a reference - overridden to point at this cohort's own aws_sagemaker_endpoint_configuration.app.name for the same cross-resource-reference reason as aws_eip_association's entry above (validate does not require this: endpoint_config_name carries no format check of its own)
resource "aws_sagemaker_endpoint" "app" {
  name                 = "tofu-sagemaker-cohort-endpoint"
  endpoint_config_name = aws_sagemaker_endpoint_configuration.app.name
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_sagemaker_endpoint.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: the generic pass's same-name parent search matches this type's own "name" argument against aws_sagemaker_endpoint (an unrelated sibling type that also self-identifies by a plain "name" argument), the same collision class as aws_glue_catalog_database's entry above; overridden back to a real placeholder name of its own
resource "aws_sagemaker_endpoint_configuration" "app" {
  name = "tofu-sagemaker-cohort-endpoint-configuration"
  production_variants {
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_sagemaker_endpoint_configuration.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: role_arn is Required (needed "if an offline_store_config is provided") and the provider validates it is a well-formed ARN once set (validate: "is an invalid ARN"); schema marks offline_store_config and online_store_config both Optional, but the provider requires exactly one (validate: "one of `offline_store_config,online_store_config` must be specified") - online_store_config is chosen, with its own required security_config child added empty (its own kms_key_id leaf is genuinely Optional)
resource "aws_sagemaker_feature_group" "app" {
  feature_group_name             = "tofu-sagemaker-cohort-feature-group"
  event_time_feature_name        = "tofu-sagemaker-cohort-feature-group"
  record_identifier_feature_name = "tofu-sagemaker-cohort-feature-group"
  role_arn                       = aws_iam_role.sagemaker.arn
  feature_definition {
  }
  online_store_config {
    security_config {
    }
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_sagemaker_feature_group.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: hub_description
resource "aws_sagemaker_hub" "app" {
  hub_name        = "tofu-sagemaker-cohort-hub"
  hub_description = "example"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_sagemaker_hub.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: role_arn is Required and the provider validates it is a well-formed ARN (validate: "is an invalid ARN"); wired to the shared aws_iam_role
resource "aws_sagemaker_image" "app" {
  image_name = "tofu-sagemaker-cohort-image"
  role_arn   = aws_iam_role.sagemaker.arn
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_sagemaker_image.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: the generic pass's same-name parent search matches this type's own "name" argument against the shared aws_iam_role (which also self-identifies by a plain "name" argument), the same collision class as aws_sagemaker_endpoint_configuration above; overridden back to a real placeholder name of its own. artifact_store_uri is Required and the provider validates it is an HTTPS or S3 URI (validate: "invalid value for artifact_store_uri (must be HTTPS or Amazon S3 URI)"); role_arn is Required and the provider validates it is a well-formed ARN (validate: "Invalid ARN Value") - wired to the shared aws_iam_role
resource "aws_sagemaker_mlflow_app" "app" {
  artifact_store_uri = "s3://tofu-sagemaker-cohort-bucket/mlflow-app"
  name               = "tofu-sagemaker-cohort-mlflow-app"
  role_arn           = aws_iam_role.sagemaker.arn
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_sagemaker_mlflow_app.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: artifact_store_uri is Required and the provider validates it is an HTTPS or S3 URI (validate: "invalid value for artifact_store_uri (must be HTTPS or Amazon S3 URI)"); role_arn is Required and the provider validates it is a well-formed ARN (validate: "is an invalid ARN") - wired to the shared aws_iam_role
resource "aws_sagemaker_mlflow_tracking_server" "app" {
  tracking_server_name = "tofu-sagemaker-cohort-mlflow-tracking-server"
  artifact_store_uri   = "s3://tofu-sagemaker-cohort-bucket/mlflow-tracking-server"
  role_arn             = aws_iam_role.sagemaker.arn
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_sagemaker_mlflow_tracking_server.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: none
resource "aws_sagemaker_model" "app" {
  name               = "tofu-sagemaker-cohort-model"
  execution_role_arn = aws_iam_role.sagemaker.arn
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_sagemaker_model.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: content is Required and the provider validates it is well-formed JSON (validate: "A string value was provided that is not valid JSON string format"); model_card_status is Required and validated against a closed enum (validate: "The provided value does not match any valid values", valid values Draft/PendingReview/Approved/Archived)
resource "aws_sagemaker_model_card" "app" {
  model_card_name = "tofu-sagemaker-cohort-model-card"
  content = jsonencode({
    model_overview = {
      model_description = "tofu cohort fixture model card"
    }
  })
  model_card_status = "Draft"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_sagemaker_model_card.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: none
resource "aws_sagemaker_model_package_group" "app" {
  model_package_group_name = "tofu-sagemaker-cohort-model-package-group"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_sagemaker_model_package_group.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: resource_policy is Required and the provider validates it is well-formed JSON (validate: "\"resource_policy\" contains an invalid JSON"), the same shape as aws_s3_bucket_policy above; the policy's Resource element references the sibling aws_sagemaker_model_package_group.app.arn this cohort also admits
resource "aws_sagemaker_model_package_group_policy" "app" {
  model_package_group_name = aws_sagemaker_model_package_group.app.model_package_group_name
  resource_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Sid       = "AddPermModelPackageGroup"
      Effect    = "Allow"
      Principal = { AWS = "arn:aws:iam::000000000000:root" }
      Action    = ["sagemaker:DescribeModelPackage", "sagemaker:ListModelPackages"]
      Resource  = "${aws_sagemaker_model_package_group.app.arn}"
    }]
  })
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: monitoring_schedule_config.monitoring_type
resource "aws_sagemaker_monitoring_schedule" "app" {
  name = "tofu-sagemaker-cohort-monitoring-schedule"
  monitoring_schedule_config {
    monitoring_type = "DataQuality"
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_sagemaker_monitoring_schedule.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: instance_type is Required and the provider validates it against a closed enum (validate: "expected instance_type to be one of [...]"); role_arn is Required and the provider validates it is a well-formed ARN (validate: "is an invalid ARN") - wired to the shared aws_iam_role
resource "aws_sagemaker_notebook_instance" "app" {
  name          = "tofu-sagemaker-cohort-notebook-instance"
  instance_type = "ml.t3.medium"
  role_arn      = aws_iam_role.sagemaker.arn
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_sagemaker_notebook_instance.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: the generic pass's same-name parent search matches this type's own "name" argument against aws_sagemaker_notebook_instance (an unrelated sibling type that also self-identifies by a plain "name" argument), the same collision class as aws_sagemaker_endpoint_configuration above; overridden back to a real placeholder name of its own
resource "aws_sagemaker_notebook_instance_lifecycle_configuration" "app" {
  name = "tofu-sagemaker-cohort-notebook-instance-lifecycle-configuration"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_sagemaker_notebook_instance_lifecycle_configuration.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: schema marks both pipeline_definition and pipeline_definition_s3_location Optional, but the provider requires exactly one (validate: "one of `pipeline_definition,pipeline_definition_s3_location` must be specified"); pipeline_definition is filled with a minimal well-formed pipeline document (a single no-op Fail step, the provider docs' own worked example)
resource "aws_sagemaker_pipeline" "app" {
  pipeline_name         = "tofu-sagemaker-cohort-pipeline"
  pipeline_display_name = "tofu-sagemaker-cohort-pipeline"
  pipeline_definition = jsonencode({
    Version = "2020-12-01"
    Steps = [{
      Name = "Placeholder"
      Type = "Fail"
      Arguments = {
        ErrorMessage = "tofu cohort fixture pipeline"
      }
    }]
  })
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_sagemaker_pipeline.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: none
resource "aws_sagemaker_project" "app" {
  project_name = "tofu-sagemaker-cohort-project"
  service_catalog_provisioning_details {
    product_id = "placeholder"
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_sagemaker_project.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: none
resource "aws_sagemaker_space" "app" {
  domain_id  = aws_sagemaker_domain.app.id
  space_name = "tofu-sagemaker-cohort-space"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_sagemaker_space.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: studio_lifecycle_config_app_type
resource "aws_sagemaker_studio_lifecycle_config" "app" {
  studio_lifecycle_config_name     = "tofu-sagemaker-cohort-studio-lifecycle-config"
  studio_lifecycle_config_app_type = "JupyterServer"
  studio_lifecycle_config_content  = "placeholder"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_sagemaker_studio_lifecycle_config.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: none
resource "aws_sagemaker_user_profile" "app" {
  domain_id         = aws_sagemaker_domain.app.id
  user_profile_name = "tofu-sagemaker-cohort-user-profile"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_sagemaker_user_profile.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: description
resource "aws_sagemaker_workteam" "app" {
  workteam_name = "tofu-sagemaker-cohort-workteam"
  description   = "example"
  member_definition {
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_sagemaker_workteam.app"
  }
}
