# Supporting, not coverage - added only so aws_iam_role.sagemaker's referring resources have a value to point at: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: schema requires "assume_role_policy" as a plain string, but the provider validates it is well-formed JSON (validate: "\"assume_role_policy\" contains an invalid JSON"); the generic string placeholder is not JSON
resource "aws_iam_role" "sagemaker" {
  name = "tofu-sagemaker-cohort-iam-role"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "sagemaker.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_iam_role.sagemaker"
  }
}

# Supporting, not coverage - added only so aws_s3_bucket.sagemaker's referring resources have a value to point at: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: none
resource "aws_s3_bucket" "sagemaker" {
  bucket = "tofu-sagemaker-cohort-s3-bucket"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_s3_bucket.sagemaker"
  }
}

# Supporting, not coverage - added only so aws_servicecatalog_product.sagemaker's referring resources have a value to point at: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: type is Required and the provider validates it against a closed enum (validate: "expected type to be one of [\"CLOUD_FORMATION_TEMPLATE\" \"MARKETPLACE\" \"TERRAFORM_OPEN_SOURCE\" \"TERRAFORM_CLOUD\" \"EXTERNAL\"]"); the generic placeholder string is not a member. provisioning_artifact_parameters is a required block whose own template_physical_id and template_url are both Optional in the schema, but the provider requires exactly one of them in practice (validate: "one of ... must be specified"), and the generic pass sets neither.
resource "aws_servicecatalog_product" "sagemaker" {
  name  = aws_iam_role.sagemaker.name
  owner = "placeholder"
  type  = "CLOUD_FORMATION_TEMPLATE"
  provisioning_artifact_parameters {
    template_url = "https://s3.amazonaws.com/tofu-sagemaker-cohort/servicecatalog-product-template.json"
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_servicecatalog_product.sagemaker"
  }
}

# Supporting, not coverage - added only so aws_subnet.sagemaker's referring resources have a value to point at: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: cidr_block
resource "aws_subnet" "sagemaker" {
  vpc_id     = aws_vpc.sagemaker.id
  cidr_block = "10.0.1.0/24"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_subnet.sagemaker"
  }
}

# Supporting, not coverage - added only so aws_vpc.sagemaker's referring resources have a value to point at: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: cidr_block
resource "aws_vpc" "sagemaker" {
  cidr_block = "10.0.0.0/16"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_vpc.sagemaker"
  }
}
