# Copyright The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# ---------------------------------------------------------------------
# GENERATED by live/e2e/corpus-cloud-platform-components/convert.sh from
# kubernetes/autoscaler's vertical-pod-autoscaler/deploy/vpa-v1-crd-gen.yaml
# at tag vertical-pod-autoscaler-1.8.0 (51,124 bytes, sha256
# 2916e9b8e0699375ed8eca8af81e00c5a8cf9d68a70b4796e24d43794838d623) with
# tfk8s v0.1.10. Do not hand-edit: rerun convert.sh. The licence notice
# above is kubernetes/autoscaler's, restated because the generated file
# carries none of its own.
# ---------------------------------------------------------------------
resource "kubernetes_manifest" "customresourcedefinition_verticalpodautoscalercheckpoints_autoscaling_k8s_io" {
  manifest = {
    "apiVersion" = "apiextensions.k8s.io/v1"
    "kind" = "CustomResourceDefinition"
    "metadata" = {
      "annotations" = {
        "api-approved.kubernetes.io" = "https://github.com/kubernetes/kubernetes/pull/63797"
        "controller-gen.kubebuilder.io/version" = "v0.21.0"
      }
      "name" = "verticalpodautoscalercheckpoints.autoscaling.k8s.io"
    }
    "spec" = {
      "group" = "autoscaling.k8s.io"
      "names" = {
        "kind" = "VerticalPodAutoscalerCheckpoint"
        "listKind" = "VerticalPodAutoscalerCheckpointList"
        "plural" = "verticalpodautoscalercheckpoints"
        "shortNames" = [
          "vpacheckpoint",
        ]
        "singular" = "verticalpodautoscalercheckpoint"
      }
      "scope" = "Namespaced"
      "versions" = [
        {
          "name" = "v1"
          "schema" = {
            "openAPIV3Schema" = {
              "description" = <<-EOT
              VerticalPodAutoscalerCheckpoint is the checkpoint of the internal state of VPA that
              is used for recovery after recommender's restart.
              EOT
              "properties" = {
                "apiVersion" = {
                  "description" = <<-EOT
                  APIVersion defines the versioned schema of this representation of an object.
                  Servers should convert recognized schemas to the latest internal value, and
                  may reject unrecognized values.
                  More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
                  EOT
                  "type" = "string"
                }
                "kind" = {
                  "description" = <<-EOT
                  Kind is a string value representing the REST resource this object represents.
                  Servers may infer this from the endpoint the client submits requests to.
                  Cannot be updated.
                  In CamelCase.
                  More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
                  EOT
                  "type" = "string"
                }
                "metadata" = {
                  "type" = "object"
                }
                "spec" = {
                  "description" = <<-EOT
                  Specification of the checkpoint.
                  More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status.
                  EOT
                  "properties" = {
                    "containerName" = {
                      "description" = "Name of the checkpointed container."
                      "type" = "string"
                    }
                    "vpaObjectName" = {
                      "description" = "Name of the VPA object that stored VerticalPodAutoscalerCheckpoint object."
                      "type" = "string"
                    }
                  }
                  "type" = "object"
                }
                "status" = {
                  "description" = "Data of the checkpoint."
                  "properties" = {
                    "cpuHistogram" = {
                      "description" = "Checkpoint of histogram for consumption of CPU."
                      "properties" = {
                        "bucketWeights" = {
                          "description" = "Map from bucket index to bucket weight."
                          "type" = "object"
                          "x-kubernetes-preserve-unknown-fields" = true
                        }
                        "referenceTimestamp" = {
                          "description" = "Reference timestamp for samples collected within this histogram."
                          "format" = "date-time"
                          "nullable" = true
                          "type" = "string"
                        }
                        "totalWeight" = {
                          "description" = "Sum of samples to be used as denominator for weights from BucketWeights."
                          "type" = "number"
                        }
                      }
                      "type" = "object"
                    }
                    "firstSampleStart" = {
                      "description" = "Timestamp of the first sample from the histograms."
                      "format" = "date-time"
                      "nullable" = true
                      "type" = "string"
                    }
                    "lastSampleStart" = {
                      "description" = "Timestamp of the last sample from the histograms."
                      "format" = "date-time"
                      "nullable" = true
                      "type" = "string"
                    }
                    "lastUpdateTime" = {
                      "description" = "The time when the status was last refreshed."
                      "format" = "date-time"
                      "nullable" = true
                      "type" = "string"
                    }
                    "memoryHistogram" = {
                      "description" = "Checkpoint of histogram for consumption of memory."
                      "properties" = {
                        "bucketWeights" = {
                          "description" = "Map from bucket index to bucket weight."
                          "type" = "object"
                          "x-kubernetes-preserve-unknown-fields" = true
                        }
                        "referenceTimestamp" = {
                          "description" = "Reference timestamp for samples collected within this histogram."
                          "format" = "date-time"
                          "nullable" = true
                          "type" = "string"
                        }
                        "totalWeight" = {
                          "description" = "Sum of samples to be used as denominator for weights from BucketWeights."
                          "type" = "number"
                        }
                      }
                      "type" = "object"
                    }
                    "totalSamplesCount" = {
                      "description" = "Total number of samples in the histograms."
                      "type" = "integer"
                    }
                    "version" = {
                      "description" = "Version of the format of the stored data."
                      "type" = "string"
                    }
                  }
                  "type" = "object"
                }
              }
              "type" = "object"
            }
          }
          "served" = true
          "storage" = true
        },
        {
          "name" = "v1beta2"
          "schema" = {
            "openAPIV3Schema" = {
              "description" = <<-EOT
              VerticalPodAutoscalerCheckpoint is the checkpoint of the internal state of VPA that
              is used for recovery after recommender's restart.
              EOT
              "properties" = {
                "apiVersion" = {
                  "description" = <<-EOT
                  APIVersion defines the versioned schema of this representation of an object.
                  Servers should convert recognized schemas to the latest internal value, and
                  may reject unrecognized values.
                  More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
                  EOT
                  "type" = "string"
                }
                "kind" = {
                  "description" = <<-EOT
                  Kind is a string value representing the REST resource this object represents.
                  Servers may infer this from the endpoint the client submits requests to.
                  Cannot be updated.
                  In CamelCase.
                  More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
                  EOT
                  "type" = "string"
                }
                "metadata" = {
                  "type" = "object"
                }
                "spec" = {
                  "description" = <<-EOT
                  Specification of the checkpoint.
                  More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status.
                  EOT
                  "properties" = {
                    "containerName" = {
                      "description" = "Name of the checkpointed container."
                      "type" = "string"
                    }
                    "vpaObjectName" = {
                      "description" = "Name of the VPA object that stored VerticalPodAutoscalerCheckpoint object."
                      "type" = "string"
                    }
                  }
                  "type" = "object"
                }
                "status" = {
                  "description" = "Data of the checkpoint."
                  "properties" = {
                    "cpuHistogram" = {
                      "description" = "Checkpoint of histogram for consumption of CPU."
                      "properties" = {
                        "bucketWeights" = {
                          "description" = "Map from bucket index to bucket weight."
                          "type" = "object"
                          "x-kubernetes-preserve-unknown-fields" = true
                        }
                        "referenceTimestamp" = {
                          "description" = "Reference timestamp for samples collected within this histogram."
                          "format" = "date-time"
                          "nullable" = true
                          "type" = "string"
                        }
                        "totalWeight" = {
                          "description" = "Sum of samples to be used as denominator for weights from BucketWeights."
                          "type" = "number"
                        }
                      }
                      "type" = "object"
                    }
                    "firstSampleStart" = {
                      "description" = "Timestamp of the first sample from the histograms."
                      "format" = "date-time"
                      "nullable" = true
                      "type" = "string"
                    }
                    "lastSampleStart" = {
                      "description" = "Timestamp of the last sample from the histograms."
                      "format" = "date-time"
                      "nullable" = true
                      "type" = "string"
                    }
                    "lastUpdateTime" = {
                      "description" = "The time when the status was last refreshed."
                      "format" = "date-time"
                      "nullable" = true
                      "type" = "string"
                    }
                    "memoryHistogram" = {
                      "description" = "Checkpoint of histogram for consumption of memory."
                      "properties" = {
                        "bucketWeights" = {
                          "description" = "Map from bucket index to bucket weight."
                          "type" = "object"
                          "x-kubernetes-preserve-unknown-fields" = true
                        }
                        "referenceTimestamp" = {
                          "description" = "Reference timestamp for samples collected within this histogram."
                          "format" = "date-time"
                          "nullable" = true
                          "type" = "string"
                        }
                        "totalWeight" = {
                          "description" = "Sum of samples to be used as denominator for weights from BucketWeights."
                          "type" = "number"
                        }
                      }
                      "type" = "object"
                    }
                    "totalSamplesCount" = {
                      "description" = "Total number of samples in the histograms."
                      "type" = "integer"
                    }
                    "version" = {
                      "description" = "Version of the format of the stored data."
                      "type" = "string"
                    }
                  }
                  "type" = "object"
                }
              }
              "type" = "object"
            }
          }
          "served" = false
          "storage" = false
        },
      ]
    }
  }
}

resource "kubernetes_manifest" "customresourcedefinition_verticalpodautoscalers_autoscaling_k8s_io" {
  manifest = {
    "apiVersion" = "apiextensions.k8s.io/v1"
    "kind" = "CustomResourceDefinition"
    "metadata" = {
      "annotations" = {
        "api-approved.kubernetes.io" = "https://github.com/kubernetes/kubernetes/pull/63797"
        "controller-gen.kubebuilder.io/version" = "v0.21.0"
      }
      "name" = "verticalpodautoscalers.autoscaling.k8s.io"
    }
    "spec" = {
      "group" = "autoscaling.k8s.io"
      "names" = {
        "kind" = "VerticalPodAutoscaler"
        "listKind" = "VerticalPodAutoscalerList"
        "plural" = "verticalpodautoscalers"
        "shortNames" = [
          "vpa",
        ]
        "singular" = "verticalpodautoscaler"
      }
      "scope" = "Namespaced"
      "versions" = [
        {
          "additionalPrinterColumns" = [
            {
              "jsonPath" = ".spec.updatePolicy.updateMode"
              "name" = "Mode"
              "type" = "string"
            },
            {
              "jsonPath" = ".status.recommendation.containerRecommendations[0].target.cpu"
              "name" = "CPU"
              "type" = "string"
            },
            {
              "jsonPath" = ".status.recommendation.containerRecommendations[0].target.memory"
              "name" = "Mem"
              "type" = "string"
            },
            {
              "jsonPath" = ".status.conditions[?(@.type=='RecommendationProvided')].status"
              "name" = "Provided"
              "type" = "string"
            },
            {
              "jsonPath" = ".metadata.creationTimestamp"
              "name" = "Age"
              "type" = "date"
            },
            {
              "jsonPath" = ".spec.updatePolicy.minReplicas"
              "name" = "MinReplicas"
              "priority" = 1
              "type" = "integer"
            },
            {
              "jsonPath" = ".spec.updatePolicy.evictAfterOOMSeconds"
              "name" = "OOMSeconds"
              "priority" = 1
              "type" = "integer"
            },
          ]
          "name" = "v1"
          "schema" = {
            "openAPIV3Schema" = {
              "description" = <<-EOT
              VerticalPodAutoscaler is the configuration for a vertical pod
              autoscaler, which automatically manages pod resources based on historical and
              real time resource utilization.
              EOT
              "properties" = {
                "apiVersion" = {
                  "description" = <<-EOT
                  APIVersion defines the versioned schema of this representation of an object.
                  Servers should convert recognized schemas to the latest internal value, and
                  may reject unrecognized values.
                  More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
                  EOT
                  "type" = "string"
                }
                "kind" = {
                  "description" = <<-EOT
                  Kind is a string value representing the REST resource this object represents.
                  Servers may infer this from the endpoint the client submits requests to.
                  Cannot be updated.
                  In CamelCase.
                  More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
                  EOT
                  "type" = "string"
                }
                "metadata" = {
                  "type" = "object"
                }
                "spec" = {
                  "description" = <<-EOT
                  Specification of the behavior of the autoscaler.
                  More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status.
                  EOT
                  "properties" = {
                    "recommenders" = {
                      "description" = <<-EOT
                      Recommender responsible for generating recommendation for this object.
                      List should be empty (then the default recommender will generate the
                      recommendation) or contain exactly one recommender.
                      EOT
                      "items" = {
                        "description" = <<-EOT
                        VerticalPodAutoscalerRecommenderSelector points to a specific Vertical Pod Autoscaler recommender.
                        In the future it might pass parameters to the recommender.
                        EOT
                        "properties" = {
                          "name" = {
                            "description" = "Name of the recommender responsible for generating recommendation for this object."
                            "type" = "string"
                          }
                        }
                        "required" = [
                          "name",
                        ]
                        "type" = "object"
                      }
                      "type" = "array"
                    }
                    "resourcePolicy" = {
                      "description" = <<-EOT
                      Controls how the autoscaler computes recommended resources.
                      The resource policy may be used to set constraints on the recommendations
                      for individual containers.
                      If any individual containers need to be excluded from getting the VPA recommendations, then
                      it must be disabled explicitly by setting mode to "Off" under containerPolicies.
                      If not specified, the autoscaler computes recommended resources for all containers in the pod,
                      without additional constraints.
                      EOT
                      "properties" = {
                        "containerPolicies" = {
                          "description" = "Per-container resource policies."
                          "items" = {
                            "description" = <<-EOT
                            ContainerResourcePolicy controls how autoscaler computes the recommended
                            resources for a specific container.
                            EOT
                            "properties" = {
                              "containerName" = {
                                "description" = <<-EOT
                                Name of the container or DefaultContainerResourcePolicy, in which
                                case the policy is used by the containers that don't have their own
                                policy specified.
                                EOT
                                "type" = "string"
                              }
                              "controlledResources" = {
                                "description" = <<-EOT
                                Specifies the type of recommendations that will be computed
                                (and possibly applied) by VPA.
                                If not specified, the default of [cpu, memory] will be used.
                                EOT
                                "items" = {
                                  "description" = "ResourceName is the name identifying various resources in a ResourceList."
                                  "type" = "string"
                                }
                                "type" = "array"
                              }
                              "controlledValues" = {
                                "description" = <<-EOT
                                Specifies which resource values should be controlled.
                                The default is "RequestsAndLimits".
                                EOT
                                "enum" = [
                                  "RequestsAndLimits",
                                  "RequestsOnly",
                                ]
                                "type" = "string"
                              }
                              "maxAllowed" = {
                                "additionalProperties" = {
                                  "anyOf" = [
                                    {
                                      "type" = "integer"
                                    },
                                    {
                                      "type" = "string"
                                    },
                                  ]
                                  "pattern" = "^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$"
                                  "x-kubernetes-int-or-string" = true
                                }
                                "description" = <<-EOT
                                Specifies the maximum amount of resources that will be recommended
                                for the container. The default is no maximum.
                                EOT
                                "type" = "object"
                              }
                              "memoryAggregationIntervalCount" = {
                                "description" = <<-EOT
                                memoryAggregationIntervalCount is the number of consecutive
                                memoryAggregationIntervals which make up the memory aggregation window.
                                The total window length is:
                                MemoryAggregationIntervalSeconds * MemoryAggregationIntervalCount.
                                EOT
                                "format" = "int64"
                                "minimum" = 1
                                "type" = "integer"
                              }
                              "memoryAggregationIntervalSeconds" = {
                                "description" = <<-EOT
                                memoryAggregationIntervalSeconds is the length of a single interval
                                (in seconds) for which the peak memory usage is computed.
                                Memory usage peaks are aggregated in multiples of this interval.
                                In other words, there is one memory usage sample per interval
                                (the maximum usage over that interval).
                                EOT
                                "format" = "int32"
                                "minimum" = 1
                                "type" = "integer"
                              }
                              "minAllowed" = {
                                "additionalProperties" = {
                                  "anyOf" = [
                                    {
                                      "type" = "integer"
                                    },
                                    {
                                      "type" = "string"
                                    },
                                  ]
                                  "pattern" = "^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$"
                                  "x-kubernetes-int-or-string" = true
                                }
                                "description" = <<-EOT
                                Specifies the minimal amount of resources that will be recommended
                                for the container. The default is no minimum.
                                EOT
                                "type" = "object"
                              }
                              "mode" = {
                                "description" = "Whether autoscaler is enabled for the container. The default is \"Auto\"."
                                "enum" = [
                                  "Auto",
                                  "Off",
                                ]
                                "type" = "string"
                              }
                              "oomBumpUpRatio" = {
                                "anyOf" = [
                                  {
                                    "type" = "integer"
                                  },
                                  {
                                    "type" = "string"
                                  },
                                ]
                                "description" = "oomBumpUpRatio is the ratio to increase memory when OOM is detected."
                                "pattern" = "^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$"
                                "x-kubernetes-int-or-string" = true
                              }
                              "oomMinBumpUp" = {
                                "anyOf" = [
                                  {
                                    "type" = "integer"
                                  },
                                  {
                                    "type" = "string"
                                  },
                                ]
                                "description" = "oomMinBumpUp is the minimum increase in memory when OOM is detected."
                                "pattern" = "^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$"
                                "x-kubernetes-int-or-string" = true
                              }
                              "startupBoost" = {
                                "description" = <<-EOT
                                startupBoost specifies the startup boost policy for the container.
                                This overrides any pod-level startup boost policy.
                                The startup boost policy takes precedence over the rest of the fields in
                                this struct, except for ContainerName and ControlledValues.
                                EOT
                                "properties" = {
                                  "cpu" = {
                                    "description" = <<-EOT
                                    cpu specifies the CPU startup boost policy.
                                    If this field is not set, no startup boost is applied.
                                    EOT
                                    "properties" = {
                                      "durationSeconds" = {
                                        "description" = <<-EOT
                                        durationSeconds indicates for how long to keep the pod boosted after it goes to Ready.
                                        Defaults to 0.
                                        EOT
                                        "format" = "int32"
                                        "type" = "integer"
                                      }
                                      "factor" = {
                                        "description" = <<-EOT
                                        factor specifies the factor to apply to the resource request.
                                        This field is required when Type is "Factor".
                                        EOT
                                        "format" = "int32"
                                        "type" = "integer"
                                      }
                                      "quantity" = {
                                        "anyOf" = [
                                          {
                                            "type" = "integer"
                                          },
                                          {
                                            "type" = "string"
                                          },
                                        ]
                                        "description" = <<-EOT
                                        quantity specifies the absolute resource quantity to be used as the
                                        resource request and limit during the boost phase.
                                        This field is required when Type is "Quantity".
                                        EOT
                                        "pattern" = "^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$"
                                        "x-kubernetes-int-or-string" = true
                                      }
                                      "type" = {
                                        "description" = <<-EOT
                                        type specifies the kind of boost to apply.
                                        Supported values are: "Factor", "Quantity".
                                        No startupboost will be applied for unrecognized values.
                                        EOT
                                        "enum" = [
                                          "Factor",
                                          "Quantity",
                                        ]
                                        "type" = "string"
                                      }
                                    }
                                    "required" = [
                                      "type",
                                    ]
                                    "type" = "object"
                                    "x-kubernetes-validations" = [
                                      {
                                        "message" = "factor is required when type is Factor and forbidden otherwise"
                                        "rule" = "(self.type == 'Factor') == has(self.factor)"
                                      },
                                      {
                                        "message" = "quantity is required when type is Quantity and forbidden otherwise"
                                        "rule" = "(self.type == 'Quantity') == has(self.quantity)"
                                      },
                                    ]
                                  }
                                }
                                "type" = "object"
                              }
                            }
                            "type" = "object"
                          }
                          "type" = "array"
                        }
                      }
                      "type" = "object"
                    }
                    "startupBoost" = {
                      "description" = "startupBoost specifies the startup boost policy for the pod."
                      "properties" = {
                        "cpu" = {
                          "description" = <<-EOT
                          cpu specifies the CPU startup boost policy.
                          If this field is not set, no startup boost is applied.
                          EOT
                          "properties" = {
                            "durationSeconds" = {
                              "description" = <<-EOT
                              durationSeconds indicates for how long to keep the pod boosted after it goes to Ready.
                              Defaults to 0.
                              EOT
                              "format" = "int32"
                              "type" = "integer"
                            }
                            "factor" = {
                              "description" = <<-EOT
                              factor specifies the factor to apply to the resource request.
                              This field is required when Type is "Factor".
                              EOT
                              "format" = "int32"
                              "type" = "integer"
                            }
                            "quantity" = {
                              "anyOf" = [
                                {
                                  "type" = "integer"
                                },
                                {
                                  "type" = "string"
                                },
                              ]
                              "description" = <<-EOT
                              quantity specifies the absolute resource quantity to be used as the
                              resource request and limit during the boost phase.
                              This field is required when Type is "Quantity".
                              EOT
                              "pattern" = "^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$"
                              "x-kubernetes-int-or-string" = true
                            }
                            "type" = {
                              "description" = <<-EOT
                              type specifies the kind of boost to apply.
                              Supported values are: "Factor", "Quantity".
                              No startupboost will be applied for unrecognized values.
                              EOT
                              "enum" = [
                                "Factor",
                                "Quantity",
                              ]
                              "type" = "string"
                            }
                          }
                          "required" = [
                            "type",
                          ]
                          "type" = "object"
                          "x-kubernetes-validations" = [
                            {
                              "message" = "factor is required when type is Factor and forbidden otherwise"
                              "rule" = "(self.type == 'Factor') == has(self.factor)"
                            },
                            {
                              "message" = "quantity is required when type is Quantity and forbidden otherwise"
                              "rule" = "(self.type == 'Quantity') == has(self.quantity)"
                            },
                          ]
                        }
                      }
                      "type" = "object"
                    }
                    "targetRef" = {
                      "description" = <<-EOT
                      TargetRef points to the controller managing the set of pods for the
                      autoscaler to control - e.g. Deployment, StatefulSet. VerticalPodAutoscaler
                      can be targeted at controller implementing scale subresource (the pod set is
                      retrieved from the controller's ScaleStatus) or some well known controllers
                      (e.g. for DaemonSet the pod set is read from the controller's spec).
                      If VerticalPodAutoscaler cannot use specified target it will report
                      ConfigUnsupported condition.
                      Note that VerticalPodAutoscaler does not require full implementation
                      of scale subresource - it will not use it to modify the replica count.
                      The only thing retrieved is a label selector matching pods grouped by
                      the target resource.
                      EOT
                      "properties" = {
                        "apiVersion" = {
                          "description" = "apiVersion is the API version of the referent"
                          "type" = "string"
                        }
                        "kind" = {
                          "description" = "kind is the kind of the referent; More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
                          "type" = "string"
                        }
                        "name" = {
                          "description" = "name is the name of the referent; More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"
                          "type" = "string"
                        }
                      }
                      "required" = [
                        "kind",
                        "name",
                      ]
                      "type" = "object"
                      "x-kubernetes-map-type" = "atomic"
                    }
                    "updatePolicy" = {
                      "description" = <<-EOT
                      Describes the rules on how changes are applied to the pods.
                      If not specified, all fields in the `PodUpdatePolicy` are set to their
                      default values.
                      EOT
                      "properties" = {
                        "evictAfterOOMSeconds" = {
                          "description" = <<-EOT
                          evictAfterOOMSeconds specifies the time in seconds to wait after an OOM event before
                          considering the pod for eviction. Pods that have OOMed in less than this time
                          since start will be evicted.
                          EOT
                          "format" = "int32"
                          "minimum" = 1
                          "type" = "integer"
                        }
                        "evictionRequirements" = {
                          "description" = <<-EOT
                          EvictionRequirements is a list of EvictionRequirements that need to
                          evaluate to true in order for a Pod to be evicted. If more than one
                          EvictionRequirement is specified, all of them need to be fulfilled to allow eviction.
                          EOT
                          "items" = {
                            "description" = <<-EOT
                            EvictionRequirement defines a single condition which needs to be true in
                            order to evict a Pod
                            EOT
                            "properties" = {
                              "changeRequirement" = {
                                "description" = "EvictionChangeRequirement refers to the relationship between the new target recommendation for a Pod and its current requests, what kind of change is necessary for the Pod to be evicted"
                                "enum" = [
                                  "TargetHigherThanRequests",
                                  "TargetLowerThanRequests",
                                ]
                                "type" = "string"
                              }
                              "resources" = {
                                "description" = <<-EOT
                                Resources is a list of one or more resources that the condition applies
                                to. If more than one resource is given, the EvictionRequirement is fulfilled
                                if at least one resource meets `changeRequirement`.
                                EOT
                                "items" = {
                                  "description" = "ResourceName is the name identifying various resources in a ResourceList."
                                  "type" = "string"
                                }
                                "type" = "array"
                              }
                            }
                            "required" = [
                              "changeRequirement",
                              "resources",
                            ]
                            "type" = "object"
                          }
                          "type" = "array"
                        }
                        "minReplicas" = {
                          "description" = <<-EOT
                          Minimal number of replicas which need to be alive for Updater to attempt
                          pod eviction (pending other checks like PDB). Only positive values are
                          allowed. Overrides global '--min-replicas' flag.
                          EOT
                          "format" = "int32"
                          "type" = "integer"
                        }
                        "updateMode" = {
                          "description" = <<-EOT
                          Controls when autoscaler applies changes to the pod resources.
                          The default is 'Recreate'.
                          EOT
                          "enum" = [
                            "Off",
                            "Initial",
                            "Recreate",
                            "InPlaceOrRecreate",
                            "InPlace",
                            "Auto",
                          ]
                          "type" = "string"
                        }
                      }
                      "type" = "object"
                    }
                  }
                  "required" = [
                    "targetRef",
                  ]
                  "type" = "object"
                }
                "status" = {
                  "description" = "Current information about the autoscaler."
                  "properties" = {
                    "conditions" = {
                      "description" = <<-EOT
                      Conditions is the set of conditions required for this autoscaler to scale its target,
                      and indicates whether or not those conditions are met.
                      EOT
                      "items" = {
                        "description" = <<-EOT
                        VerticalPodAutoscalerCondition describes the state of
                        a VerticalPodAutoscaler at a certain point.
                        EOT
                        "properties" = {
                          "lastTransitionTime" = {
                            "description" = <<-EOT
                            lastTransitionTime is the last time the condition transitioned from
                            one status to another
                            EOT
                            "format" = "date-time"
                            "type" = "string"
                          }
                          "message" = {
                            "description" = <<-EOT
                            message is a human-readable explanation containing details about
                            the transition
                            EOT
                            "type" = "string"
                          }
                          "observedGeneration" = {
                            "description" = <<-EOT
                            observedGeneration represents the .metadata.generation that the condition was set based upon.
                            For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                            with respect to the current state of the instance.
                            EOT
                            "format" = "int64"
                            "minimum" = 0
                            "type" = "integer"
                          }
                          "reason" = {
                            "description" = "reason is the reason for the condition's last transition."
                            "type" = "string"
                          }
                          "status" = {
                            "description" = "status is the status of the condition (True, False, Unknown)"
                            "type" = "string"
                          }
                          "type" = {
                            "description" = "type describes the current condition"
                            "type" = "string"
                          }
                        }
                        "required" = [
                          "status",
                          "type",
                        ]
                        "type" = "object"
                      }
                      "type" = "array"
                    }
                    "observedGeneration" = {
                      "description" = "observedGeneration is the most recent generation observed by this autoscaler."
                      "format" = "int64"
                      "minimum" = 0
                      "type" = "integer"
                    }
                    "recommendation" = {
                      "description" = <<-EOT
                      The most recently computed amount of resources recommended by the
                      autoscaler for the controlled pods.
                      EOT
                      "properties" = {
                        "containerRecommendations" = {
                          "description" = "Resources recommended by the autoscaler for each container."
                          "items" = {
                            "description" = <<-EOT
                            RecommendedContainerResources is the recommendation of resources computed by
                            autoscaler for a specific container. Respects the container resource policy
                            if present in the spec. In particular the recommendation is not produced for
                            containers with `ContainerScalingMode` set to 'Off'.
                            EOT
                            "properties" = {
                              "containerName" = {
                                "description" = "Name of the container."
                                "type" = "string"
                              }
                              "lowerBound" = {
                                "additionalProperties" = {
                                  "anyOf" = [
                                    {
                                      "type" = "integer"
                                    },
                                    {
                                      "type" = "string"
                                    },
                                  ]
                                  "pattern" = "^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$"
                                  "x-kubernetes-int-or-string" = true
                                }
                                "description" = <<-EOT
                                Minimum recommended amount of resources. Observes ContainerResourcePolicy.
                                This amount is not guaranteed to be sufficient for the application to operate in a stable way, however
                                running with less resources is likely to have significant impact on performance/availability.
                                EOT
                                "type" = "object"
                              }
                              "target" = {
                                "additionalProperties" = {
                                  "anyOf" = [
                                    {
                                      "type" = "integer"
                                    },
                                    {
                                      "type" = "string"
                                    },
                                  ]
                                  "pattern" = "^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$"
                                  "x-kubernetes-int-or-string" = true
                                }
                                "description" = "Recommended amount of resources. Observes ContainerResourcePolicy."
                                "type" = "object"
                              }
                              "uncappedTarget" = {
                                "additionalProperties" = {
                                  "anyOf" = [
                                    {
                                      "type" = "integer"
                                    },
                                    {
                                      "type" = "string"
                                    },
                                  ]
                                  "pattern" = "^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$"
                                  "x-kubernetes-int-or-string" = true
                                }
                                "description" = <<-EOT
                                The most recent recommended resources target computed by the autoscaler
                                for the controlled pods, based only on actual resource usage, not taking
                                into account the ContainerResourcePolicy.
                                May differ from the Recommendation if the actual resource usage causes
                                the target to violate the ContainerResourcePolicy (lower than MinAllowed
                                or higher that MaxAllowed).
                                Used only as status indication, will not affect actual resource assignment.
                                EOT
                                "type" = "object"
                              }
                              "upperBound" = {
                                "additionalProperties" = {
                                  "anyOf" = [
                                    {
                                      "type" = "integer"
                                    },
                                    {
                                      "type" = "string"
                                    },
                                  ]
                                  "pattern" = "^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$"
                                  "x-kubernetes-int-or-string" = true
                                }
                                "description" = <<-EOT
                                Maximum recommended amount of resources. Observes ContainerResourcePolicy.
                                Any resources allocated beyond this value are likely wasted. This value may be larger than the maximum
                                amount of application is actually capable of consuming.
                                EOT
                                "type" = "object"
                              }
                            }
                            "required" = [
                              "target",
                            ]
                            "type" = "object"
                          }
                          "type" = "array"
                        }
                      }
                      "type" = "object"
                    }
                  }
                  "type" = "object"
                }
              }
              "required" = [
                "spec",
              ]
              "type" = "object"
            }
          }
          "served" = true
          "storage" = true
          "subresources" = {
            "status" = {}
          }
        },
        {
          "deprecated" = true
          "deprecationWarning" = "autoscaling.k8s.io/v1beta2 API is deprecated"
          "name" = "v1beta2"
          "schema" = {
            "openAPIV3Schema" = {
              "description" = <<-EOT
              VerticalPodAutoscaler is the configuration for a vertical pod
              autoscaler, which automatically manages pod resources based on historical and
              real time resource utilization.
              EOT
              "properties" = {
                "apiVersion" = {
                  "description" = <<-EOT
                  APIVersion defines the versioned schema of this representation of an object.
                  Servers should convert recognized schemas to the latest internal value, and
                  may reject unrecognized values.
                  More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
                  EOT
                  "type" = "string"
                }
                "kind" = {
                  "description" = <<-EOT
                  Kind is a string value representing the REST resource this object represents.
                  Servers may infer this from the endpoint the client submits requests to.
                  Cannot be updated.
                  In CamelCase.
                  More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
                  EOT
                  "type" = "string"
                }
                "metadata" = {
                  "type" = "object"
                }
                "spec" = {
                  "description" = <<-EOT
                  Specification of the behavior of the autoscaler.
                  More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status.
                  EOT
                  "properties" = {
                    "resourcePolicy" = {
                      "description" = <<-EOT
                      Controls how the autoscaler computes recommended resources.
                      The resource policy may be used to set constraints on the recommendations
                      for individual containers. If not specified, the autoscaler computes recommended
                      resources for all containers in the pod, without additional constraints.
                      EOT
                      "properties" = {
                        "containerPolicies" = {
                          "description" = "Per-container resource policies."
                          "items" = {
                            "description" = <<-EOT
                            ContainerResourcePolicy controls how autoscaler computes the recommended
                            resources for a specific container.
                            EOT
                            "properties" = {
                              "containerName" = {
                                "description" = <<-EOT
                                Name of the container or DefaultContainerResourcePolicy, in which
                                case the policy is used by the containers that don't have their own
                                policy specified.
                                EOT
                                "type" = "string"
                              }
                              "maxAllowed" = {
                                "additionalProperties" = {
                                  "anyOf" = [
                                    {
                                      "type" = "integer"
                                    },
                                    {
                                      "type" = "string"
                                    },
                                  ]
                                  "pattern" = "^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$"
                                  "x-kubernetes-int-or-string" = true
                                }
                                "description" = <<-EOT
                                Specifies the maximum amount of resources that will be recommended
                                for the container. The default is no maximum.
                                EOT
                                "type" = "object"
                              }
                              "minAllowed" = {
                                "additionalProperties" = {
                                  "anyOf" = [
                                    {
                                      "type" = "integer"
                                    },
                                    {
                                      "type" = "string"
                                    },
                                  ]
                                  "pattern" = "^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$"
                                  "x-kubernetes-int-or-string" = true
                                }
                                "description" = <<-EOT
                                Specifies the minimal amount of resources that will be recommended
                                for the container. The default is no minimum.
                                EOT
                                "type" = "object"
                              }
                              "mode" = {
                                "description" = "Whether autoscaler is enabled for the container. The default is \"Auto\"."
                                "enum" = [
                                  "Auto",
                                  "Off",
                                ]
                                "type" = "string"
                              }
                            }
                            "type" = "object"
                          }
                          "type" = "array"
                        }
                      }
                      "type" = "object"
                    }
                    "targetRef" = {
                      "description" = <<-EOT
                      TargetRef points to the controller managing the set of pods for the
                      autoscaler to control - e.g. Deployment, StatefulSet. VerticalPodAutoscaler
                      can be targeted at controller implementing scale subresource (the pod set is
                      retrieved from the controller's ScaleStatus) or some well known controllers
                      (e.g. for DaemonSet the pod set is read from the controller's spec).
                      If VerticalPodAutoscaler cannot use specified target it will report
                      ConfigUnsupported condition.
                      Note that VerticalPodAutoscaler does not require full implementation
                      of scale subresource - it will not use it to modify the replica count.
                      The only thing retrieved is a label selector matching pods grouped by
                      the target resource.
                      EOT
                      "properties" = {
                        "apiVersion" = {
                          "description" = "apiVersion is the API version of the referent"
                          "type" = "string"
                        }
                        "kind" = {
                          "description" = "kind is the kind of the referent; More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
                          "type" = "string"
                        }
                        "name" = {
                          "description" = "name is the name of the referent; More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"
                          "type" = "string"
                        }
                      }
                      "required" = [
                        "kind",
                        "name",
                      ]
                      "type" = "object"
                      "x-kubernetes-map-type" = "atomic"
                    }
                    "updatePolicy" = {
                      "description" = <<-EOT
                      Describes the rules on how changes are applied to the pods.
                      If not specified, all fields in the `PodUpdatePolicy` are set to their
                      default values.
                      EOT
                      "properties" = {
                        "updateMode" = {
                          "description" = <<-EOT
                          Controls when autoscaler applies changes to the pod resources.
                          The default is 'Auto'.
                          EOT
                          "enum" = [
                            "Off",
                            "Initial",
                            "Recreate",
                            "Auto",
                          ]
                          "type" = "string"
                        }
                      }
                      "type" = "object"
                    }
                  }
                  "required" = [
                    "targetRef",
                  ]
                  "type" = "object"
                }
                "status" = {
                  "description" = "Current information about the autoscaler."
                  "properties" = {
                    "conditions" = {
                      "description" = <<-EOT
                      Conditions is the set of conditions required for this autoscaler to scale its target,
                      and indicates whether or not those conditions are met.
                      EOT
                      "items" = {
                        "description" = <<-EOT
                        VerticalPodAutoscalerCondition describes the state of
                        a VerticalPodAutoscaler at a certain point.
                        EOT
                        "properties" = {
                          "lastTransitionTime" = {
                            "description" = <<-EOT
                            lastTransitionTime is the last time the condition transitioned from
                            one status to another
                            EOT
                            "format" = "date-time"
                            "type" = "string"
                          }
                          "message" = {
                            "description" = <<-EOT
                            message is a human-readable explanation containing details about
                            the transition
                            EOT
                            "type" = "string"
                          }
                          "reason" = {
                            "description" = "reason is the reason for the condition's last transition."
                            "type" = "string"
                          }
                          "status" = {
                            "description" = "status is the status of the condition (True, False, Unknown)"
                            "type" = "string"
                          }
                          "type" = {
                            "description" = "type describes the current condition"
                            "type" = "string"
                          }
                        }
                        "required" = [
                          "status",
                          "type",
                        ]
                        "type" = "object"
                      }
                      "type" = "array"
                    }
                    "recommendation" = {
                      "description" = <<-EOT
                      The most recently computed amount of resources recommended by the
                      autoscaler for the controlled pods.
                      EOT
                      "properties" = {
                        "containerRecommendations" = {
                          "description" = "Resources recommended by the autoscaler for each container."
                          "items" = {
                            "description" = <<-EOT
                            RecommendedContainerResources is the recommendation of resources computed by
                            autoscaler for a specific container. Respects the container resource policy
                            if present in the spec. In particular the recommendation is not produced for
                            containers with `ContainerScalingMode` set to 'Off'.
                            EOT
                            "properties" = {
                              "containerName" = {
                                "description" = "Name of the container."
                                "type" = "string"
                              }
                              "lowerBound" = {
                                "additionalProperties" = {
                                  "anyOf" = [
                                    {
                                      "type" = "integer"
                                    },
                                    {
                                      "type" = "string"
                                    },
                                  ]
                                  "pattern" = "^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$"
                                  "x-kubernetes-int-or-string" = true
                                }
                                "description" = <<-EOT
                                Minimum recommended amount of resources. Observes ContainerResourcePolicy.
                                This amount is not guaranteed to be sufficient for the application to operate in a stable way, however
                                running with less resources is likely to have significant impact on performance/availability.
                                EOT
                                "type" = "object"
                              }
                              "target" = {
                                "additionalProperties" = {
                                  "anyOf" = [
                                    {
                                      "type" = "integer"
                                    },
                                    {
                                      "type" = "string"
                                    },
                                  ]
                                  "pattern" = "^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$"
                                  "x-kubernetes-int-or-string" = true
                                }
                                "description" = "Recommended amount of resources. Observes ContainerResourcePolicy."
                                "type" = "object"
                              }
                              "uncappedTarget" = {
                                "additionalProperties" = {
                                  "anyOf" = [
                                    {
                                      "type" = "integer"
                                    },
                                    {
                                      "type" = "string"
                                    },
                                  ]
                                  "pattern" = "^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$"
                                  "x-kubernetes-int-or-string" = true
                                }
                                "description" = <<-EOT
                                The most recent recommended resources target computed by the autoscaler
                                for the controlled pods, based only on actual resource usage, not taking
                                into account the ContainerResourcePolicy.
                                May differ from the Recommendation if the actual resource usage causes
                                the target to violate the ContainerResourcePolicy (lower than MinAllowed
                                or higher that MaxAllowed).
                                Used only as status indication, will not affect actual resource assignment.
                                EOT
                                "type" = "object"
                              }
                              "upperBound" = {
                                "additionalProperties" = {
                                  "anyOf" = [
                                    {
                                      "type" = "integer"
                                    },
                                    {
                                      "type" = "string"
                                    },
                                  ]
                                  "pattern" = "^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$"
                                  "x-kubernetes-int-or-string" = true
                                }
                                "description" = <<-EOT
                                Maximum recommended amount of resources. Observes ContainerResourcePolicy.
                                Any resources allocated beyond this value are likely wasted. This value may be larger than the maximum
                                amount of application is actually capable of consuming.
                                EOT
                                "type" = "object"
                              }
                            }
                            "required" = [
                              "target",
                            ]
                            "type" = "object"
                          }
                          "type" = "array"
                        }
                      }
                      "type" = "object"
                    }
                  }
                  "type" = "object"
                }
              }
              "required" = [
                "spec",
              ]
              "type" = "object"
            }
          }
          "served" = false
          "storage" = false
          "subresources" = {
            "status" = {}
          }
        },
      ]
    }
  }
}
