# Supporting, not coverage - added only so aws_eip.ec2-networking's referring resources have a value to point at: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: domain, public_ipv4_pool
resource "aws_eip" "ec2-networking" {
  domain           = "vpc"
  public_ipv4_pool = "ipv4pool-ec2-012345"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_eip.ec2-networking"
  }
}

# Supporting, not coverage - added only so aws_lb.ec2-networking's referring resources have a value to point at: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: none
resource "aws_lb" "ec2-networking" {
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_lb.ec2-networking"
  }
}

# Supporting, not coverage - added only so aws_route_table.ec2-networking's referring resources have a value to point at: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: route
resource "aws_route_table" "ec2-networking" {
  vpc_id = aws_vpc_dhcp_options_association.app.vpc_id
  route  = []
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_route_table.ec2-networking"
  }
}

# Supporting, not coverage - added only so aws_security_group.ec2-networking's referring resources have a value to point at: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: none
resource "aws_security_group" "ec2-networking" {
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_security_group.ec2-networking"
  }
}

# Supporting, not coverage - added only so aws_subnet.ec2-networking's referring resources have a value to point at: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: cidr_block
resource "aws_subnet" "ec2-networking" {
  vpc_id     = aws_vpc_dhcp_options_association.app.vpc_id
  cidr_block = "10.0.1.0/24"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_subnet.ec2-networking"
  }
}

# Supporting, not coverage - added only so aws_vpc.ec2-networking's referring resources have a value to point at: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: cidr_block
resource "aws_vpc" "ec2-networking" {
  cidr_block = "10.0.0.0/16"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_vpc.ec2-networking"
  }
}
