# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: "policy" is a required string the schema does not constrain, but the provider validates it is well-formed JSON (validate: "\"policy\" contains an invalid JSON"); the generic placeholder string is not
resource "aws_ecr_lifecycle_policy" "app" {
  repository = aws_ecr_repository.stragglers.name
  policy = jsonencode({
    rules = [{
      rulePriority = 1
      description  = "expire untagged images"
      selection = {
        tagStatus   = "untagged"
        countType   = "imageCountMoreThan"
        countNumber = 1
      }
      action = {
        type = "expire"
      }
    }]
  })
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: "ecr_repository_prefix" is a required string the provider length-constrains to 2-30 characters (validate: "expected length of ecr_repository_prefix to be in the range (2 - 30)"); the generic tofu-<cohort>-cohort-<type> placeholder is 44 characters
resource "aws_ecr_pull_through_cache_rule" "app" {
  ecr_repository_prefix = "tofu-stragglers"
  upstream_registry_url = "placeholder"
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: "principal_arn" is a required string the provider validates is a well-formed ARN (validate: "The provided value cannot be parsed as an ARN"); the generic placeholder string is not one
resource "aws_ecr_pull_time_update_exclusion" "app" {
  principal_arn = "arn:aws:iam::000000000000:role/tofu-stragglers-cohort-ecr-pull-exclusion"
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: "applied_for" is a required set of strings the provider validates against a fixed set (validate: "expected applied_for to be one of [\"REPLICATION\" \"PULL_THROUGH_CACHE\" \"CREATE_ON_PUSH\"]"); the generic placeholder string matches none of them
resource "aws_ecr_repository_creation_template" "app" {
  prefix      = "tofu-stragglers-cohort-ecr-repository-creation-template"
  applied_for = ["CREATE_ON_PUSH"]
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: schema requires "policy" as a plain string, but the provider validates it is well-formed JSON (validate: "\"policy\" contains an invalid JSON"), the same shape as aws_s3_bucket_policy above
resource "aws_ecr_repository_policy" "app" {
  repository = aws_ecr_repository.stragglers.name
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Sid       = "AllowPull"
      Effect    = "Allow"
      Principal = "*"
      Action    = ["ecr:GetDownloadUrlForLayer", "ecr:BatchGetImage"]
      Resource  = "arn:aws:ecr:us-east-1:000000000000:repository/tofu-stragglers-cohort-ecr-repository-policy"
    }]
  })
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: "core_network_id" is a required string the provider length- and format-constrains (validate: "expected length of core_network_id to be in the range (0 - 50)" and "invalid value for core_network_id (must be a valid Core Network ID)"); the generic tofu-<cohort>-cohort-<type> placeholder matches neither. "policy_document" is a required string the schema does not constrain, but the provider validates it is well-formed JSON (validate: "\"policy_document\" contains an invalid JSON") - set to the shape the provider's own Core Network Policy documentation describes (version, core-network-configuration, segments), the same minimal-but-well-formed-JSON standard aws_networkfirewall_rule_group's own override uses for its own service-specific document shape.
resource "aws_networkmanager_core_network_policy_attachment" "app" {
  core_network_id = "core-network-0123456789abcdef0"
  policy_document = jsonencode({
    version = "2021.12"
    "core-network-configuration" = {
      "vpn-ecmp-support" = false
      "asn-ranges"       = ["64512-64555"]
    }
    segments = [{
      name = "segment1"
    }]
  })
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: storage_class
resource "aws_storagegateway_tape_pool" "app" {
  pool_name     = "tofu-stragglers-cohort-storagegateway-tape-pool"
  storage_class = "GLACIER"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_storagegateway_tape_pool.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: "access_role" is a required string the schema does not constrain, but the provider validates it is a well-formed ARN (validate: "\"access_role\" (placeholder) is an invalid ARN: arn: invalid prefix"); the generic placeholder string is not one
resource "aws_transfer_agreement" "app" {
  access_role        = "arn:aws:iam::000000000000:role/tofu-stragglers-cohort-transfer-agreement"
  base_directory     = "placeholder"
  local_profile_id   = "placeholder"
  partner_profile_id = "placeholder"
  server_id          = "placeholder"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_transfer_agreement.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: usage
resource "aws_transfer_certificate" "app" {
  certificate = "placeholder"
  usage       = "SIGNING"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_transfer_certificate.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: "profile_type" is a required string the provider validates against a fixed set (validate: "expected profile_type to be one of [\"LOCAL\" \"PARTNER\"]"); the generic placeholder string matches neither
resource "aws_transfer_profile" "app" {
  as2_id       = "placeholder"
  profile_type = "LOCAL"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_transfer_profile.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: identity_provider_details is a required block appearing zero times in the generic pass's output (the wire schema's own MinItems does not force it, unlike a required string argument) - not caught by the generic required-only pass, only surfaced by "terraform validate" ("Block identity_provider_details must have a configuration value as the provider has marked it as required"). A wholly empty block satisfies validate, but not apply: hand-verifying this cohort against the pinned floci image surfaced a provider-side panic expanding an empty identity_provider_details ("Expanding ...webAppIdentityProviderDetailsModel returned nil"), reachable independently of floci since it happens client-side during request marshaling, before any HTTP call. identity_center_config's own fields are Optional, but populating them with placeholder values avoids the empty-block panic entirely.
resource "aws_transfer_web_app" "app" {
  identity_provider_details {
    identity_center_config {
      instance_arn = "arn:aws:sso:::instance/ssoins-1234567890abcdef"
      role         = "arn:aws:iam::000000000000:role/tofu-stragglers-cohort-transfer-web-app"
    }
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_transfer_web_app.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: none
resource "aws_transfer_web_app_customization" "app" {
  web_app_id = aws_transfer_web_app.app.web_app_id
}
