# Supporting, not coverage - added only so aws_lb.apigateway's referring resources have a value to point at: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: none
resource "aws_lb" "apigateway" {
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_lb.apigateway"
  }
}
