// Copyright (c) The OpenTofu Authors
// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2023 HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package residue

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

// TestContributingArtifactTableNamesTheWriter is issue #1222's fourth guard.
//
// contributing/README.md's "Measurement" table maps each artifact to the
// tool that writes it. That is a hand-kept copy of a list this package
// already derives: discoverGeneratorArtifacts (artifact_readers_test.go)
// finds each committed artifact's writer from the generators' own
// os.WriteFile paths and the artifacts' own generated_by. The table said
// live/rowgen-buckets.json came from tools/survey-gen; both signals say
// tools/row-gen.
//
// So every row whose artifact the scan can see must name the writer the scan
// found. A row the scan cannot see must be listed in tableRowsTheScanCannotSee
// with the exact cell it carries, so an exception bounds what it allows, and
// an exception the scan has since learned to see fails until it is removed.
func TestContributingArtifactTableNamesTheWriter(t *testing.T) {
	root := repoRoot(t)
	writers := discoverGeneratorArtifacts(t, root)
	rows := measurementTableRows(t, root)
	if len(rows) == 0 {
		t.Fatal("found no rows in contributing/README.md's Measurement table; this guard is seeing nothing")
	}

	seenException := map[string]bool{}
	for _, r := range rows {
		writerDir, discovered := writers[r.artifact]
		cell, excepted := tableRowsTheScanCannotSee[r.artifact]
		switch {
		case discovered && excepted:
			t.Errorf("%s is listed in tableRowsTheScanCannotSee, but the scan now finds its writer "+
				"(tools/%s); remove the exception", r.artifact, writerDir)
		case discovered:
			want := "tools/" + writerDir
			if !namesTool(r.producer, want) {
				t.Errorf("contributing/README.md says %s is generated by %s; its writer is %s "+
					"(artifact_readers_test.go's write-set scan)", r.artifact, r.producer, want)
			}
		case excepted:
			seenException[r.artifact] = true
			if r.producer != cell {
				t.Errorf("contributing/README.md's row for %s reads %q; the exception for it allows "+
					"exactly %q. Re-check the producer and update both together", r.artifact, r.producer, cell)
			}
		default:
			t.Errorf("contributing/README.md lists %s (generated by %s), and the write-set scan cannot "+
				"see who writes it. Make its writer discoverable, or add it to "+
				"tableRowsTheScanCannotSee with the cell checked by hand", r.artifact, r.producer)
		}
	}
	for a := range tableRowsTheScanCannotSee {
		if !seenException[a] {
			if _, discovered := writers[a]; !discovered {
				t.Errorf("tableRowsTheScanCannotSee lists %s, which the table no longer has; remove it", a)
			}
		}
	}
}

// tableRowsTheScanCannotSee are the table's rows whose writer
// discoverGeneratorArtifacts does not find, each with the producer cell it
// was checked to carry.
var tableRowsTheScanCannotSee = map[string]string{
	// tools/corpus-gen takes its -out from flag.String (main.go) and writes
	// through a helper parameter, the shape artifact_readers_test.go names
	// as invisible to both signals.
	"live/corpus-refusals.json": "`tools/corpus-gen`",
	// Not a tool: the table itself says it is superseded by gauntlet.json.
	"live/corpus-crossing-manifest.json": "the crossing runs",
}

type tableRow struct{ artifact, producer string }

var tableRowRE = regexp.MustCompile("^\\| `([^`]+)` \\| ([^|]+?) \\|")

func measurementTableRows(t *testing.T, root string) []tableRow {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join(root, "contributing", "README.md"))
	if err != nil {
		t.Fatalf("reading contributing/README.md: %v", err)
	}
	var rows []tableRow
	in := false
	for _, line := range strings.Split(string(raw), "\n") {
		if strings.HasPrefix(line, "## ") {
			in = strings.TrimSpace(line) == "## Measurement"
			continue
		}
		if !in {
			continue
		}
		if m := tableRowRE.FindStringSubmatch(line); m != nil {
			rows = append(rows, tableRow{artifact: m[1], producer: strings.TrimSpace(m[2])})
		}
	}
	return rows
}

// namesTool reports whether a producer cell names tool as its command: a
// backticked span starting with exactly that path, so "tools/row-gen" is not
// satisfied by "tools/row-gen-x".
func namesTool(cell, tool string) bool {
	if !strings.HasPrefix(cell, "`"+tool) {
		return false
	}
	rest := cell[len(tool)+1:]
	return strings.HasPrefix(rest, "`") || strings.HasPrefix(rest, " ")
}
