package residue

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
	"unicode/utf8"
)

// ── issue #1294: no shell script we sweep may be binary to grep ──────────
//
// live/e2e/corpus-mastino-dns/run.sh carried four NUL bytes in 159,562, in
// two comment blocks that pasted a measured record-store tombstone file
// verbatim. grep classes a file with a NUL as binary and skips it: no line
// output, no warning, exit 0 across the sweep. The file is simply not in
// the answer, and nothing says so.
//
// That cost time three times in one session. PR #1157's sweep of the
// crossing scripts counted 23 of 24. #1214 had to add a guard asserting the
// missing script was in its population at all. #1291's issue text said 36
// call sites where a real read found 41, all five of the missing ones in
// that script.
//
// Each time it was rediscovered and guarded locally, as a convention
// ("read with os.ReadFile, not grep") that the next author was never told.
// This is that rule, stated once, as the property it actually rests on:
//
//	NO SHELL SCRIPT UNDER live/ OR scripts/ MAY CONTAIN A BYTE THAT MAKES
//	grep TREAT IT AS BINARY.
//
// Stated that way rather than as a ban on grep, because a ban only reaches
// sweeps written in this tree, and neither #1157 nor #1291 was one - both
// were a grep an author typed at a terminal, which no guard in this
// repository can see. Keeping the population textual makes grep a correct
// tool over it instead of a forbidden one, and that does reach the
// terminal. See TestNoSweptShellScriptIsBinaryToGrep's limits comment for
// what this still does not cover.

// grepSweptRoots are the directories whose shell scripts something in this
// repository sweeps: live/ holds the crossing scripts (e2e/*/run.sh), their
// shared helpers (e2e/lib/*.sh) and the live-cert scripts; scripts/ holds
// the developer and CI entry points. Both are swept by guards in this
// package and in tools/gauntlet, and by hand far more often.
var grepSweptRoots = []string{"live", "scripts"}

// binaryToGrep reports, in words, why grep would decline to read data as
// text, or "" if it would read it.
//
// Two conditions, because grep implementations differ and the guard has to
// hold for whichever one is on the author's PATH:
//
//   - A NUL byte. Every implementation treats this as binary - GNU grep,
//     BSD grep (the macOS default) and ugrep alike. This is the condition
//     corpus-mastino-dns tripped.
//   - Invalid UTF-8. GNU grep and ugrep class an encoding error in a
//     multibyte locale as binary too; BSD grep in the C locale does not.
//     Included because the union is what makes the answer the same
//     everywhere, and the whole failure being guarded here is a sweep whose
//     answer depended on something the author could not see.
func binaryToGrep(data []byte) string {
	if i := bytes.IndexByte(data, 0); i >= 0 {
		return fmt.Sprintf("a NUL byte at offset %d", i)
	}
	if !utf8.Valid(data) {
		for i := 0; i < len(data); {
			r, size := utf8.DecodeRune(data[i:])
			if r == utf8.RuneError && size <= 1 {
				return fmt.Sprintf("invalid UTF-8 at offset %d", i)
			}
			i += size
		}
		return "invalid UTF-8"
	}
	return ""
}

// scanSweptShellScripts reads every *.sh under each of roots (relative to
// base) with os.ReadFile - not grep, which is the point - and reports how
// many it read and which of them grep would decline. Directories whose name
// begins with "." are skipped: .terraform/ and .git/ hold nothing anyone
// sweeps, and .terraform/ is regenerated by every estate run.
//
// Taking base as an argument is what lets the BREAK arms below run this
// same function over a planted population rather than assert about it.
func scanSweptShellScripts(base string, roots []string) (scanned int, violations []string, err error) {
	for _, root := range roots {
		dir := filepath.Join(base, root)
		if _, statErr := os.Stat(dir); statErr != nil {
			if os.IsNotExist(statErr) {
				continue
			}
			return 0, nil, statErr
		}
		walkErr := filepath.WalkDir(dir, func(p string, d os.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if d.IsDir() {
				if p != dir && strings.HasPrefix(d.Name(), ".") {
					return filepath.SkipDir
				}
				return nil
			}
			if !strings.HasSuffix(d.Name(), ".sh") {
				return nil
			}
			data, err := os.ReadFile(p)
			if err != nil {
				return err
			}
			scanned++
			rel, err := filepath.Rel(base, p)
			if err != nil {
				return err
			}
			if why := binaryToGrep(data); why != "" {
				violations = append(violations, fmt.Sprintf("%s: %s", filepath.ToSlash(rel), why))
			}
			return nil
		})
		if walkErr != nil {
			return 0, nil, walkErr
		}
	}
	sort.Strings(violations)
	return scanned, violations, nil
}

// TestNoSweptShellScriptIsBinaryToGrep is the guard.
//
// WHAT IT COVERS. Every *.sh under live/ and scripts/, whoever reads them
// and however: a Go guard globbing and os.ReadFile-ing them, a shell sweep
// in this tree, or a grep an author types at a terminal. Keeping the files
// textual is what makes all three agree. The next file to acquire a control
// byte fails here the day it lands, instead of after a third sweep has
// quietly under-counted.
//
// WHAT IT DOES NOT COVER, stated plainly because #1294 asked and because a
// guard whose reach is overstated is the same failure one rung up:
//
//   - A sweep over some OTHER population. .corpus/ (vendored third-party
//     modules), internal/ fixtures, and anything added under a new
//     directory are outside grepSweptRoots, and grep over them still has
//     the blind spot. Widen grepSweptRoots when a sweep starts reading
//     somewhere new.
//   - grep declining a file for a reason that is neither a NUL nor an
//     encoding error. No such reason is known for the implementations
//     named on binaryToGrep, but the classifier is a model of them, not
//     the tools themselves.
//   - The gap between a commit and CI. A working tree can carry a NUL
//     while an author runs the sweep that misses it.
//   - Someone grepping a file this guard has never seen. The issue asked
//     for a guard that fails a new grep-based SWEEP; scanning this tree's
//     own text for one was tried and abandoned - the prose corpus quotes
//     grep recipes hundreds of times (live/corpus-crossing-manifest.json
//     alone), so the scan is all false positives. That half of the class is
//     not closed, and calling it closed would be the same silent-pass shape
//     this issue is about.
//
// Belt and braces: .gitattributes marks *.sh as text, so `git grep` reads a
// shell script in full even if one does acquire a NUL between landings.
// Measured, not assumed - see TestGitattributesKeepsGitGrepReadingShell.
func TestNoSweptShellScriptIsBinaryToGrep(t *testing.T) {
	root := repoRoot(t)
	scanned, violations, err := scanSweptShellScripts(root, grepSweptRoots)
	if err != nil {
		t.Fatal(err)
	}
	if scanned == 0 {
		t.Fatalf("no *.sh found under %v - the guard checked nothing, which reads as a pass and is worse than not existing", grepSweptRoots)
	}
	if len(violations) > 0 {
		t.Errorf("shell script(s) grep would class as binary and SKIP IN SILENCE, at exit 0, in every sweep of them (issue #1294; the same byte cost PR #1157 a 24th script and gave #1291 a count of 36 where a real read found 41):\n  %s\n\nQuote a control byte as an escape (\\0, \\x1b) rather than pasting the byte: a transcript in a comment reads better that way too - a raw NUL rendered corpus-mastino-dns's record key as \"...datacite.orgtype=A\", hiding the very separator the comment existed to show.", strings.Join(violations, "\n  "))
	}
	t.Logf("%d shell script(s) under %v, all readable by grep", scanned, grepSweptRoots)
}

// TestScanIsRedOnAPlantedControlByte runs the guard's own scanner over a
// planted population rather than asserting what it would do: one clean
// script it must pass, one carrying the exact byte corpus-mastino-dns
// carried, and one carrying an encoding error. A classifier written from
// the implementation passes forever; these arms are the proof it can fail.
func TestScanIsRedOnAPlantedControlByte(t *testing.T) {
	// The clean arm first: if this is not green, a red arm below proves
	// nothing, because the scanner might be failing everything.
	base := t.TempDir()
	mustWrite(t, filepath.Join(base, "live", "e2e", "clean", "run.sh"), []byte("#!/usr/bin/env bash\necho name=a type=A zone_id=z\n"))
	scanned, violations, err := scanSweptShellScripts(base, grepSweptRoots)
	if err != nil {
		t.Fatal(err)
	}
	if scanned != 1 {
		t.Fatalf("planted 1 script, scanner read %d - the walk is not finding the population it claims to", scanned)
	}
	if len(violations) != 0 {
		t.Fatalf("the clean script is reported as binary to grep: %v", violations)
	}

	for _, arm := range []struct {
		name    string
		body    []byte
		wantSub string
	}{
		{
			// Byte for byte what live/e2e/corpus-mastino-dns/run.sh
			// carried at line 1857 before #1294: a NUL-joined record key
			// pasted into a shell COMMENT. Inert to bash, fatal to grep.
			name:    "the mastino comment, verbatim",
			body:    append([]byte("#!/usr/bin/env bash\n#    "), []byte("name=staging12.datacite.org\x00type=A\x00zone_id=<...>\necho ok\n")...),
			wantSub: "a NUL byte at offset",
		},
		{
			name:    "an encoding error",
			body:    []byte("#!/usr/bin/env bash\n# caf\xe9\necho ok\n"),
			wantSub: "invalid UTF-8 at offset",
		},
	} {
		t.Run(arm.name, func(t *testing.T) {
			base := t.TempDir()
			mustWrite(t, filepath.Join(base, "live", "e2e", "clean", "run.sh"), []byte("#!/usr/bin/env bash\necho ok\n"))
			mustWrite(t, filepath.Join(base, "live", "e2e", "offender", "run.sh"), arm.body)
			scanned, violations, err := scanSweptShellScripts(base, grepSweptRoots)
			if err != nil {
				t.Fatal(err)
			}
			if scanned != 2 {
				t.Fatalf("planted 2 scripts, scanner read %d", scanned)
			}
			if len(violations) != 1 {
				t.Fatalf("want exactly the offender reported, got %d violation(s): %v", len(violations), violations)
			}
			if !strings.HasPrefix(violations[0], "live/e2e/offender/run.sh: ") {
				t.Errorf("the guard named the wrong file: %q", violations[0])
			}
			if !strings.Contains(violations[0], arm.wantSub) {
				t.Errorf("violation %q does not say %q, so it would not tell the next author what to fix", violations[0], arm.wantSub)
			}
			t.Logf("red as required: %s", violations[0])
		})
	}
}

// TestTheMastinoBytesAreGoneAndGrepAgreesWithARealRead pins the instance
// #1294 cleared, in the terms the issue measured it in. Two readings of the
// same file that used to disagree by five: grep's, and one that reads
// bytes. Asserted by value so that reintroducing the byte fails here with
// the number, not only in the population guard above.
func TestTheMastinoBytesAreGoneAndGrepAgreesWithARealRead(t *testing.T) {
	const rel = "e2e/corpus-mastino-dns/run.sh"
	sources, err := CrossingScriptSources(".")
	if err != nil {
		t.Fatal(err)
	}
	src, ok := sources[rel]
	if !ok {
		t.Fatalf("live/%s is not in the scanned population", rel)
	}
	if why := binaryToGrep([]byte(src)); why != "" {
		t.Fatalf("live/%s is binary to grep again (%s) - #1294 removed four NUL bytes from two comment transcripts there; quote control bytes as escapes", rel, why)
	}
	// The five call sites #1291's grep-derived count of 36 was missing.
	const needle = "gauntlet_record_count"
	if got := strings.Count(src, needle); got != 5 {
		t.Errorf("live/%s carries %d %s call site(s), want 5 - #1291's grep read 0 of them here while a real read found 5; if the script genuinely changed, re-derive this number from a real read and say so", rel, got, needle)
	}
}

// TestGitattributesKeepsGitGrepReadingShell. `git grep` is not plain grep:
// on a file with a NUL it prints "Binary file X matches" - a match with no
// line, which a sweep piping to `wc -l` counts as one line instead of N.
// The `diff` attribute makes git treat the path as text and git grep then
// reads it in full. Measured on a scratch repository in #1294 before this
// line was added; asserted here as the .gitattributes entry, because the
// entry is the thing that can be deleted.
func TestGitattributesKeepsGitGrepReadingShell(t *testing.T) {
	data, err := os.ReadFile(filepath.Join(repoRoot(t), ".gitattributes"))
	if err != nil {
		t.Fatal(err)
	}
	const want = "*.sh text eol=lf diff"
	if !strings.Contains(string(data), want) {
		t.Errorf(".gitattributes no longer carries %q. Without it, `git grep` over a shell script that has acquired a NUL reports \"Binary file ... matches\" instead of its lines (issue #1294).", want)
	}
}

func mustWrite(t *testing.T, path string, data []byte) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		t.Fatal(err)
	}
}
