// Copyright (c) The OpenTofu Authors
// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2023 HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package residue

import (
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The floci tier copies each fixture's .terraform.lock.hcl into a scratch
// directory so that `terraform init` trusts the shared plugin cache
// (flocitest.CopyFixtureDir). Terraform verifies a package it links from
// that cache against the lock file's h1: hashes, and an h1: is
// per-platform. The four fixture lock files carried exactly one, generated
// on darwin_arm64, so on the ubuntu runner the first init of the night
// downloaded and passed and every later one failed with
//
//	Error: Failed to install provider from shared cache
//	... doesn't match any of the checksums recorded in the dependency lock file.
//
// Eleven packages, three nights (2026-09-19 to 2026-09-21, the first nights
// the tier had a terraform binary at all - #1280), and a laptop could not
// reproduce it because a laptop is the platform the hash was for (#1316).
//
// The fix is a lock file with one h1: per platform the tier runs on, made
// in a scratch copy of the fixture with
//
//	terraform providers lock -platform=linux_amd64 -platform=linux_arm64 \
//	    -platform=darwin_amd64 -platform=darwin_arm64
//
// and this test holds every fixture lock file to that. A lock file
// regenerated by a plain `terraform init` on one machine drops back to a
// single h1: and fails here rather than on the next night.
func TestFixtureLockFilesCarryEveryPlatformsHash(t *testing.T) {
	root := repoRoot(t)
	const wantPlatforms = 4
	var checked int
	// The fixtures the tier copies live under these two roots; the
	// upstream command test data under internal/command carries lock
	// files of its own that are inputs to init tests, not fixtures the
	// shared cache ever serves.
	for _, base := range []string{"live/e2e", "internal/live"} {
		err := filepath.WalkDir(filepath.Join(root, base), func(path string, d fs.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if d.IsDir() && (d.Name() == ".terraform" || d.Name() == "node_modules") {
				return filepath.SkipDir
			}
			if d.IsDir() || d.Name() != ".terraform.lock.hcl" {
				return nil
			}
			b, rerr := os.ReadFile(path)
			if rerr != nil {
				return rerr
			}
			checked++
			h1 := strings.Count(string(b), `"h1:`)
			if h1 < wantPlatforms {
				rel, _ := filepath.Rel(root, path)
				t.Errorf("%s carries %d h1: hash(es), want at least %d (linux_amd64, linux_arm64, darwin_amd64, darwin_arm64): an init from the shared plugin cache on any other platform fails its checksum check; regenerate with `terraform providers lock -platform=...` in a copy of the fixture", rel, h1, wantPlatforms)
			}
			return nil
		})
		if err != nil {
			t.Fatal(err)
		}
	}
	if checked < 4 {
		t.Fatalf("found only %d fixture lock files under live/e2e and internal/; the walk is broken rather than the fixtures having moved", checked)
	}
}
