// Copyright (c) The OpenTofu Authors
// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2023 HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package residue

import (
	"encoding/json"
	"os"
	"path/filepath"
	"sort"
	"testing"

	"github.com/intentius/choudoufu/internal/live/identity"
)

// This file crosses the two halves of GitHub issue #272's evidence and pins
// what the crossing reaches.
//
// The claim being evidenced is narrow: for a resource type whose name AWS
// itself guarantees unique within an account and region, a live object can be
// bound by matching that name against a listing, and doing so is not the
// content-match guess internal/live/foreign refuses to make. It is reading
// the identity the configuration already states.
//
// The two halves, neither sufficient alone:
//
//   - live/import-grammar.json's argument_reference[].declared_unique, from
//     the provider's own argument-reference prose (tools/importdocs-gen);
//   - live/registry.json's unique_name_property, from the CloudFormation
//     registry schema's own description of the same property
//     (tools/registry-gen).
//
// Both read the same rule, internal/live/uniquename.Asserted, over two texts
// AWS wrote independently. The rule's doc comment carries every phrasing it
// deliberately refuses; this file carries what happens when the two answers
// are laid side by side.
//
// # What this file does NOT do
//
// It does not admit anything. No type moves out of
// [identity.MarkerlessTypes] on the strength of this evidence yet, because
// the discovery leg that would USE the evidence does not exist: nothing in
// internal/live/discovery compares a listed object's own property against a
// declared argument's value. Admitting a type before that leg lands would be
// plan-and-create-only support for a type whose whole problem is that a later
// run cannot find the object again - the exact debt the markerless veto's own
// comment names. This file is the evidence, ratified and measured, waiting
// for its consumer.

// uniqueNameEvidence is one type's crossed evidence.
type uniqueNameEvidence struct {
	TFType string
	CFN    string
	// Property is where in a Cloud Control ResourceDescription's Properties
	// map the name lives, which is what a binding leg would read.
	Property string
	// Markerless reports whether this type would be vetoed as markerless
	// WITHOUT the mechanism this evidence feeds. Only these types have
	// anything to gain: a taggable type is already found by its marker, and
	// one that names itself from configuration never reaches discovery at
	// all.
	//
	// It is a union of two states rather than a read of
	// [identity.MarkerlessTypes] alone, and it has to be: a type the
	// mechanism successfully rescued has LEFT that roster, so reading the
	// roster would report the reach shrinking to nothing at the exact moment
	// the mechanism started working. The second half - an admitted row
	// carrying a UniqueName - is that same population seen from the other
	// side.
	Markerless bool
}

// crossedUniqueNameEvidence computes the crossing from the two committed
// artifacts. It is a function rather than a fixture so every test below reads
// the same derivation, and so a change to either generator shows up in all of
// them at once.
func crossedUniqueNameEvidence(t *testing.T) []uniqueNameEvidence {
	t.Helper()

	type argRef struct {
		Name           string `json:"name"`
		Required       bool   `json:"required"`
		DeclaredUnique bool   `json:"declared_unique"`
	}
	var grammar struct {
		Rows []struct {
			TFType    string   `json:"tf_type"`
			Arguments []argRef `json:"argument_reference"`
		} `json:"rows"`
	}
	readArtifact(t, "import-grammar.json", &grammar)

	var registry struct {
		Types []struct {
			TypeName           string `json:"type_name"`
			UniqueNameProperty string `json:"unique_name_property"`
		} `json:"types"`
	}
	readArtifact(t, "registry.json", &registry)

	var mapping struct {
		Rows []struct {
			TFType  string `json:"tf_type"`
			CFNType string `json:"cfn_type"`
		} `json:"rows"`
	}
	readArtifact(t, "mapping.json", &mapping)

	cfnOf := make(map[string]string, len(mapping.Rows))
	for _, r := range mapping.Rows {
		cfnOf[r.TFType] = r.CFNType
	}
	propOf := make(map[string]string, len(registry.Types))
	for _, e := range registry.Types {
		if e.UniqueNameProperty != "" {
			propOf[e.TypeName] = e.UniqueNameProperty
		}
	}

	var out []uniqueNameEvidence
	for _, row := range grammar.Rows {
		// The provider half. The argument has to be REQUIRED: an optional
		// name is one a configuration may leave out, and a name the
		// configuration does not state is a name no listing can be matched
		// against. aws_lb is the worked example - its name is genuinely
		// documented unique per account, and genuinely autogenerated when
		// omitted, so half its instances would have nothing to match.
		declared := false
		for _, a := range row.Arguments {
			if a.Name == "name" && a.Required && a.DeclaredUnique {
				declared = true
				break
			}
		}
		if !declared {
			continue
		}
		// The registry half, reached through the type's CFN mapping.
		cfn := cfnOf[row.TFType]
		prop, ok := propOf[cfn]
		if !ok {
			continue
		}
		_, vetoed := identity.MarkerlessTypes[row.TFType]
		markerless := vetoed || identity.DefaultTable[row.TFType].UniqueName.Set()
		out = append(out, uniqueNameEvidence{
			TFType:     row.TFType,
			CFN:        cfn,
			Property:   prop,
			Markerless: markerless,
		})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].TFType < out[j].TFType })
	return out
}

func readArtifact(t *testing.T, name string, into any) {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(".", name))
	if err != nil {
		t.Fatalf("reading %s: %v", name, err)
	}
	if err := json.Unmarshal(b, into); err != nil {
		t.Fatalf("decoding %s: %v", name, err)
	}
}

// TestUniqueNameEvidenceIsCrossed pins the crossed population by name.
//
// The list is pinned rather than counted because the point of issue #272's
// bar is WHICH types clear it, not how many. A regenerated artifact that
// moves a type in or out is a change to what this fork claims AWS guarantees,
// and it should be read one type at a time.
func TestUniqueNameEvidenceIsCrossed(t *testing.T) {
	want := []string{
		// "The catalog name must be unique for the AWS account" in both
		// texts. Already admitted and imported BY its name, so it gains
		// nothing here - it is in the list because the rule found it, and a
		// rule that only ever returned the types someone was looking for
		// would be a hand-written list with extra steps.
		"aws_athena_data_catalog",
		"aws_cloudfront_cache_policy",
		"aws_cloudfront_origin_request_policy",
		"aws_cloudfront_realtime_log_config",
		"aws_cloudfront_response_headers_policy",
		"aws_route53_cidr_collection",
		"aws_timestreaminfluxdb_db_cluster",
		"aws_timestreaminfluxdb_db_instance",
	}
	got := crossedUniqueNameEvidence(t)
	var names []string
	for _, e := range got {
		names = append(names, e.TFType)
	}
	if len(names) != len(want) {
		t.Errorf("crossed evidence covers %d types, want %d:\n got  %v\n want %v", len(names), len(want), names, want)
		return
	}
	for i := range want {
		if names[i] != want[i] {
			t.Errorf("crossed evidence[%d] = %q, want %q (full: %v)", i, names[i], want[i], names)
		}
	}
}

// TestUniqueNameEvidenceRefusesTheUnprovenTypes is the permanent negative
// case, and the reason this whole mechanism is worth being strict about.
//
// aws_cloudfront_origin_access_control sits beside the two CloudFront policy
// types in the same service, is untaggable in the same way, is listed by
// Cloud Control in the same way, and appears in the same estates. What
// separates it is only the wording, and the wording is the whole evidence:
// its CreateOriginAccessControl error reads "An origin access control with
// the specified parameters already exists" rather than naming the name, its
// CFN schema says "A name to identify the origin access control" with no
// uniqueness claim, and the provider docs say "A name that identifies the
// Origin Access Control". The differently-worded error suggests the dedup key
// is the whole configuration tuple rather than the name alone, which would
// make a name match bind the wrong object.
//
// The other three are here for the shapes they represent - a name AWS says
// need not be unique, a name scoped to a parent rather than to the account,
// and a name whose uniqueness belongs to a value CloudFormation generates
// when the client supplies none.
func TestUniqueNameEvidenceRefusesTheUnprovenTypes(t *testing.T) {
	refused := map[string]string{
		"aws_cloudfront_origin_access_control": "neither source claims uniqueness; the create error names the parameters, not the name",
		"aws_gamelift_alias":                   "AWS says alias names do not need to be unique",
		"aws_route53_key_signing_key":          "unique only within one hosted zone, and a listing spans every hosted zone",
		"aws_api_gateway_api_key":              "the unique value is a physical ID CloudFormation generates, not a client-supplied name",
	}
	for _, e := range crossedUniqueNameEvidence(t) {
		if why, bad := refused[e.TFType]; bad {
			t.Errorf("%s cleared the two-source bar, but %s; review this: the crossing admitted a type whose name is not proven unique, which is a wrong-bind risk, not a coverage win", e.TFType, why)
		}
	}
}

// TestUniqueNameEvidencePropertyPathsAreResourceLevel checks the half of the
// registry rule that no wording guard can cover: the property found has to be
// the RESOURCE's own name, not the name of an element of a list inside it.
//
// A third of the schemas whose Name description says "unique" are describing
// a list element - AWS::GameLift::Fleet's ScalingPolicy.Name,
// AWS::SageMaker::ModelPackage's AdditionalInferenceSpecificationDefinition.
// Name. Those names are unique among their siblings inside one resource and
// say so plainly, and binding a live object by one would match every resource
// that happens to contain a sibling of that name.
func TestUniqueNameEvidencePropertyPathsAreResourceLevel(t *testing.T) {
	for _, e := range crossedUniqueNameEvidence(t) {
		if e.Property == "" {
			t.Errorf("%s crossed the bar with no property path; review this: a binding leg would have nowhere to read the name from", e.TFType)
		}
	}
	// The two nested-but-not-in-a-list paths this fork does reach are the
	// CloudFront config-object shape, and they are the reason the walk
	// descends at all rather than reading only top-level properties.
	nested := map[string]string{
		"aws_cloudfront_cache_policy":            "CachePolicyConfig/Name",
		"aws_cloudfront_origin_request_policy":   "OriginRequestPolicyConfig/Name",
		"aws_cloudfront_response_headers_policy": "ResponseHeadersPolicyConfig/Name",
	}
	for _, e := range crossedUniqueNameEvidence(t) {
		if want, ok := nested[e.TFType]; ok && e.Property != want {
			t.Errorf("%s property path = %q, want %q", e.TFType, e.Property, want)
		}
	}
}

// TestUniqueNameEvidenceReachesVetoedTypes records which of the crossed types
// the evidence could actually rescue, and is the honest form of "how much is
// this worth".
//
// A type that is taggable is already found by its ownership marker and gains
// nothing here; one whose identity the configuration states never reaches
// discovery at all. Only a type in [identity.MarkerlessTypes] is refused
// today FOR the reason this evidence answers - the provider mints the
// identity and there is nowhere to write a marker - and only those types
// would become admissible once the binding leg exists.
//
// Four of eight, at hashicorp/aws 6.59.0. Two of the four are the types issue
// #272 set out to reach; the other two the rule found on its own, which is
// the difference between a rule and a hand-written list.
func TestUniqueNameEvidenceReachesVetoedTypes(t *testing.T) {
	want := []string{
		"aws_cloudfront_cache_policy",
		"aws_cloudfront_origin_request_policy",
		"aws_cloudfront_response_headers_policy",
		"aws_route53_cidr_collection",
	}
	var got []string
	for _, e := range crossedUniqueNameEvidence(t) {
		if e.Markerless {
			got = append(got, e.TFType)
		}
	}
	if len(got) != len(want) {
		t.Errorf("evidence reaches %d markerless-vetoed types, want %d:\n got  %v\n want %v", len(got), len(want), got, want)
		return
	}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("markerless-vetoed reach[%d] = %q, want %q", i, got[i], want[i])
		}
	}
}

// TestUniqueNameEvidenceIsActedOn is the successor to a test this file used
// to carry, TestUniqueNameEvidenceIsNotActedOnYet, which asserted that no
// type had been admitted on this evidence because the discovery leg that
// would USE it did not exist. It does now
// (internal/live/discovery/uniquename.go), so the assertion inverts: every
// type the crossing reaches has to be admitted, carrying the evidence in its
// own row, and off the veto's roster.
//
// The three conditions are checked together on purpose. Each one alone is
// satisfiable by a half-landed change - a row in the table with no UniqueName
// on it would resolve and then be found by nothing; a UniqueName on a row
// still named by MarkerlessTypes would leave two rosters disagreeing about
// whether the type exists - and the failure mode of a half-landed change here
// is plan-and-create-only support for exactly the population that cannot be
// found again.
func TestUniqueNameEvidenceIsActedOn(t *testing.T) {
	reached := 0
	for _, e := range crossedUniqueNameEvidence(t) {
		if !e.Markerless {
			// Taggable, or named from its own configuration: found already,
			// and this mechanism has nothing to add. See
			// TestUniqueNameEvidenceReachesVetoedTypes.
			continue
		}
		reached++
		row, admitted := identity.DefaultTable[e.TFType]
		if !admitted {
			t.Errorf("%s crosses the two-source bar and is still outside the admission table; the evidence reaches it and nothing acts on it", e.TFType)
			continue
		}
		if row.UniqueName.Property != e.Property {
			t.Errorf("%s is admitted with UniqueName.Property = %q, but the registry says the name lives at %q; discovery would read the wrong place",
				e.TFType, row.UniqueName.Property, e.Property)
		}
		if !row.ServerAssigned {
			t.Errorf("%s is admitted without ServerAssigned; its identity IS minted by the provider - the name is how the object is found, not what its import ID is", e.TFType)
		}
		if _, vetoed := identity.MarkerlessTypes[e.TFType]; vetoed {
			t.Errorf("%s is both admitted and on the markerless veto's roster; the two must be disjoint", e.TFType)
		}
	}
	if reached == 0 {
		t.Fatal("no markerless-vetoed type was reached at all, so every assertion above passed over nothing")
	}
}

// TestUnprovenUniqueNameTypesStayRefused is acceptance criterion (d) of issue
// #272 and the permanent record of where the bar sits.
//
// TestUniqueNameEvidenceRefusesTheUnprovenTypes above checks that these types
// do not clear the CROSSING. This checks the consequence: they are still
// refused where a user meets them. The two are different claims, and only the
// second is about what ships - a crossing that correctly excluded a type
// while something else admitted it anyway would satisfy the first and none of
// the point.
func TestUnprovenUniqueNameTypesStayRefused(t *testing.T) {
	// aws_cloudfront_origin_access_control is the worked example, and the
	// reason it is worth naming a type in a test: it is the nearest possible
	// neighbour of the two CloudFront policy types that DID clear - same
	// service, same untaggability, same Cloud Control listing, same estates -
	// and the only thing separating them is the wording of two texts AWS
	// wrote. A rule loose enough to admit this type would be a rule reading
	// "a name to identify X" as a uniqueness guarantee.
	const unproven = "aws_cloudfront_origin_access_control"

	if _, admitted := identity.DefaultTable[unproven]; admitted {
		t.Errorf("%s is admitted; neither its provider argument reference nor its CloudFormation schema calls its name unique, and its create error names \"the specified parameters\" rather than the name - which suggests the dedup key is the whole configuration tuple, so a name match would bind the wrong object", unproven)
	}
	if _, vetoed := identity.MarkerlessTypes[unproven]; !vetoed {
		t.Errorf("%s is no longer on the markerless veto's roster; it is untaggable and server-assigned and nothing has been shown to find it again, so the veto is exactly where it belongs", unproven)
	}
	for _, e := range crossedUniqueNameEvidence(t) {
		if e.TFType == unproven {
			t.Errorf("%s reached the crossing at all; both halves of the evidence have to make the claim and neither does", unproven)
		}
	}
}
