# Supporting, not coverage - added only so aws_iam_group.identity's referring resources have a value to point at: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: path
resource "aws_iam_group" "identity" {
  name = "tofu-identity-cohort-iam-group"
  path = "/users/"
}

# Supporting, not coverage - added only so aws_iam_saml_provider.identity's referring resources have a value to point at: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: "saml_metadata_document" is a required string the schema does not constrain, but the provider validates its length (1000 - 10000000 characters, validate: "expected length of saml_metadata_document to be in the range (1000 - 10000000)"); the generic "placeholder" literal is 11 characters. Found triaging issue #432 (cohort "identity" fails apply on this exact check). Set to a well-formed, if fake, SAML IdP metadata document - not a real certificate, just XML shaped and padded past the provider's own floor so this exercises the actual CreateSAMLProvider call during a floci apply instead of failing before it
resource "aws_iam_saml_provider" "identity" {
  name                   = "tofu-identity-cohort-iam-saml-provider"
  saml_metadata_document = "<?xml version=\"1.0\" encoding=\"UTF-8\"?><md:EntityDescriptor xmlns:md=\"urn:oasis:names:tc:SAML:2.0:metadata\" entityID=\"https://idp.example.com/tofu-fixture\"><md:IDPSSODescriptor protocolSupportEnumeration=\"urn:oasis:names:tc:SAML:2.0:protocol\"><md:KeyDescriptor use=\"signing\"><ds:KeyInfo xmlns:ds=\"http://www.w3.org/2000/09/xmldsig#\"><ds:X509Data><ds:X509Certificate>+iX8xFu+aBARK7DB6uiMnODWpoPoRMYnMV3H2gnJIdrXMycLxqGN6FDk+KXIlkIVIYyB+iQw69TQuWLbIJ6J/Ts0IKsrbSVLkOFGMRN12yaw9bfpfkSnAXPsEcFobW0/bmHYs85B7agcduTncSjswM/Me1C5P0epjHAkvF6qCnC7EB4oUyUR0/eo4X42JqVdZ9bcDyMx9tmo+rogEYxzICg11KY8qMX0nQLaDPZah1A/sdDhEh8OOqfaRZf69J4HWptl17okGnGzQdF9fMflEZdU/yrufR9U5fBs+P9YgLI/U7lGbX82W3uyEhC44lFUXOdMbdEOmbjtq/KQQcB67LhJYM/bWgyAQ8BRymh1FW1C7yvEmC0qUyVY10T47LjuyvdV3LZf4oUzInJ+uPpyUwzHoPsTZxZSxXzT6pZihfpKBhg9GEvyKnsSPEEv37PTp70hllkhMo1kt9b6sIZBcfRx6H5jxv2Xg7yGSNg/5zisvEoumqkImOrMYtVn8/BtbphCf6BJZ8wLuV83ykRmR7cResbZaW7NfUZmlEbqnhKaWZcsrltAmBlLeryJPMnuc4htM9OvIV9pxy5+OIhfs/KgNEb3orTAJ99KRdXO3rP0glvq9RuS8i21Our7TRQL65NVSeNnlnucL48UT+0uTtNH6E2IY4ZzBaBe/ZQzRyJb2a5D/bPeg9lGOt6lR1gm5hkKZnZlvFyOfOq5dheJAryX8XJnsYgBwuKdTJF2jBf2rmmknD7cArZ617yiYcdQVrtt0/aXTvA9CTUVGq6Brw/ZfjjQ2QRK9y3zPM3/i49fjhYAk4ZRV9mYMQyPIn6UIqKwrw3xIVmCc0Q1+eNmW0elEDsLPm8Q1fzWPfMHyx4GTynmWyAM6WAqhO8hvoIGEJDBVtUW6zAOG7M4dgDeHxsSjrX0ghoG91Jz4nWHHYRAQjmoGm/THn9fYoM2qUmtCuiqnBYVqVAsbdbDQdhaUI9tURM3JnmyDw3BiiFJyULWVuoU8LWWUsFtqgC4ySvNNRu+qRKRW+8PGna1NAMAefo/ReFTP/9e+2y6trj87zA6AC/0znms8v/EEl/H43J8TJ0q2cl7d177LbUQscBxnfgLoJdH8vn9vPfmXavYlDBgdhHaV+yjsXkTzN9/TnJrO/tGjCt0Cpx6xay/RKDW+C1kc0/6Y/fDqo82I4JIYGYMneRx</ds:X509Certificate></ds:X509Data></ds:KeyInfo></md:KeyDescriptor><md:SingleSignOnService Binding=\"urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect\" Location=\"https://idp.example.com/tofu-fixture/sso\"/></md:IDPSSODescriptor></md:EntityDescriptor>"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_iam_saml_provider.identity"
  }
}

# Supporting, not coverage - added only so aws_iam_user.identity's referring resources have a value to point at: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: path
resource "aws_iam_user" "identity" {
  name = "tofu-identity-cohort-iam-user"
  path = "/system/"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_iam_user.identity"
  }
}
