# Supporting, not coverage - added only so aws_iam_group.identity's referring resources have a value to point at: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: path
resource "aws_iam_group" "identity" {
  name = "tofu-identity-cohort-iam-group"
  path = "/users/"
}

# Supporting, not coverage - added only so aws_iam_saml_provider.identity's referring resources have a value to point at: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: none
resource "aws_iam_saml_provider" "identity" {
  name                   = aws_iam_group.identity.name
  saml_metadata_document = "placeholder"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_iam_saml_provider.identity"
  }
}

# Supporting, not coverage - added only so aws_iam_user.identity's referring resources have a value to point at: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: path
resource "aws_iam_user" "identity" {
  name = "tofu-identity-cohort-iam-user"
  path = "/system/"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_iam_user.identity"
  }
}
