// Copyright (c) The OpenTofu Authors
// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2023 HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package main

import (
	"os"
	"path/filepath"
	"testing"
)

func testRepoRoot(t *testing.T) string {
	t.Helper()
	root, err := repoRoot()
	if err != nil {
		t.Fatal(err)
	}
	return root
}

// readCommittedSurface reads and decodes the committed
// live/fork-surface.json - the render_test.go counterpart of
// loadForkSurfaceArtifact in render.go, kept separate the same way
// readiness-gen's readCommitted (test-only) sits beside loadArtifact
// (production).
func readCommittedSurface(t *testing.T, root string) forkSurface {
	t.Helper()
	a, err := loadForkSurfaceArtifact(root)
	if err != nil {
		t.Fatal(err)
	}
	return a
}

// TestForkSurfaceSiteDataIsCurrent is issue #424's staleness guard,
// mirroring TestReadinessSiteDataIsCurrent (tools/readiness-gen): it holds
// SiteDataRel byte-for-byte to what render.go's renderSiteData produces from
// the committed live/fork-surface.json. Because the comparison is against
// the artifact's already-committed bytes (readCommittedSurface) and not a
// fresh diff, a live/fork-surface.json that changes - regenerated by `go
// run ./tools/forkdiff-gen` or hand-edited - without a matching `go run
// ./tools/forkdiff-gen -render` run fails this test, the same
// fail-when-stale pattern every other -render mode in this tree uses.
func TestForkSurfaceSiteDataIsCurrent(t *testing.T) {
	root := testRepoRoot(t)
	artifact := readCommittedSurface(t, root)
	want, err := renderSiteData(artifact)
	if err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(SiteDataRel))) //nolint:gosec // a fixed path in the checkout
	if err != nil {
		t.Fatalf("reading %s: %v (run `go run ./tools/forkdiff-gen -render` and commit the result)", SiteDataRel, err)
	}
	if string(got) != string(want) {
		t.Errorf("%s is stale; run `go run ./tools/forkdiff-gen -render` and commit the result", SiteDataRel)
	}
}

// TestSiteDataCountsAgree proves buildSiteData's totals are not free-
// floating: the grand total it carries equals the independently computed
// sum of the artifact's own Counts, for every named root plus other, and
// every named root is present in its Counts so the site's table cannot
// silently drop a row.
func TestSiteDataCountsAgree(t *testing.T) {
	root := testRepoRoot(t)
	artifact := readCommittedSurface(t, root)

	wantTotal := 0
	for _, r := range namedRoots {
		wantTotal += artifact.Counts[r]
	}
	wantTotal += artifact.Counts[otherBucket]
	if wantTotal == 0 {
		t.Fatal("live/fork-surface.json's counts sum to 0; this test is checking nothing - the artifact is stale or empty")
	}

	d := buildSiteData(artifact)
	if d.Total != wantTotal {
		t.Errorf("buildSiteData total = %d, want %d", d.Total, wantTotal)
	}
	if d.NamedTotal+d.OtherCount != d.Total {
		t.Errorf("named %d + other %d != total %d", d.NamedTotal, d.OtherCount, d.Total)
	}
	for _, r := range namedRoots {
		if _, ok := d.Counts[r]; !ok {
			t.Errorf("buildSiteData's counts lack named root %q", r)
		}
	}
	if len(d.NamedRoots) != len(namedRoots) {
		t.Errorf("buildSiteData carries %d named roots, want %d", len(d.NamedRoots), len(namedRoots))
	}
}
