// Copyright (c) The OpenTofu Authors
// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2023 HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package main

import (
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

func testRepoRoot(t *testing.T) string {
	t.Helper()
	root, err := repoRoot()
	if err != nil {
		t.Fatal(err)
	}
	return root
}

// readCommittedSurface reads and decodes the committed
// live/fork-surface.json - the render_test.go counterpart of
// loadForkSurfaceArtifact in render.go, kept separate the same way
// readiness-gen's readCommitted (test-only) sits beside loadArtifact
// (production).
func readCommittedSurface(t *testing.T, root string) forkSurface {
	t.Helper()
	a, err := loadForkSurfaceArtifact(root)
	if err != nil {
		t.Fatal(err)
	}
	return a
}

// TestForkSurfaceRenderedSpanIsCurrent is issue #424's staleness guard,
// mirroring TestReadinessRenderedSpansAreCurrent (tools/readiness-gen): it
// holds PositioningMDRel's fork-surface span byte-for-byte to what
// render.go's renderForkSurfaceSummary produces from the committed
// live/fork-surface.json. Because the comparison is against the artifact's
// already-committed bytes (readCommittedSurface) and not a fresh diff, a
// live/fork-surface.json that changes - regenerated by `go run
// ./tools/forkdiff-gen` or hand-edited - without a matching `go run
// ./tools/forkdiff-gen -render` run fails this test, the same
// fail-when-stale pattern every other -render mode in this tree uses.
func TestForkSurfaceRenderedSpanIsCurrent(t *testing.T) {
	root := testRepoRoot(t)
	artifact := readCommittedSurface(t, root)
	want := renderForkSurfaceSummary(artifact)

	path := filepath.Join(root, filepath.FromSlash(PositioningMDRel))
	doc, err := os.ReadFile(path) //nolint:gosec // a fixed path in the checkout
	if err != nil {
		t.Fatalf("reading %s: %v", PositioningMDRel, err)
	}
	md := string(doc)

	got, err := markers.Content(PositioningMDRel, md, spanForkSurface)
	if err != nil {
		t.Fatalf("%v", err)
	}
	if got != want {
		t.Errorf("%s's %q span is stale; run `go run ./tools/forkdiff-gen -render` and commit the result.\n--- committed ---\n%s\n--- rendered ---\n%s",
			PositioningMDRel, spanForkSurface, got, want)
	}

	out, err := markers.Replace(PositioningMDRel, md, spanForkSurface, want)
	if err != nil {
		t.Fatalf("rendering %s: %v", PositioningMDRel, err)
	}
	if out != md {
		t.Errorf("%s differs from its rendered form; run `go run ./tools/forkdiff-gen -render` and commit the result", PositioningMDRel)
	}
}

// TestRenderForkSurfaceSummaryCountsAgree proves renderForkSurfaceSummary's
// prose and table are not free-floating text: the grand total it renders
// (paragraph and the table's own "Total" row both) equals the independently
// computed sum of the artifact's own Counts, for every named root plus
// other. Made to fail on purpose while writing this test, by asserting
// against wantTotal+1 instead: it failed with a "never mentions" error, as
// expected.
func TestRenderForkSurfaceSummaryCountsAgree(t *testing.T) {
	root := testRepoRoot(t)
	artifact := readCommittedSurface(t, root)

	wantTotal := 0
	for _, r := range namedRoots {
		wantTotal += artifact.Counts[r]
	}
	wantTotal += artifact.Counts[otherBucket]
	if wantTotal == 0 {
		t.Fatal("live/fork-surface.json's counts sum to 0; this test is checking nothing - the artifact is stale or empty")
	}

	rendered := renderForkSurfaceSummary(artifact)

	wantLine := "**" + strconv.Itoa(wantTotal) + " files**"
	if !strings.Contains(rendered, wantLine) {
		t.Errorf("rendered fork-surface summary never opens with %q (the artifact's own total, %d):\n%s", wantLine, wantTotal, rendered)
	}
	wantTableTotal := "| **Total** | " + strconv.Itoa(wantTotal) + " |"
	if !strings.Contains(rendered, wantTableTotal) {
		t.Errorf("rendered fork-surface summary's table never has %q:\n%s", wantTableTotal, rendered)
	}
}
