// Copyright (c) The OpenTofu Authors
// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2023 HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package main

import (
	"fmt"
	"sort"
	"strings"
)

// versionsTF is versions.tf, byte-for-byte the same shape as
// live/e2e/estates/lambda/versions.tf and live/e2e/estate/versions.tf: the
// provider pin is the one thing every cohort estate shares verbatim, so it
// is not templated per cohort at all beyond the header comment naming this
// cohort.
func versionsTF(cohort string) string {
	return fmt.Sprintf(`# %s cohort — provider wiring only, identical in shape to
# live/e2e/estate/versions.tf and live/e2e/estates/lambda/versions.tf.
# Generated by tools/estate-gen; see that file's comment for why the
# provider block carries only the flags with no environment-variable form.

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    aws = {
      source  = %q
      version = "= %s"
    }
  }
}

provider "aws" {
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  s3_use_path_style           = true
}
`, cohort, providerSource, providerVersion)
}

// localsTF is locals.tf: just the estate_tag marker
// (live/MARKERS.md, P0.3), "<cohort>-cohort" - the same naming convention
// live/e2e/estates/lambda/locals.tf's "lambda-cohort" already uses.
func localsTF(cohort string) string {
	return fmt.Sprintf(`locals {
  # The marker's estate value (live/MARKERS.md, P0.3), distinct from the
  # demo estate's "stateless-e2e" and from every other cohort's own tag, so
  # no two cohorts collide if ever applied against the same account side by
  # side.
  estate_tag = %q
}
`, cohort+"-cohort")
}

// readmeMD is README.md: the per-type provenance table issue #56 asks for
// ("generated by estate-gen from <inputs>; overrides: none"), plus enough
// framing that a reader lands the same way live/e2e/estates/lambda/README.md
// and live/e2e/estates/example/README.md's readers do.
//
// moduleWrap changes two things about the write-up: the regenerate command
// carries -module-wrap, and the file table points at wrappedModuleDir/ for
// everything but versions.tf. It does not change the Gating paragraph's
// claim about internal/live/flocitest.FixtureDirs - a -module-wrap run is
// written wherever -out says, and a caller writing it under
// live/e2e/estates/ (picked up by the #48 union pin) is claiming the
// resulting tree loads through every fixture-wide test that pin sweeps,
// [loadConfig] included; see live/e2e/estate-module/README.md for the
// fixture this flag actually built, which is deliberately outside that
// tree for exactly this reason.
func readmeMD(cohort string, requested []string, g *generator, moduleWrap bool) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s cohort\n\n", cohort)
	fmt.Fprintf(&b, "Cohort: `%s`. Generated by `tools/estate-gen` (issue #56) from %s %s's schema and `internal/live/identity/table.go`'s identity table.\n\n",
		cohort, providerSource, providerVersion)
	regen := "go run ./tools/estate-gen -cohort " + cohort + " -out live/e2e/estates/" + cohort
	if moduleWrap {
		regen = "go run ./tools/estate-gen -cohort " + cohort + " -module-wrap -out <dir>"
	}
	b.WriteString("Regenerate with:\n\n```\n" + regen + "\n```\n\n")
	if moduleWrap {
		b.WriteString("Generated with `-module-wrap` (issue #59, 59b): every resource below lives\n")
		b.WriteString("in `" + wrappedModuleDir + "/`, called from a `module \"" + wrappedModuleDir + "\"` block in the root's\n")
		b.WriteString("`main.tf`, so this estate exercises the five walkers' traversal into a static\n")
		b.WriteString("module rather than planning at the root.\n\n")
	}

	b.WriteString("## Provenance\n\n")
	b.WriteString("| Resource | Kind | Overrides |\n|---|---|---|\n")
	for _, p := range g.order {
		kind := "coverage"
		if p.Kind == kindSupporting {
			kind = "supporting, not coverage"
		}
		overrides := "none"
		if ov, ok := typeOverrides[p.Addr.Type]; ok {
			overrides = strings.Join(ov.Reasons, "; ")
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s |\n", p.Addr, kind, overrides)
	}

	b.WriteString("\n## Requested types\n\n")
	sorted := append([]string(nil), requested...)
	sort.Strings(sorted)
	for _, t := range sorted {
		fmt.Fprintf(&b, "- `%s`\n", t)
	}

	b.WriteString("\n## Files\n\n")
	b.WriteString("| File | Contents |\n|---|---|\n")
	fmt.Fprintf(&b, "| `versions.tf` | `terraform`/`provider \"aws\"` blocks, identical in shape to `live/e2e/estate/versions.tf`. |\n")
	contentPrefix := ""
	if moduleWrap {
		fmt.Fprintf(&b, "| `main.tf` | The one module call: `module \"%s\" { source = \"./%s\" }`. |\n", wrappedModuleDir, wrappedModuleDir)
		contentPrefix = wrappedModuleDir + "/"
	}
	fmt.Fprintf(&b, "| `%slocals.tf` | `estate_tag` — %q, distinct from every other cohort's own tag. |\n", contentPrefix, cohort+"-cohort")
	fmt.Fprintf(&b, "| `%s%s.tf` | Every requested (coverage) resource. |\n", contentPrefix, cohort)
	if hasSupporting(g) {
		fmt.Fprintf(&b, "| `%ssupporting.tf` | Resources this generator added on its own so a required argument had something to reference - not a coverage row (see the Provenance table above). |\n", contentPrefix)
	}

	b.WriteString("\n## Gating\n\n")
	if moduleWrap {
		b.WriteString("Nothing here runs against a live or emulated cloud by default; see this directory's\n")
		b.WriteString("own README for which test drives it against floci.\n\n")
	} else {
		b.WriteString("Nothing here runs against a live or emulated cloud. `go test ./internal/live/lint/... ./internal/live/identity/...` picks this\n")
		b.WriteString("directory up through `internal/live/flocitest.FixtureDirs` (#48's union pin).\n\n")
	}
	fmt.Fprintf(&b, "`terraform validate` passes against the real provider release (%s) this fixture pins.\n", providerVersion)
	return b.String()
}

func hasSupporting(g *generator) bool {
	for _, p := range g.order {
		if p.Kind == kindSupporting {
			return true
		}
	}
	return false
}
