# Generated by tools/estate-gen -module-wrap -module-keys (issue #59, 59c).
# Every resource this cohort declares lives in ./wrapped instead of here, so that
# the five walkers' traversal into a keyed module is what this estate
# exercises. The for_each is a literal set of strings, the most static a
# for_each expression can be, so RuleChildModule admits it; each.key is
# passed through as the "key" variable, which is the only way a resource
# inside the module can learn its own instance's key (see
# wrapped/variables.tf).

module "wrapped" {
  source   = "./wrapped"
  for_each = toset(["a", "b"])
  key      = each.key
}
