# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: image_tag_mutability, image_scanning_configuration.scan_on_push
resource "aws_ecr_repository" "app" {
  name                 = "tofu-iam-ecr-cohort-ecr-repository"
  image_tag_mutability = "MUTABLE"
  image_scanning_configuration {
    scan_on_push = true
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_ecr_repository.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: path
resource "aws_iam_group" "app" {
  name = "tofu-iam-ecr-cohort-iam-group"
  path = "/users/"
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: role
resource "aws_iam_instance_profile" "app" {
  name = "tofu-iam-ecr-cohort-iam-instance-profile"
  role = aws_iam_role.iam-ecr.name
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_iam_instance_profile.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: aws_service_name is a required argument the provider validates by shape (validate: "must be a full service hostname e.g. elasticbeanstalk.amazonaws.com"); set to elasticbeanstalk.amazonaws.com, the provider's own documented example service, as the hand-written cohort chose
resource "aws_iam_service_linked_role" "app" {
  aws_service_name = "elasticbeanstalk.amazonaws.com"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_iam_service_linked_role.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: path
resource "aws_iam_user" "app" {
  name = "tofu-iam-ecr-cohort-iam-user"
  path = "/system/"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_iam_user.app"
  }
}
