# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: schema requires "policy" as a plain string, but the provider validates it is well-formed JSON (validate: "\"policy\" contains an invalid JSON"); set to the hand-written cohort's own registry policy - an allow-pull statement for the account root principal, kept verbatim (the Sid charset permits no cohort-derived hyphens)
resource "aws_ecr_registry_policy" "app" {
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Sid       = "TofuIamEcrCohortAllowPull"
      Effect    = "Allow"
      Principal = { AWS = "arn:aws:iam::000000000000:root" }
      Action    = ["ecr:GetDownloadUrlForLayer", "ecr:BatchGetImage"]
    }]
  })
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: scan_type is a required argument the provider validates as an enum (validate: "expected scan_type to be one of [\"BASIC\" \"ENHANCED\"], got placeholder"); set to "BASIC", the member the hand-written cohort used
resource "aws_ecr_registry_scanning_configuration" "app" {
  scan_type = "BASIC"
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: replication_configuration is optional in the wire schema (MinItems 0), so the generic pass renders an empty resource - but a replication configuration with no rule configures nothing, and the destination's region and registry_id carry provider-side shape validation (a region name and a 12-digit account ID) no generic placeholder satisfies. The hand-written block's literal us-west-2/000000000000 destination is kept: a placeholder region and registry ID rather than a second real account, the same "keep the block out of the emulator's boundary" choice live/e2e/estates/lambda's placeholder ARNs make
resource "aws_ecr_replication_configuration" "app" {
  replication_configuration {
    rule {
      destination {
        region      = "us-west-2"
        registry_id = "000000000000"
      }
    }
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: image_tag_mutability
resource "aws_ecr_repository" "app" {
  name                 = "tofu-iam-ecr-cohort-ecr-repository"
  image_tag_mutability = "MUTABLE"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_ecr_repository.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: path
resource "aws_iam_group" "app" {
  name = "tofu-iam-ecr-cohort-iam-group"
  path = "/users/"
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: "role" is Optional in the wire schema, so neither isRoleArg's alias nor the generic required-only pass wires it - but an instance profile exists to carry a role (the hand-written cohort's aws_iam_role.support existed only so this resource had one), so the shared supporting role is requested (NeedsIAMRole) and referenced by its name attribute: the argument takes the role's name, not the ARN iamRoleRefExpr's "role"/"*_role_arn" callers want
resource "aws_iam_instance_profile" "app" {
  name = "tofu-iam-ecr-cohort-iam-instance-profile"
  role = aws_iam_role.iam-ecr.name
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_iam_instance_profile.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: aws_service_name is a required argument the provider validates by shape (validate: "must be a full service hostname e.g. elasticbeanstalk.amazonaws.com"); set to elasticbeanstalk.amazonaws.com, the provider's own documented example service, as the hand-written cohort chose
resource "aws_iam_service_linked_role" "app" {
  aws_service_name = "elasticbeanstalk.amazonaws.com"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_iam_service_linked_role.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: path
resource "aws_iam_user" "app" {
  name = "tofu-iam-ecr-cohort-iam-user"
  path = "/system/"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_iam_user.app"
  }
}
