# Supporting, not coverage - added only so aws_cloudwatch_metric_alarm.messaging's referring resources have a value to point at: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: comparison_operator/evaluation_periods are the schema's only Required arguments, but the provider additionally requires one of evaluation_criteria, metric_name or metric_query (validate: "one of evaluation_criteria,metric_name,metric_query must be specified"), and metric_name is exactly the argument the doc-example seed must skip (looksLikeName treats "*_name" as generator-owned naming, but this one names the metric watched, not the resource) - so the seed alone leaves the block invalid and the whole documented example lives here instead, the same CPUUtilization shape live/e2e/estate/monitoring.tf already carries by hand
resource "aws_cloudwatch_metric_alarm" "messaging" {
  alarm_name          = "tofu-messaging-cohort-cloudwatch-metric-alarm"
  comparison_operator = "GreaterThanOrEqualToThreshold"
  evaluation_periods  = 2
  metric_name         = "CPUUtilization"
  namespace           = "AWS/EC2"
  period              = 120
  statistic           = "Average"
  threshold           = 80
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_cloudwatch_metric_alarm.messaging"
  }
}

# Supporting, not coverage - added only so aws_iam_role.messaging's referring resources have a value to point at: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: schema requires "assume_role_policy" as a plain string, but the provider validates it is well-formed JSON (validate: "\"assume_role_policy\" contains an invalid JSON"); the generic string placeholder is not JSON
resource "aws_iam_role" "messaging" {
  name = "tofu-messaging-cohort-iam-role"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "streams.metrics.cloudwatch.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_iam_role.messaging"
  }
}
