// Copyright (c) The OpenTofu Authors
// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2023 HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package main

// OutputJSONRel is where the artifact is committed.
const OutputJSONRel = "live/substrates.json"

// SiteDataJSONRel is the site's byte-identical copy, the same pattern
// live/smoke/claims.json's site/data/claims.json copy uses.
const SiteDataJSONRel = "site/data/substrates.json"

// ReadinessJSONRel is the input the untaggable-tier column is computed
// from: tools/readiness-gen's own committed partition, never regenerated
// here.
const ReadinessJSONRel = "live/readiness.json"

// Artifact is live/substrates.json's shape: one [Row] per provider family
// registered in internal/live/substrate.All, generated by asking each
// family's Substrate value its own questions.
type Artifact struct {
	GeneratedBy string `json:"generated_by"`

	// FlociPin is live/floci-image's own content, duplicated at the top
	// level so live/flociimage_test.go's flociImageFields can name a flat
	// field to check against the pin (its own comment: "no nested-path
	// support"), rather than the aws row's harness.pin, which sits three
	// levels deep in Rows. Always equal to the current pin, since Build()
	// reads it fresh every run.
	FlociPin string `json:"floci_pin"`

	Rows []Row `json:"rows"`
}

// Row is one substrate family's capability row (GitHub issue #1588, #1118's
// axis table): identity, marker carrier(s), write occasions, sweep kind,
// address carriage, controller-held handling, an untaggable-types tally,
// and the two hand-kept columns (fence, harness notes).
type Row struct {
	// Family is the Substrate's own Name(), also the provider type
	// [substrate.ForProvider] matches ("aws", "kubernetes").
	Family string `json:"family"`

	Identity IdentityFacts `json:"identity"`

	// Surfaces is one entry per markers.Surface this family owns
	// ([substrate.Substrate.Surfaces]).
	Surfaces []SurfaceRow `json:"surfaces"`

	Sweep SweepFacts `json:"sweep"`

	ControllerHeld ControllerHeldFacts `json:"controller_held"`

	Untaggable UntaggableFacts `json:"untaggable"`

	// Fence is hand-kept: the fence is never code in this repository (#1118),
	// so there is nothing on Substrate to ask.
	Fence string `json:"fence"`

	Harness HarnessFacts `json:"harness"`
}

// IdentityFacts is derived from [substrate.Substrate.CarriesAddress] and
// [substrate.Substrate.AddressInMarkers] rather than typed per family, so a
// third family reads correctly from its own two answers with no new code
// here.
type IdentityFacts struct {
	CarriesAddress   bool   `json:"carries_address"`
	AddressInMarkers bool   `json:"address_in_markers"`
	Description      string `json:"description"`
}

// SurfaceRow is one markers.Surface this family owns, with every per-surface
// answer the Substrate interface carries.
type SurfaceRow struct {
	Surface          string      `json:"surface"`
	MarkerNoun       string      `json:"marker_noun"`
	CarrierPhrase    string      `json:"carrier_phrase"`
	CarrierPaths     []string    `json:"carrier_paths"`
	CollidesOnKey    bool        `json:"collides_on_key"`
	Writes           WritesFacts `json:"writes"`
	PostCreateWriter string      `json:"post_create_writer"`
}

// WritesFacts is [substrate.Writes] rendered as strings.
type WritesFacts struct {
	Create     string `json:"create"`
	Adopt      string `json:"adopt"`
	PostCreate string `json:"post_create"`
}

// SweepFacts is [substrate.Substrate.Sweep] plus a sentence naming what that
// sweep kind means, keyed on the [substrate.Sweep] value rather than on the
// family's name.
type SweepFacts struct {
	Kind        string `json:"kind"`
	Description string `json:"description"`
}

// ControllerHeldFacts is how this family recognizes a controller-held
// resource (GitHub issues #1604, #1606), read off the family's own
// [substrate.Substrate.HoldRecognition] (GitHub issue #1706).
type ControllerHeldFacts struct {
	Recognized bool     `json:"recognized"`
	Mechanism  string   `json:"mechanism"`
	Keys       []string `json:"keys"`
}

// UntaggableFacts tallies, from the committed live/readiness.json, how many
// of this family's admitted types carry no marker surface at all, and which
// tier they fall into.
type UntaggableFacts struct {
	Definition string         `json:"definition"`
	Count      int            `json:"count"`
	ByTier     map[string]int `json:"by_tier"`
}

// HarnessFacts is the emulator this family's estates run against: its name,
// the single pin file the rest of the tree reads (live/flociimage_test.go's
// and live/kind_pin_test.go's own pin), the pin's current content read at
// generation time, and a hand-kept sentence of anything the pin does not
// say.
type HarnessFacts struct {
	Name    string `json:"name"`
	PinFile string `json:"pin_file"`
	Pin     string `json:"pin"`
	Notes   string `json:"notes"`
}
