# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: connection_mode and connector_type are both Required strings validated against fixed enums (validate: "expected connection_mode to be one of [Public Private]", "expected connector_type to be one of [...]"); connector_profile_config.connector_profile_credentials and .connector_profile_properties are both required blocks (min_items 1) but every field inside their per-connector-type oneof sub-blocks is itself optional in the schema, so the generic pass renders both empty - the provider needs one real connector-type sub-block filled in, chosen here as CustomConnector/APIKEY, the connector type needing the fewest required fields of the 24 the enum offers
resource "aws_appflow_connector_profile" "app" {
  name            = "tofu-streaming-cohort-appflow-connector-profile"
  connection_mode = "Public"
  connector_type  = "CustomConnector"
  connector_profile_config {
    connector_profile_credentials {
      custom_connector {
        authentication_type = "APIKEY"
        api_key {
          api_key = "tofu-streaming-cohort-appflow-api-key"
        }
      }
    }
    connector_profile_properties {
      custom_connector {
      }
    }
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: destination_flow_config.connector_type and source_flow_config.connector_type are both Required strings validated against the same fixed enum as aws_appflow_connector_profile above; task.task_type is Required and validated against its own fixed enum (validate: "expected task_type to be one of [...]"); trigger_config.trigger_type is Required and validated against a fixed enum too. Chosen connector type is S3 rather than aws_appflow_connector_profile's CustomConnector: S3 flows need no connector_profile_name at all (Optional in the schema, and AppFlow's own S3 connector is IAM-based, not credential-based), the simplest of the connector types this cohort's sibling resource does not have to match
resource "aws_appflow_flow" "app" {
  name = "tofu-streaming-cohort-appflow-flow"
  destination_flow_config {
    connector_type = "S3"
    destination_connector_properties {
      s3 {
        bucket_name = "tofu-streaming-cohort-appflow-dest"
      }
    }
  }
  source_flow_config {
    connector_type = "S3"
    source_connector_properties {
      s3 {
        bucket_name   = "tofu-streaming-cohort-appflow-source"
        bucket_prefix = "data"
      }
    }
  }
  task {
    task_type = "Passthrough"
  }
  trigger_config {
    trigger_type = "OnDemand"
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_appflow_flow.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: none
resource "aws_appsync_channel_namespace" "app" {
  api_id = aws_appsync_graphql_api.app.id
  name   = aws_appflow_connector_profile.app.name
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_appsync_channel_namespace.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: certificate_arn is Required and validated as a well-formed ARN (validate: "certificate_arn" (placeholder) is an invalid ARN: arn: invalid prefix); no admitted ACM type exists in this cohort to reference, so it stays a literal placeholder ARN naming an ACM certificate - the same "no real sibling to reference" shape aws_pipes_pipe's target accepts below
resource "aws_appsync_domain_name" "app" {
  domain_name     = "tofu-streaming-cohort-appsync-domain-name"
  certificate_arn = "arn:aws:acm:us-east-1:123456789012:certificate/12345678-1234-1234-1234-123456789012"
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: "name" mis-wired to aws_appflow_connector_profile.app.name by the generic pass's same-name parent search (this type is server-assigned, so identityArgName never supplies its own name); corrected to a literal. authentication_type is Required and the provider validates it against a fixed enum (validate: "expected authentication_type to be one of [...]"), and the generic placeholder string is not a member
resource "aws_appsync_graphql_api" "app" {
  authentication_type = "API_KEY"
  name                = "tofu-streaming-cohort-appsync-graphql-api"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_appsync_graphql_api.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: engine_type, engine_version and host_instance_type are all Required strings the provider validates against real ActiveMQ/RabbitMQ values, not an arbitrary placeholder (engine_type: validate "expected engine_type to be one of [ACTIVEMQ RABBITMQ]"); user is Optional-shaped in the schema (a set with no min_items) but the provider requires at least one broker user in practice (found only by exercising a create against floci during this batch's verification, not by validate). engine_type is RABBITMQ rather than the more common ActiveMQ: floci's own AmazonMQ emulation refuses ACTIVEMQ outright ("BadRequestException: Only RABBITMQ EngineType is supported"), confirmed by hand against floci during this batch's verification - both engine types are equally real and valid against the actual AWS API, so this is a floci-emulator accommodation, not a correctness compromise
resource "aws_mq_broker" "app" {
  broker_name        = "tofu-streaming-cohort-mq-broker"
  engine_type        = "RABBITMQ"
  engine_version     = "3.13"
  host_instance_type = "mq.t3.micro"
  user {
    username = "tofuadmin"
    password = "TofustreamingCohortPw1!"
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_mq_broker.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: "name" mis-wired the same way as aws_appsync_graphql_api above (this type is client-named in the identity table, but via a "name" argument the generic pass's own parent search also treats as a same-name candidate before Components resolves it, so the override is needed regardless of admission path). engine_type and engine_version are Required strings validated against real ActiveMQ/RabbitMQ values, the same shape as aws_mq_broker above; data is Required and must be a well-formed broker configuration document (XML for ActiveMQ), not an arbitrary placeholder string - not caught by validate, found by exercising a create against floci during this batch's verification
resource "aws_mq_configuration" "app" {
  data           = <<DATA
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<broker xmlns="http://activemq.apache.org/schema/core">
  <plugins>
  </plugins>
</broker>
DATA
  engine_type    = "ACTIVEMQ"
  engine_version = "5.18"
  name           = "tofu-streaming-cohort-mq-configuration"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_mq_configuration.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: kafka_version and number_of_broker_nodes are both Required, and the generic pass's zero-value/placeholder defaults (0, "placeholder") are neither a real Kafka version nor a legal broker count (must be at least 1 and a multiple of the number of client_subnets); broker_node_group_info.instance_type is Required and the provider validates it is a real MSK-supported instance type, not an arbitrary string
resource "aws_msk_cluster" "app" {
  cluster_name           = "tofu-streaming-cohort-msk-cluster"
  kafka_version          = "3.6.0"
  number_of_broker_nodes = 1
  broker_node_group_info {
    client_subnets  = ["placeholder"]
    instance_type   = "kafka.m5.large"
    security_groups = ["placeholder"]
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_msk_cluster.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: "name" mis-wired to aws_appflow_connector_profile.app.name, the same cause and fix as aws_appsync_graphql_api above. server_properties is Required but the generic placeholder string is not a real Kafka broker properties file, which the provider does not validate at plan time but does need at apply time (confirmed by hand against floci during this batch's verification)
resource "aws_msk_configuration" "app" {
  name              = "tofu-streaming-cohort-msk-configuration"
  server_properties = "auto.create.topics.enable=true"
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: cluster_arn and every secret_arn_list member are validated as well-formed ARNs (validate: "cluster_arn" ... is an invalid ARN: arn: invalid prefix / "secret_arn_list.0" (placeholder) is an invalid ARN). cluster_arn is wired to this cohort's own aws_msk_cluster - the association's identity IS that cluster's server-assigned ARN, the identity-bound reference shape the table's IdentityAttrs sanction - and secret_arn_list stays a literal placeholder ARN naming a Secrets Manager secret with the AmazonMSK_ prefix the service requires of associated secrets, since no admitted Secrets Manager type exists in this cohort to reference
resource "aws_msk_scram_secret_association" "app" {
  cluster_arn     = aws_msk_cluster.app.arn
  secret_arn_list = ["arn:aws:secretsmanager:us-east-1:123456789012:secret:AmazonMSK_tofu-streaming-cohort-AbCdEf"]
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: client_authentication.sasl.iam.enabled is Required and schema-valid as either bool, but MSK Serverless accepts only IAM-authenticated SASL in practice (the generic pass's zero-value "false" passes validate but the provider refuses it at create - confirmed by hand against floci during this batch's verification); vpc_config.subnet_ids is Required and schema-valid with the generic pass's single-element placeholder list, but MSK Serverless requires subnets in at least two distinct Availability Zones in practice, the same not-caught-by-validate shape
resource "aws_msk_serverless_cluster" "app" {
  cluster_name = "tofu-streaming-cohort-msk-serverless-cluster"
  client_authentication {
    sasl {
      iam {
        enabled = true
      }
    }
  }
  vpc_config {
    subnet_ids = ["subnet-0123456789abcdef0", "subnet-0123456789abcdef1"]
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_msk_serverless_cluster.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: partition_count, replication_factor
resource "aws_msk_topic" "app" {
  cluster_arn        = aws_msk_scram_secret_association.app.cluster_arn
  name               = aws_appflow_connector_profile.app.name
  partition_count    = 2
  replication_factor = 2
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: "name" mis-wired the same way as aws_appsync_graphql_api above. capacity is a required block whose two nested block_types (autoscaling, provisioned_capacity) are both themselves Optional in the schema, but the provider requires exactly one (validate: "Missing required argument" once floci is asked to create it); kafka_cluster.apache_kafka_cluster.bootstrap_servers is Required but the generic placeholder string is not the bootstrap-broker-list format the provider expects, so it is wired to this cohort's own aws_msk_cluster's bootstrap_brokers output; kafka_cluster_client_authentication.authentication_type and kafka_cluster_encryption_in_transit.encryption_type are both Optional in the schema but their empty blocks leave the provider to guess, set here to their documented defaults for clarity; plugin.custom_plugin.arn/revision are Required but the generic placeholder string and zero are neither a real plugin ARN nor a real revision, wired to this cohort's own aws_mskconnect_custom_plugin instead; kafkaconnect_version is Required and the provider validates it against the versions MSK Connect actually supports, not an arbitrary string
resource "aws_mskconnect_connector" "app" {
  connector_configuration = {
    "connector.class" = "org.apache.kafka.connect.mirror.MirrorSourceConnector"
    "tasks.max"       = "1"
    "topics"          = "example"
  }
  kafkaconnect_version       = "2.7.1"
  name                       = "tofu-streaming-cohort-mskconnect-connector"
  service_execution_role_arn = aws_iam_role.streaming.arn
  capacity {
    provisioned_capacity {
      worker_count = 1
    }
  }
  kafka_cluster {
    apache_kafka_cluster {
      bootstrap_servers = aws_msk_cluster.app.bootstrap_brokers
      vpc {
        security_groups = ["placeholder"]
        subnets         = ["placeholder"]
      }
    }
  }
  kafka_cluster_client_authentication {
    authentication_type = "NONE"
  }
  kafka_cluster_encryption_in_transit {
    encryption_type = "PLAINTEXT"
  }
  plugin {
    custom_plugin {
      arn      = aws_mskconnect_custom_plugin.app.arn
      revision = aws_mskconnect_custom_plugin.app.latest_revision
    }
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_mskconnect_connector.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: "name" mis-wired the same way as aws_appsync_graphql_api above. content_type is Required and the provider validates it against a fixed enum (validate: "expected content_type to be one of [JAR ZIP]"), and the generic placeholder string is not a member; location.s3.bucket_arn is Required and validated as a well-formed ARN (validate: "is an invalid ARN")
resource "aws_mskconnect_custom_plugin" "app" {
  content_type = "JAR"
  name         = "tofu-streaming-cohort-mskconnect-custom-plugin"
  location {
    s3 {
      bucket_arn = "arn:aws:s3:::tofu-streaming-cohort-plugins"
      file_key   = "placeholder"
    }
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_mskconnect_custom_plugin.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: "name" mis-wired the same way as aws_appsync_graphql_api above. properties_file_content is Required but the generic placeholder string is not a real Kafka Connect worker properties file, which the provider does not validate at plan time but does need at apply time (confirmed by hand against floci during this batch's verification)
resource "aws_mskconnect_worker_configuration" "app" {
  name                    = "tofu-streaming-cohort-mskconnect-worker-configuration"
  properties_file_content = "key.converter=org.apache.kafka.connect.storage.StringConverter\nvalue.converter=org.apache.kafka.connect.storage.StringConverter\n"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_mskconnect_worker_configuration.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: role_arn, source and target are all Required and validated as well-formed ARNs (validate: "is an invalid ARN"), and source is additionally validated against a pattern requiring either an "smk://" bootstrap string or a real ARN (validate: "expected value of source to match regular expression ..."); the generic placeholder string satisfies none of the three. source is wired to this cohort's own aws_msk_cluster (a Managed Streaming Kafka source pipe reads from), with the source_parameters.managed_streaming_kafka_parameters.topic_name the MSK source type requires in practice (Optional in the schema, not caught by validate); target stays a literal placeholder ARN naming an SQS queue - no admitted type in this cohort is a valid Pipes target, the same "no real sibling to reference" shape aws_rds_integration's own override above accepts for its target_arn
resource "aws_pipes_pipe" "app" {
  name     = "tofu-streaming-cohort-pipes-pipe"
  role_arn = aws_iam_role.streaming.arn
  source   = aws_msk_cluster.app.arn
  target   = "arn:aws:sqs:us-east-1:000000000000:tofu-streaming-cohort-pipes-target"
  source_parameters {
    managed_streaming_kafka_parameters {
      topic_name = "example"
    }
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_pipes_pipe.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: none
resource "aws_scheduler_schedule_group" "app" {
  name = "tofu-streaming-cohort-scheduler-schedule-group"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_scheduler_schedule_group.app"
  }
}
