# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: workspace_id left as a generic placeholder name instead of a reference (aws_prometheus_workspace is server-assigned, so parentRef never proposes it); wired to the workspace this cohort renders. definition is a required string the provider expects as YAML Alertmanager configuration; the generic placeholder is not valid YAML
resource "aws_prometheus_alert_manager_definition" "app" {
  workspace_id = aws_prometheus_workspace.app.id
  definition   = <<-EOT
    route:
      receiver: default
    receivers:
      - name: default
  EOT
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: workspace_id left as a generic placeholder name instead of a reference, the same reason and correction as aws_prometheus_alert_manager_definition above. destination is a required block the schema marks optional-in-shape but the provider requires present, and its own nested filters block is required in turn (validate: "Block destination[0].filters must have a configuration value")
resource "aws_prometheus_query_logging_configuration" "app" {
  workspace_id = aws_prometheus_workspace.app.id
  destination {
    cloudwatch_logs {
      log_group_arn = "arn:aws:logs:us-east-1:000000000000:log-group:/aws/prometheus/tofu-aps-cohort:*"
    }
    filters {
      qsp_threshold = 0
    }
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: schema requires only scrape_configuration; the provider also requires the source and destination blocks (validate: "Missing required argument"), each with their own nested required arguments (an EKS-shaped source, an AMP workspace ARN destination) the generic pass has no schema signal for
resource "aws_prometheus_scraper" "app" {
  scrape_configuration = <<-EOT
    global:
      scrape_interval: 30s
    scrape_configs:
      - job_name: placeholder
  EOT
  source {
    eks {
      cluster_arn = "arn:aws:eks:us-east-1:000000000000:cluster/tofu-aps-cohort"
      subnet_ids  = ["subnet-0123456789abcdef0"]
    }
  }
  destination {
    amp {
      workspace_arn = aws_prometheus_workspace.app.arn
    }
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_prometheus_scraper.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: scraper_id left as a generic placeholder name instead of a reference (aws_prometheus_scraper is server-assigned, so parentRef never proposes it); wired to the scraper this cohort renders. logging_destination is a required block the schema marks optional-in-shape but the provider requires present
resource "aws_prometheus_scraper_logging_configuration" "app" {
  scraper_id = aws_prometheus_scraper.app.id
  logging_destination {
    cloudwatch_logs {
      log_group_arn = "arn:aws:logs:us-east-1:000000000000:log-group:/aws/prometheus/scraper/tofu-aps-cohort:*"
    }
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: alias
resource "aws_prometheus_workspace" "app" {
  alias = "example"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_prometheus_workspace.app"
  }
}
