# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: max_capacity, min_capacity, scalable_dimension, service_namespace
resource "aws_appautoscaling_target" "app" {
  service_namespace  = "dynamodb"
  max_capacity       = 100
  min_capacity       = 5
  resource_id        = "placeholder"
  scalable_dimension = "dynamodb:table:ReadCapacityUnits"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_appautoscaling_target.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: cluster_name must name an actual ECS cluster - PutClusterCapacityProviders 400s with ClusterNotFoundException against one that does not exist - and no resource in this cohort's own requested types creates one, since aws_ecs_cluster is already covered by live/e2e/estate/ rather than by this cohort. A supporting aws_ecs_cluster is generated instead (NeedsSupporting), the same "supporting, not coverage" shape as the shared aws_iam_role; this entry folds the hand-written block live/e2e/estates/ecs-eks carried before #108 criterion 4, which every regeneration reverted
resource "aws_ecs_cluster_capacity_providers" "app" {
  cluster_name = aws_ecs_cluster.ecs-eks.name
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: the generic pass's same-name parent search matches this type's own client-chosen "name" argument against aws_eks_cluster (an unrelated EKS type whose single-component identity also happens to be named "name"), producing a cross-service reference where a plain placeholder string belongs; overridden back to a placeholder. capacity_provider_arns and daemon_task_definition_arn are required arguments the provider validates as well-formed ARNs (validate: "cannot be parsed as an ARN"); this batch rejected both aws_ecs_capacity_provider and aws_ecs_daemon_task_definition (see internal/live/identity/table.go), so no real sibling resource supplies either, and both are set to well-formed placeholder ARNs instead
resource "aws_ecs_daemon" "app" {
  capacity_provider_arns     = ["arn:aws:ecs:us-east-1:000000000000:capacity-provider/tofu-ecs-eks-cohort-capacity-provider"]
  daemon_task_definition_arn = "arn:aws:ecs:us-east-1:000000000000:daemon-task-definition/tofu-ecs-eks-cohort-daemon-task:1"
  name                       = "tofu-ecs-eks-cohort-ecs-daemon"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_ecs_daemon.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: ordered_placement_strategy.field, ordered_placement_strategy.type, placement_constraints.expression, placement_constraints.type
resource "aws_ecs_service" "app" {
  cluster = aws_ecs_cluster.ecs-eks.name
  name    = aws_ecs_cluster.ecs-eks.name
  ordered_placement_strategy {
    field = "cpu"
    type  = "binpack"
  }
  placement_constraints {
    expression = "attribute:ecs.availability-zone in [us-west-2a, us-west-2b]"
    type       = "memberOf"
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_ecs_service.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: the generic pass's same-name parent search matches cluster_name against aws_ecs_cluster_capacity_providers (an unrelated ECS type that also self-identifies by "cluster_name"), not aws_eks_cluster; overridden to the correct parent. principal_arn is a required argument the provider validates as a well-formed IAM ARN (validate: "is an invalid ARN"); set to the shared aws_iam_role's own ARN, standing in for "the IAM principal this entry grants access to"
resource "aws_eks_access_entry" "app" {
  cluster_name  = aws_eks_cluster.app.name
  principal_arn = aws_iam_role.ecs-eks.arn
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_eks_access_entry.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: same cluster_name and principal_arn shapes as aws_eks_access_entry; overridden the same way. policy_arn is also set to a real AWS-managed EKS access policy ARN in place of the generic placeholder string, which is not one
resource "aws_eks_access_policy_association" "app" {
  cluster_name  = aws_eks_cluster.app.name
  policy_arn    = "arn:aws:eks::aws:cluster-access-policy/AmazonEKSViewPolicy"
  principal_arn = aws_iam_role.ecs-eks.arn
  access_scope {
    type = "placeholder"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: same cluster_name mismatch as aws_eks_access_entry; overridden to the correct parent
resource "aws_eks_addon" "app" {
  cluster_name = aws_eks_cluster.app.name
  addon_name   = "tofu-ecs-eks-cohort-eks-addon"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_eks_addon.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: same cluster_name mismatch as aws_eks_access_entry; overridden to the correct parent. type and delete_propagation_policy are also set to real provider enum members in place of the generic placeholder string, which is neither
resource "aws_eks_capability" "app" {
  cluster_name              = aws_eks_cluster.app.name
  capability_name           = "tofu-ecs-eks-cohort-eks-capability"
  delete_propagation_policy = "RETAIN"
  role_arn                  = aws_iam_role.ecs-eks.arn
  type                      = "ARGOCD"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_eks_capability.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: role_arn is a required argument the provider validates as a well-formed ARN (validate: "is an invalid ARN"); the generic pass's placeholder string is not one, and no same-name parent search finds the shared aws_iam_role for it (the argument is "role_arn", not "role"), so it is set here the same way isRoleArg's "role"/"*_role_arn" alias would if the generic pass's own suffix rule reached this argument name
resource "aws_eks_cluster" "app" {
  name     = "tofu-ecs-eks-cohort-eks-cluster"
  role_arn = aws_iam_role.ecs-eks.arn
  vpc_config {
    subnet_ids = ["placeholder"]
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_eks_cluster.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: same cluster_name mismatch as aws_eks_access_entry; overridden to the correct parent
resource "aws_eks_fargate_profile" "app" {
  cluster_name           = aws_eks_cluster.app.name
  fargate_profile_name   = "tofu-ecs-eks-cohort-eks-fargate-profile"
  pod_execution_role_arn = aws_iam_role.ecs-eks.arn
  selector {
    namespace = "placeholder"
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_eks_fargate_profile.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: same cluster_name mismatch as aws_eks_access_entry; overridden to the correct parent. scaling_config is a required block whose max_size the provider validates as at least 1 (validate: "expected scaling_config.0.max_size to be at least (1)"); the generic pass's zero value fails that, so it is set to 1 alongside desired_size and min_size
resource "aws_eks_node_group" "app" {
  cluster_name    = aws_eks_cluster.app.name
  node_group_name = "tofu-ecs-eks-cohort-eks-node-group"
  node_role_arn   = aws_iam_role.ecs-eks.arn
  subnet_ids      = ["placeholder"]
  scaling_config {
    desired_size = 1
    max_size     = 1
    min_size     = 1
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_eks_node_group.app"
  }
}
