# Supporting, not coverage - added only so aws_iam_role.ecs-eks's referring resources have a value to point at: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: schema requires "assume_role_policy" as a plain string, but the provider validates it is well-formed JSON (validate: "\"assume_role_policy\" contains an invalid JSON"); the generic string placeholder is not JSON
resource "aws_iam_role" "ecs-eks" {
  name = "tofu-ecs-eks-cohort-iam-role"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "ecs-eks.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_iam_role.ecs-eks"
  }
}

# Supporting, not coverage - hand-added (not estate-gen's own doing):
# aws_ecs_cluster_capacity_providers.app needs a real cluster to attach to,
# and aws_ecs_cluster is not one of this cohort's own requested types (it
# is already covered by live/e2e/estate/). Client-named-shaped exactly the
# way live/e2e/estate/'s own aws_ecs_cluster.app is.
resource "aws_ecs_cluster" "ecs-eks" {
  name = "tofu-ecs-eks-cohort-ecs-cluster"

  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_ecs_cluster.ecs-eks"
  }
}
