# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: none
resource "aws_ivs_channel" "app" {
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_ivs_channel.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: none
resource "aws_ivs_recording_configuration" "app" {
  destination_configuration {
    s3 {
      bucket_name = "placeholder"
    }
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_ivs_recording_configuration.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: destination_configuration is Required in the provider's own docs (exactly one of cloudwatch_logs/firehose/s3, each with its own Required leaf) but Optional in the wire schema - enforced only by the provider's plan-time validation, so the generic required-only pass never visits it at all; wired to a literal S3 bucket name, the same destination_configuration.s3 shape aws_ivs_recording_configuration already renders (the generic pass fills that one because it is genuinely block-Required there)
resource "aws_ivschat_logging_configuration" "app" {
  destination_configuration {
    s3 {
      bucket_name = "placeholder"
    }
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_ivschat_logging_configuration.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: none
resource "aws_ivschat_room" "app" {
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_ivschat_room.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: none
resource "aws_media_package_channel" "app" {
  channel_id = "tofu-media-cohort-package-channel"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_media_package_channel.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: none
resource "aws_media_packagev2_channel_group" "app" {
  name = "tofu-media-cohort-packagev2-channel-group"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_media_packagev2_channel_group.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: name is a plain client-chosen string (not this type's identity - aws_medialive_multiplex is server-assigned), but gen.go's parentRef mistakes it for a parent reference: this cohort's other client-named type, aws_media_packagev2_channel_group, also owns a single-component identity argument called "name", and parentRef's own same-name tiebreaker only guards two types that *both* claim "name" as their identity - not a server-assigned type's ordinary same-named argument. Left alone, the generic pass would point the multiplex at an unrelated MediaPackage channel group's name; availability_zones is a required list of strings, but the provider validates a 2-item minimum (validate: "attribute availability_zones requires 2 item minimum, but config has only 1 declared"); the generic pass emits one placeholder element; multiplex_settings is Required in the provider's own docs (transport_stream_bitrate and transport_stream_id both Required within it) but Optional in the wire schema - enforced only by the provider's plan-time validation, so the generic required-only pass never visits it at all
resource "aws_medialive_multiplex" "app" {
  availability_zones = ["us-east-1a", "us-east-1b"]
  name               = "tofu-media-cohort-medialive-multiplex"
  multiplex_settings {
    transport_stream_bitrate = 1000000
    transport_stream_id      = 1
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_medialive_multiplex.app"
  }
}
