// Copyright (c) The OpenTofu Authors
// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2023 HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package lint

// admittedTypesRemainder is the remainder cohort's slice of [admittedTypesV0]:
// the types the remainder ratification batch admitted. Registered into
// admittedTypesV0 by init below; see contributing/LIVE-TABLES.md.
var admittedTypesRemainder = map[string]struct{}{
	// ---- Registry-ratified (#40, #44, #65): the REMAINDER ratification
	// ---- batch. Issue #65 pool worked down service by service,
	// ---- excluding every service already owned by a concurrent batch,
	// ---- and dropping types a concurrently-landed batch admitted (or
	// ---- deliberately rejected, for aws_elasticache_global_replication_group)
	// ---- first when this session own scope also reached them
	// ---- independently - see live/e2e/estates/remainder/README.md,
	// ---- "Dropped to a concurrent batch", for the full reconciliation
	// ---- across three separate merge waves. Every row below was
	// ---- independently verified against the pinned v6.58.0 provider own
	// ---- documented Import section, not accepted on row-gen registry
	// ---- classification alone - see internal/live/identity/table.go for
	// ---- the per-type corrections and live/e2e/estates/remainder/README.md
	// ---- for the full accounting of what was rejected, excluded, or
	// ---- dropped and why. Cohort estate: live/e2e/estates/remainder,
	// ---- capped at a representative subset rather than one resource per
	// ---- admitted type - see that README own "Estate-covered vs
	// ---- identity-only-verified" section.
	"aws_datapipeline_pipeline":          {},
	"aws_datazone_domain":                {},
	"aws_detective_graph":                {},
	"aws_devopsguru_resource_collection": {},
	"aws_dlm_lifecycle_policy":           {},
	"aws_dsql_cluster":                   {},
	"aws_dx_connection":                  {},
	"aws_dx_gateway":                     {},
	"aws_dx_lag":                         {},
	"aws_dx_private_virtual_interface":   {},
	"aws_dx_public_virtual_interface":    {},
	"aws_dx_transit_virtual_interface":   {},
	"aws_ec2_instance_connect_endpoint":  {},
	"aws_ec2_local_gateway_route_table":  {},
	"aws_ec2_local_gateway_route_table_virtual_interface_group_association": {},
	"aws_ec2_local_gateway_route_table_vpc_association":                     {},
	"aws_ec2_network_insights_access_scope":                                 {},
	"aws_ec2_network_insights_analysis":                                     {},
	"aws_ec2_network_insights_path":                                         {},
	"aws_ec2_traffic_mirror_filter":                                         {},
	"aws_ec2_traffic_mirror_session":                                        {},
	"aws_ec2_traffic_mirror_target":                                         {},
	"aws_ecs_daemon_task_definition":                                        {},
	"aws_ecs_express_gateway_service":                                       {},
	"aws_ecs_task_definition":                                               {},
	"aws_efs_mount_target":                                                  {},
	"aws_egress_only_internet_gateway":                                      {},
	"aws_elb":                                                               {},
	"aws_evidently_project":                                                 {},
	"aws_evidently_segment":                                                 {},
	"aws_fis_experiment_template":                                           {},
	"aws_fms_resource_set":                                                  {},
	"aws_gamelift_alias":                                                    {},
	"aws_gamelift_build":                                                    {},
	"aws_gamelift_fleet":                                                    {},
	"aws_gamelift_script":                                                   {},
	"aws_glue_data_quality_ruleset":                                         {},
	"aws_glue_schema":                                                       {},
	"aws_glue_security_configuration":                                       {},
	"aws_glue_workflow":                                                     {},
	"aws_iam_access_key":                                                    {},
	"aws_iam_saml_provider":                                                 {},
	"aws_iam_virtual_mfa_device":                                            {},
	"aws_imagebuilder_component":                                            {},
	"aws_imagebuilder_container_recipe":                                     {},
	"aws_imagebuilder_distribution_configuration":                           {},
	"aws_imagebuilder_image":                                                {},
	"aws_imagebuilder_image_pipeline":                                       {},
	"aws_imagebuilder_image_recipe":                                         {},
	"aws_imagebuilder_infrastructure_configuration":                         {},
	"aws_imagebuilder_lifecycle_policy":                                     {},
	"aws_imagebuilder_workflow":                                             {},
	"aws_inspector_assessment_target":                                       {},
	"aws_inspector_assessment_template":                                     {},
	"aws_internetmonitor_monitor":                                           {},
	"aws_invoicing_invoice_unit":                                            {},
	"aws_kinesis_analytics_application":                                     {},
	"aws_kinesis_resource_policy":                                           {},
	"aws_lb_listener_rule":                                                  {},
	"aws_lb_trust_store":                                                    {},
	"aws_m2_application":                                                    {},
	"aws_m2_environment":                                                    {},
	"aws_macie2_account":                                                    {},
	"aws_mailmanager_rule_set":                                              {},
	"aws_mailmanager_traffic_policy":                                        {},
	"aws_msk_cluster_policy":                                                {},
	"aws_msk_replicator":                                                    {},
	"aws_msk_vpc_connection":                                                {},
	"aws_mwaa_environment":                                                  {},
	"aws_notifications_event_rule":                                          {},
	"aws_notifications_notification_configuration":                          {},
	"aws_notifications_notification_hub":                                    {},
	"aws_notificationscontacts_email_contact":                               {},
	"aws_oam_link":                                                          {},
	"aws_oam_sink":                                                          {},
	"aws_observabilityadmin_s3_table_integration":                           {},
	"aws_observabilityadmin_telemetry_pipeline":                             {},
	"aws_odb_cloud_autonomous_vm_cluster":                                   {},
	"aws_odb_cloud_exadata_infrastructure":                                  {},
	"aws_odb_cloud_vm_cluster":                                              {},
	"aws_odb_network":                                                       {},
	"aws_odb_network_peering_connection":                                    {},
	"aws_paymentcryptography_key":                                           {},
	"aws_pinpointsmsvoicev2_configuration_set":                              {},
	"aws_pinpointsmsvoicev2_opt_out_list":                                   {},
	"aws_pinpointsmsvoicev2_phone_number":                                   {},
	"aws_pinpointsmsvoicev2_pool":                                           {},
	"aws_ram_permission":                                                    {},
	"aws_ram_resource_share":                                                {},
	"aws_rbin_rule":                                                         {},
	"aws_resiliencehub_resiliency_policy":                                   {},
	"aws_resiliencehubv2_policy":                                            {},
	"aws_rolesanywhere_profile":                                             {},
	"aws_rolesanywhere_trust_anchor":                                        {},
	"aws_route53_cidr_collection":                                           {},
	"aws_route53_resolver_dnssec_config":                                    {},
	"aws_route53_resolver_query_log_config_association":                     {},
	"aws_route53profiles_resource_association":                              {},
	"aws_route53recoverycontrolconfig_routing_control":                      {},
	"aws_s3_directory_bucket":                                               {},
	"aws_s3control_bucket":                                                  {},
	"aws_s3control_multi_region_access_point":                               {},
	"aws_s3files_access_point":                                              {},
	"aws_s3files_file_system":                                               {},
	"aws_s3files_file_system_policy":                                        {},
	"aws_s3files_mount_target":                                              {},
	"aws_s3tables_table_bucket":                                             {},
	"aws_s3tables_table_bucket_policy":                                      {},
	"aws_s3vectors_index":                                                   {},
	"aws_s3vectors_vector_bucket":                                           {},
	"aws_s3vectors_vector_bucket_policy":                                    {},
	"aws_schemas_discoverer":                                                {},
	"aws_securityhub_account":                                               {},
	"aws_securityhub_configuration_policy":                                  {},
	"aws_securityhub_finding_aggregator":                                    {},
	"aws_securityhub_insight":                                               {},
	"aws_securityhub_organization_configuration":                            {},
	"aws_securityhub_standards_subscription":                                {},
	"aws_securitylake_data_lake":                                            {},
	"aws_securitylake_subscriber":                                           {},
	"aws_service_discovery_http_namespace":                                  {},
	"aws_service_discovery_public_dns_namespace":                            {},
	"aws_service_discovery_service":                                         {},
	"aws_sesv2_account_vdm_attributes":                                      {},
	"aws_sesv2_configuration_set":                                           {},
	"aws_sesv2_dedicated_ip_pool":                                           {},
	"aws_sesv2_email_identity":                                              {},
	"aws_sesv2_tenant":                                                      {},
	"aws_sfn_alias":                                                         {},
	"aws_shield_proactive_engagement":                                       {},
	"aws_shield_protection":                                                 {},
	"aws_sns_topic_subscription":                                            {},
	"aws_ssmcontacts_contact":                                               {},
	"aws_ssmcontacts_contact_channel":                                       {},
	"aws_ssmcontacts_plan":                                                  {},
	"aws_ssmcontacts_rotation":                                              {},
	"aws_ssmincidents_replication_set":                                      {},
	"aws_ssmincidents_response_plan":                                        {},
	"aws_ssmquicksetup_configuration_manager":                               {},
	"aws_verifiedaccess_endpoint":                                           {},
	"aws_verifiedaccess_instance":                                           {},
	"aws_verifiedaccess_trust_provider":                                     {},
	"aws_verifiedpermissions_policy_store":                                  {},
	"aws_vpc_block_public_access_exclusion":                                 {},
	"aws_vpc_encryption_control":                                            {},
	"aws_vpc_route_server":                                                  {},
	"aws_vpc_route_server_endpoint":                                         {},
	"aws_vpc_route_server_peer":                                             {},
	"aws_vpn_concentrator":                                                  {},
	// ---- Registry-ratified (#40, #44, #65): the REMAINDER ratification
	// ---- batch, second slice - APS, ARC Region Switch, ARC Zonal Shift,
	// ---- AppConfig, AppIntegrations, AppSync own newer Api-family types,
	// ---- Athena, AutoScaling own launch-configuration pair, BCM Data
	// ---- Exports, Billing, Cost Explorer, Cost and Usage Reports,
	// ---- Chatbot, Clean Rooms, Cloud9, CloudFront own policy/identity
	// ---- family, and CloudTrail.
	"aws_prometheus_rule_group_namespace":                      {},
	"aws_arcregionswitch_plan":                                 {},
	"aws_arczonalshift_zonal_autoshift_configuration":          {},
	"aws_appconfig_application":                                {},
	"aws_appconfig_deployment_strategy":                        {},
	"aws_appconfig_extension":                                  {},
	"aws_appconfig_extension_association":                      {},
	"aws_athena_named_query":                                   {},
	"aws_autoscaling_group":                                    {},
	"aws_launch_configuration":                                 {},
	"aws_bcmdataexports_export":                                {},
	"aws_billing_view":                                         {},
	"aws_ce_anomaly_monitor":                                   {},
	"aws_ce_anomaly_subscription":                              {},
	"aws_ce_cost_category":                                     {},
	"aws_cur_report_definition":                                {},
	"aws_chatbot_slack_channel_configuration":                  {},
	"aws_cleanrooms_collaboration":                             {},
	"aws_cleanrooms_configured_table":                          {},
	"aws_cleanrooms_membership":                                {},
	"aws_cloud9_environment_ec2":                               {},
	"aws_cloudfront_cache_policy":                              {},
	"aws_cloudfront_continuous_deployment_policy":              {},
	"aws_cloudfront_key_group":                                 {},
	"aws_cloudfront_origin_access_identity":                    {},
	"aws_cloudfront_origin_request_policy":                     {},
	"aws_cloudfront_public_key":                                {},
	"aws_cloudfront_response_headers_policy":                   {},
	"aws_cloudtrail":                                           {},
	"aws_cloudtrail_event_data_store":                          {},
	"aws_codegurureviewer_repository_association":              {},
	"aws_appsync_api":                                          {},
	"aws_arczonalshift_autoshift_observer_notification_status": {},
	"aws_appsync_api_cache":                                    {},
	"aws_appsync_domain_name_api_association":                  {},
}

func init() { registerCohortAdmitted(admittedTypesRemainder) }
