// Copyright (c) The OpenTofu Authors
// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2023 HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by tools/row-gen -emit. DO NOT EDIT.

package lint

// logicalFamilyPrefixes are the provider-local type prefixes whose resources
// exist only inside OpenTofu's own record of them. See live/LIMITATIONS.md.
//
// Membership here is what makes a type with no [logicalTypes] row of its own
// still classify - as [ClassOtherRefused], except the tls_ family, see
// [ClassifyLogicalType] - instead of falling through to the generic
// unadmitted-type refusal. A random_id gets the logical-resource explanation
// for why its whole family is out, not the generic "not in the v0 table"
// message.
//
// One entry per provider in tools/row-gen's logicalProviderSources, taken
// from the last segment of its source address. OpenTofu's built-in provider
// contributes no prefix at all - terraform_data is admitted by exact type
// name, because a "terraform_" prefix would claim a whole family this fork
// has never surveyed.
//
// The variable's name predates [ClassExternalAdmitted] and is now slightly
// wider than it reads: hashicorp/local's resources do NOT exist only inside
// OpenTofu's record - they write a file - and local_ is a member here all the
// same, because what this list decides is which families lint explains at all.
var logicalFamilyPrefixes = []string{
	"local_",
	"null_",
	"random_",
	"time_",
	"tls_",
}

// logicalTypes is the per-type classification table, derived from
// live/logical-schemas.json: every managed resource type of every measured
// provider, classified by the rule that a live (non-deprecated) sensitive
// attribute anywhere in the type's schema means it handles material
// live/RECEIPTS.md's no-secrets rule forbids a record from carrying, and none
// means the record can hold the type's whole prior state.
//
// It is the same rule, over the same artifact, that derives
// [identity.TypeIdentity.RecordBacked] - deliberately, so that lint's admitted
// classes and identity's RecordBacked cannot name different sets. They did
// once: the four types the hand-written table predated resolved under identity
// and were refused outright by lint, so a configuration with a record_store
// declared got told its type was out of the subset.
//
// The provider's own store_only measurement then splits the admitted rows in
// two. RECORD_ADMITTED means the record is the whole of the resource;
// EXTERNAL_ADMITTED means the record holds its prior state while one of its
// own arguments names something outside it, which is why that class does not
// get countIndexScopeForType's skip.
//
// A type in a [logicalFamilyPrefixes] family with no row here classifies
// [ClassOtherRefused] by default (see [ClassifyLogicalType]).
var logicalTypes = map[string]LogicalType{
	"local_file":              {Type: "local_file", Class: ClassExternalAdmitted, Prefix: "local_", Evidence: "hashicorp/local 2.9.0 marks sensitive_content sensitive, but deprecates every one of them (sensitive_content: \"Use the `local_sensitive_file` resource instead\"), so no attribute the provider still tells you to use carries secret material", External: "hashicorp/local's resources write a file to the local filesystem and read it back on refresh. Measured against 2.9.0: delete the file and the provider drops the resource so the next plan proposes a create, and id is the SHA1 of the content, so changing the file changes the resource. The file outlives any record, and two instances at distinct addresses hold distinct records and still collide on one filename, so what the resource affects is named by its filename argument rather than bounded by the record"},
	"local_sensitive_file":    {Type: "local_sensitive_file", Class: ClassSecretRefused, Prefix: "local_", Evidence: "hashicorp/local 2.9.0 marks content and content_base64 sensitive"},
	"null_resource":           {Type: "null_resource", Class: ClassRecordAdmitted, Prefix: "null_", Evidence: "hashicorp/null 3.3.1 marks no attribute of null_resource sensitive, measured over every attribute of every block of its schema, nested attribute types and nested blocks included"},
	"random_bytes":            {Type: "random_bytes", Class: ClassSecretRefused, Prefix: "random_", Evidence: "hashicorp/random 3.9.0 marks base64 and hex sensitive"},
	"random_id":               {Type: "random_id", Class: ClassRecordAdmitted, Prefix: "random_", Evidence: "hashicorp/random 3.9.0 marks no attribute of random_id sensitive, measured over every attribute of every block of its schema, nested attribute types and nested blocks included"},
	"random_integer":          {Type: "random_integer", Class: ClassRecordAdmitted, Prefix: "random_", Evidence: "hashicorp/random 3.9.0 marks no attribute of random_integer sensitive, measured over every attribute of every block of its schema, nested attribute types and nested blocks included"},
	"random_password":         {Type: "random_password", Class: ClassSecretRefused, Prefix: "random_", Evidence: "hashicorp/random 3.9.0 marks bcrypt_hash and result sensitive"},
	"random_pet":              {Type: "random_pet", Class: ClassRecordAdmitted, Prefix: "random_", Evidence: "hashicorp/random 3.9.0 marks no attribute of random_pet sensitive, measured over every attribute of every block of its schema, nested attribute types and nested blocks included"},
	"random_shuffle":          {Type: "random_shuffle", Class: ClassRecordAdmitted, Prefix: "random_", Evidence: "hashicorp/random 3.9.0 marks no attribute of random_shuffle sensitive, measured over every attribute of every block of its schema, nested attribute types and nested blocks included"},
	"random_string":           {Type: "random_string", Class: ClassRecordAdmitted, Prefix: "random_", Evidence: "hashicorp/random 3.9.0 marks no attribute of random_string sensitive, measured over every attribute of every block of its schema, nested attribute types and nested blocks included"},
	"random_uuid":             {Type: "random_uuid", Class: ClassRecordAdmitted, Prefix: "random_", Evidence: "hashicorp/random 3.9.0 marks no attribute of random_uuid sensitive, measured over every attribute of every block of its schema, nested attribute types and nested blocks included"},
	"random_uuid4":            {Type: "random_uuid4", Class: ClassRecordAdmitted, Prefix: "random_", Evidence: "hashicorp/random 3.9.0 marks no attribute of random_uuid4 sensitive, measured over every attribute of every block of its schema, nested attribute types and nested blocks included"},
	"random_uuid7":            {Type: "random_uuid7", Class: ClassRecordAdmitted, Prefix: "random_", Evidence: "hashicorp/random 3.9.0 marks no attribute of random_uuid7 sensitive, measured over every attribute of every block of its schema, nested attribute types and nested blocks included"},
	"terraform_data":          {Type: "terraform_data", Class: ClassRecordAdmitted, Prefix: "", Evidence: "OpenTofu's built-in terraform provider marks no attribute of terraform_data sensitive, measured over every attribute of every block of its schema, nested attribute types and nested blocks included"},
	"time_offset":             {Type: "time_offset", Class: ClassRecordAdmitted, Prefix: "time_", Evidence: "hashicorp/time 0.14.1 marks no attribute of time_offset sensitive, measured over every attribute of every block of its schema, nested attribute types and nested blocks included"},
	"time_rotating":           {Type: "time_rotating", Class: ClassRecordAdmitted, Prefix: "time_", Evidence: "hashicorp/time 0.14.1 marks no attribute of time_rotating sensitive, measured over every attribute of every block of its schema, nested attribute types and nested blocks included"},
	"time_sleep":              {Type: "time_sleep", Class: ClassRecordAdmitted, Prefix: "time_", Evidence: "hashicorp/time 0.14.1 marks no attribute of time_sleep sensitive, measured over every attribute of every block of its schema, nested attribute types and nested blocks included"},
	"time_static":             {Type: "time_static", Class: ClassRecordAdmitted, Prefix: "time_", Evidence: "hashicorp/time 0.14.1 marks no attribute of time_static sensitive, measured over every attribute of every block of its schema, nested attribute types and nested blocks included"},
	"tls_cert_request":        {Type: "tls_cert_request", Class: ClassSecretRefused, Prefix: "tls_", Evidence: "hashicorp/tls 4.3.0 marks private_key_pem sensitive"},
	"tls_locally_signed_cert": {Type: "tls_locally_signed_cert", Class: ClassSecretRefused, Prefix: "tls_", Evidence: "hashicorp/tls 4.3.0 marks ca_private_key_pem sensitive"},
	"tls_private_key":         {Type: "tls_private_key", Class: ClassSecretRefused, Prefix: "tls_", Evidence: "hashicorp/tls 4.3.0 marks private_key_openssh, private_key_pem and private_key_pem_pkcs8 sensitive"},
	"tls_self_signed_cert":    {Type: "tls_self_signed_cert", Class: ClassSecretRefused, Prefix: "tls_", Evidence: "hashicorp/tls 4.3.0 marks private_key_pem sensitive"},
}
