// Copyright (c) The OpenTofu Authors
// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2023 HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by tools/row-gen -emit. DO NOT EDIT.

package lint

// logicalFamilyPrefixes are the provider-local type prefixes whose resources
// exist only inside OpenTofu's own record of them. See live/LIMITATIONS.md.
//
// Membership here is what makes a type with no [logicalTypes] row of its own
// still classify - as [ClassOtherRefused], except the tls_ family, see
// [ClassifyLogicalType] - instead of falling through to the generic
// unadmitted-type refusal. A random_id gets the logical-resource explanation
// for why its whole family is out, not the generic "not in the v0 table"
// message.
//
// One entry per provider in tools/row-gen's logicalProviderSources, taken
// from the last segment of its source address. hashicorp/local is here and
// contributes no [logicalTypes] row: its resources are not store-only, so its
// types keep the no-row-found default. OpenTofu's built-in provider
// contributes no prefix at all - terraform_data is admitted by exact type
// name, because a "terraform_" prefix would claim a whole family this fork
// has never surveyed.
var logicalFamilyPrefixes = []string{
	"local_",
	"null_",
	"random_",
	"time_",
	"tls_",
}

// logicalTypes is the per-type classification table, derived from
// live/logical-schemas.json: every managed resource type served by a
// store-only provider, classified by the rule that a live (non-deprecated)
// sensitive attribute anywhere in the type's schema means it handles material
// live/RECEIPTS.md's no-secrets rule forbids a record from carrying, and none
// means the record can hold the type's whole value.
//
// It is the same rule, over the same artifact, that derives
// [identity.TypeIdentity.RecordBacked] - deliberately, so that lint's
// RECORD_ADMITTED and identity's RecordBacked cannot name different sets.
// They did once: the four types the hand-written table predated resolved
// under identity and were refused outright by lint, so a configuration with a
// record_store declared got told its type was out of the subset.
//
// A type in a [logicalFamilyPrefixes] family with no row here classifies
// [ClassOtherRefused] by default (see [ClassifyLogicalType]).
var logicalTypes = map[string]LogicalType{
	"null_resource":           {Type: "null_resource", Class: ClassRecordAdmitted, Prefix: "null_", Evidence: "hashicorp/null 3.3.1 marks no attribute of null_resource sensitive, measured over every attribute of every block of its schema, nested attribute types and nested blocks included"},
	"random_bytes":            {Type: "random_bytes", Class: ClassSecretRefused, Prefix: "random_", Evidence: "hashicorp/random 3.9.0 marks base64 and hex sensitive"},
	"random_id":               {Type: "random_id", Class: ClassRecordAdmitted, Prefix: "random_", Evidence: "hashicorp/random 3.9.0 marks no attribute of random_id sensitive, measured over every attribute of every block of its schema, nested attribute types and nested blocks included"},
	"random_integer":          {Type: "random_integer", Class: ClassRecordAdmitted, Prefix: "random_", Evidence: "hashicorp/random 3.9.0 marks no attribute of random_integer sensitive, measured over every attribute of every block of its schema, nested attribute types and nested blocks included"},
	"random_password":         {Type: "random_password", Class: ClassSecretRefused, Prefix: "random_", Evidence: "hashicorp/random 3.9.0 marks bcrypt_hash and result sensitive"},
	"random_pet":              {Type: "random_pet", Class: ClassRecordAdmitted, Prefix: "random_", Evidence: "hashicorp/random 3.9.0 marks no attribute of random_pet sensitive, measured over every attribute of every block of its schema, nested attribute types and nested blocks included"},
	"random_shuffle":          {Type: "random_shuffle", Class: ClassRecordAdmitted, Prefix: "random_", Evidence: "hashicorp/random 3.9.0 marks no attribute of random_shuffle sensitive, measured over every attribute of every block of its schema, nested attribute types and nested blocks included"},
	"random_string":           {Type: "random_string", Class: ClassRecordAdmitted, Prefix: "random_", Evidence: "hashicorp/random 3.9.0 marks no attribute of random_string sensitive, measured over every attribute of every block of its schema, nested attribute types and nested blocks included"},
	"random_uuid":             {Type: "random_uuid", Class: ClassRecordAdmitted, Prefix: "random_", Evidence: "hashicorp/random 3.9.0 marks no attribute of random_uuid sensitive, measured over every attribute of every block of its schema, nested attribute types and nested blocks included"},
	"random_uuid4":            {Type: "random_uuid4", Class: ClassRecordAdmitted, Prefix: "random_", Evidence: "hashicorp/random 3.9.0 marks no attribute of random_uuid4 sensitive, measured over every attribute of every block of its schema, nested attribute types and nested blocks included"},
	"random_uuid7":            {Type: "random_uuid7", Class: ClassRecordAdmitted, Prefix: "random_", Evidence: "hashicorp/random 3.9.0 marks no attribute of random_uuid7 sensitive, measured over every attribute of every block of its schema, nested attribute types and nested blocks included"},
	"terraform_data":          {Type: "terraform_data", Class: ClassRecordAdmitted, Prefix: "", Evidence: "OpenTofu's built-in terraform provider marks no attribute of terraform_data sensitive, measured over every attribute of every block of its schema, nested attribute types and nested blocks included"},
	"time_offset":             {Type: "time_offset", Class: ClassRecordAdmitted, Prefix: "time_", Evidence: "hashicorp/time 0.14.1 marks no attribute of time_offset sensitive, measured over every attribute of every block of its schema, nested attribute types and nested blocks included"},
	"time_rotating":           {Type: "time_rotating", Class: ClassRecordAdmitted, Prefix: "time_", Evidence: "hashicorp/time 0.14.1 marks no attribute of time_rotating sensitive, measured over every attribute of every block of its schema, nested attribute types and nested blocks included"},
	"time_sleep":              {Type: "time_sleep", Class: ClassRecordAdmitted, Prefix: "time_", Evidence: "hashicorp/time 0.14.1 marks no attribute of time_sleep sensitive, measured over every attribute of every block of its schema, nested attribute types and nested blocks included"},
	"time_static":             {Type: "time_static", Class: ClassRecordAdmitted, Prefix: "time_", Evidence: "hashicorp/time 0.14.1 marks no attribute of time_static sensitive, measured over every attribute of every block of its schema, nested attribute types and nested blocks included"},
	"tls_cert_request":        {Type: "tls_cert_request", Class: ClassSecretRefused, Prefix: "tls_", Evidence: "hashicorp/tls 4.3.0 marks private_key_pem sensitive"},
	"tls_locally_signed_cert": {Type: "tls_locally_signed_cert", Class: ClassSecretRefused, Prefix: "tls_", Evidence: "hashicorp/tls 4.3.0 marks ca_private_key_pem sensitive"},
	"tls_private_key":         {Type: "tls_private_key", Class: ClassSecretRefused, Prefix: "tls_", Evidence: "hashicorp/tls 4.3.0 marks private_key_openssh, private_key_pem and private_key_pem_pkcs8 sensitive"},
	"tls_self_signed_cert":    {Type: "tls_self_signed_cert", Class: ClassSecretRefused, Prefix: "tls_", Evidence: "hashicorp/tls 4.3.0 marks private_key_pem sensitive"},
}
