// Copyright (c) The OpenTofu Authors
// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2023 HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package main

import (
	"sort"
	"strings"

	"github.com/intentius/choudoufu/internal/live/identity"
)

// This file is the second admission bound this generator states as a rule
// (GitHub issue #272), and it is markerless.go's rule read the other way
// round: a type the veto catches - the provider mints its identity, and it
// has no tags argument to write an ownership marker into - is nonetheless
// admissible when AWS itself refuses to issue the name the configuration
// supplies twice.
//
// # Why that is not the guess the marker spec forbids
//
// internal/live/foreign matches a live object's content against a
// declaration and deliberately never binds on the result: a content match is
// "surfaced for explicit adoption and never bound automatically", because
// "inferring it from a content match would be exactly the guess the marker
// spec exists to forbid". That is right for content. Two objects can carry
// the same CIDR, the same policy document, the same anything, and picking
// one of them is a guess.
//
// A name AWS guarantees unique is not content. If the API refuses to create
// a second cache policy called "static-assets", then "the cache policy
// called static-assets" names exactly one object in the account, and reading
// it off a listing is not inference - it is reading the identity the
// configuration already states. The exception is exactly as wide as the
// guarantee, and the guarantee's absence fails closed: a type reaches this
// rule only when TWO texts AWS wrote independently both make the claim, and
// a type with one source, or none, is left where the veto put it.
//
// # The two sources, and the rest of the bar
//
// Both halves compute internal/live/uniquename.Asserted over a different
// text, and neither generator knows about the other:
//
//   - live/import-grammar.json's argument_reference[].declared_unique, from
//     the provider's own Argument Reference bullet (tools/importdocs-gen);
//   - live/registry.json's unique_name_property, from the CloudFormation
//     registry schema's description of the same property, carrying the PATH
//     at which the name sits in a Cloud Control ResourceDescription
//     (tools/registry-gen).
//
// Four further conditions, each of which turns a maybe into a no:
//
//   - the argument has to be REQUIRED. An optional name is one a
//     configuration may leave out, and a name the configuration does not
//     state is a name no listing can be matched against. aws_lb is the
//     worked example: genuinely documented unique per account, and genuinely
//     autogenerated when omitted, so half its instances would have nothing
//     to match.
//   - the two sources have to be talking about the SAME argument. The
//     registry names a property path and the provider names a bullet, and
//     nothing guarantees a priori that they meet; the rule requires the
//     path's last segment, in the provider's own snake_case spelling, to be
//     the bullet that carries the claim. A schema whose unique name is
//     PolicyName and a doc whose unique argument is `name` are two claims
//     about two things, and this rule declines to treat them as one.
//   - the type has to be one the veto would otherwise catch, asked through
//     [markerless] itself rather than through a re-derivation of it, so the
//     rescue and the veto can never disagree about which types they are
//     talking about. A taggable type is already found by its own marker and
//     gains nothing; a type whose identity the configuration states never
//     reaches discovery at all.
//   - the type must NOT already be in the ratified corpus. A ratified row is
//     what ships for its type (see emit.go's own doc comment), and a
//     generator overriding one would be deciding something a human decided.
//
// # What the row says, and what it deliberately does not
//
// The identity is still the provider's to mint, so the row is
// ServerAssigned exactly as the veto said it was: [identity.Resolve]
// classifies every instance ClassNeedsDiscovery and builds no import ID.
// What changes is HOW discovery finds the object -
// [identity.TypeIdentity.UniqueName] tells it to compare the declared name
// against the listed object's own property instead of reading a marker off
// it - and, downstream of that, what a missing marker means: see
// [identity.DiscoveryUniqueName] and internal/live/stamp's mustStamp.
//
// ImportSyntax is left empty. It is documentation only (Components is what
// the code follows), nothing in either input states it for this class, and
// inventing a plausible token for four rows and leaving it blank for the
// next four would be worse than absence.

// uniqueNameReason is the whole ruling, stated once, for the same reason
// [markerlessReason] is: it is a rule, not one judgement per type, so a
// batch cannot edit one copy of it and diverge.
const uniqueNameReason = "the provider assigns this type's identity at create time and the type has no tags argument, " +
	"but the provider's own argument reference and the CloudFormation registry schema independently document the name this " +
	"configuration supplies as unique within the account and region, so a later run recognises the object by that name rather " +
	"than by an ownership marker"

// uniqueNameRows is the unique-name half of the emitted table: the rows this
// rule derives whole, for types the ratified corpus does not carry and the
// markerless veto would otherwise refuse.
//
// It returns the rows keyed by TF type. The key set is also the set
// [markerlessRoster] must skip, and it is passed there rather than recomputed
// so the two cannot drift.
func uniqueNameRows(ratified map[string]identity.TypeIdentity, survey map[string]surveyEntry, proposals []proposal, importGrammar map[string]importGrammarRow) map[string]identity.TypeIdentity {
	byType := indexByType(proposals)
	classified, documented := serverAssignmentVerdicts(proposals, importGrammar)

	out := make(map[string]identity.TypeIdentity)
	for typeName, entry := range survey {
		if _, admitted := ratified[typeName]; admitted {
			continue
		}
		// The veto's own question, asked with the rescue switched off. If
		// the answer is no, this type is not refused for the reason this
		// rule answers and has nothing to gain from it.
		agree := sourcesAgree(typeName, byType, importGrammar)
		if !markerless(entry.Signals.Taggable, false, identity.TypeIdentity{}, classified[typeName], documented[typeName], agree, false) {
			continue
		}
		p, ok := byType[typeName]
		if !ok || p.UniqueNameProp == "" {
			continue
		}
		arg, ok := uniqueNameArgument(p.UniqueNameProp, importGrammar[typeName])
		if !ok {
			continue
		}
		row := identity.TypeIdentity{
			Type:           typeName,
			ServerAssigned: true,
			Reason:         uniqueNameReason,
			ImportSyntax:   uniqueNameImportSyntax(p),
			UniqueName: identity.UniqueName{
				Attrs:    []string{arg},
				Property: p.UniqueNameProp,
			},
		}
		out[typeName] = mergeIdentityAttrs(row, survey[typeName])
	}
	return out
}

// uniqueNameImportSyntax is the documented import-ID grammar for a derived
// row, by the same rule [proposedFields] and [renderServerAssignedEntry]
// already use for every other server-assigned proposal: the import example's
// own shape where the documentation scrape recovered one, and the registry's
// primary identifier otherwise. It is documentation only - Components is what
// the code follows, and a ServerAssigned row has none - but every non-record
// row is required to carry one (identity.TestTableEntriesWellFormed), and a
// derived row has no ratification pass to write one during.
func uniqueNameImportSyntax(p proposal) string {
	if p.DerivedImportSyntax != "" {
		return p.DerivedImportSyntax
	}
	return strings.ToUpper(strings.Join(p.PrimaryIdentifier, "-"))
}

// uniqueNameArgument is the crossing itself: it reports the configuration
// argument that both sources are talking about, or refuses.
//
// prop is the registry's property path ("CachePolicyConfig/Name"), whose
// last segment is the property carrying the uniqueness claim. That segment,
// in the provider's own snake_case spelling, is the argument the provider's
// Argument Reference has to be making the same claim about - as a REQUIRED
// bullet whose own declared_unique is set.
//
// Requiring the two to name one argument is what stops the rule from reading
// a claim about one thing as a claim about another. Nothing guarantees that
// a schema calling PolicyName unique and a doc calling `name` unique are
// describing the same value, and treating them as one would be a bind on a
// property the provider never said anything about.
//
// [snakeCase]'s own doc comment calls the CFN-to-TF spelling a GUESS, and it
// is - which is why it is used here to REFUSE rather than to name. A wrong
// guess finds no matching bullet and the type stays vetoed; it can never
// produce a row pointing at an argument the provider does not document.
func uniqueNameArgument(prop string, g importGrammarRow) (string, bool) {
	segs := strings.Split(prop, "/")
	want := snakeCase(segs[len(segs)-1])
	if want == "" {
		return "", false
	}
	for _, a := range g.ArgumentReference {
		if a.Name == want && a.Required && a.DeclaredUnique {
			return a.Name, true
		}
	}
	return "", false
}

// sortedUniqueNameTypes is uniqueNameRows' key set, sorted, for the callers
// that report it.
func sortedUniqueNameTypes(rows map[string]identity.TypeIdentity) []string {
	out := make([]string, 0, len(rows))
	for t := range rows {
		out = append(out, t)
	}
	sort.Strings(out)
	return out
}
