# Supporting, not coverage - added only so aws_iam_role.databases's referring resources have a value to point at: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: schema requires "assume_role_policy" as a plain string, but the provider validates it is well-formed JSON (validate: "\"assume_role_policy\" contains an invalid JSON"); the generic string placeholder is not JSON
resource "aws_iam_role" "databases" {
  name = "tofu-databases-cohort-iam-role"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "databases.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_iam_role.databases"
  }
}

# Supporting, not coverage - added only so aws_security_group.databases's referring resources have a value to point at: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: none
resource "aws_security_group" "databases" {
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_security_group.databases"
  }
}

# Supporting, not coverage - added only so aws_subnet.databases's referring resources have a value to point at: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: none
resource "aws_subnet" "databases" {
  vpc_id = "placeholder"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_subnet.databases"
  }
}
