#!/usr/bin/env bash
# convert.sh: how root/vpa-crd.tf was made, and how to remake it.
#
# corpus-cloud-platform-components declares kubernetes_manifest objects of
# kind VerticalPodAutoscaler (manager-vpas.tf, ministryofjustice/
# cloud-platform-infrastructure at 6e1eca7be0). On cloud-platform's own
# clusters the CRD that serves that kind is installed by a module this
# crossing prunes (the ~15 github.com/ministryofjustice/* module calls are
# not in .corpus/_modules), so a kind cluster does not serve it. The
# crossing installs it as a declared cold-deploy pre-apply (#1173), the way
# reference-k8s-cert-manager installs cert-manager's: this file converts
# the VPA project's own CRD manifest into two kubernetes_manifest blocks.
#
# Provenance, re-verified on 2026-10-04 before this file was written and
# asserted below rather than trusted:
#
#   source   https://raw.githubusercontent.com/kubernetes/autoscaler/vertical-pod-autoscaler-1.8.0/vertical-pod-autoscaler/deploy/vpa-v1-crd-gen.yaml
#   tag      vertical-pod-autoscaler-1.8.0 (commit 238579734e73e4a263d1ab75a44353e58eeee3ea), published 2026-09-23
#   size     51,124 bytes
#   sha256   2916e9b8e0699375ed8eca8af81e00c5a8cf9d68a70b4796e24d43794838d623
#   licence  Apache-2.0 (kubernetes/autoscaler's LICENSE). The file is
#            controller-gen output and carries no header of its own, so
#            the notice is restated at the top of root/vpa-crd.tf.
#   tool     tfk8s v0.1.10 (go install github.com/jrhouston/tfk8s@v0.1.10)
#
# Needs network and tfk8s. The run script does NOT call this: root/ is
# committed, so a run needs no fetch beyond the corpus pin and the
# providers, and this file exists so that "converted mechanically" is a
# claim someone can check.
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
URL="https://raw.githubusercontent.com/kubernetes/autoscaler/vertical-pod-autoscaler-1.8.0/vertical-pod-autoscaler/deploy/vpa-v1-crd-gen.yaml"
WANT_SHA="2916e9b8e0699375ed8eca8af81e00c5a8cf9d68a70b4796e24d43794838d623"
WANT_BYTES=51124
WORK="$(mktemp -d)"
# A run that stops before its last step is refused rather than read as a
# pass (#1421, the same trap reference-k8s-cert-manager/convert.sh sets).
convert_finished=0
# shellcheck disable=SC2154 # convert_rc is assigned on the trap's first line
trap 'convert_rc=$?
      rm -rf "$WORK"
      if [ "$convert_finished" != 1 ]; then
        echo "convert.sh: FAIL: stopped before writing root/vpa-crd.tf, so the file on disk is whatever was there before. Read the output above for where." >&2
        exit 1
      fi
      exit $convert_rc' EXIT

command -v tfk8s >/dev/null 2>&1 || { echo "convert.sh: tfk8s is not on PATH (go install github.com/jrhouston/tfk8s@v0.1.10)" >&2; exit 1; }

echo "fetching $URL"
curl -fsSL -o "$WORK/vpa-v1-crd-gen.yaml" "$URL" || { echo "convert.sh: fetch failed" >&2; exit 1; }

got_sha="$(shasum -a 256 "$WORK/vpa-v1-crd-gen.yaml" | awk '{print $1}')"
got_bytes="$(wc -c < "$WORK/vpa-v1-crd-gen.yaml" | tr -d ' ')"
[ "$got_sha" = "$WANT_SHA" ] || { echo "convert.sh: sha256 is $got_sha, want $WANT_SHA - the tagged file moved, which is a fact worth an issue, not a pin to update quietly" >&2; exit 1; }
[ "$got_bytes" = "$WANT_BYTES" ] || { echo "convert.sh: $got_bytes bytes, want $WANT_BYTES" >&2; exit 1; }
echo "  $got_bytes bytes, sha256 $got_sha - matches the pin"

# tfk8s turns each YAML document into one kubernetes_manifest block. The
# file holds two CRDs (VerticalPodAutoscalerCheckpoint and
# VerticalPodAutoscaler); both are converted, because the pair is what the
# VPA project ships as "the CRDs", and the declared pre-apply installs
# what was shipped rather than the half this root happens to use.
tfk8s -f "$WORK/vpa-v1-crd-gen.yaml" -o "$WORK/vpa-crd.tf" || { echo "convert.sh: tfk8s failed" >&2; exit 1; }
n="$(grep -c '^resource "kubernetes_manifest"' "$WORK/vpa-crd.tf")"
[ "$n" = "2" ] || { echo "convert.sh: the conversion produced $n blocks, want 2" >&2; exit 1; }

{
  cat <<'HDR'
# Copyright The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# ---------------------------------------------------------------------
# GENERATED by live/e2e/corpus-cloud-platform-components/convert.sh from
# kubernetes/autoscaler's vertical-pod-autoscaler/deploy/vpa-v1-crd-gen.yaml
# at tag vertical-pod-autoscaler-1.8.0 (51,124 bytes, sha256
# 2916e9b8e0699375ed8eca8af81e00c5a8cf9d68a70b4796e24d43794838d623) with
# tfk8s v0.1.10. Do not hand-edit: rerun convert.sh. The licence notice
# above is kubernetes/autoscaler's, restated because the generated file
# carries none of its own.
# ---------------------------------------------------------------------
HDR
  cat "$WORK/vpa-crd.tf"
} > "$HERE/root/vpa-crd.tf"
convert_finished=1

echo "wrote $HERE/root/vpa-crd.tf ($(wc -c < "$HERE/root/vpa-crd.tf" | tr -d ' ') bytes, $n blocks)"
echo
echo "If the block NAMES changed, live/gauntlet/estates.json's pre_apply list is now stale."
echo "These two addresses must be in it:"
grep -o '^resource "kubernetes_manifest" "[^"]*"' "$HERE/root/vpa-crd.tf" | sed 's/.*"kubernetes_manifest" "/  kubernetes_manifest./; s/"$//'
