// Copyright (c) The OpenTofu Authors
// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2023 HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package projection

import (
	"context"

	"github.com/hashicorp/hcl/v2"
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"

	"github.com/intentius/choudoufu/internal/addrs"
	"github.com/intentius/choudoufu/internal/configs"
	"github.com/intentius/choudoufu/internal/lang"
	"github.com/intentius/choudoufu/internal/live/markers"
	"github.com/intentius/choudoufu/internal/providers"
)

// The metadata seed (#1885: corpus-govuk-cluster-access and
// corpus-k8s-metrics-server, both a perpetual in-place diff on a plan with
// no state file).
//
// hashicorp/kubernetes's typed resources read metadata through
// flattenMetadata, which drops every live label and annotation whose key is
// "internal" - any host ending in kubernetes.io other than app.kubernetes.io
// and service.beta.kubernetes.io - UNLESS the prior state's own
// metadata.0.labels (or annotations) already names that key. A state file's
// prior always names the keys the configuration last applied, so stock keeps
// pod-security.kubernetes.io/enforce or kubernetes.io/name and plans nothing.
// choudoufu's prior is an import stub whose metadata is empty, so the read
// drops the key, the plan proposes adding it back, the apply writes the value
// the object already holds, and the next read drops it again - forever.
//
// [configuredAttrsSeed] never reaches inside a nested block, so this seeds
// the two maps from the configuration into the stub's single metadata item,
// the same "what a persisted prior would have held" claim the flat seed
// makes. It cannot invent a value: the provider's read builds both maps from
// the LIVE object and only consults the prior to decide which live internal
// keys to keep, so a declared key the live object lacks is still absent from
// the result and still plans. name and namespace are never seeded - they
// are identity, which only the marker and the record decide.

// metadataSeedKey is the attrsSeed entry carrying the seed, an object of the
// seeded leaves. It cannot collide with a schema attribute name (a NUL is not
// a legal identifier) nor with a residue path key (those begin with '['), so
// [withSeededAttrs] passes over it and only [readImported] applies it.
const metadataSeedKey = "\x00metadata"

// metadataSeedAttrs are the metadata leaves the seed carries.
var metadataSeedAttrs = []string{markers.LabelSurfaceAttr, "annotations"}

// configuredMetadataSeed statically evaluates the configuration's own
// metadata { labels, annotations } for a label-surface resource. It returns
// only the leaves that evaluate wholly known; nothing at all when the block
// is absent, repeated, generated by a dynamic block, or unresolvable.
func configuredMetadataSeed(ctx context.Context, eval *configs.StaticEvaluator, modPath addrs.Module, rc *configs.Resource, schema providers.Schema) (seed map[string]cty.Value) {
	if eval == nil || rc == nil || rc.Config == nil || schema.Block == nil {
		return nil
	}
	if _, ok := markers.LabelSurface(schema.Block); !ok {
		return nil
	}
	nested := schema.Block.BlockTypes[markers.LabelSurfaceBlock]
	defer func() {
		if rec := recover(); rec != nil {
			seed = nil
		}
	}()

	content, _, diags := rc.Config.PartialContent(&hcl.BodySchema{
		Blocks: []hcl.BlockHeaderSchema{{Type: markers.LabelSurfaceBlock}},
	})
	if diags.HasErrors() || len(content.Blocks) != 1 {
		return nil
	}
	body := content.Blocks[0].Body

	ident := configs.StaticIdentifier{
		Module:    modPath,
		Subject:   rc.Addr().String(),
		DeclRange: rc.DeclRange,
	}
	for _, name := range metadataSeedAttrs {
		attr := nested.Block.Attributes[name]
		if attr == nil || attr.Computed || !attr.Type.IsMapType() {
			continue
		}
		spec := hcldec.ObjectSpec{name: &hcldec.AttrSpec{Name: name, Type: attr.Type}}
		refs, refDiags := lang.References(addrs.ParseRef, hcldec.Variables(body, spec))
		if refDiags.HasErrors() {
			continue
		}
		hclCtx, ctxDiags := eval.EvalContext(ctx, ident, refs)
		if ctxDiags.HasErrors() {
			continue
		}
		if hclCtx == nil {
			hclCtx = &hcl.EvalContext{}
		}
		val, _, valDiags := hcldec.PartialDecode(body, spec, hclCtx)
		if valDiags.HasErrors() || val == cty.NilVal || val.IsNull() || !val.Type().HasAttribute(name) {
			continue
		}
		// Unmarked for the same reason configuredTagsSeed unmarks: the seed
		// crosses the plugin channel, which refuses a marked value, and what
		// is persisted is the read's answer, marked from the schema.
		v, _ := val.GetAttr(name).UnmarkDeep()
		if v.IsNull() || !v.IsWhollyKnown() {
			continue
		}
		if seed == nil {
			seed = map[string]cty.Value{}
		}
		seed[name] = v
	}
	return seed
}

// mergeMetadataSeed returns the stub's metadata list with its single item's
// seeded leaves set, creating that item (every other leaf null) when the
// stub's list is null or empty. A list of more than one item, or a value of
// an unexpected shape, is returned unchanged with false.
func mergeMetadataSeed(stub cty.Value, seed map[string]cty.Value, elemTy cty.Type) (cty.Value, bool) {
	if len(seed) == 0 || !elemTy.IsObjectType() {
		return stub, false
	}
	elem := cty.NullVal(elemTy)
	if stub != cty.NilVal && !stub.IsNull() {
		if stub.IsMarked() || !stub.IsWhollyKnown() || !stub.Type().IsListType() || !stub.Type().ElementType().Equals(elemTy) {
			return stub, false
		}
		switch stub.LengthInt() {
		case 0:
		case 1:
			elem = stub.Index(cty.NumberIntVal(0))
		default:
			return stub, false
		}
	}
	attrs := make(map[string]cty.Value, len(elemTy.AttributeTypes()))
	for name, aty := range elemTy.AttributeTypes() {
		if elem.IsNull() {
			attrs[name] = cty.NullVal(aty)
		} else {
			attrs[name] = elem.GetAttr(name)
		}
	}
	seeded := false
	for name, v := range seed {
		aty, has := elemTy.AttributeTypes()[name]
		if !has || !v.Type().Equals(aty) {
			continue
		}
		attrs[name] = v
		seeded = true
	}
	if !seeded {
		return stub, false
	}
	return cty.ListVal([]cty.Value{cty.ObjectVal(attrs)}), true
}

// withSeededMetadata applies [configuredMetadataSeed]'s answer to an import
// stub. See this file's doc comment.
func withSeededMetadata(v cty.Value, seed map[string]cty.Value, schema providers.Schema) (cty.Value, bool) {
	if len(seed) == 0 || schema.Block == nil || v == cty.NilVal || v.IsNull() || v.IsMarked() || !v.Type().IsObjectType() || !v.Type().HasAttribute(markers.LabelSurfaceBlock) {
		return v, false
	}
	nested := schema.Block.BlockTypes[markers.LabelSurfaceBlock]
	if nested == nil {
		return v, false
	}
	merged, ok := mergeMetadataSeed(v.GetAttr(markers.LabelSurfaceBlock), seed, nested.Block.ImpliedType())
	if !ok {
		return v, false
	}
	attrs := v.AsValueMap()
	attrs[markers.LabelSurfaceBlock] = merged
	return cty.ObjectVal(attrs), true
}
