# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: schema requires only name; vpc_config and permissions_config are both optional blocks, but the provider requires both in practice (validate: "Missing required argument") - permissions_config needs the shared aws_iam_role's ARN, which is why this type also sets NeedsIAMRole
resource "aws_lambda_capacity_provider" "app" {
  name = "tofu-lambda-cohort-capacity-provider"
  vpc_config {
    subnet_ids         = ["subnet-0123456789abcdef0"]
    security_group_ids = ["sg-0123456789abcdef0"]
  }
  permissions_config {
    capacity_provider_operator_role_arn = aws_iam_role.lambda.arn
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_lambda_capacity_provider.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: allowed_publishers.signing_profile_version_arns is a required set of strings, but the provider validates each element is a well-formed ARN (validate: "is an invalid ARN"); the generic placeholder string is not one
resource "aws_lambda_code_signing_config" "app" {
  allowed_publishers {
    signing_profile_version_arns = ["arn:aws:signer:us-east-1:000000000000:/signing-profiles/tofu_lambda_cohort/1a2b3c4d5e"]
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_lambda_code_signing_config.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: schema requires only function_name; the provider also requires exactly one of event_source_arn/self_managed_event_source (validate: "one of ... must be specified"), and event_source_arn requires starting_position
resource "aws_lambda_event_source_mapping" "app" {
  function_name     = aws_lambda_function.app.function_name
  event_source_arn  = "arn:aws:dynamodb:us-east-1:000000000000:table/tofu-lambda-cohort-events/stream/2026-01-01T00:00:00.000"
  starting_position = "LATEST"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_lambda_event_source_mapping.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: schema requires only function_name and role; the provider also requires exactly one of filename/image_uri/s3_bucket (validate: "one of ... must be specified"), and image_uri requires package_type = "Image"
resource "aws_lambda_function" "app" {
  function_name = "tofu-lambda-cohort-function"
  role          = aws_iam_role.lambda.arn
  package_type  = "Image"
  image_uri     = "000000000000.dkr.ecr.us-east-1.amazonaws.com/tofu-lambda-cohort-app:latest"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_lambda_function.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: schema requires only layer_name; the provider also requires one of filename/s3_bucket (validate: "one of ... must be specified"), and s3_bucket requires s3_key; compatible_runtimes is optional in the schema but left empty renders a layer no function could ever reference
resource "aws_lambda_layer_version" "app" {
  layer_name          = "tofu-lambda-cohort-layer-version"
  s3_bucket           = "tofu-lambda-cohort-artifacts"
  s3_key              = "layers/app.zip"
  compatible_runtimes = ["python3.13"]
}

# Coverage: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: action, principal, statement_id
resource "aws_lambda_permission" "app" {
  function_name = aws_lambda_function.app.function_name
  action        = "lambda:InvokeFunction"
  principal     = "apigateway.amazonaws.com"
  statement_id  = "AllowMyDemoAPIInvoke"
}
