# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: build_spec, repository, custom_rule.source, custom_rule.status, custom_rule.target
resource "aws_amplify_app" "app" {
  name       = aws_elastic_beanstalk_application.app.name
  build_spec = "version: 0.1\nfrontend:\n  phases:\n    preBuild:\n      commands:\n        - yarn install\n    build:\n      commands:\n        - yarn run build\n  artifacts:\n    baseDirectory: build\n    files:\n      - '**/*'\n  cache:\n    paths:\n      - node_modules/**/*\n"
  repository = "https://github.com/example/app"
  custom_rule {
    source = "/<*>"
    status = "404"
    target = "/index.html"
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_amplify_app.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: none
resource "aws_amplify_branch" "app" {
  app_id      = aws_amplify_app.app.id
  branch_name = "tofu-compute-platforms-cohort-amplify-branch"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_amplify_branch.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: max_concurrency, max_size, min_size
resource "aws_apprunner_auto_scaling_configuration_version" "app" {
  auto_scaling_configuration_name = "tofu-compute-platforms-cohort-apprunner-auto-scaling-configuration-version"
  max_concurrency                 = 50
  max_size                        = 10
  min_size                        = 2
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_apprunner_auto_scaling_configuration_version.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: trace_configuration.vendor
resource "aws_apprunner_observability_configuration" "app" {
  observability_configuration_name = "tofu-compute-platforms-cohort-apprunner-observability-configuration"
  trace_configuration {
    vendor = "AWSXRAY"
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_apprunner_observability_configuration.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: source_configuration is a required block with no required attributes the schema itself names inside it, but the provider requires exactly one of source_configuration.code_repository or source_configuration.image_repository set (validate: "one of ... must be specified"); the generic pass emits the outer block empty
resource "aws_apprunner_service" "app" {
  service_name = "tofu-compute-platforms-cohort-apprunner-service"
  source_configuration {
    image_repository {
      image_identifier      = "public.ecr.aws/aws-containers/hello-app-runner:latest"
      image_repository_type = "ECR_PUBLIC"
    }
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_apprunner_service.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: vpc_connector_name is a required string the schema does not length-constrain, but the provider validates it is at most 40 characters (validate: "expected length of vpc_connector_name to be in the range (4 - 40)"); the generic "tofu-<cohort>-cohort-<type>" name is 44
resource "aws_apprunner_vpc_connector" "app" {
  security_groups    = ["placeholder"]
  subnets            = ["placeholder"]
  vpc_connector_name = "tofu-cp-apprunner-vpc-conn"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_apprunner_vpc_connector.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: service_arn is a required string the schema does not constrain, but the provider validates it is a well-formed ARN (validate: "is an invalid ARN")
resource "aws_apprunner_vpc_ingress_connection" "app" {
  name        = aws_elastic_beanstalk_application.app.name
  service_arn = "arn:aws:apprunner:us-east-1:000000000000:service/tofu-compute-platforms-cohort-apprunner-service/00000000000000000000000000000000"
  ingress_vpc_configuration {
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_apprunner_vpc_ingress_connection.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: type is a required string the schema does not constrain to an enum, but the provider validates it against a fixed set (validate: "expected type to be one of [MANAGED UNMANAGED]"); UNMANAGED needs no further compute_resources block, the smaller of the two shapes
resource "aws_batch_compute_environment" "app" {
  type = "UNMANAGED"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_batch_compute_environment.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: type is a required string the schema does not constrain to an enum, but the provider validates it against a fixed set (validate: "expected type to be one of [container multinode]"); a container job definition also needs container_properties, a JSON string the schema does not otherwise require, with at least image and a resource sizing (validate: "invalid JSON")
resource "aws_batch_job_definition" "app" {
  name = aws_elastic_beanstalk_application.app.name
  type = "container"
  container_properties = jsonencode({
    image  = "busybox"
    vcpus  = 1
    memory = 512
  })
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_batch_job_definition.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: state is a required string the schema does not constrain to an enum, but the provider validates it against a fixed set (validate: "Attribute state value must be one of: [\"ENABLED\" \"DISABLED\"]")
resource "aws_batch_job_queue" "app" {
  name     = aws_elastic_beanstalk_application.app.name
  priority = 0
  state    = "ENABLED"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_batch_job_queue.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: fair_share_policy.compute_reservation, fair_share_policy.share_decay_seconds
resource "aws_batch_scheduling_policy" "app" {
  name = aws_elastic_beanstalk_application.app.name
  fair_share_policy {
    compute_reservation = 1
    share_decay_seconds = 3600
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_batch_scheduling_policy.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: description
resource "aws_elastic_beanstalk_application" "app" {
  name        = "tofu-compute-platforms-cohort-elastic-beanstalk-application"
  description = "tf-test-desc"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_elastic_beanstalk_application.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: none
resource "aws_elastic_beanstalk_environment" "app" {
  application = "placeholder"
  name        = aws_elastic_beanstalk_application.app.name
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_elastic_beanstalk_environment.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: release_label, master_instance_group.instance_type, core_instance_group.autoscaling_policy, core_instance_group.bid_price, core_instance_group.instance_count, core_instance_group.instance_type, core_instance_group.ebs_config.size, core_instance_group.ebs_config.type, core_instance_group.ebs_config.volumes_per_instance, bootstrap_action.name, bootstrap_action.path
resource "aws_emr_cluster" "app" {
  name          = aws_elastic_beanstalk_application.app.name
  release_label = "emr-4.6.0"
  service_role  = "placeholder"
  master_instance_group {
    instance_type = "m4.large"
  }
  core_instance_group {
    autoscaling_policy = "{\n\"Constraints\": {\n  \"MinCapacity\": 1,\n  \"MaxCapacity\": 2\n},\n\"Rules\": [\n  {\n    \"Name\": \"ScaleOutMemoryPercentage\",\n    \"Description\": \"Scale out if YARNMemoryAvailablePercentage is less than 15\",\n    \"Action\": {\n      \"SimpleScalingPolicyConfiguration\": {\n        \"AdjustmentType\": \"CHANGE_IN_CAPACITY\",\n        \"ScalingAdjustment\": 1,\n        \"CoolDown\": 300\n      }\n    },\n    \"Trigger\": {\n      \"CloudWatchAlarmDefinition\": {\n        \"ComparisonOperator\": \"LESS_THAN\",\n        \"EvaluationPeriods\": 1,\n        \"MetricName\": \"YARNMemoryAvailablePercentage\",\n        \"Namespace\": \"AWS/ElasticMapReduce\",\n        \"Period\": 300,\n        \"Statistic\": \"AVERAGE\",\n        \"Threshold\": 15.0,\n        \"Unit\": \"PERCENT\"\n      }\n    }\n  }\n]\n}\n"
    bid_price          = "0.30"
    instance_count     = 1
    instance_type      = "c4.large"
    ebs_config {
      size                 = "40"
      type                 = "gp2"
      volumes_per_instance = 1
    }
  }
  bootstrap_action {
    name = "runif"
    path = "s3://elasticmapreduce/bootstrap-actions/run-if"
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_emr_cluster.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: configuration is a required string the schema does not otherwise constrain, but the provider validates it is well-formed JSON (validate: "contains an invalid JSON"); the generic string placeholder is not
resource "aws_emr_security_configuration" "app" {
  name = "tofu-compute-platforms-cohort-emr-security-configuration"
  configuration = jsonencode({
    EncryptionConfiguration = {
      EnableInTransitEncryption = false
      EnableAtRestEncryption    = false
    }
  })
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: auth_mode is a required string the schema does not constrain to an enum, but the provider validates it against a fixed set (validate: "expected auth_mode to be one of [SSO IAM]"); service_role is a required string the schema does not constrain, but the provider validates it is a well-formed ARN (validate: "is an invalid ARN")
resource "aws_emr_studio" "app" {
  auth_mode                   = "SSO"
  default_s3_location         = "placeholder"
  engine_security_group_id    = "placeholder"
  name                        = aws_elastic_beanstalk_application.app.name
  service_role                = "arn:aws:iam::000000000000:role/tofu-compute-platforms-cohort-emr-studio"
  subnet_ids                  = ["placeholder"]
  vpc_id                      = "placeholder"
  workspace_security_group_id = "placeholder"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_emr_studio.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: container_provider.type is a required string the schema does not constrain to an enum, but the provider validates it against a fixed set (validate: "expected type to be one of [EKS]")
resource "aws_emrcontainers_virtual_cluster" "app" {
  name = aws_elastic_beanstalk_application.app.name
  container_provider {
    id   = "placeholder"
    type = "EKS"
    info {
      eks_info {
      }
    }
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_emrcontainers_virtual_cluster.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: release_label, type
resource "aws_emrserverless_application" "app" {
  name          = aws_elastic_beanstalk_application.app.name
  release_label = "emr-6.6.0"
  type          = "hive"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_emrserverless_application.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: bundle_id
resource "aws_lightsail_bucket" "app" {
  name      = "tofu-compute-platforms-cohort-lightsail-bucket"
  bundle_id = "small_1_0"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_lightsail_bucket.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: cfn-required (live/registry-schema-facts.json): domain_name
resource "aws_lightsail_certificate" "app" {
  name        = "tofu-compute-platforms-cohort-lightsail-certificate"
  domain_name = "tofu-compute-platforms-cohort-lightsail-certificate"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_lightsail_certificate.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: power is a required string the schema does not constrain to an enum, but the provider validates it against a fixed set (validate: "expected power to be one of [...]"); scale is a required number the schema does not range-constrain, but the provider validates it is between 1 and 20 (validate: "expected scale to be in the range (1 - 20), got 0")
resource "aws_lightsail_container_service" "app" {
  name  = "tofu-compute-platforms-cohort-lightsail-container-service"
  power = "nano"
  scale = 1
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_lightsail_container_service.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: master_database_name is a required string the schema does not otherwise constrain, but the provider validates it against a stricter character set than the generic "tofu-<cohort>-cohort-<type>" placeholder's hyphens allow (validate: "Subsequent characters can be letters, underscores, or digits")
resource "aws_lightsail_database" "app" {
  relational_database_name = "tofu-compute-platforms-cohort-lightsail-database"
  blueprint_id             = "placeholder"
  bundle_id                = "placeholder"
  master_database_name     = "tofu_compute_platforms_database"
  master_password          = "placeholder"
  master_username          = "placeholder"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_lightsail_database.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: size_in_gb
resource "aws_lightsail_disk" "app" {
  name              = "tofu-compute-platforms-cohort-lightsail-disk"
  availability_zone = "placeholder"
  size_in_gb        = 8
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_lightsail_disk.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: default_cache_behavior.behavior is a required string the schema does not constrain to an enum, but the provider validates it against a fixed set (validate: "expected default_cache_behavior.0.behavior to be one of [dont-cache cache]"); origin.region_name is a required string the schema does not constrain, but the provider validates it looks like an AWS region (validate: "doesn't look like AWS Region")
resource "aws_lightsail_distribution" "app" {
  name      = "tofu-compute-platforms-cohort-lightsail-distribution"
  bundle_id = "placeholder"
  default_cache_behavior {
    behavior = "cache"
  }
  origin {
    name        = "placeholder"
    region_name = "us-east-1"
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_lightsail_distribution.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: availability_zone is a required string the schema does not constrain, but the provider validates it names an AZ within the configured provider region (validate/plan: "availability_zone must be within the same region as provider region: us-east-1"); the generic placeholder string does not
resource "aws_lightsail_instance" "app" {
  name              = "tofu-compute-platforms-cohort-lightsail-instance"
  availability_zone = "us-east-1a"
  blueprint_id      = "placeholder"
  bundle_id         = "placeholder"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_lightsail_instance.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: health_check_path, instance_port
resource "aws_lightsail_lb" "app" {
  name              = "tofu-compute-platforms-cohort-lightsail-lb"
  instance_port     = 80
  health_check_path = "/"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_lightsail_lb.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: none
resource "aws_lightsail_lb_certificate" "app" {
  lb_name = "tofu-compute-platforms-cohort-lightsail-lb-certificate"
  name    = aws_elastic_beanstalk_application.app.name
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: none
resource "aws_lightsail_static_ip" "app" {
  name = "tofu-compute-platforms-cohort-lightsail-static-ip"
}
