# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: certificate_authority_configuration.key_algorithm and .signing_algorithm are plain strings in the schema but the provider validates both against fixed enums (validate: "expected key_algorithm/signing_algorithm to be one of [...]")
resource "aws_acmpca_certificate_authority" "app" {
  certificate_authority_configuration {
    key_algorithm     = "RSA_2048"
    signing_algorithm = "SHA256WITHRSA"
    subject {
    }
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_acmpca_certificate_authority.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: none
resource "aws_acmpca_certificate_authority_certificate" "app" {
  certificate_authority_arn = aws_acmpca_certificate_authority.app.arn
  certificate               = "placeholder"
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: resource_arn is not wired to any resource by the generic pass (aws_acmpca_certificate_authority is server-assigned, so parentRef's identity-argument match never fires - see this file's batch header comment); policy is a plain string in the schema but the provider validates it is well-formed JSON (validate: "contains an invalid JSON")
resource "aws_acmpca_policy" "app" {
  resource_arn = aws_acmpca_certificate_authority.app.arn
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { AWS = "arn:aws:iam::000000000000:root" }
      Action    = "acm-pca:IssueCertificate"
    }]
  })
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: enable, datasources.s3_logs.enable, datasources.kubernetes.audit_logs.enable, datasources.malware_protection.scan_ec2_instance_with_findings.ebs_volumes.enable
resource "aws_guardduty_detector" "app" {
  enable = true
  datasources {
    s3_logs {
      enable = true
    }
    kubernetes {
      audit_logs {
        enable = false
      }
    }
    malware_protection {
      scan_ec2_instance_with_findings {
        ebs_volumes {
          enable = true
        }
      }
    }
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_guardduty_detector.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: detector_id collides with aws_guardduty_organization_configuration's own identity argument name (see this file's batch header comment), so the generic pass wires it to that unrelated resource's own detector_id echo instead of the real aws_guardduty_detector.app.id; action is a plain string in the schema but the provider validates it against a fixed enum (validate: "expected action to be one of [NOOP ARCHIVE]")
resource "aws_guardduty_filter" "app" {
  action      = "NOOP"
  detector_id = aws_guardduty_detector.app.id
  name        = aws_iam_role.security.name
  rank        = 0
  finding_criteria {
    criterion {
      field = "placeholder"
    }
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_guardduty_filter.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: detector_id collides with aws_guardduty_organization_configuration's own identity argument name (see this file's batch header comment), so the generic pass wires it to that unrelated resource's own detector_id echo instead of the real aws_guardduty_detector.app.id; format is a plain string in the schema but the provider validates it against a fixed enum (validate: "expected format to be one of [TXT STIX OTX_CSV ALIEN_VAULT PROOF_POINT FIRE_EYE]")
resource "aws_guardduty_ipset" "app" {
  activate    = false
  detector_id = aws_guardduty_detector.app.id
  format      = "TXT"
  location    = "placeholder"
  name        = aws_iam_role.security.name
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_guardduty_ipset.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: protected_resource is a required block the schema does not mark Required at the wire level in a way the generic pass fills (validate: "Block protected_resource must have a configuration value"), and its own nested s3_bucket.bucket_name is required with no schema-visible default
resource "aws_guardduty_malware_protection_plan" "app" {
  role = aws_iam_role.security.arn
  protected_resource {
    s3_bucket {
      bucket_name = "tofu-security-cohort-malware-bucket"
    }
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_guardduty_malware_protection_plan.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: detector_id collides with aws_guardduty_organization_configuration's own identity argument name (see this file's batch header comment), so the generic pass wires it to that unrelated resource's own detector_id echo instead of the real aws_guardduty_detector.app.id; account_id is a plain string in the schema but the provider validates it is exactly 12 digits (validate: "doesn't look like AWS Account ID")
resource "aws_guardduty_member" "app" {
  account_id  = "000000000000"
  detector_id = aws_guardduty_detector.app.id
  email       = "placeholder"
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: admin_account_id is a plain string in the schema but the provider validates it is exactly 12 digits (validate: "doesn't look like AWS Account ID")
resource "aws_guardduty_organization_admin_account" "app" {
  admin_account_id = "000000000000"
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: auto_enable_organization_members is a plain string in the schema but the provider validates it against a fixed enum (validate: "expected auto_enable_organization_members to be one of [NEW ALL NONE]"); detector_id collides with this same type's own identity argument name (see this file's batch header comment), so the generic pass gives it a placeholder string instead of the real aws_guardduty_detector.app.id it should carry
resource "aws_guardduty_organization_configuration" "app" {
  detector_id                      = aws_guardduty_detector.app.id
  auto_enable_organization_members = "NEW"
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: detector_id collides with aws_guardduty_organization_configuration's own identity argument name (see this file's batch header comment), so the generic pass wires it to that unrelated resource's own detector_id echo instead of the real aws_guardduty_detector.app.id; destination_arn and kms_key_arn are plain strings in the schema but the provider validates both are well-formed ARNs (validate: "is an invalid ARN")
resource "aws_guardduty_publishing_destination" "app" {
  destination_arn = "arn:aws:s3:::tofu-security-cohort-guardduty-findings-bucket"
  detector_id     = aws_guardduty_detector.app.id
  kms_key_arn     = "arn:aws:kms:us-east-1:000000000000:key/1234abcd-12ab-34cd-56ef-1234567890ab"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_guardduty_publishing_destination.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: detector_id collides with aws_guardduty_organization_configuration's own identity argument name (see this file's batch header comment), so the generic pass wires it to that unrelated resource's own detector_id echo instead of the real aws_guardduty_detector.app.id; format is a plain string in the schema but the provider validates it against a fixed enum (validate: "expected format to be one of [TXT STIX OTX_CSV ALIEN_VAULT PROOF_POINT FIRE_EYE]")
resource "aws_guardduty_threatintelset" "app" {
  activate    = false
  detector_id = aws_guardduty_detector.app.id
  format      = "TXT"
  location    = "placeholder"
  name        = aws_iam_role.security.name
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_guardduty_threatintelset.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: none
resource "aws_inspector2_delegated_admin_account" "app" {
  account_id = "tofu-security-cohort-inspector2-delegated-admin-account"
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: filter_criteria is a required block the schema does not mark Required at the wire level in a way the generic pass fills (validate: "Block filter_criteria must have a configuration value"); action is a plain string in the schema but the provider validates it against a fixed enum (validate: "Invalid String Enum Value", valid values [NONE SUPPRESS])
resource "aws_inspector2_filter" "app" {
  action = "NONE"
  name   = aws_iam_role.security.name
  filter_criteria {
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_inspector2_filter.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: account_id is a plain string in the schema but the provider validates it is exactly 12 digits (validate: "doesn't look like AWS Account ID")
resource "aws_inspector2_member_association" "app" {
  account_id = "000000000000"
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: description
resource "aws_kms_external_key" "app" {
  description = "KMS EXTERNAL for AMI encryption"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_kms_external_key.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: primary_key_arn is a plain string in the schema but the provider validates it is a well-formed ARN (validate: "is an invalid ARN"); no aws_kms_key/aws_kms_external_key coverage row exists in this cohort to reference (KMS's own marker types are covered by the pre-registry v0 table and the KMS-remainder rows above), so this is a realistic literal rather than a cross-reference
resource "aws_kms_replica_key" "app" {
  primary_key_arn = "arn:aws:kms:us-west-2:000000000000:key/1234abcd-12ab-34cd-56ef-1234567890ab"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_kms_replica_key.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: job_type is a plain string in the schema but the provider validates it against a fixed enum (validate: "expected job_type to be one of [ONE_TIME SCHEDULED]"); s3_job_definition.bucket_definitions.account_id/.buckets are required with no schema-visible default once the parent block is present
resource "aws_macie2_classification_job" "app" {
  job_type = "ONE_TIME"
  s3_job_definition {
    bucket_definitions {
      account_id = "000000000000"
      buckets    = ["tofu-security-cohort-macie-bucket"]
    }
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_macie2_classification_job.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: cfn-required (live/registry-schema-facts.json): name
resource "aws_macie2_custom_data_identifier" "app" {
  name = aws_iam_role.security.name
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_macie2_custom_data_identifier.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: action; cfn-required (live/registry-schema-facts.json): name
resource "aws_macie2_findings_filter" "app" {
  action = "ARCHIVE"
  finding_criteria {
  }
  name = aws_iam_role.security.name
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_macie2_findings_filter.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: email
resource "aws_macie2_member" "app" {
  account_id = "tofu-security-cohort-macie2-member"
  email      = "EMAIL"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_macie2_member.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: none
resource "aws_macie2_organization_admin_account" "app" {
  admin_account_id = "tofu-security-cohort-macie2-organization-admin-account"
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: none
resource "aws_secretsmanager_secret" "app" {
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_secretsmanager_secret.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: secret_arn is a plain string in the schema but the provider validates it is a well-formed ARN (validate: "is an invalid ARN"), which the generic pass's placeholder name is not - a real cross-reference to aws_secretsmanager_secret.app's own arn is both the fix and the point of this coverage row (the parent-derived composite this batch ratified); policy is a plain string in the schema but the provider validates it is well-formed JSON (validate: "contains an invalid JSON")
resource "aws_secretsmanager_secret_policy" "app" {
  secret_arn = aws_secretsmanager_secret.app.arn
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { AWS = "arn:aws:iam::000000000000:root" }
      Action    = "secretsmanager:GetSecretValue"
      Resource  = "*"
    }]
  })
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: rotation_rules.automatically_after_days
resource "aws_secretsmanager_secret_rotation" "app" {
  secret_id = aws_secretsmanager_secret.app.id
  rotation_rules {
    automatically_after_days = 30
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: none
resource "aws_securityhub_account_v2" "app" {
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_securityhub_account_v2.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: region_linking_mode
resource "aws_securityhub_aggregator_v2" "app" {
  region_linking_mode = "ALL_REGIONS"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_securityhub_aggregator_v2.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: actions and criteria are both required blocks the schema does not mark Required at the wire level in a way the generic pass fills (validate: "Block actions/criteria must have a configuration value"); every field inside both is itself optional, so empty blocks are enough
resource "aws_securityhub_automation_rule" "app" {
  description = "placeholder"
  rule_name   = "tofu-security-cohort-securityhub-automation-rule"
  rule_order  = 0
  actions {
  }
  criteria {
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_securityhub_automation_rule.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: action and criteria are both required blocks the schema does not mark Required at the wire level in a way the generic pass fills (validate: "Block criteria/action must have a configuration value"); action.type and criteria.ocsf_finding_criteria_json are each required once their parent block is present; rule_order is a plain number in the schema but the provider validates it against a 1-1000 range (validate: "value must be between 1.000000 and 1000.000000", the generic pass's zero placeholder is out of range)
resource "aws_securityhub_automation_rule_v2" "app" {
  description = "placeholder"
  rule_name   = "tofu-security-cohort-securityhub-automation-rule-v2"
  rule_order  = 1
  action {
    type = "FINDING_FIELDS_UPDATE"
  }
  criteria {
    ocsf_finding_criteria_json = "{}"
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_securityhub_automation_rule_v2.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: target_id is a plain string in the schema but the provider validates it is a root, OU or account id (validate: "Target ID must be a valid root, organizational unit or account id"); policy_id is a plain string in the schema but the provider validates it is either a UUID or the literal "SELF_MANAGED_SECURITY_HUB" (validate: "expected \"policy_id\" to be a valid UUID" / "expected policy_id to be one of [SELF_MANAGED_SECURITY_HUB]"), and this batch does not ratify aws_securityhub_configuration_policy (see the cohort README), so there is no real policy id to reference
resource "aws_securityhub_configuration_policy_association" "app" {
  target_id = "000000000000"
  policy_id = "SELF_MANAGED_SECURITY_HUB"
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: connector_provider is a required block the schema does not mark Required at the wire level in a way the generic pass fills (validate: "Block connector_provider must have a configuration value"); its own service_now.instance_name/.secret_arn are required once the block is present - secret_arn references aws_secretsmanager_secret.app's own arn, a real in-cohort value rather than a second placeholder ARN
resource "aws_securityhub_connector_v2" "app" {
  name = aws_iam_role.security.name
  connector_provider {
    service_now {
      instance_name = "tofu-security-cohort"
      secret_arn    = aws_secretsmanager_secret.app.arn
    }
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_securityhub_connector_v2.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: account_id is a plain string in the schema but the provider validates it is exactly 12 digits (validate: "doesn't look like AWS Account ID")
resource "aws_securityhub_member" "app" {
  account_id = "000000000000"
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: admin_account_id is a plain string in the schema but the provider validates it is exactly 12 digits (validate: "doesn't look like AWS Account ID")
resource "aws_securityhub_organization_admin_account" "app" {
  admin_account_id = "000000000000"
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: standards_control_arn is a plain string in the schema but the provider validates it is a well-formed ARN (validate: "is an invalid ARN"); control_status is a plain string in the schema but the provider validates it against a fixed enum (validate: "expected control_status to be one of [ENABLED DISABLED]")
resource "aws_securityhub_standards_control" "app" {
  standards_control_arn = "arn:aws:securityhub:us-east-1:000000000000:control/cis-aws-foundations-benchmark/v/1.2.0/1.10"
  control_status        = "ENABLED"
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: association_status is a plain string in the schema but the provider validates it against a fixed enum (validate: "Invalid String Enum Value", valid values [ENABLED DISABLED]); standards_arn is a plain string in the schema but the provider validates it is a well-formed ARN (validate: "Invalid ARN Value")
resource "aws_securityhub_standards_control_association" "app" {
  association_status  = "ENABLED"
  security_control_id = "placeholder"
  standards_arn       = "arn:aws:securityhub:us-east-1:000000000000:control/cis-aws-foundations-benchmark/v/1.2.0"
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: none
resource "aws_ssm_association" "app" {
  name = aws_iam_role.security.name
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_ssm_association.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: doc example: cutoff, duration, schedule
resource "aws_ssm_maintenance_window" "app" {
  cutoff   = 1
  duration = 3
  name     = aws_iam_role.security.name
  schedule = "cron(0 16 ? * TUE *)"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_ssm_maintenance_window.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: none
resource "aws_ssm_patch_baseline" "app" {
  name = aws_iam_role.security.name
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_ssm_patch_baseline.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: baseline_id is not wired to any resource by the generic pass (aws_ssm_patch_baseline is a marker type with no Components, so parentRef's identity-argument match never fires) - a real cross-reference to aws_ssm_patch_baseline.app's own id is both the fix and the point of this coverage row (the parent-derived composite this batch ratified)
resource "aws_ssm_patch_group" "app" {
  baseline_id = aws_ssm_patch_baseline.app.id
  patch_group = "placeholder"
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: s3_destination.region is a plain string in the schema but the provider validates it looks like an AWS region (validate: "doesn't look like AWS Region")
resource "aws_ssm_resource_data_sync" "app" {
  name = "tofu-security-cohort-ssm-resource-data-sync"
  s3_destination {
    bucket_name = "placeholder"
    region      = "us-east-1"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: setting_id is a plain string in the schema but the provider validates it against two rules at once: it must begin with "/ssm/" and (per a separate check) parse as an ARN once the AWS provider prefixes it - a bare "/ssm/..." path is what the resource's own documented example uses
resource "aws_ssm_service_setting" "app" {
  setting_id    = "/ssm/parameter-store/high-throughput-enabled"
  setting_value = "placeholder"
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: ip_address_version and scope are plain strings in the schema but the provider validates both against fixed enums (validate: "expected ip_address_version to be one of [IPV4 IPV6]" / "expected scope to be one of [CLOUDFRONT REGIONAL]")
resource "aws_wafv2_ip_set" "app" {
  ip_address_version = "IPV4"
  scope              = "REGIONAL"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_wafv2_ip_set.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: scope is a plain string in the schema but the provider validates it against a fixed enum (validate: "expected scope to be one of [CLOUDFRONT REGIONAL]")
resource "aws_wafv2_regex_pattern_set" "app" {
  scope = "REGIONAL"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_wafv2_regex_pattern_set.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: scope is a plain string in the schema but the provider validates it against a fixed enum (validate: "expected scope to be one of [CLOUDFRONT REGIONAL]"); capacity is optional/computed in the schema, rendered as the generic pass's numeric zero placeholder, but the provider validates it is at least 1 (validate: "expected capacity to be at least (1), got 0")
resource "aws_wafv2_rule_group" "app" {
  capacity = 100
  scope    = "REGIONAL"
  visibility_config {
    cloudwatch_metrics_enabled = false
    metric_name                = "placeholder"
    sampled_requests_enabled   = false
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_wafv2_rule_group.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: scope is a plain string in the schema but the provider validates it against a fixed enum (validate: "expected scope to be one of [CLOUDFRONT REGIONAL]")
resource "aws_wafv2_web_acl" "app" {
  scope = "REGIONAL"
  default_action {
  }
  visibility_config {
    cloudwatch_metrics_enabled = false
    metric_name                = "placeholder"
    sampled_requests_enabled   = false
  }
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_wafv2_web_acl.app"
  }
}

# Coverage: generated by estate-gen from hashicorp/aws 6.58.0 and the identity table (internal/live/identity/table.go).
# overrides: web_acl_arn is a plain string in the schema but the provider validates it is a well-formed ARN (validate: "is an invalid ARN"), which the generic pass's placeholder name is not - a real cross-reference to aws_wafv2_web_acl.app's own arn is both the fix and the point of this coverage row (the parent-derived composite this batch ratified)
resource "aws_wafv2_web_acl_rule" "app" {
  name        = aws_iam_role.security.name
  priority    = 0
  web_acl_arn = aws_wafv2_web_acl.app.arn
}
