# Supporting, not coverage - added only so aws_iam_role.security's referring resources have a value to point at: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: schema requires "assume_role_policy" as a plain string, but the provider validates it is well-formed JSON (validate: "\"assume_role_policy\" contains an invalid JSON"); the generic string placeholder is not JSON
resource "aws_iam_role" "security" {
  name = "tofu-security-cohort-iam-role"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "security.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_iam_role.security"
  }
}

# Supporting, not coverage - added only so aws_instance.security's referring resources have a value to point at: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: ami and instance_type are both Optional in the schema (a launch_template can supply either instead), but the provider requires ami and instance_type when no launch_template is set (validate: "Missing required argument" x3), and the generic required-only pass sets neither since the schema alone does not say so
resource "aws_instance" "security" {
  ami           = "ami-0123456789abcdef0"
  instance_type = "t3.micro"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_instance.security"
  }
}

# Supporting, not coverage - added only so aws_lambda_function.security's referring resources have a value to point at: generated by estate-gen from hashicorp/aws 6.59.0 and the identity table (internal/live/identity/table.go).
# overrides: schema requires only function_name and role; the provider also requires exactly one of filename/image_uri/s3_bucket (validate: "one of ... must be specified"), and image_uri requires package_type = "Image"
resource "aws_lambda_function" "security" {
  function_name = "tofu-security-cohort-lambda-function"
  role          = aws_iam_role.security.arn
  package_type  = "Image"
  image_uri     = "000000000000.dkr.ecr.us-east-1.amazonaws.com/tofu-security-cohort-app:latest"
  tags = {
    tofu-estate  = local.estate_tag
    tofu-address = "aws_lambda_function.security"
  }
}
