// Copyright (c) The OpenTofu Authors
// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2023 HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// Rendered outputs, relative to the repository root. Everything here is
// written in full by `gauntlet render` and held to the tree by
// TestRenderedDocsAreCurrent. Hand edits are overwritten on the next render.
//
// Nothing under site/content is written here any more (#1055): the site's
// progress pages are hand-written markdown plus a content adapter, both
// reading SiteDataPath and SiteBoardPath. SiteProgressPage, SiteAddPage
// and SiteContribPage name those hand-written pages so the spec and the
// briefs can point at them; this tool never writes them.
const (
	SpecPath         = "live/GAUNTLET.md"
	SiteProgressDir  = "site/content/docs/progress"
	SiteProgressPage = "site/content/docs/progress/_index.md"
	SiteAddPage      = "site/content/docs/progress/add-an-estate.md"
	SiteContribPage  = "site/content/docs/progress/contribute.md"
	WorkerBriefPath  = ".claude/agents/gauntlet-worker.md"
	// OrchestratorBriefPath is the brief for whoever keeps the loop running.
	OrchestratorBriefPath = ".claude/agents/gauntlet-orchestrator.md"
)

// Render writes every generated file into root. It returns the list of
// files written so a caller (or a test rendering into a temp dir) can
// compare. tt is live/estate-types.json's totals, read by the caller
// (never re-derived from root, which a caller comparing against a temp
// write directory - StaleFiles - deliberately does not share with the
// checkout tt was read from) so the spec's prose can quote it instead of
// carrying its own stale copy (issue #658).
//
// scale is live/gauntlet-scale.json's committed bytes, or nil when the file
// does not exist yet; Render copies it to SiteScalePath so the site's
// scale-num shortcode can quote a measured plan-call split without anyone
// typing it (#1055). Read by the caller from the real checkout, never from
// root, for the same reason tt is.
//
// st is per-row script staleness (#1264), read from the real checkout by
// the caller for that same reason - it is a git comparison, and root here
// may be a scratch directory with no history. A nil map renders no
// staleness at all rather than a board asserting every row is current.
func Render(root string, m *Manifest, a *Artifact, tt TypeIndexTotals, scale []byte, st map[string]ScriptStaleness) ([]string, error) {
	var written []string
	write := func(rel string, body string) error {
		p := filepath.Join(root, rel)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
			return err
		}
		written = append(written, rel)
		return nil
	}

	// The manifest, canonically.
	mb, err := m.Canonical()
	if err != nil {
		return nil, err
	}
	if err := write(ManifestPath, string(mb)); err != nil {
		return nil, err
	}
	// The artifact, and its copy for Hugo.
	ab, err := a.Canonical()
	if err != nil {
		return nil, err
	}
	if err := write(ArtifactPath, string(ab)); err != nil {
		return nil, err
	}
	if err := write(SiteDataPath, string(ab)); err != nil {
		return nil, err
	}
	if err := write(SpecPath, renderSpec(m, a, tt)); err != nil {
		return nil, err
	}
	// The board: every display value the site's progress pages need, as
	// data. The pages themselves live in site/ and are never written here.
	bb, err := buildBoard(m, a, st).Canonical()
	if err != nil {
		return nil, err
	}
	if err := write(SiteBoardPath, string(bb)); err != nil {
		return nil, err
	}
	if scale != nil {
		if err := write(SiteScalePath, string(scale)); err != nil {
			return nil, err
		}
	}
	return written, nil
}

// SiteScalePath is the site's copy of ScaleRecordsPath.
const SiteScalePath = "site/data/gauntlet_scale.json"

// loadScaleRecordsBytes reads ScaleRecordsPath as committed, or nil when it
// does not exist. Any other error is returned.
func loadScaleRecordsBytes(root string) ([]byte, error) {
	b, err := os.ReadFile(filepath.Join(root, ScaleRecordsPath))
	if os.IsNotExist(err) {
		return nil, nil
	}
	return b, err
}

const generatedBanner = "<!-- Generated by `go run ./tools/gauntlet render` from tools/gauntlet/stages.go, live/gauntlet/estates.json and live/gauntlet.json. Do not edit; TestRenderedDocsAreCurrent holds this file to the tree. -->"

// renderSpec is live/GAUNTLET.md: the contract for contributors.
func renderSpec(m *Manifest, a *Artifact, tt TypeIndexTotals) string {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format, args...); b.WriteString("\n") }

	w("%s", generatedBanner)
	w("# The gauntlet")
	w("")
	w("The gauntlet is how choudoufu measures itself against stock OpenTofu. Real,")
	w("popular OpenTofu and Terraform configurations are run through a fixed set of")
	w("stages, each a comparison with what stock does for the same configuration,")
	w("against the pinned emulator. The result is one artifact, `%s`, and the", ArtifactPath)
	w("two bars on the site read it directly. Nothing on the site about progress is")
	w("typed by hand.")
	w("")
	w("The promise it measures: if OpenTofu runs an estate, choudoufu runs it too.")
	w("Migration from a stock state file is lossless and a greenfield apply is")
	w("equivalent. Everything below is that sentence made checkable.")
	w("")
	w("This page defines the gauntlet; it does not walk you through running it.")
	w("The two procedures are their own pages on the site, hand-written and")
	w("reading the lanes and the example entry from `%s`:", SiteBoardPath)
	w("adding an estate is `%s`, and", SiteAddPage)
	w("contributing compute is `%s`.", SiteContribPage)
	w("")
	w("## The two numbers")
	w("")
	w("An estate is **clear** when every headline stage passes: an active stage")
	w("whose own entry below is not marked \"not part of the headline bars\". The")
	w("first bar is clear estates over the core set; the second is clear estates")
	w("over every estate in the manifest. Planned stages are listed so the target")
	w("is visible, but do not count until their status is flipped to active in")
	w("`tools/gauntlet/stages.go`. For a headline stage that flip is the deliberate")
	w("change that lowers the bars until estates catch up; a non-headline stage")
	w("(`strict` today) can be active, and pass or fail per estate, without ever")
	w("moving either bar.")
	w("")
	w("A headline stage marked \"tier-1 gated\" below (#999) activates on tier-1")
	w("fixture evidence (`live/behaviors.json`, #522's ruling) rather than on 26")
	w("hand-written per-estate sections: an estate that has never been asked to")
	w("run it reads `not_run` and stays clear, while a genuine `fail` on it still")
	w("breaks clear, exactly as any other headline stage.")
	w("")
	w("Core is a pinned population that can reach 100%%. The rule for membership is")
	w("in \"The core set\" below; a core estate carries its reason in the manifest.")
	w("")
	w("Both bars are the floci emulator's. The `%s` lane (#1067) runs against a", LaneKubernetes)
	w("kind cluster instead - a real API server, not an emulator - and has a bar")
	w("of its own, `lanes.%s` in `%s`, counted toward neither bar", LaneKubernetes, ArtifactPath)
	w("above. A stage whose oracle is AWS-shaped says under its entry below how")
	w("it reads on the kind substrate, or that it does not apply there, in which")
	w("case the estate's cell reads `n/a` and is neutral for clear; nothing is")
	w("skipped silently.")
	w("")
	w("## Stages")
	w("")
	w("Each stage states what a pass proves, what stock's answer to the same question")
	w("is and how it is compared (the oracle), and how a script shows its check is")
	w("load-bearing (`BREAK=1` must make the stage fail).")
	w("")
	for _, s := range a.Stages {
		label := s.Status
		if !s.Headline {
			label += ", not part of the headline bars"
		} else if s.Tier1Gated {
			label += ", tier-1 gated: not_run does not gate clear"
		}
		w("### %d. %s (`%s`, %s)", s.Order, s.Title, s.ID, label)
		w("")
		w("Proves: %s", s.Proves)
		w("")
		w("Oracle: %s", s.Oracle)
		w("")
		w("Break: %s", s.Break)
		w("")
		for _, sub := range sortedKeys(s.Substrates) {
			if reason, na := s.NotApplicable(sub); na {
				w("On the %s substrate: not applicable, recorded as `n/a` and neutral for clear. %s", sub, reason)
			} else {
				w("On the %s substrate: %s", sub, s.Substrates[sub])
			}
			w("")
		}
	}
	w("## The plan-fidelity contract")
	w("")
	w("What every stage above adds up to, stated as one promise: an equal plan, or")
	w("a refusal this document names in advance. Anything else is a defect.")
	w("")
	w("\"Equal\" is checked after one normalisation, applied the same way on every")
	w("stage that compares a plan or the resulting cloud: the marker tags choudoufu")
	w("writes for identity (`tofu-estate` and `tofu-address`, see")
	w("[Identity](https://github.com/INTENTIUS/choudoufu/blob/main/site/content/docs/model/identity.md))")
	w("are stripped from both sides first. Stock has no argument to write them")
	w("into, so their presence is not a difference to explain, and nothing else is")
	w("normalised away.")
	w("")
	w("Past that, HANDOFF.md's five-row table is what turns a remaining difference")
	w("into an action: choudoufu refusing where stock proceeds is a defect, the")
	w("plans or the cloud differing is a defect, stock failing too still leaves the")
	w("estate to clear, a wrong answer from the emulator is fixed in the emulator,")
	w("and an instance that would need a wrong marker to converge drops to the")
	w("record rung and proceeds rather than forcing one. None of those five rows")
	w("closes a finding without fixing something.")
	w("")
	w("A \"named refusal\" is the one way \"choudoufu refuses where stock proceeds\"")
	w("is not automatically that table's first row: a stage whose own Proves and")
	w("Oracle text above commits, before any estate runs against it, to refusing on")
	w("purpose. Today that is `plan_approval` (stage 12, planned): its Oracle")
	w("states plainly that the planfile applies when the world has not moved, and")
	w("that choudoufu is stricter than stock by design when it has, so that refusal")
	w("is asserted rather than diffed against stock. A refusal no stage names this")
	w("way is not exempt; it is the table's first row, and it is a defect.")
	w("")
	w("The Break line under every stage above is the enforcement mechanism:")
	w("`BREAK=1` forces the exact defect the stage exists to catch, and the stage")
	w("must fail. A check that cannot be made to fail this way is not proving the")
	w("contract, whatever verdict it reports.")
	w("")
	w("## The protocol a script speaks")
	w("")
	w("A crossing script lives at `live/e2e/<name>/run.sh`, sources")
	w("`live/e2e/lib/gauntlet.sh`, and reports each stage on stdout:")
	w("")
	w("```")
	w("GAUNTLET protocol=1")
	w("GAUNTLET stage=cold_deploy verdict=pass")
	w("GAUNTLET stage=migrate verdict=pass detail=68 added, 41 stamped, 27 skipped")
	w("GAUNTLET stage=test_plan verdict=fail detail=Non-static identity argument on aws_x.y")
	w("```")
	w("")
	w("Verdicts are `pass`, `fail` or `not_run`; `not_run` means the script does not")
	w("exercise that stage yet, which is itself a gap the artifact shows. A script")
	w("that never prints the protocol line is legacy: the runner records its exit")
	w("code and leaves the imported verdicts as they are. The runner is")
	w("`go run ./tools/gauntlet run [<name>...]`, logs land in `%s/`.", LogDir)
	w("")
	w("A run that will not attempt what it was asked for says so with one more")
	w("line, emitted by `gauntlet_refused` (#1151):")
	w("")
	w("```")
	w("GAUNTLET refused=1 scale=136 needed=10070 limit=10000 unit=ssm-parameters detail=10,069 resources need 10,070 SSM parameters against SSM's hard 10,000 cap (#1146)")
	w("```")
	w("")
	w("That is a run-level outcome, not a stage verdict: a stage cannot refuse.")
	w("`needed`/`limit` go together or not at all, and a `detail` is required - the")
	w("reason and the arithmetic are the whole value of recording a refusal rather")
	w("than skipping the rung in silence. `scale=` is required of an estate that")
	w("declares a scale ladder and absent from one that does not; where each lands")
	w("is the `%s` section below.", ScaleRecordsPath)
	w("")
	w("## The manifest entry")
	w("")
	w("Every estate is one entry in `%s`:", ManifestPath)
	w("")
	w("```json")
	w("%s", exampleEntryJSON(m))
	w("```")
	w("")
	w("`set` is `core` or `growing`; `reason` is required for core; `script` defaults")
	w("to `live/e2e/<name>/run.sh`; `url` and `pin` are required except for the")
	w("`reference` lane and a `%s`-lane estate kept in this repository.", LaneKubernetes)
	w("")
	w("Lanes: %s.", strings.Join(KnownLanes, ", "))
	w("")
	w("### The cold-deploy pre-apply")
	w("")
	w("Some configurations cannot be planned in one pass. A root declaring a")
	w("CustomResourceDefinition and an object of that CRD is the case that forced")
	w("this: `kubernetes_manifest` builds the object's schema at plan time, so the")
	w("plan fails before anything is created, `depends_on` does not help, and")
	w("re-running fails identically forever. Stock terraform has exactly the same")
	w("problem with exactly the same configuration, and a real operator does the")
	w("same thing: `apply -target=<the CRD>`, then a plain apply.")
	w("")
	w("Such an estate declares the addresses in its manifest entry:")
	w("")
	w("```json")
	w("\"pre_apply\": [\"kubernetes_manifest.crd_certificates\"],")
	w("\"pre_apply_reason\": \"why one apply is not enough\"")
	w("```")
	w("")
	w("and its crossing script calls `gauntlet_pre_apply <estate>")
	w("estate:<fn> oracle:<fn>`, which reads that list once and drives every side")
	w("from it. Four rules hold it honest (#1173):")
	w("")
	w("- **the stock oracle performs the identical pre-apply**, from the same")
	w("  declared list, in the same call - a crossing where only choudoufu got the")
	w("  targeted first apply is not comparing like with like, so the helper")
	w("  refuses a single-sided call;")
	w("- **the run shows it happened**, in two halves. The verdict line says how")
	w("  MANY addresses were pre-applied and which manifest field declares them")
	w("  (`gauntlet_pre_apply_note`), so a reader sees two applies without opening")
	w("  the log; `gauntlet_pre_apply` separately emits")
	w("  `GAUNTLET pre_apply=<addr>,<addr> sides=<label>,<label>`, and the runner")
	w("  checks the declared list against THAT, address by address, failing")
	w("  `cold_deploy` if one was not performed or if one was performed that")
	w("  nobody declared. The first spelling of this rule put every address in the")
	w("  verdict line; on cert-manager's 47 that was a 3.3KB sentence, which")
	w("  satisfied the words and defeated the reason for them, so it was corrected")
	w("  on 2026-09-16 - only the printed sentence got shorter;")
	w("- **it is declared, not scripted**, so the manifest and this page carry it;")
	w("- **an estate that declares none behaves exactly as before** - the check")
	w("  never fires, and no estate in the manifest today declares one except")
	w("  where the table below says so.")
	w("")
	w("Readiness is the caller's job and has to be bounded:")
	w("`gauntlet_wait_until <seconds> <what> -- <command>` polls and fails loudly")
	w("on timeout rather than falling through into the admission error a webhook")
	w("that exists but is not yet serving produces.")
	w("")
	if preApplyEstates(m) != "" {
		w("Declares a pre-apply today: %s.", preApplyEstates(m))
		w("")
	} else {
		w("No estate declares a pre-apply today.")
		w("")
	}
	w("## The core set")
	w("")
	w("Rule: the most-downloaded terraform-aws-modules examples, the OpenTofu-native")
	w("projects already crossed, and the reference shapes kept in this repository,")
	w("each pinned by tag or commit. Adding one needs a reason in the manifest, which")
	w("is the whole approval step. Anything real goes in the growing set without one.")
	w("")
	w("| Estate | Lane | Pin | Reason |")
	w("|---|---|---|---|")
	for _, e := range m.Estates {
		if e.Set != SetCore {
			continue
		}
		w("| `%s` | %s | %s | %s |", e.Name, e.Lane, mdCell(e.Pin), mdCell(e.Reason))
	}
	w("")
	w("## Estate admission")
	w("")
	w("**Estates buy behaviors, cohorts buy types.** Every estate pays for itself")
	w("once, in fetch and configuration, and then again on every run after: every")
	w("active stage above runs it, every re-measure re-runs it, and none of that")
	w("time buys anything but what its topology actually exercises. Coverage")
	w("pressure that reaches for \"add another estate\" is usually paying that price")
	w("to re-prove a type the board already has.")
	w("")
	w("Check `live/estate-types.json` (`go run ./tools/estate-types`, issue #435)")
	w("before proposing one: it lists, from real committed or fetched")
	w("configuration and no gauntlet run, every resource type each estate in the")
	w("manifest already exercises. As of that artifact's last run, it reports")
	w("%d estates exercising %d distinct types between them, of which %d no", tt.Estates, tt.DistinctTypes, tt.TypesInNoCohort)
	w("cohort fixture covers yet (`totals.estates`, `totals.distinct_types`,")
	w("`totals.types_in_no_cohort`; these figures are rendered from the")
	w("artifact by `gauntlet render`, so they can only be as current as the")
	w("artifact - re-run `tools/estate-types` and `gauntlet render` together")
	w("before trusting either). A new estate has")
	w("to name the behavior or topology missing from that list - a module shape,")
	w("an ordering, a day-2 operation - not a type; a proposal that only points at")
	w("a type is a proposal for a cohort.")
	w("")
	w("Type-only coverage goes to a cohort instead: `tools/estate-gen` builds a")
	w("minimal fixture straight off the admission table, one resource block per")
	w("type, required arguments only, and `live/cohort-acceptance.json` measures")
	w("its round-trip identity against the emulator - the whole product claim for")
	w("that type, at the cost of an apply and a replan rather than a full estate's")
	w("fourteen stages on every future run. A type already in")
	w("`types_in_no_cohort` is still a cohort's job to pick up, seeding or")
	w("extending one with `-types`, not an estate's.")
	w("")
	w("This does not relax the core-set rule above: an estate that clears this")
	w("bar with a real behavior still needs its own reason to join core.")
	w("")
	w("## The artifact")
	w("")
	w("`%s` carries `schema`, `emulator`, the `stages`", ArtifactPath)
	w("table above, `sets` (`core` and `all`, each with `estates`, `clear`, and a")
	w("per-stage tally), and one row per estate: `name`, `source`, `url`, `pin`,")
	w("`lane`, `set`, `reason`, `script`, `stages` (id to verdict), `clear`,")
	w("`protocol` (`gauntlet` or `legacy`), `last_run` (`commit`, `date`,")
	w("`emulator` - the pin THAT run actually used, distinct from the")
	w("top-level `emulator`, which is the pin the NEXT run will use -")
	w("`exit_code`, optional per-stage `detail`, `duration_s` (the whole")
	w("script's wall-clock seconds, recorded for every run regardless of")
	w("protocol) and optional per-stage `stage_seconds` (wall-clock seconds")
	w("each stage took, recorded only for a gauntlet-protocol script whose")
	w("copy of `live/e2e/lib/gauntlet.sh` emits `duration_s`)), and")
	w("`stage_runs` (id to the `commit` and `date` of the run that actually")
	w("measured that verdict, #1069). A run that aborts early still leaves")
	w("the stages it never reached reading the last run to reach them - that")
	w("carry-forward is deliberate - but `stage_runs` now says which cells")
	w("those are: a verdict whose `stage_runs` entry is not this row's own")
	w("`last_run` renders as `stale` rather than as the verdict it carries,")
	w("and does not count toward `clear`. A stage with no entry is unknown")
	w("provenance, not stale: rows recorded before the field existed keep")
	w("the cells and the clear flag they had.")
	w("")
	w("A whole row goes stale a second way (#1264): the crossing script it")
	w("was measured against changes afterwards, so every verdict in it")
	w("describes a script that is no longer in the tree. That is not")
	w("recorded in the artifact - it is computed on demand by diffing the")
	w("row's `last_run.commit` against the working tree, which needs nothing")
	w("the row does not already carry. Two directories are compared, not")
	w("one (#1292): the estate's own, and `%s`, the protocol", SharedLibDir)
	w("library every crossing script sources. The library is the half that")
	w("belongs to no estate, so watching only the first badged nothing at")
	w("all when `gauntlet_record_count` changed under all 31 rows. The")
	w("rendered sentence says which of the two moved, because they send a")
	w("reader to different places. Deliberately NOT compared, each for a")
	w("stated reason: `live/floci-image` and `live/oracle-versions.json`,")
	w("whose values the row already records and `check` already compares by")
	w("value; `live/gauntlet/estates.json`, one file holding every estate's")
	w("manifest data, where a diff would badge all 31 rows for one estate's")
	w("edit; and `internal/`, the product half (#1288), which almost every")
	w("commit touches. A badge lit on every merge is read by nobody, which")
	w("is worse than the gap it would close. Three answers: `current`,")
	w("`changed`, and `unknown` for a row whose commit this checkout cannot")
	w("place in HEAD's history (a shallow clone, or a run recorded on a")
	w("branch that never landed). A change touching only markdown under")
	w("either directory is not a change; nothing else is")
	w("exempt. `go run ./tools/gauntlet check` prints the live answer and")
	w("the board carries a snapshot of it, refreshed by every render. It")
	w("never fails a build: re-running an estate can take half an hour, so")
	w("a script change makes the drift visible rather than making the pull")
	w("request that caused it wait on a run. `go run")
	w("./tools/gauntlet snapshot <version>` copies it to")
	w("`live/history/<version>.json` at release; `go run")
	w("./tools/gauntlet notes <old-snapshot.json> <new-snapshot.json>` (`just")
	w("gauntlet-notes`) diffs two such snapshots into paste-ready release-notes")
	w("markdown - board movement per set, which estates newly cleared or")
	w("regressed, and the emulator pin change - for the release body.")
	w("")
	w("## The scale ladder (`%s`)", ScaleRecordsPath)
	w("")
	w("`%s`'s `live_cert` array keeps **one row per estate**: a new", ArtifactPath)
	w("certification replaces the last one outright. `%s` keeps", ScaleRecordsPath)
	w("**one record per (estate, target, scale)**, which is what lets the ladder")
	w("hold every size at once. The two files answer different questions and")
	w("neither is folded into the other.")
	w("")
	w("One record per (estate, target, scale) is a stated rule, in three parts")
	w("(#1151):")
	w("")
	w("1. A run at one scale never touches another scale's row. The key is the")
	w("   whole identity, not the estate.")
	w("2. Newer wins, but never silently. The new row's `supersedes` names the")
	w("   commit, date and outcome of the row it replaced, so a citation that")
	w("   followed a figure which has since moved still leads somewhere. A")
	w("   scale-50 row measured on 2026-09-15 replaced the 2026-09-11 one this")
	w("   way, and `site/content/docs/what-you-pay.md` quotes that file by path.")
	w("3. A refusal never replaces a measurement. The runner refuses the write")
	w("   and names the row it protected; nothing is written. Dropping a measured")
	w("   row is a reviewed change, not a side effect of a later run that")
	w("   declined to run.")
	w("")
	w("Each record carries an `outcome`: `pass`, `fail`, `not_run` or `refused`.")
	w("The first three are the protocol's own verdict words at run scope - `pass`")
	w("is the run's own `clear` flag, so a run that failed nothing but completed")
	w("nothing reads `not_run`, never `pass`. `refused` is the fourth, and carries")
	w("a `refusal` with the `reason` and, when there is one, the")
	w("`needed`/`limit`/`unit` arithmetic behind it. A record with no `outcome` at")
	w("all predates the field; that means nobody recorded one, and such a row is")
	w("read through its stages the way every reader did before.")
	w("")
	w("A refusal is deliberately **not** written to `live_cert`. That row holds one")
	w("certification per estate, so a refusal at scale 136 landing there would")
	w("destroy the certification at scale 50 - which is what happened on")
	w("2026-09-13 (#1100), and what #1151 closes for the refusals that came after.")
	w("")
	w("### Where a refusal that names no rung goes (`refusals`)")
	w("")
	w("Not every estate is run at a size. `reference-ec2-vpc` is one fixed")
	w("five-resource shape certified against a real account, and it has no rung")
	w("anywhere - yet it can still refuse: an account whose region resolves no")
	w("Amazon Linux AMI, a missing permission, a quota that is not about scale.")
	w("A refusal is the only record its run produces (it is kept out of")
	w("`live_cert` by the rule above), so under #1149's rule that record has to")
	w("land or the run fails - and there was no rung to land it on (#1233).")
	w("")
	w("`%s` therefore has a second array, `refusals`: one refusal", ScaleRecordsPath)
	w("per (estate, target), scale absent, for an estate that has no ladder. It is")
	w("kept out of `records` for the same reason a refusal is kept out of")
	w("`live_cert` - a row at scale 0 would read as the smallest rung, which is a")
	w("measurement nobody made. Newer supersedes older there too, with the same")
	w("`supersedes` pointer.")
	w("")
	w("Which of the two an estate gets is the estate's own declaration, not an")
	w("inference from what a run happened to print: `\"scale_ladder\": true` in")
	w("`%s`, which `terralith-scale` carries and nothing else does.", ManifestPath)
	w("A refusal with no `scale=` from a **laddered** estate still fails the run,")
	w("exactly as #1231 ruled - for that estate a missing scale is a")
	w("`gauntlet_refused` call that forgot its rung, and shelving it would hide")
	w("which size was declined.")
	w("")
	w("## One live-cert per estate at a time")
	w("")
	w("`gauntlet live-cert` takes a lock file beside the log it is about to write,")
	w("`%s/live-cert-<estate>.lock`, carrying the run id, pid and start", LogDir)
	w("time, and a second run for the same estate refuses rather than starting")
	w("(#1150).")
	w("")
	w("Two runs of one estate do not collide in the *account* - every resource is")
	w("named from a per-run prefix, and `verify_empty` and the sweep are scoped to")
	w("it. They collide in the *evidence*: both open the same log with")
	w("`os.Create`, so the second truncates the first while the first keeps writing")
	w("at its old offset, and both write `%s` at the end. Measured: two", ArtifactPath)
	w("overlapping runs produced a 295,759-byte log of which 280,961 bytes were")
	w("NUL, carrying lines from both runs, and neither invocation reported")
	w("anything. On 2026-09-15 that overlap - a pre-restart screen session 166")
	w("seconds ahead of a new one - also exhausted the account's IAM role quota and")
	w("produced a **false `cold_deploy` failure** on real AWS.")
	w("")
	w("A lock whose pid is gone is reported as looking stale, with the path to")
	w("delete; the run still refuses. Nothing breaks a lock automatically, because")
	w("pids are reused, and there is no environment variable that turns this off.")
	w("")
	w("## Selective re-queue (`next -types`)")
	w("")
	w("`go run ./tools/gauntlet next` orders whole-estate work: core before")
	w("growing, fewest remaining headline stages first, and a repin's stale-clear")
	w("estates trailing every genuine failure. `-types T1,T2,...` (#436) adds an")
	w("orthogonal filter on top of that ordering, never a replacement for it: it")
	w("reads `%s` (#435), the per-estate exercised-type index,", TypeIndexPath)
	w("and drops any ordinary (`fail` or `not_run`) unit whose estate exercises")
	w("none of the requested types. A repin still queues every stale-clear")
	w("estate regardless of `-types` - the stale-pin rule stays completely")
	w("untouched, deliberately, because emulator behaviour is not type-scoped:")
	w("a bad emulator response can corrupt any type, so \"was this estate")
	w("re-verified against the current pin\" cannot be answered by looking at")
	w("only some of its types.")
	w("")
	w("What that makes `-types` honest to claim, and what it does not: a")
	w("type-filtered confirmation is evidence about those types specifically,")
	w("never a board-wide claim. Clearing what `next -types aws_lambda_function`")
	w("returns says the estates that exercise `aws_lambda_function` still behave")
	w("like stock; it says nothing about the estates or the resource types the")
	w("filter excluded. That is the same house rule the site's own per-row")
	w("emulator provenance already holds to (`boardBanner`,")
	w("`tools/gauntlet/render.go`: render what the rows underneath actually")
	w("support, never a claim wider than the evidence). The two headline bars")
	w("stay computed from every headline stage on every estate regardless of any")
	w("`-types` run. Use `-types` to shrink a repin's queue to the estates a")
	w("change could plausibly have touched; use plain `next` when the question")
	w("is whether the board, not a slice of it, still clears.")
	w("")
	w("## Merging estate rows across PRs (`merge-artifact`)")
	w("")
	w("With several estate PRs open at once, a plain `git merge` re-conflicts")
	w("every other open PR the moment any one lands, and resolving it by hand has")
	w("produced a wrong board with no conflict markers at all: `sets.core.clear`")
	w("and `sets.all.clear` are counters two branches each incremented from the")
	w("same starting point, so a textually-clean auto-merge of two DISTINCT")
	w("estates' rows keeps one increment and silently drops the other (#488).")
	w("")
	w("`go run ./tools/gauntlet merge-artifact <base> <ours> <theirs>` is the")
	w("row-granular alternative: it three-way-merges %s at the level of one", ArtifactPath)
	w("estate's row rather than the whole file, then calls the same `Rebuild`")
	w("every other command uses (never a reimplementation) so the aggregate is")
	w("correct by construction from the merged rows. `<base>`, `<ours>`, and")
	w("`<theirs>` are git revisions (a sha, a branch, `HEAD`, ...), not file")
	w("paths - the tool reads the artifact at each with `git show` and diffs")
	w("trees with `git diff` itself.")
	w("")
	w("It applies only when the rows are independent evidence: two estate PRs")
	w("that each measured a DIFFERENT estate. It does not apply, and a full")
	w("re-run is mandatory instead, when:")
	w("")
	w("- **Both sides changed the same estate's row.** Two branches disagreeing")
	w("  about one estate's verdict needs a human or a re-run to say which")
	w("  measurement is current - guessing is how a wrong verdict lands. The")
	w("  tool refuses and names the estate and both sides' `last_run.commit`/")
	w("  `last_run.date`.")
	w("- **Product code moved between a row's measurement and the merge.**")
	w("  The merge is only valid when nothing outside %s,", ArtifactPath)
	w("  `%s`, `%s`, and an estate's own", SiteDataPath, SiteBoardPath)
	w("  `live/e2e/<name>/run.sh` differs between base and either side. PRs")
	w("  #502 and #503 both genuinely needed a re-run for exactly this reason -")
	w("  `tools/gauntlet/run.go`'s recording path changed underneath them - and")
	w("  the tool refuses, naming the file, rather than assume the rows are")
	w("  still evidence about the code as it stands now.")
	w("- **A surviving row's `last_run.commit` is not a real ancestor of the**")
	w("  **revision that produced it.** A rebase can replay a commit's diff")
	w("  without re-running the generator, leaving the JSON's embedded commit")
	w("  hash pointing at a dangling, now-unreachable object (#509). The tool")
	w("  checks every merged row's provenance and refuses rather than merge one")
	w("  it cannot verify.")
	w("- **The merge would violate an existing guard**, in particular")
	w("  `TestNonzeroExitCodeImpliesAFailingStage`'s invariant (#413): a")
	w("  nonzero `exit_code` with no stage reading `fail` anywhere in the row.")
	w("")
	w("A refusal always means re-run, never resolve by hand - the same rule")
	w("the merge playbook already holds plain `git merge` conflicts to. The")
	w("tool exists precisely so that judgment call is a program with a test,")
	w("not a worker's guess under time pressure.")
	w("")
	w("## What holds this together")
	w("")
	w("`tools/gauntlet/gauntlet_test.go`: the stage registry is well formed; the")
	w("manifest is canonical and every entry's script exists; every rendered file")
	w("matches a fresh render; the artifact agrees with the manifest; the protocol")
	w("parser round-trips; the number of legacy scripts can only fall.")
	w("`tools/gauntlet/mergeartifact_test.go` guards `merge-artifact` itself:")
	w("distinct-estate rows merge and the rebuilt aggregate matches the rows;")
	w("a same-estate conflict refuses and names the estate; a dangling")
	w("`last_run.commit` refuses (#509's class); a nonzero exit with no failing")
	w("stage refuses (#413's class); product code differing between base and a")
	w("side refuses and names the file.")
	w("")
	w("## The regression ratchet")
	w("")
	w("Every guard above is about internal consistency and provenance - the")
	w("artifact agrees with itself and with the manifest. None of them is about")
	w("regression: a stage that was recorded `pass` and comes back anything else")
	w("this run, with nothing outside the script to contradict the new verdict")
	w("(#553). `gauntlet run` closes the visible half of that gap: it reads the")
	w("committed artifact fresh, before this run's own results can overwrite it")
	w("in memory, and `RatchetViolations` (`tools/gauntlet/ratchet.go`) compares")
	w("the two. Any estate/stage that regressed off a committed `pass` fails the")
	w("run - printed to stderr and a nonzero exit - unless it is named in")
	w("`live/gauntlet/regressions.json`, a small hand-authored ledger, never")
	w("generated, that a human edits in the same change that earns the")
	w("regression: the same convention #552 uses for a cohort's resource-count")
	w("shrink, adapted because `live/gauntlet.json` itself may never be hand-")
	w("edited. The artifact is still written and rendered either way - ground")
	w("truth is never withheld to avoid a bad headline - only the run's own exit")
	w("status carries the refusal.")
	w("")
	w("This does not close the invisible half: a script that stops asserting")
	w("what it used to and still reports `pass` has no independent witness the")
	w("way a cohort's `resources` count gives #552's shrink guard one. #553's")
	w("own investigation into the strongest candidate - each stage's `BREAK=1`-")
	w("style negative control, whose whole job is proving an assertion is load-")
	w("bearing - found real coverage (every estate in the manifest carries at")
	w("least one) but no cheap way to re-run it: exercising every control found")
	w("across the manifest once costs on the order of the full board's own")
	w("measured wall-clock, not a fraction of it, and nothing today runs them on")
	w("any cadence at all. That investigation, and why it stops short of")
	w("building an automated sweep, is recorded in #553 rather than repeated")
	w("here.")
	return b.String()
}

// preApplyEstates names every estate declaring a cold-deploy pre-apply,
// with its address count, so the rendered contract says which estates take
// two applies rather than leaving a reader to grep the manifest (#1173).
func preApplyEstates(m *Manifest) string {
	var parts []string
	for _, e := range m.Estates {
		if len(e.PreApply) == 0 {
			continue
		}
		parts = append(parts, fmt.Sprintf("`%s` (%d address(es))", e.Name, len(e.PreApply)))
	}
	return strings.Join(parts, ", ")
}

func exampleEntryJSON(m *Manifest) string {
	var ex Estate
	for _, e := range m.Estates {
		if e.Set == SetCore && e.URL != "" {
			ex = e
			break
		}
	}
	if ex.Name == "" && len(m.Estates) > 0 {
		ex = m.Estates[0]
	}
	one := &Manifest{Estates: []Estate{ex}}
	b, _ := one.Canonical()
	// Show just the entry, not the wrapper.
	s := string(b)
	start := strings.Index(s, "{\n      \"name\"")
	end := strings.LastIndex(s, "}\n  ]")
	if start < 0 || end < 0 || end <= start {
		return s
	}
	body := s[start : end+1]
	// De-indent by four spaces.
	lines := strings.Split(body, "\n")
	for i, l := range lines {
		lines[i] = strings.TrimPrefix(l, "    ")
	}
	return strings.Join(lines, "\n")
}

func mdCell(s string) string {
	if s == "" {
		return ""
	}
	return strings.ReplaceAll(s, "|", "\\|")
}

// estateDateRange returns the oldest and newest last_run.date across every
// estate that has recorded at least one run. ok is false when none has -
// a fresh manifest before its first `gauntlet run`. RFC3339 UTC strings
// (the only format LastRun.Date is ever written in, run.go) sort correctly
// as plain strings, so no time parsing is needed.
func estateDateRange(a *Artifact) (oldest, newest string, ok bool) {
	for _, r := range a.Estates {
		if r.LastRun == nil || r.LastRun.Date == "" {
			continue
		}
		d := r.LastRun.Date
		if !ok || d < oldest {
			oldest = d
		}
		if !ok || d > newest {
			newest = d
		}
		ok = true
	}
	return oldest, newest, ok
}

// emulatorGroup is one distinct emulator digest recorded across the board's
// rows, and how many rows recorded it.
type emulatorGroup struct {
	Emulator string // "" is its own group: a row that ran but recorded no digest
	Count    int
}

// emulatorGroups buckets every estate that has recorded a run by its OWN
// last_run.emulator - the digest that specific run actually launched
// against, stamped by RunEstates at run time (run.go). It never reads
// a.Emulator: that field is configuration (a plain copy of live/floci-image,
// true of the checked-out tree regardless of what has or hasn't run), and
// conflating the two is exactly the shape #414 already found once, one
// field over (top-level Commit/Generated borrowed to describe evidence).
// A row with no last_run is excluded (it has recorded nothing to bucket);
// a row whose last_run has no recorded digest lands in the "" bucket -
// unknown provenance, distinct from and never merged into any real digest.
// Sorted by count descending, ties broken by digest, with the "" bucket
// always last regardless of its count so a board-wide sentence names the
// largest real agreement first.
func emulatorGroups(a *Artifact) []emulatorGroup {
	counts := map[string]int{}
	for _, r := range a.Estates {
		if r.LastRun == nil {
			continue
		}
		counts[r.LastRun.Emulator]++
	}
	var groups []emulatorGroup
	unknown := 0
	for e, n := range counts {
		if e == "" {
			unknown = n
			continue
		}
		groups = append(groups, emulatorGroup{Emulator: e, Count: n})
	}
	sort.Slice(groups, func(i, j int) bool {
		if groups[i].Count != groups[j].Count {
			return groups[i].Count > groups[j].Count
		}
		return groups[i].Emulator < groups[j].Emulator
	})
	if unknown > 0 {
		groups = append(groups, emulatorGroup{Emulator: "", Count: unknown})
	}
	return groups
}

// boardBanner is the one board-wide sentence the index page still gets to
// make, and it may only assert what every row below actually agrees on
// (the standing rule for every rendered claim in this fork: never ship a
// claim the rows underneath cannot support). It used to claim a single "measured
// at commit X" stamp for the whole board; no procedure ever produced that
// fact honestly (#414), so it is gone rather than kept lying. It was then
// fixed to borrow a.Emulator - CONFIGURATION, the pin the next run will use
// - to describe every row's EVIDENCE, which is true for exactly one
// instant (when a full sweep finishes) and false the moment any single
// estate re-runs against a repinned image while the rest sit unrun. That is
// the same defect one layer down, so this reads emulatorGroups (rows) and
// estateDateRange (rows), never a.Emulator, to describe what happened -
// a.Emulator appears only to say what the CURRENT pin is, never to claim a
// past run used it.
//
// Computed fresh from a.Estates on every call, never carried from a
// previous render, so it cannot go stale independently of the table below
// it. Handles: no runs yet; every row agreeing (with or without matching
// the current pin - a fully-agreeing board can still be uniformly stale
// after a repin); and rows disagreeing, which renders as a breakdown
// rather than picking a side.
func boardBanner(a *Artifact) string {
	oldest, newest, ok := estateDateRange(a)
	if !ok {
		return fmt.Sprintf("The pinned emulator image is `%s` (configuration for the next run); no estate below has recorded a run yet.", a.Emulator)
	}
	dateClause := fmt.Sprintf("recorded at %s", oldest)
	if oldest != newest {
		dateClause = fmt.Sprintf("recorded between %s and %s. Each row below carries its own `last_run` date; they are not all the same run", oldest, newest)
	}

	groups := emulatorGroups(a)
	switch {
	case len(groups) == 1 && groups[0].Emulator == "":
		return fmt.Sprintf("Every estate below has recorded a run, but none recorded which emulator image it used; nothing here confirms whether they matched the current pin `%s`.", a.Emulator)
	case len(groups) == 1:
		digest := groups[0].Emulator
		if digest == a.Emulator {
			return fmt.Sprintf("Every estate below last ran against the pinned emulator image `%s`, %s.", digest, dateClause)
		}
		return fmt.Sprintf("Every estate below last ran against emulator image `%s`, %s. The pin has since moved to `%s`; every row below is stale evidence against the current image.", digest, dateClause, a.Emulator)
	default:
		var parts []string
		for _, g := range groups {
			label := fmt.Sprintf("`%s`", g.Emulator)
			switch {
			case g.Emulator == "":
				label = "an unrecorded image"
			case g.Emulator == a.Emulator:
				label += " (current pin)"
			}
			parts = append(parts, fmt.Sprintf("%d against %s", g.Count, label))
		}
		// A row-disagreement claim needs the same date-range evidence the
		// single-group branches above already carry (dateClause) - found by
		// TestBoardBannerMatchesEstateRows the first time this artifact ever
		// had two distinct last_run.emulator groups at once (#434's own
		// verification run against reference-ec2-vpc and
		// corpus-dynamodb-table-basic): this branch asserted the emulator
		// split but never mentioned when any of it was measured, so the
		// oldest/newest last_run.date the rows actually carry went unstated
		// on the one board-wide sentence that gets to make a claim at all.
		// (#411's own worktree found and fixed the same gap independently,
		// the same night, against #411's own gauntlet run advancing
		// corpus-iam-policy to a new pin - #434's fix landed on main first,
		// so it is what stands here.)
		dateNote := fmt.Sprintf("last_run.date reads %s on every row measured so far", oldest)
		if oldest != newest {
			dateNote = fmt.Sprintf("last_run.date ranges from %s to %s across these rows, not one shared measurement", oldest, newest)
		}
		return fmt.Sprintf("Estates below were last measured against different emulator pins: %s (%s). The current pin is `%s`; a row not measured against it is stale evidence, not a failure - `go run ./tools/gauntlet next` surfaces it as work.", strings.Join(parts, ", "), dateNote, a.Emulator)
	}
}

// runtimeBanner is the one board-wide sentence about wall-clock time this
// page gets to make (#434), held to the same discipline boardBanner already
// holds the emulator/date claims to: it may only assert what the rows below
// actually support, computed fresh from a.Estates on every render rather
// than carried over, so it cannot go stale independently of what it
// summarizes. duration_s (run.go) is new with #434, so most rows will have
// none for a while after this lands - that must read as "partial, N of M
// estates recorded" rather than a "the full board takes N hours" claim no
// single sweep has actually produced (see HANDOFF.md's #414 lesson: no
// procedure runs the whole board in one shot, so no field may claim it did).
func runtimeBanner(a *Artifact) string {
	type group struct {
		total float64
		count int
	}
	groups := map[string]*group{}
	var order []string
	recorded := 0
	for _, r := range a.Estates {
		if r.LastRun == nil || r.LastRun.DurationS <= 0 {
			continue
		}
		recorded++
		g, ok := groups[r.LastRun.Commit]
		if !ok {
			g = &group{}
			groups[r.LastRun.Commit] = g
			order = append(order, r.LastRun.Commit)
		}
		g.total += r.LastRun.DurationS
		g.count++
	}
	if recorded == 0 {
		return "No estate has a recorded `last_run.duration_s` yet; it is populated the next time each estate runs (#434)."
	}
	sort.Strings(order) // commit hashes have no other natural order; sorted only for determinism
	var parts []string
	var grandTotal float64
	for _, c := range order {
		g := groups[c]
		grandTotal += g.total
		parts = append(parts, fmt.Sprintf("%s across %d estate(s) at commit `%s`", formatDuration(g.total), g.count, short(c)))
	}
	missing := len(a.Estates) - recorded
	if len(order) == 1 {
		note := ""
		if missing > 0 {
			note = fmt.Sprintf(" This is not a full-board figure: %d of %d estates have no recorded duration yet.", missing, len(a.Estates))
		}
		return fmt.Sprintf("%d of %d estates have a recorded run duration, totaling %s at commit `%s`.%s", recorded, len(a.Estates), formatDuration(grandTotal), short(order[0]), note)
	}
	return fmt.Sprintf("%d of %d estates have a recorded run duration, totaling %s, but not from one sweep: %s. This total spans different commits, not a single board run, and excludes %d estate(s) with no recorded duration yet.", recorded, len(a.Estates), formatDuration(grandTotal), strings.Join(parts, "; "), missing)
}

// formatDuration renders seconds the way a human reads a stopwatch
// ("3m45s", "1h2m3s"); time.Duration.String() already does exactly this and
// is what a full-board figure needs to read as hours once one exists.
func formatDuration(seconds float64) string {
	if seconds <= 0 {
		return "-"
	}
	return time.Duration(seconds * float64(time.Second)).Round(100 * time.Millisecond).String()
}

// runtimeTotalCell is one estate row's last_run.duration_s, or "-" when this
// run predates #434 or never completed.
func runtimeTotalCell(r EstateResult) string {
	if r.LastRun == nil {
		return "-"
	}
	return formatDuration(r.LastRun.DurationS)
}

// runtimeStageCells lists "<stage id> <duration>" for every active stage
// that recorded one, omitting stages with none rather than padding every
// row with dashes - a row from before #434, or from a script sourcing an
// older live/e2e/lib/gauntlet.sh that does not emit duration_s, legitimately
// has zero of these, and the sentence says so plainly instead of a wall of
// dashes.
func runtimeStageCells(r EstateResult, a *Artifact) string {
	var parts []string
	for _, s := range a.Stages {
		if s.Status != StatusActive {
			continue
		}
		if r.LastRun == nil {
			continue
		}
		secs, ok := r.LastRun.Seconds[s.ID]
		if !ok {
			continue
		}
		parts = append(parts, fmt.Sprintf("%s %s", s.ID, formatDuration(secs)))
	}
	if len(parts) == 0 {
		return "none recorded yet"
	}
	return strings.Join(parts, ", ")
}

// sortedKeys is a map's keys in order, for deterministic rendering.
func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func verdictMark(v string) string {
	switch v {
	case VerdictPass:
		return "pass"
	case VerdictFail:
		return "FAIL"
	case VerdictNA:
		return "n/a"
	default:
		return "not run"
	}
}

// VerdictMarkStale is the cell a carried-forward verdict prints (#1069).
// It deliberately does not contain the word "pass": the whole finding was
// that a row could show `greenfield: fail` and `day2_remove: pass` at once,
// because the pass was some earlier run's and the board had no way to say
// so. A reader scanning the row must not be able to read a pass out of a
// stage the recorded run never reached; the estate page's own row says
// underneath it which verdict was carried and from when.
const VerdictMarkStale = "stale"

// verdictMarkFor is verdictMark with the row's per-stage provenance in
// hand. carried is EstateResult.StageCarried: true only when the artifact
// records that this verdict came from a run other than the one the row
// names, never merely because provenance is unknown.
//
// Only pass and fail become "stale". A carried "not_run" or "n/a" asserts
// nothing that could mislead, so it prints exactly as it always has.
func verdictMarkFor(v string, carried bool) string {
	if carried && (v == VerdictPass || v == VerdictFail) {
		return VerdictMarkStale
	}
	return verdictMark(v)
}

// stageProvenanceNote is the sentence an estate page prints under a carried
// stage: which verdict was carried, and which run actually measured it.
// Empty for a stage this row's recorded run measured itself, and for one
// whose provenance was never recorded (a row written before #1069 - see
// StageCarried's three states; claiming staleness there would be an
// assertion the artifact cannot support).
func stageProvenanceNote(r EstateResult, id string) string {
	if !r.StageCarried(id) {
		return ""
	}
	v := r.Stages[id]
	if v != VerdictPass && v != VerdictFail {
		return ""
	}
	sr := r.StageRuns[id]
	if sr.Commit == "" && sr.Date == "" {
		return fmt.Sprintf("**Stale**: this cell reads `%s` from an earlier run, not from the run recorded below, which never reached this stage. That earlier run's own commit and date were not recorded (the row kept one commit for every stage until #1069), so it cannot be named here; the next run of this estate replaces the cell with a measured verdict.", v)
	}
	return fmt.Sprintf("**Stale**: this cell reads `%s` as measured at commit `%s` on %s, not by the run recorded below, which never reached this stage.", v, short(sr.Commit), sr.Date)
}

// staleStagesNote is the estate page's one sentence about carried verdicts
// across the whole row, printed beside the clear flag so a reader meets it
// before the table rather than after. Empty when nothing is carried.
func staleStagesNote(r EstateResult) string {
	carried := r.CarriedStages()
	if len(carried) == 0 {
		return ""
	}
	var parts []string
	for _, id := range carried {
		parts = append(parts, fmt.Sprintf("`%s` (%s)", id, r.Stages[id]))
	}
	noun, verb := "verdict", "was"
	if len(carried) > 1 {
		noun, verb = "verdicts", "were"
	}
	return fmt.Sprintf("**%d stage %s below %s carried forward from an earlier run** and show as `%s`, not as the verdict they carry: %s. A run that aborts early leaves the stages it never reached reading whatever the last run to reach them said (#1069); the cell is kept because it is still the best thing known about that stage, and marked because it is not evidence about the run recorded below.", len(carried), noun, verb, VerdictMarkStale, strings.Join(parts, ", "))
}

func short(sha string) string {
	if len(sha) > 10 {
		return sha[:10]
	}
	return sha
}

func firstSentence(s string) string {
	if i := strings.Index(s, ". "); i > 0 {
		return s[:i+1]
	}
	return s
}
