// Copyright (c) The OpenTofu Authors
// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2023 HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Rendered outputs, relative to the repository root. Everything here is
// written in full by `gauntlet render` and held to the tree by
// TestRenderedDocsAreCurrent. Hand edits are overwritten on the next render.
const (
	SpecPath         = "live/GAUNTLET.md"
	SiteProgressDir  = "site/content/docs/progress"
	SiteProgressPage = "site/content/docs/progress/_index.md"
	SiteAddPage      = "site/content/docs/progress/add-an-estate.md"
	SiteContribPage  = "site/content/docs/progress/contribute.md"
	WorkerBriefPath  = ".claude/agents/gauntlet-worker.md"
	// OrchestratorBriefPath is the brief for whoever keeps the loop running.
	OrchestratorBriefPath = ".claude/agents/gauntlet-orchestrator.md"
)

// Render writes every generated file into root. It returns the list of
// files written so a caller (or a test rendering into a temp dir) can compare.
func Render(root string, m *Manifest, a *Artifact) ([]string, error) {
	var written []string
	write := func(rel string, body string) error {
		p := filepath.Join(root, rel)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
			return err
		}
		written = append(written, rel)
		return nil
	}

	// The manifest, canonically.
	mb, err := m.Canonical()
	if err != nil {
		return nil, err
	}
	if err := write(ManifestPath, string(mb)); err != nil {
		return nil, err
	}
	// The artifact, and its copy for Hugo.
	ab, err := a.Canonical()
	if err != nil {
		return nil, err
	}
	if err := write(ArtifactPath, string(ab)); err != nil {
		return nil, err
	}
	if err := write(SiteDataPath, string(ab)); err != nil {
		return nil, err
	}
	if err := write(SpecPath, renderSpec(m, a)); err != nil {
		return nil, err
	}
	if err := write(SiteProgressPage, renderProgressIndex(a)); err != nil {
		return nil, err
	}
	if err := write(SiteAddPage, renderAddPage(m)); err != nil {
		return nil, err
	}
	if err := write(SiteContribPage, renderContributePage()); err != nil {
		return nil, err
	}
	// Remove estate pages that no longer have an estate, then write each.
	dir := filepath.Join(root, SiteProgressDir)
	entries, _ := os.ReadDir(dir)
	for _, ent := range entries {
		name := ent.Name()
		if name == "_index.md" || name == "add-an-estate.md" || name == "contribute.md" || !strings.HasSuffix(name, ".md") {
			continue
		}
		if _, ok := a.Result(strings.TrimSuffix(name, ".md")); !ok {
			_ = os.Remove(filepath.Join(dir, name))
		}
	}
	for _, r := range a.Estates {
		if err := write(filepath.Join(SiteProgressDir, r.Name+".md"), renderEstatePage(r, a)); err != nil {
			return nil, err
		}
	}
	return written, nil
}

const generatedBanner = "<!-- Generated by `go run ./tools/gauntlet render` from tools/gauntlet/stages.go, live/gauntlet/estates.json and live/gauntlet.json. Do not edit; TestRenderedDocsAreCurrent holds this file to the tree. -->"

// renderSpec is live/GAUNTLET.md: the contract for contributors.
func renderSpec(m *Manifest, a *Artifact) string {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format, args...); b.WriteString("\n") }

	w("%s", generatedBanner)
	w("# The gauntlet")
	w("")
	w("The gauntlet is how choudoufu measures itself against stock OpenTofu. Real,")
	w("popular OpenTofu and Terraform configurations are run through a fixed set of")
	w("stages, each a comparison with what stock does for the same configuration,")
	w("against the pinned emulator. The result is one artifact, `%s`, and the", ArtifactPath)
	w("two bars on the site read it directly. Nothing on the site about progress is")
	w("typed by hand.")
	w("")
	w("The promise it measures: if OpenTofu runs an estate, choudoufu runs it too.")
	w("Migration from a stock state file is lossless and a greenfield apply is")
	w("equivalent. Everything below is that sentence made checkable.")
	w("")
	w("This page defines the gauntlet; it does not walk you through running it.")
	w("The two procedures are rendered from this same tool as their own pages:")
	w("adding an estate is `%s`, and", SiteAddPage)
	w("contributing compute is `%s`.", SiteContribPage)
	w("")
	w("## The two numbers")
	w("")
	w("An estate is **clear** when every active stage passes. The first bar is clear")
	w("estates over the core set; the second is clear estates over every estate in")
	w("the manifest. Planned stages are listed so the target is visible, but do not")
	w("count until their status is flipped to active in `tools/gauntlet/stages.go`,")
	w("which is a deliberate change that lowers the bars until estates catch up.")
	w("")
	w("Core is a pinned population that can reach 100%%. The rule for membership is")
	w("in \"The core set\" below; a core estate carries its reason in the manifest.")
	w("")
	w("## Stages")
	w("")
	w("Each stage states what a pass proves, what stock's answer to the same question")
	w("is and how it is compared (the oracle), and how a script shows its check is")
	w("load-bearing (`BREAK=1` must make the stage fail).")
	w("")
	for _, s := range a.Stages {
		w("### %d. %s (`%s`, %s)", s.Order, s.Title, s.ID, s.Status)
		w("")
		w("Proves: %s", s.Proves)
		w("")
		w("Oracle: %s", s.Oracle)
		w("")
		w("Break: %s", s.Break)
		w("")
	}
	w("## The protocol a script speaks")
	w("")
	w("A crossing script lives at `live/e2e/<name>/run.sh`, sources")
	w("`live/e2e/lib/gauntlet.sh`, and reports each stage on stdout:")
	w("")
	w("```")
	w("GAUNTLET protocol=1")
	w("GAUNTLET stage=cold_deploy verdict=pass")
	w("GAUNTLET stage=migrate verdict=pass detail=68 added, 41 stamped, 27 skipped")
	w("GAUNTLET stage=test_plan verdict=fail detail=Non-static identity argument on aws_x.y")
	w("```")
	w("")
	w("Verdicts are `pass`, `fail` or `not_run`; `not_run` means the script does not")
	w("exercise that stage yet, which is itself a gap the artifact shows. A script")
	w("that never prints the protocol line is legacy: the runner records its exit")
	w("code and leaves the imported verdicts as they are. The runner is")
	w("`go run ./tools/gauntlet run [<name>...]`, logs land in `%s/`.", LogDir)
	w("")
	w("## The manifest entry")
	w("")
	w("Every estate is one entry in `%s`:", ManifestPath)
	w("")
	w("```json")
	w("%s", exampleEntryJSON(m))
	w("```")
	w("")
	w("`set` is `core` or `growing`; `reason` is required for core; `script` defaults")
	w("to `live/e2e/<name>/run.sh`; `url` and `pin` are required except for the")
	w("`reference` lane.")
	w("")
	w("Lanes: %s.", strings.Join(KnownLanes, ", "))
	w("")
	w("## The core set")
	w("")
	w("Rule: the most-downloaded terraform-aws-modules examples, the OpenTofu-native")
	w("projects already crossed, and the reference shapes kept in this repository,")
	w("each pinned by tag or commit. Adding one needs a reason in the manifest, which")
	w("is the whole approval step. Anything real goes in the growing set without one.")
	w("")
	w("| Estate | Lane | Pin | Reason |")
	w("|---|---|---|---|")
	for _, e := range m.Estates {
		if e.Set != SetCore {
			continue
		}
		w("| `%s` | %s | %s | %s |", e.Name, e.Lane, mdCell(e.Pin), mdCell(e.Reason))
	}
	w("")
	w("## The artifact")
	w("")
	w("`%s` carries `schema`, `emulator`, the `stages`", ArtifactPath)
	w("table above, `sets` (`core` and `all`, each with `estates`, `clear`, and a")
	w("per-stage tally), and one row per estate: `name`, `source`, `url`, `pin`,")
	w("`lane`, `set`, `reason`, `script`, `stages` (id to verdict), `clear`,")
	w("`protocol` (`gauntlet` or `legacy`), `last_run` (`commit`, `date`,")
	w("`emulator` - the pin THAT run actually used, distinct from the")
	w("top-level `emulator`, which is the pin the NEXT run will use -")
	w("`exit_code`, optional per-stage `detail`). `go run ./tools/gauntlet snapshot")
	w("<version>` copies it to `live/history/<version>.json` at release.")
	w("")
	w("## What holds this together")
	w("")
	w("`tools/gauntlet/gauntlet_test.go`: the stage registry is well formed; the")
	w("manifest is canonical and every entry's script exists; every rendered file")
	w("matches a fresh render; the artifact agrees with the manifest; the protocol")
	w("parser round-trips; the number of legacy scripts can only fall.")
	return b.String()
}

func exampleEntryJSON(m *Manifest) string {
	var ex Estate
	for _, e := range m.Estates {
		if e.Set == SetCore && e.URL != "" {
			ex = e
			break
		}
	}
	if ex.Name == "" && len(m.Estates) > 0 {
		ex = m.Estates[0]
	}
	one := &Manifest{Estates: []Estate{ex}}
	b, _ := one.Canonical()
	// Show just the entry, not the wrapper.
	s := string(b)
	start := strings.Index(s, "{\n      \"name\"")
	end := strings.LastIndex(s, "}\n  ]")
	if start < 0 || end < 0 || end <= start {
		return s
	}
	body := s[start : end+1]
	// De-indent by four spaces.
	lines := strings.Split(body, "\n")
	for i, l := range lines {
		lines[i] = strings.TrimPrefix(l, "    ")
	}
	return strings.Join(lines, "\n")
}

func mdCell(s string) string {
	if s == "" {
		return ""
	}
	return strings.ReplaceAll(s, "|", "\\|")
}

func frontMatter(title string, weight int, extra ...string) string {
	var b strings.Builder
	b.WriteString("---\n")
	fmt.Fprintf(&b, "title: %q\n", title)
	fmt.Fprintf(&b, "weight: %d\n", weight)
	for _, l := range extra {
		b.WriteString(l + "\n")
	}
	b.WriteString("---\n")
	return b.String()
}

// estateDateRange returns the oldest and newest last_run.date across every
// estate that has recorded at least one run. ok is false when none has -
// a fresh manifest before its first `gauntlet run`. RFC3339 UTC strings
// (the only format LastRun.Date is ever written in, run.go) sort correctly
// as plain strings, so no time parsing is needed.
func estateDateRange(a *Artifact) (oldest, newest string, ok bool) {
	for _, r := range a.Estates {
		if r.LastRun == nil || r.LastRun.Date == "" {
			continue
		}
		d := r.LastRun.Date
		if !ok || d < oldest {
			oldest = d
		}
		if !ok || d > newest {
			newest = d
		}
		ok = true
	}
	return oldest, newest, ok
}

// emulatorGroup is one distinct emulator digest recorded across the board's
// rows, and how many rows recorded it.
type emulatorGroup struct {
	Emulator string // "" is its own group: a row that ran but recorded no digest
	Count    int
}

// emulatorGroups buckets every estate that has recorded a run by its OWN
// last_run.emulator - the digest that specific run actually launched
// against, stamped by RunEstates at run time (run.go). It never reads
// a.Emulator: that field is configuration (a plain copy of live/floci-image,
// true of the checked-out tree regardless of what has or hasn't run), and
// conflating the two is exactly the shape #414 already found once, one
// field over (top-level Commit/Generated borrowed to describe evidence).
// A row with no last_run is excluded (it has recorded nothing to bucket);
// a row whose last_run has no recorded digest lands in the "" bucket -
// unknown provenance, distinct from and never merged into any real digest.
// Sorted by count descending, ties broken by digest, with the "" bucket
// always last regardless of its count so a board-wide sentence names the
// largest real agreement first.
func emulatorGroups(a *Artifact) []emulatorGroup {
	counts := map[string]int{}
	for _, r := range a.Estates {
		if r.LastRun == nil {
			continue
		}
		counts[r.LastRun.Emulator]++
	}
	var groups []emulatorGroup
	unknown := 0
	for e, n := range counts {
		if e == "" {
			unknown = n
			continue
		}
		groups = append(groups, emulatorGroup{Emulator: e, Count: n})
	}
	sort.Slice(groups, func(i, j int) bool {
		if groups[i].Count != groups[j].Count {
			return groups[i].Count > groups[j].Count
		}
		return groups[i].Emulator < groups[j].Emulator
	})
	if unknown > 0 {
		groups = append(groups, emulatorGroup{Emulator: "", Count: unknown})
	}
	return groups
}

// boardBanner is the one board-wide sentence the index page still gets to
// make, and it may only assert what every row below actually agrees on
// (the RFC on process-as-code names this exact shape: never ship a claim
// the rows underneath cannot support). It used to claim a single "measured
// at commit X" stamp for the whole board; no procedure ever produced that
// fact honestly (#414), so it is gone rather than kept lying. It was then
// fixed to borrow a.Emulator - CONFIGURATION, the pin the next run will use
// - to describe every row's EVIDENCE, which is true for exactly one
// instant (when a full sweep finishes) and false the moment any single
// estate re-runs against a repinned image while the rest sit unrun. That is
// the same defect one layer down, so this reads emulatorGroups (rows) and
// estateDateRange (rows), never a.Emulator, to describe what happened -
// a.Emulator appears only to say what the CURRENT pin is, never to claim a
// past run used it.
//
// Computed fresh from a.Estates on every call, never carried from a
// previous render, so it cannot go stale independently of the table below
// it. Handles: no runs yet; every row agreeing (with or without matching
// the current pin - a fully-agreeing board can still be uniformly stale
// after a repin); and rows disagreeing, which renders as a breakdown
// rather than picking a side.
func boardBanner(a *Artifact) string {
	oldest, newest, ok := estateDateRange(a)
	if !ok {
		return fmt.Sprintf("The pinned emulator image is `%s` (configuration for the next run); no estate below has recorded a run yet.", a.Emulator)
	}
	dateClause := fmt.Sprintf("recorded at %s", oldest)
	if oldest != newest {
		dateClause = fmt.Sprintf("recorded between %s and %s. Each row below carries its own `last_run` date; they are not all the same run", oldest, newest)
	}

	groups := emulatorGroups(a)
	switch {
	case len(groups) == 1 && groups[0].Emulator == "":
		return fmt.Sprintf("Every estate below has recorded a run, but none recorded which emulator image it used; nothing here confirms whether they matched the current pin `%s`.", a.Emulator)
	case len(groups) == 1:
		digest := groups[0].Emulator
		if digest == a.Emulator {
			return fmt.Sprintf("Every estate below last ran against the pinned emulator image `%s`, %s.", digest, dateClause)
		}
		return fmt.Sprintf("Every estate below last ran against emulator image `%s`, %s. The pin has since moved to `%s`; every row below is stale evidence against the current image.", digest, dateClause, a.Emulator)
	default:
		var parts []string
		for _, g := range groups {
			label := fmt.Sprintf("`%s`", g.Emulator)
			switch {
			case g.Emulator == "":
				label = "an unrecorded image"
			case g.Emulator == a.Emulator:
				label += " (current pin)"
			}
			parts = append(parts, fmt.Sprintf("%d against %s", g.Count, label))
		}
		return fmt.Sprintf("Estates below were last measured against different emulator pins: %s. The current pin is `%s`; a row not measured against it is stale evidence, not a failure - `go run ./tools/gauntlet next` surfaces it as work.", strings.Join(parts, ", "), a.Emulator)
	}
}

// renderProgressIndex is the site's progress page.
func renderProgressIndex(a *Artifact) string {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format, args...); b.WriteString("\n") }
	b.WriteString(frontMatter("How close AWS is", 30, "bookCollapseSection: true"))
	w("%s", generatedBanner)
	w("")
	w("Two numbers, both read from the same artifact the test suite writes. An")
	w("estate is a real OpenTofu or Terraform configuration, pinned by commit, run")
	w("through every active stage below side by side with stock OpenTofu against the")
	w("pinned emulator. It is clear when every active stage passes.")
	w("")
	w("{{< gauntlet-bars >}}")
	w("")
	w("%s", boardBanner(a))
	w("")
	w("## The stages")
	w("")
	w("| | Stage | Status | What a pass proves |")
	w("|---|---|---|---|")
	for _, s := range a.Stages {
		w("| %d | %s | %s | %s |", s.Order, s.Title, s.Status, mdCell(firstSentence(s.Proves)))
	}
	w("")
	w("Planned stages are listed so the target is visible. They do not count toward")
	w("clear until they are activated, and activating one lowers the bars until the")
	w("estates catch up. The full definition of every stage, including what stock's")
	w("answer is and how each check is proven non-vacuous, is")
	w("[`live/GAUNTLET.md`](https://github.com/INTENTIUS/choudoufu/blob/main/live/GAUNTLET.md).")
	w("")
	w("## The estates")
	w("")
	w("| Estate | Set | Lane | Clear | Stages |")
	w("|---|---|---|---|---|")
	rows := append([]EstateResult(nil), a.Estates...)
	sort.SliceStable(rows, func(i, j int) bool {
		if rows[i].Set != rows[j].Set {
			return rows[i].Set == SetCore
		}
		return rows[i].Name < rows[j].Name
	})
	for _, r := range rows {
		clear := "no"
		if r.Clear {
			clear = "yes"
		}
		w("| [%s]({{< relref \"%s\" >}}) | %s | %s | %s | %s |", r.Name, r.Name, r.Set, r.Lane, clear, stageCells(r, a))
	}
	w("")
	w("To add an estate, see [Add an estate]({{< relref \"add-an-estate\" >}}).")
	return b.String()
}

func stageCells(r EstateResult, a *Artifact) string {
	var parts []string
	for _, s := range a.Stages {
		if s.Status != StatusActive {
			continue
		}
		parts = append(parts, verdictMark(r.Stages[s.ID]))
	}
	return strings.Join(parts, " ")
}

func verdictMark(v string) string {
	switch v {
	case VerdictPass:
		return "pass"
	case VerdictFail:
		return "FAIL"
	default:
		return "not run"
	}
}

// renderEstatePage is one estate's page.
func renderEstatePage(r EstateResult, a *Artifact) string {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format, args...); b.WriteString("\n") }
	b.WriteString(frontMatter(r.Name, 50))
	w("%s", generatedBanner)
	w("")
	w("%s", r.Source)
	w("")
	if r.URL != "" {
		w("Source: <%s> at `%s`.", r.URL, r.Pin)
		w("")
	}
	w("Set: %s. Lane: %s.", r.Set, r.Lane)
	if r.Reason != "" {
		w("")
		w("Why it is in the core set: %s", r.Reason)
	}
	w("")
	if r.Clear {
		w("**Clear.** Every active stage passes.")
	} else {
		w("**Not clear yet.**")
	}
	w("")
	w("| Stage | Verdict | Detail |")
	w("|---|---|---|")
	for _, s := range a.Stages {
		detail := ""
		if r.LastRun != nil {
			detail = r.LastRun.Detail[s.ID]
		}
		title := s.Title
		if s.Status != StatusActive {
			title += " (planned)"
		}
		w("| %s | %s | %s |", title, verdictMark(r.Stages[s.ID]), mdCell(detail))
	}
	w("")
	switch r.Protocol {
	case ProtocolGauntlet:
		if r.LastRun != nil {
			switch {
			case r.LastRun.Emulator == "":
				w("Last run at commit `%s` on %s, exit code %d. This run's emulator image was not recorded.", short(r.LastRun.Commit), r.LastRun.Date, r.LastRun.ExitCode)
			case r.LastRun.Emulator == a.Emulator:
				w("Last run at commit `%s` on %s, exit code %d, against emulator image `%s`.", short(r.LastRun.Commit), r.LastRun.Date, r.LastRun.ExitCode, r.LastRun.Emulator)
			default:
				w("Last run at commit `%s` on %s, exit code %d, against emulator image `%s`. **Stale**: the current pin is `%s`.", short(r.LastRun.Commit), r.LastRun.Date, r.LastRun.ExitCode, r.LastRun.Emulator, a.Emulator)
			}
		}
	default:
		w("Verdicts were recorded from this estate's crossing script by hand before the")
		w("script spoke the gauntlet protocol; the next run that does will replace them.")
	}
	if r.Notes != "" {
		w("")
		w("%s", r.Notes)
	}
	w("")
	w("## Reproduce it")
	w("")
	w("```")
	w("go run ./tools/gauntlet run %s", r.Name)
	w("```")
	w("")
	w("Needs Docker (the emulator is pulled at the pinned digest), the AWS CLI, and a")
	w("stock `terraform` or `tofu` binary on PATH for the cold deploy. The script is")
	w("`%s`; `BREAK=1` corrupts its assertions to show they are load-bearing.", r.Script)
	return b.String()
}

// renderAddPage is the site copy of "Adding an estate".
func renderAddPage(m *Manifest) string {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format, args...); b.WriteString("\n") }
	b.WriteString(frontMatter("Add an estate", 40))
	w("%s", generatedBanner)
	w("")
	w("An estate is any real OpenTofu or Terraform configuration, pinned by tag or")
	w("commit. Adding one is a manifest entry and a script, and the site picks it up")
	w("on the next run.")
	w("")
	w("```")
	w("go run ./tools/gauntlet add <name> <repo-url> <tag-or-commit> -lane <lane> [-core -reason \"...\"] -source \"<one line>\"")
	w("```")
	w("")
	w("That writes the entry and a script stub at `live/e2e/<name>/run.sh` with every")
	w("stage wired to the protocol and marked `not_run`. Fill the stub in, using the")
	w("script of a similar estate as the template")
	w("(`live/e2e/corpus-vpc-complete/run.sh` is the fullest), then:")
	w("")
	w("```")
	w("go run ./tools/gauntlet run <name>     # runs it against the emulator, records verdicts")
	w("go run ./tools/gauntlet render         # regenerates the artifact and these pages")
	w("```")
	w("")
	w("Commit the entry, the script, `live/gauntlet.json` and the rendered pages. CI")
	w("runs the same two commands nightly.")
	w("")
	w("Lanes: %s. A `-core` estate needs `-reason`; the rule for the core set is in", strings.Join(KnownLanes, ", "))
	w("[`live/GAUNTLET.md`](https://github.com/INTENTIUS/choudoufu/blob/main/live/GAUNTLET.md).")
	w("")
	w("A manifest entry looks like this:")
	w("")
	w("```json")
	w("%s", exampleEntryJSON(m))
	w("```")
	return b.String()
}

func short(sha string) string {
	if len(sha) > 10 {
		return sha[:10]
	}
	return sha
}

func firstSentence(s string) string {
	if i := strings.Index(s, ". "); i > 0 {
		return s[:i+1]
	}
	return s
}

// contributeProse is the "contribute compute" how-to. It has one home, the
// site page below; the spec names that page rather than repeating it.
func contributeProse() string {
	return strings.TrimSpace(`
Anyone can move the bars by spending tokens rather than time. The loop is
deterministic, so it needs no coordinator:

` + "```" + `
go run ./tools/gauntlet next        # the next unit: an estate and the first active stage it does not pass
just contribute [max-usd]           # one worker run on that unit, in a fresh worktree, with your own key
` + "```" + `

` + "`just contribute`" + ` runs Claude Code headless under the brief in
` + "`" + WorkerBriefPath + "`" + `, which does exactly one unit: run the estate, classify every
difference from stock with the five-row table in HANDOFF.md, fix it generically,
re-run, render, and open a pull request whose title carries the unit ID. It
never merges. The same thing runs on GitHub Actions from your fork:
` + "`.github/workflows/contribute.yml`" + ` is ` + "`workflow_dispatch`" + `, reads your fork's
` + "`ANTHROPIC_API_KEY`" + ` secret, and opens the pull request against this repository when
a ` + "`CONTRIBUTE_TOKEN`" + ` with pull-request scope is present, or prints the compare URL
when it is not. There is no hosted path; every worker runs under the key of
whoever started it.

Two contributors picking the same unit is expected. The worker checks for an
open pull request carrying the unit ID before starting and takes the next unit
if one exists. A pull request that changes only the artifact and the rendered
docs (a re-run that moved verdicts) is merged automatically once CI passes
(` + "`.github/workflows/automerge-artifact.yml`" + `); anything that changes code waits for a
maintainer.

Providers are lanes. A GCP or Azure estate enters the same manifest with its
own lane, runs the same stages against its own emulator, and ` + "`next`" + ` picks it up
like any other; an emulator gap is a unit in the emulator's repository.
`)
}

// renderContributePage is the site copy of "Contributing compute".
func renderContributePage() string {
	var b strings.Builder
	b.WriteString(frontMatter("Contribute compute", 45))
	b.WriteString(generatedBanner + "\n\n")
	b.WriteString(contributeProse())
	b.WriteString("\n")
	return b.String()
}
