// Copyright (c) The OpenTofu Authors
// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2023 HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package main

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

// scalerecord.go: issue #1051 and its sibling INTENTIUS/chant-bench#33 -
// "how much does a plan cost as an estate grows" is answered today by three
// things that only prose ties together: live/gauntlet.json's own `estates`
// row for terralith-scale and its `live_cert` rows (per-run commit, date,
// emulator digest, oracle versions, per-stage verdicts and DETAIL STRINGS,
// duration), site/content/docs/model/plan-cost.md's hand-copied sweep/
// read-pass split per instance count, and site/content/docs/what-you-pay.md's
// hand-copied real-AWS API-call pairs. None of the three is machine-readable
// as a "measurement" - a reader (chant-bench's ingest, or anyone else) has to
// parse English to get a number out.
//
// ScaleRecord is the structured field this file adds, one per (estate,
// target, scale) actually measured, and ScaleRecordsPath
// ("live/gauntlet-scale.json") is where they live - a companion to
// ArtifactPath, never folded into it, for the same reason LiveCertResult is
// its own top-level slice rather than a row in Estates (see livecert.go):
// this is a DIFFERENT question ("what did a plan cost at this size") than
// either of gauntlet.json's own two ("does choudoufu match stock against the
// pinned emulator" / "did this one real-AWS run verify what the emulator
// already agreed to"), and conflating them would let a scale point silently
// count toward, or be silently overwritten by, machinery that has nothing to
// do with scale.
//
// The smallest change issue #1051 asks for turns out to be: nothing else
// needs to start recording new numbers. terralith-scale.sh's own
// gauntlet_stage calls already compute every number this file wants as a
// plain bash variable before folding it into a human sentence - resource and
// taggable counts, seconds, throttle/retry line counts, index_lag_s. Two
// things happen instead of a bigger rewrite:
//
//  1. terralith-scale.sh now ALSO appends explicit `key=value` tokens to the
//     end of each of those four sentences (the exact pattern `index_lag_s=`
//     already used, extended rather than replaced) - the prose stays, for
//     the human tailing a live-cert run, and the tokens ride beside it, for
//     a machine.
//  2. This file's parseXDetail functions read those tokens when present, and
//     fall back to a fixed regex over the ORIGINAL sentence shape when they
//     are not - every historical live_cert/estates row in live/gauntlet.json
//     predates the tokens and only ever had the sentence, and issue #1051
//     asks for those points backfilled too (see `gauntlet scale-backfill` in
//     main.go), not thrown away for having shipped one script version too
//     early.
//
// A number this file cannot recover either way - because the run genuinely
// never measured it, not because the parser is lazy - is left absent
// (nil/omitted), never zero: "Absent is honest; zero is a lie" is this
// repository's own rule (issue #1051's brief, restating HANDOFF.md). The
// biggest field left absent by every record this unit backfills is
// PlanCalls: terralith-scale.sh's own analyze_api_calls (the sweep/read-pass
// split, #622) logs its report to stdout/WORK only and no gauntlet_stage
// call ever carries it, so no historical live_cert or estates row has it to
// recover. internal/live/discovery/slicing_bench_test.go's
// TestSlicingMatrixAgainstFloci measures exactly this split (its own
// legSplit type - TaggingLegCalls, NativeSweepCalls, BuildCalls) but only
// against the floci emulator, and writes it to SLICE_OUT, a path nothing
// commits - so plan-cost.md's own 79/301/745 sweep/read-pass numbers, and
// what-you-pay.md's real-AWS API-call pairs, are not backfillable from
// live/gauntlet.json at all: they exist only as the prose in those two
// pages, and issue #1051 is explicit that prose is not transcribed into a
// record - it is named in the report as needing a re-run instead.
//
// That split is ScaleAuditCalls today, not ScaleRecord.PlanCalls - see both
// fields' own doc comments (#1053's correction, after an earlier version of
// this file conflated the two and shipped the audit's 706 as though it were
// a plan's cost).

// ScaleRecordSchema is ScaleRecord's own schema version, independent of
// Artifact.Schema (they describe unrelated documents that merely happen to
// live beside each other).
const ScaleRecordSchema = 1

// ScaleRecordsPath is live/gauntlet-scale.json: named to read as gauntlet.json's
// obvious companion, sitting in the same directory, never mistaken for a
// third, unrelated artifact.
const ScaleRecordsPath = "live/gauntlet-scale.json"

// ScaleArtifact is the whole of live/gauntlet-scale.json. Regenerated by
// `gauntlet live-cert` (every future real-AWS/floci run upserts its own
// record) and by `gauntlet scale-backfill` (issue #1051's one-time recovery
// of the points already sitting, unrecovered, in live/gauntlet.json's own
// history) - never hand-edited, the same discipline live/gauntlet.json
// itself documents on Artifact's own doc comment.
type ScaleArtifact struct {
	Schema int `json:"schema"`
	// Emulator mirrors Artifact.Emulator's own meaning exactly (see that
	// field's doc comment, artifact.go): a plain copy of live/floci-image at
	// the moment this file was last (re)written - CONFIGURATION, the pin the
	// NEXT floci-target run will use, never a claim about what any past
	// record here actually measured against (each record's own, per-row
	// `emulator` field is that evidence). Kept here, at the top level,
	// purely so live/flociimage_test.go's flociImageFields guard - the one
	// mechanism this repository already has for "does a committed artifact
	// name the emulator it goes with" - has a single, flat field to check
	// this file against, the same way it checks live/gauntlet.json's own
	// top-level Emulator.
	Emulator string        `json:"emulator,omitempty"`
	Records  []ScaleRecord `json:"records"`
}

// ScaleRecord is one measured run of one estate at one scale, against one
// target. Two rows can share Estate and Target and differ only in Scale -
// unlike LiveCertResult (keyed by estate alone, one row survives per
// estate), a ScaleRecord's whole point is to keep every size on record at
// once, which is exactly what issue #1051 says live/gauntlet.json's own
// live_cert array cannot do today.
type ScaleRecord struct {
	Schema int `json:"schema"`
	// Estate and Target together with Scale are this record's identity -
	// see UpsertScaleRecord.
	Estate string `json:"estate"`
	// Target is "floci" (the emulator) or "aws" (a real account), mirroring
	// LiveCertResult.Target's own two values.
	Target string `json:"target"`
	// Scale is terralith-gen's own -scale for this run, when the estate has
	// one; absent for an estate this schema cannot size (nothing here
	// invents a scale a run's own detail never named).
	Scale int `json:"scale,omitempty"`
	// Commit is the checkout state the run measured against - copied
	// verbatim from the source row (LiveCertResult.Commit or
	// EstateResult.LastRun.Commit), never re-derived.
	Commit string `json:"commit"`
	Date   string `json:"date,omitempty"`
	// Emulator is the floci digest a target=floci run launched against;
	// absent for target=aws (there is no emulator to name).
	Emulator string `json:"emulator,omitempty"`
	// Region is the AWS region a target=aws run used; absent for
	// target=floci.
	Region string `json:"region,omitempty"`
	// Oracle is the stock terraform/tofu versions this run compared
	// choudoufu against, when the source row recorded one. A real-AWS
	// live_cert row does not record this today (LiveCertResult carries no
	// Oracle field) - absent here reports that honestly rather than
	// guessing from live/oracle-versions.json's CURRENT pin, which may not
	// be what an old run actually used.
	Oracle *OracleVersions `json:"oracle,omitempty"`
	// Resources is the estate's own size, in objects - not the same number
	// as Scale (which is terralith-gen's input, not its output).
	Resources *ScaleResources `json:"resources,omitempty"`
	// Held is true when the run that produced this record left its real-AWS
	// resources live rather than tearing them down (LIVECERT_HOLD=1,
	// terralith-scale.sh's own HOLD_TAG) - copied through so a record can
	// never be mistaken for a finished, verified-empty certification the
	// way a held gauntlet_stage detail already cannot be (see
	// terralith-scale.sh's own doc comment on LIVECERT_HOLD).
	Held bool `json:"held,omitempty"`
	// Stages is per-stage verdict/seconds/throttle/retry, keyed by stage id
	// (cold_deploy, migrate, test_plan, test_apply for a live_cert row).
	// A stage present in Stages but with Seconds/Throttle/Retry all nil
	// means the source row named that stage's verdict but this parser could
	// not recover any of its numbers from the detail text (an unrecognized
	// sentence shape, or a refusal whose message never mentioned them) -
	// still worth recording, since the verdict itself is evidence.
	Stages map[string]ScaleStage `json:"stages,omitempty"`
	// IndexLagS is the Resource Groups Tagging API index-wait measurement
	// (#1046, #1049) test_plan's own detail carries as index_lag_s=N;
	// absent for a target=floci run (the index lag is not under test there
	// - terralith-scale.sh's own index_wait skips it outright) and for any
	// real-AWS row recorded before that instrumentation existed.
	IndexLagS *int `json:"index_lag_s,omitempty"`
	// PlanCalls is what an ORDINARY PLAN costs, cold and warm, with the
	// stock oracle's count beside choudoufu's cold plan when the same run
	// measured both. This is the number issue #1051 asks for. It is NOT
	// #622's sweep/read-pass split - that split only exists for a run
	// instrumented with Request.CollectUnclaimed forced true (the account
	// inventory), which by construction takes the whole admission table
	// regardless of narrowing and cache state (nativesweep.go's own
	// unconditional CollectUnclaimed branch), so it can never answer "what
	// does a plan of an adopted estate cost". See AuditCalls for that
	// number, kept under its own name for exactly this reason: an earlier
	// version of this field (#1053, before this doc comment) sourced
	// PlanCalls from that CollectUnclaimed measurement, and chant-bench
	// went on to publish it as choudoufu's plan cost. It was not a plan.
	PlanCalls *ScalePlanCalls `json:"plan_calls,omitempty"`
	// AuditCalls is live-discover's account-inventory cost - the sweep run
	// with Request.CollectUnclaimed:true, split into the sweep leg and the
	// read pass (#622's question), with the stock oracle's count beside
	// choudoufu's when the same run measured both. This is a REAL cost: it
	// is what `-adoption-only`, an audit, or a rebuild-from-markers pays,
	// every time, on purpose (see site/content/docs/model/plan-cost.md's
	// "When the native leg is narrowed, and when it is not"). It is NOT
	// what an ordinary plan of an already-adopted estate costs - that
	// number is PlanCalls, above - and a reader who wants "the plan's
	// cost" should never reach for this field.
	AuditCalls *ScaleAuditCalls `json:"audit_calls,omitempty"`
	// TotalSeconds is this run's own overall wall-clock duration -
	// LiveCertResult.DurationS for a target=aws record, LastRun.DurationS
	// for target=floci - measured independently of any one stage's own
	// duration_s (Go's time.Since around the whole script, run.go/
	// livecert.go), so a reader can check a record's stages against it
	// rather than trusting either number alone. Absent only when the
	// source row itself never measured a total (a legacy-protocol run, or
	// one recorded before DurationS existed) - never zero.
	TotalSeconds *float64 `json:"total_seconds,omitempty"`
	// UnaccountedSeconds is TotalSeconds minus every stage's own Seconds
	// (wall-clock duration, never OperationSeconds - see ScaleStage's own
	// doc comment) this record carries: time the run spent that no stage
	// claims - setup before the first stage's own gauntlet_stage call, a
	// wait phase between two stages that is not itself a recorded stage
	// (real-AWS's index wait, today), and teardown after the last one.
	// Computed and populated by both Build* functions below whenever
	// TotalSeconds is known, precisely so it can never silently go missing
	// the way this same gap went unrecorded, and unnoticed, in every
	// real-AWS ScaleRecord before this field existed (issue #1051/#1053's
	// own finding: a published `11180.5s (cold_deploy=2023s,
	// migrate=1214s)` whose two named numbers do not add up to its own
	// total, with nothing saying so). TestScaleRecordsAccountForTheirOwnTotal
	// (scaleaccounting_test.go) is the guard that keeps it that way: it
	// reads this file exactly as committed and fails if any record's own
	// arithmetic does not close within its stated tolerance - UNLESS
	// AccountingInconsistent says otherwise (below).
	//
	// A negative UnaccountedSeconds means the stages overcount the total,
	// which is impossible for sequential slices of one run and is exactly
	// what issue #1069 found in the terralith-scale/floci/scale-1 row: 329s
	// of stage seconds against a 231.7s total. The cause is known, and it
	// was not the crossing script's timers: that run aborted at greenfield,
	// and RunEstates used to merge a run's per-stage seconds into the
	// previous row's map, so the nine stages this run never reached kept an
	// older run's duration_s (98s) while the total came from this run's own
	// wall clock. Fixed in run.go - LastRun.Seconds now holds only the
	// stages a run itself emitted a duration_s for - so a record built after
	// that fix cannot take this shape again. It remains a real defect to
	// name, not something this schema should paper over by widening the
	// tolerance everywhere.
	UnaccountedSeconds *float64 `json:"unaccounted_seconds,omitempty"`
	// UnaccountedDetail is free text naming what UnaccountedSeconds is
	// believed to cover, when a record's own investigation identified
	// something more specific than "the rest" (e.g. "post-test_plan
	// teardown; this run predates index-wait instrumentation"). Never a
	// guess dressed as a measurement - absent means exactly what
	// UnaccountedSeconds already says on its own: an unattributed
	// remainder, named as a number but not further explained.
	UnaccountedDetail string `json:"unaccounted_detail,omitempty"`
	// AccountingInconsistent marks a record whose own stage seconds are
	// KNOWN to overcount its total - UnaccountedSeconds negative by a
	// margin the guard would otherwise refuse, not a defect the guard
	// failed to catch. It is never set by any Build* function: the only
	// way a record carries it is a maintainer's explicit, reviewed
	// decision (via `gauntlet scale-patch-seconds -accounting-inconsistent
	// -note "..."`) that the overcounting is understood well enough to
	// name and track, with UnaccountedDetail required (ValidateScaleRecord
	// enforces this) to say what is inconsistent and which issue owns it
	// (issue #1069's own row: "floci scale 1's fourteen stage timers sum
	// to more than the run's own total ... tracked at #1069").
	//
	// TestScaleRecordsAccountForTheirOwnTotal is the only reader that
	// treats this flag as meaningful: a negative remainder beyond
	// scaleAccountingTolerance still fails the guard UNLESS this is true
	// AND UnaccountedDetail is non-empty and names an issue - so a record
	// can never opt out of the guard by leaving the detail blank, and an
	// ordinary bug (this flag false, as every other record's is) is still
	// caught exactly as before. The guard is widened by name, never by a
	// wider tolerance.
	AccountingInconsistent bool `json:"accounting_inconsistent,omitempty"`
	// Source names where this record's numbers came from - a git revision
	// and path, or "gauntlet live-cert" for a record the runner just
	// produced live - so a reader can always trace a number back to
	// something they could re-open themselves, the same discipline this
	// repository already applies to every other measured claim.
	Source string `json:"source"`
	// CallCountsSource is where PlanCalls and AuditCalls came from, kept
	// apart from Source because they come from somewhere else entirely.
	// Source names the run this row describes - a live/gauntlet.json row at
	// a revision. That artifact has never held a call count and never will;
	// the counts come from the slicing bench, via `gauntlet
	// scale-import-slice`, often at a different commit.
	//
	// It exists because folding the two into one sentence lost the second
	// one. `scale-backfill` rebuilds a row from live/gauntlet.json and
	// overwrites Source with its own; once UpsertScaleRecordKeepingCallCounts
	// started carrying the NUMBERS through that rebuild, the numbers survived
	// while the sentence saying where they came from did not - leaving a row
	// asserting 186 calls whose stated source was a file that has never
	// contained one. A reader following it would find nothing, which is the
	// precise failure this repository's provenance discipline exists to
	// prevent.
	CallCountsSource string `json:"call_counts_source,omitempty"`
}

// unaccountedSeconds returns total minus every stage's own known Seconds
// (wall duration) in stages - OperationSeconds is never summed here, only
// Seconds, because OperationSeconds is deliberately not additive against a
// run's own total (see ScaleStage's own doc comment). Always returns a
// non-nil pointer: once a caller has a total to reconcile against, "no
// remainder" (0.0) and "did not check" must never look the same, so the
// zero case is written out rather than left absent.
func unaccountedSeconds(total float64, stages map[string]ScaleStage) *float64 {
	sum := 0.0
	for _, st := range stages {
		if st.Seconds != nil {
			sum += *st.Seconds
		}
	}
	// roundSeconds (run.go): total and every stage Seconds already carry at
	// most one decimal place, but a plain float64 subtraction between them
	// can still land on something like 0.6999999999999886 - round the
	// result the same way every other duration in this schema already is,
	// rather than publishing that noise as if it meant something.
	u := roundSeconds(total - sum)
	return &u
}

// ScaleResources is the estate's own object count, split the way
// terralith-scale.sh's own EXPECTED/VERIFIED formula and every migrate
// detail already do: Total is every resource instance the estate declares,
// Taggable is the subset live-import can stamp with an identity marker, and
// Skipped is the rest (untaggable - identity composes from an already-
// stamped parent, per migrate's own detail line). Skipped is always
// Total-Taggable when both are present, but is carried as its own field
// because it is what migrate's detail names directly, and re-deriving it
// from a possibly-partial Total/Taggable pair would be exactly the kind of
// guess this schema refuses to make elsewhere.
type ScaleResources struct {
	Total    int `json:"total"`
	Taggable int `json:"taggable,omitempty"`
	Skipped  int `json:"skipped,omitempty"`
}

// ScaleStage is one stage's verdict and, where the run's own detail
// recorded them, its numbers. Detail keeps the ORIGINAL sentence
// (human-readable, and the one place a number this parser could not
// recognize is still visible) so nothing this record's parser dropped is
// actually lost.
type ScaleStage struct {
	Verdict string `json:"verdict"`
	// Seconds is THIS STAGE'S OWN wall-clock duration - the runner's own
	// duration_s reading (LiveCertResult.Seconds for target=aws,
	// LastRun.Seconds for target=floci), the same quantity
	// ScaleRecord.TotalSeconds/UnaccountedSeconds sum against. It is never
	// the inner operation's own reported timing (OperationSeconds, below):
	// conflating the two - a stage's "seconds" silently meaning whatever a
	// detail sentence happened to report, e.g. "3705 resources ... in
	// 2023s" for cold_deploy - is the exact defect issue #1051/#1053's
	// wall-time-accounting unit found (a published 11180.5s total whose
	// named per-stage seconds summed to 3,237, with nothing saying the
	// other two hours were missing). Absent when the source row never
	// measured this stage's own duration_s at all - see LiveCertResult.
	// Seconds's own doc comment for the historical rows this is true of.
	Seconds *float64 `json:"seconds,omitempty"`
	// OperationSeconds is the inner operation's own reported time, when the
	// stage's detail sentence names one directly - e.g. cold_deploy's
	// "3705 resources from stock terraform ... in 2023s" (the stock apply
	// itself; the stage's own Seconds, when known, additionally includes
	// terralith-gen/init overhead the apply's own timer excludes), or
	// migrate's "... in 1214s" (the approve step alone). A useful,
	// self-describing number in its own right - "3,705 resources applied
	// in 2,023 seconds" reads fine on its own - but NOT additive with a
	// sibling stage's OperationSeconds, and NOT what TotalSeconds/
	// UnaccountedSeconds reconcile against: only Seconds is.
	OperationSeconds *float64 `json:"operation_seconds,omitempty"`
	Throttle         *int     `json:"throttle,omitempty"`
	Retry            *int     `json:"retry,omitempty"`
	Detail           string   `json:"detail,omitempty"`
}

// ScalePlanCalls is an ORDINARY PLAN's own provider-mediated call count -
// never the account-inventory sweep (see AuditCalls, and this field's own
// doc comment on ScaleRecord.PlanCalls for why the two must never be
// confused again). Cold is the first CLI `tofu plan` taken against a
// freshly migrated estate, with stock's own plan of the identical,
// unmigrated state beside it as the oracle (what this estate would cost to
// plan if nothing had ever adopted it). Warm is a second, back-to-back CLI
// plan against the same estate with nothing changed in between -
// internal/live/discovery/slicing_bench_test.go's own bench takes stock's
// plan exactly once, before migrate, and never repeats it, so Warm.Stock is
// always absent, not zero. A Cold/Warm pair that reads byte-identical
// (same Choudoufu count) is itself a finding worth stating - the cache
// costs the second plan nothing extra - not a defect in the harness.
// terralith-scale.sh's own real-AWS analyze_api_calls takes only one plan
// (the first one after migrate, #1051/chant-bench#33's own
// plan_calls_choudoufu=/plan_calls_stock= tokens), so a target=aws record's
// PlanCalls always has Cold and never Warm.
type ScalePlanCalls struct {
	Cold *ScaleCallPair `json:"cold,omitempty"`
	Warm *ScaleCallPair `json:"warm,omitempty"`
}

// ScaleAuditCalls is live-discover's account-inventory cost, split the way
// internal/live/discovery/slicing_bench_test.go's legSplit measures it on
// the emulator, with Request.CollectUnclaimed forced true: Sweep is the
// O(types) leg (the tagging sweep's one estate-filtered call plus whatever
// native per-type listing it could not reach), ReadPass is the ownership
// read pass over what the sweep found, and Total is the audit's whole
// provider-mediated call count. Any of the three may be present without the
// others - a run instrumented only for a total call count has no leg split
// to report at all. This is NOT a plan's cost (see ScalePlanCalls and
// ScaleRecord.PlanCalls's own doc comments) - CollectUnclaimed:true makes
// nativesweep.go return the full admission table unconditionally, before it
// even consults the record store, so this number is constant regardless of
// how warm the cache is and cannot be read as "what a plan costs" at any
// scale.
type ScaleAuditCalls struct {
	Sweep    *ScaleCallPair `json:"sweep,omitempty"`
	ReadPass *ScaleCallPair `json:"read_pass,omitempty"`
	Total    *ScaleCallPair `json:"total,omitempty"`
}

// ScaleCallPair is one leg's call count for choudoufu, with stock's own
// count for the SAME leg beside it when the same run measured both sides -
// Stock absent means only choudoufu's side was instrumented, not that stock
// made zero calls.
type ScaleCallPair struct {
	Choudoufu int  `json:"choudoufu"`
	Stock     *int `json:"stock,omitempty"`
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

// validScaleTargets mirrors the two values LiveCertResult.Target already
// permits (floci, aws) - a ScaleRecord never invents a third.
var validScaleTargets = map[string]bool{"floci": true, "aws": true}

// ValidateScaleRecord reports whether r has the shape ScaleRecordsPath
// promises: every REQUIRED field (Schema, Estate, Target, Commit, Source)
// present and non-zero, Target one of the two values LiveCertResult itself
// permits, and every stage's Verdict one of the three the gauntlet protocol
// defines (VerdictPass/VerdictFail/VerdictNotRun) - the same enum
// gauntlet_stage itself refuses to emit outside of (live/e2e/lib/gauntlet.sh).
// A record missing any of this is not a partial measurement, it is not a
// ScaleRecord at all, and callers (the runner, scale-backfill, and
// TestScaleRecordSchema below) treat it exactly that way: refuse to write
// it, rather than commit a row a later reader cannot trust to even parse.
func ValidateScaleRecord(r ScaleRecord) error {
	var missing []string
	if r.Schema == 0 {
		missing = append(missing, "schema")
	}
	if r.Estate == "" {
		missing = append(missing, "estate")
	}
	if r.Target == "" {
		missing = append(missing, "target")
	}
	if r.Commit == "" {
		missing = append(missing, "commit")
	}
	if r.Source == "" {
		missing = append(missing, "source")
	}
	if len(missing) > 0 {
		return fmt.Errorf("scale record for estate=%q target=%q scale=%d is missing required field(s): %s",
			r.Estate, r.Target, r.Scale, strings.Join(missing, ", "))
	}
	if !validScaleTargets[r.Target] {
		return fmt.Errorf("scale record for estate=%q: target must be \"floci\" or \"aws\", got %q", r.Estate, r.Target)
	}
	for id, st := range r.Stages {
		switch st.Verdict {
		case VerdictPass, VerdictFail, VerdictNotRun:
		default:
			return fmt.Errorf("scale record for estate=%q: stage %q carries verdict %q, want one of pass/fail/not_run", r.Estate, id, st.Verdict)
		}
	}
	if r.AccountingInconsistent {
		if strings.TrimSpace(r.UnaccountedDetail) == "" {
			return fmt.Errorf("scale record for estate=%q target=%q scale=%d: accounting_inconsistent is true but unaccounted_detail is empty - see ScaleRecord.AccountingInconsistent's own doc comment, this must say what is inconsistent and which issue tracks it", r.Estate, r.Target, r.Scale)
		}
		if !issueRefRe.MatchString(r.UnaccountedDetail) {
			return fmt.Errorf("scale record for estate=%q target=%q scale=%d: accounting_inconsistent is true but unaccounted_detail %q names no issue (want a \"#123\" reference) - a known inconsistency must be tracked, not just asserted", r.Estate, r.Target, r.Scale, r.UnaccountedDetail)
		}
	}
	return nil
}

// issueRefRe matches an issue reference like "#1069" inside free text -
// ValidateScaleRecord's own proof that AccountingInconsistent's required
// UnaccountedDetail names something a reader can go open, not just an
// adjective ("known", "expected") asserting the gap away.
var issueRefRe = regexp.MustCompile(`#\d+`)

// ---------------------------------------------------------------------------
// Parsing: turning an existing detail sentence into structured fields
// ---------------------------------------------------------------------------

// Token patterns (issue #1051's own addition to terralith-scale.sh):
// `key=value` pairs appended to a stage's detail, read in preference to the
// prose regexes below whenever present. `\S+` rather than `\d+` for the
// value: a token-bearing detail is trusted to have been written by this
// repository's own code, so a malformed token is a bug to surface (the
// int/float parse below fails loudly), not a shape to tolerate silently.
var (
	tokenRe = func(key string) *regexp.Regexp {
		return regexp.MustCompile(`\b` + regexp.QuoteMeta(key) + `=(\S+)`)
	}
	tokenResources = tokenRe("resources")
	tokenTaggable  = tokenRe("taggable")
	tokenSkipped   = tokenRe("skipped")
	tokenSeconds   = tokenRe("seconds")
	tokenThrottle  = tokenRe("throttle")
	tokenRetry     = tokenRe("retry")
	tokenObjects   = tokenRe("objects")
	tokenIndexLag  = tokenRe("index_lag_s")
	// tokenPlanCallsChoudoufu/tokenPlanCallsStock (issue #1053, this file's
	// real-AWS half of #1051/INTENTIUS/chant-bench#33): terralith-scale.sh's
	// analyze_api_calls, real-AWS only, computes an exact provider-mediated
	// request TOTAL for one plan - no sweep/read-pass leg split, unlike the
	// emulator-side slicing bench (scaleslice.go), because the shell harness
	// never separates the two (see ScalePlanCalls's own doc comment: "a run
	// instrumented only for a total call count ... has no leg split to
	// report at all"). Both tokens ride on test_plan's own detail, choudoufu's
	// from the stage-gating plan's own debug log and stock's from 2d's
	// pre-migrate instrumented plan on the SAME estate - see
	// terralith-scale.sh's own comments at STOCK_PLAN_CALLS/CHOUDOUFU_PLAN_CALLS.
	tokenPlanCallsChoudoufu = tokenRe("plan_calls_choudoufu")
	tokenPlanCallsStock     = tokenRe("plan_calls_stock")
)

// Prose fallback patterns: the exact sentence shapes
// live/live-cert/terralith-scale.sh's gauntlet_stage calls have used since
// issue #567, unchanged by #1051's token addition (see this file's own
// package comment) - every row recorded before that addition has ONLY
// these to parse.
var (
	reColdDeployProse = regexp.MustCompile(`^(\d+) resources from stock \S+ against \w+ at scale=(\d+) in (\d+)s.*?(\d+) throttle/(\d+) retry`)
	reMigrateProse    = regexp.MustCompile(`^(\d+) of (\d+) verified, \d+ stamped, (\d+) skipped, in (\d+)s.*?(\d+) throttle/(\d+) retry`)
	reTestPlanProse   = regexp.MustCompile(`in (\d+)s;.*?debug log \d+ bytes, (\d+) throttling-error line\(s\), (\d+) retry line\(s\)`)
	reTestApplyProse  = regexp.MustCompile(`object count unchanged at (\d+)`)
	// The floci crossing script (live/e2e/terralith-scale/run.sh) speaks a
	// completely different sentence for cold_deploy/migrate - no throttle
	// instrumentation at all (floci never throttles), so only the counts
	// these two patterns name are ever recoverable for a target=floci row.
	reColdDeployFloci = regexp.MustCompile(`applied (\d+) resources at scale=(\d+)`)
	reMigrateFloci    = regexp.MustCompile(`ratified (\d+) of (\d+) instances as eligible`)
)

func mustAtoi(s string) int {
	n, err := strconv.Atoi(s)
	if err != nil {
		// Every caller only ever passes a regex-captured all-digit group;
		// an error here means a pattern above stopped matching only
		// digits, which is a bug in this file, not bad input.
		panic(fmt.Sprintf("scalerecord: %q is not an integer: %v", s, err))
	}
	return n
}

func mustAtof(s string) float64 {
	f, err := strconv.ParseFloat(s, 64)
	if err != nil {
		panic(fmt.Sprintf("scalerecord: %q is not a number: %v", s, err))
	}
	return f
}

func intPtr(n int) *int           { return &n }
func floatPtr(f float64) *float64 { return &f }

// parseColdDeployDetail extracts resources/scale/seconds/throttle/retry from
// a cold_deploy stage's detail text - token-first, then the real-AWS prose
// shape, then the floci crossing-script's own (throttle/retry-less) shape.
// Every return is nil/zero when NONE of the three recognize the text -
// never a guess.
func parseColdDeployDetail(detail string) (resources, scale *int, seconds *float64, throttle, retry *int) {
	if m := tokenResources.FindStringSubmatch(detail); m != nil {
		resources = intPtr(mustAtoi(m[1]))
	}
	if m := tokenSeconds.FindStringSubmatch(detail); m != nil {
		seconds = floatPtr(mustAtof(m[1]))
	}
	if m := tokenThrottle.FindStringSubmatch(detail); m != nil {
		throttle = intPtr(mustAtoi(m[1]))
	}
	if m := tokenRetry.FindStringSubmatch(detail); m != nil {
		retry = intPtr(mustAtoi(m[1]))
	}
	// scale=N appears in the prose itself on every shape this repository has
	// ever emitted (there is no token for it - scale is unambiguous in the
	// sentence and #1051 did not duplicate it as a token), so it is always
	// read from the text, not gated behind the token-vs-prose branch below.
	if m := regexp.MustCompile(`\bscale=(\d+)\b`).FindStringSubmatch(detail); m != nil {
		scale = intPtr(mustAtoi(m[1]))
	}
	if resources != nil {
		return resources, scale, seconds, throttle, retry
	}
	if m := reColdDeployProse.FindStringSubmatch(detail); m != nil {
		resources = intPtr(mustAtoi(m[1]))
		if scale == nil {
			scale = intPtr(mustAtoi(m[2]))
		}
		if seconds == nil {
			seconds = floatPtr(mustAtof(m[3]))
		}
		if throttle == nil {
			throttle = intPtr(mustAtoi(m[4]))
		}
		if retry == nil {
			retry = intPtr(mustAtoi(m[5]))
		}
		return resources, scale, seconds, throttle, retry
	}
	if m := reColdDeployFloci.FindStringSubmatch(detail); m != nil {
		resources = intPtr(mustAtoi(m[1]))
		if scale == nil {
			scale = intPtr(mustAtoi(m[2]))
		}
		return resources, scale, seconds, throttle, retry
	}
	return nil, scale, seconds, throttle, retry
}

// parseMigrateDetail extracts taggable/skipped/seconds/throttle/retry from a
// migrate stage's detail text, same token-first/prose-fallback discipline as
// parseColdDeployDetail.
func parseMigrateDetail(detail string) (taggable, skipped *int, seconds *float64, throttle, retry *int) {
	if m := tokenTaggable.FindStringSubmatch(detail); m != nil {
		taggable = intPtr(mustAtoi(m[1]))
	}
	if m := tokenSkipped.FindStringSubmatch(detail); m != nil {
		skipped = intPtr(mustAtoi(m[1]))
	}
	if m := tokenSeconds.FindStringSubmatch(detail); m != nil {
		seconds = floatPtr(mustAtof(m[1]))
	}
	if m := tokenThrottle.FindStringSubmatch(detail); m != nil {
		throttle = intPtr(mustAtoi(m[1]))
	}
	if m := tokenRetry.FindStringSubmatch(detail); m != nil {
		retry = intPtr(mustAtoi(m[1]))
	}
	if taggable != nil {
		return taggable, skipped, seconds, throttle, retry
	}
	if m := reMigrateProse.FindStringSubmatch(detail); m != nil {
		taggable = intPtr(mustAtoi(m[1]))
		if skipped == nil {
			skipped = intPtr(mustAtoi(m[3]))
		}
		if seconds == nil {
			seconds = floatPtr(mustAtof(m[4]))
		}
		if throttle == nil {
			throttle = intPtr(mustAtoi(m[5]))
		}
		if retry == nil {
			retry = intPtr(mustAtoi(m[6]))
		}
		return taggable, skipped, seconds, throttle, retry
	}
	if m := reMigrateFloci.FindStringSubmatch(detail); m != nil {
		taggable = intPtr(mustAtoi(m[1]))
		return taggable, skipped, seconds, throttle, retry
	}
	return nil, skipped, seconds, throttle, retry
}

// parseTestPlanDetail extracts seconds/throttle/retry/index_lag_s from a
// test_plan stage's detail text - a PASS row's sentence ("plan is empty in
// Ns; ...") and a FAIL row's (TP_FAIL's own text, which may carry none of
// these if the plan exited before the throttle/pagination read at 4b ever
// ran) both flow through the same patterns, so a refused plan still yields
// whatever it measured before refusing (the same discipline
// terralith-scale.sh's own comment on TP_FAIL/#588 already applies at the
// shell level).
func parseTestPlanDetail(detail string) (seconds *float64, throttle, retry, indexLag *int) {
	if m := tokenSeconds.FindStringSubmatch(detail); m != nil {
		seconds = floatPtr(mustAtof(m[1]))
	}
	if m := tokenThrottle.FindStringSubmatch(detail); m != nil {
		throttle = intPtr(mustAtoi(m[1]))
	}
	if m := tokenRetry.FindStringSubmatch(detail); m != nil {
		retry = intPtr(mustAtoi(m[1]))
	}
	if m := tokenIndexLag.FindStringSubmatch(detail); m != nil {
		indexLag = intPtr(mustAtoi(m[1]))
	}
	if seconds == nil || throttle == nil || retry == nil {
		if m := reTestPlanProse.FindStringSubmatch(detail); m != nil {
			if seconds == nil {
				seconds = floatPtr(mustAtof(m[1]))
			}
			if throttle == nil {
				throttle = intPtr(mustAtoi(m[2]))
			}
			if retry == nil {
				retry = intPtr(mustAtoi(m[3]))
			}
		}
	}
	return seconds, throttle, retry, indexLag
}

// parseTestApplyDetail extracts the tofu-cert-run-tagged object count from a
// test_apply stage's detail - kept on the ScaleStage's own Detail text only
// (there is no dedicated field for it: see ScaleResources's own doc comment
// for why this count is a different universe than Resources.Taggable).
// Returned so a future field can use it without re-parsing; unused by
// BuildScaleRecordFromLiveCert today beyond proving the pattern matches.
func parseTestApplyDetail(detail string) *int {
	if m := tokenObjects.FindStringSubmatch(detail); m != nil {
		return intPtr(mustAtoi(m[1]))
	}
	if m := reTestApplyProse.FindStringSubmatch(detail); m != nil {
		return intPtr(mustAtoi(m[1]))
	}
	return nil
}

// parsePlanCallsDetail extracts the plan's own API-call total from a
// test_plan stage detail's plan_calls_choudoufu=/plan_calls_stock= tokens
// (issue #1053) - terralith-scale.sh's own analyze_api_calls times the
// FIRST plan taken after migrate ("choudoufu-first" in the script's own
// label), which is a cold plan, never a second, warm one - so the pair this
// function reads always becomes PlanCalls.Cold; Warm stays nil for every
// target=aws record because the shell harness never takes it. Returns nil,
// not a zero-valued ScalePlanCalls, when the choudoufu token is absent -
// there is no prose fallback for this pair (unlike every other
// parseXDetail function here): no live_cert/estates row predates the
// tokens with an equivalent sentence to fall back to, because
// analyze_api_calls' own total was never folded into a sentence at all
// before this issue. A ScaleCallPair's own Choudoufu field is a plain int,
// never a pointer (see its doc comment), so a present pair always means
// choudoufu's side was actually measured; stock's token is read only when
// choudoufu's is, for the same reason.
func parsePlanCallsDetail(detail string) *ScalePlanCalls {
	m := tokenPlanCallsChoudoufu.FindStringSubmatch(detail)
	if m == nil {
		return nil
	}
	cold := &ScaleCallPair{Choudoufu: mustAtoi(m[1])}
	if ms := tokenPlanCallsStock.FindStringSubmatch(detail); ms != nil {
		stock := mustAtoi(ms[1])
		cold.Stock = &stock
	}
	return &ScalePlanCalls{Cold: cold}
}

// ---------------------------------------------------------------------------
// Building a record from an existing artifact row
// ---------------------------------------------------------------------------

// BuildScaleRecordFromLiveCert converts one LiveCertResult
// (live/gauntlet.json's own live_cert array) into a ScaleRecord. source
// names where r itself came from (a git revision, typically) for the
// resulting record's own Source field.
func BuildScaleRecordFromLiveCert(r LiveCertResult, source string) ScaleRecord {
	rec := ScaleRecord{
		Schema: ScaleRecordSchema,
		Estate: r.Estate,
		Target: r.Target,
		Region: r.Region,
		Commit: r.Commit,
		Date:   r.Date,
		Source: source,
	}
	if len(r.Stages) > 0 {
		rec.Stages = map[string]ScaleStage{}
	}
	for id, verdict := range r.Stages {
		detail := r.Detail[id]
		if strings.Contains(detail, "held: true") {
			rec.Held = true
		}
		st := ScaleStage{Verdict: verdict, Detail: detail}
		// Seconds - this stage's own wall-clock duration - comes ONLY from
		// the runner's own duration_s reading (r.Seconds), never from a
		// detail sentence: see ScaleStage.Seconds's own doc comment for why
		// conflating the two was the defect this file's package comment (and
		// issue #1051/#1053's wall-time-accounting unit) exists to fix.
		// Absent when r.Seconds carries nothing for this id - a run recorded
		// before LiveCertResult.Seconds existed, most historical rows today.
		if secs, ok := r.Seconds[id]; ok {
			st.Seconds = floatPtr(secs)
		}
		switch id {
		case "cold_deploy":
			resources, scale, opSeconds, throttle, retry := parseColdDeployDetail(detail)
			if resources != nil {
				rec.Resources = mergeResourcesTotal(rec.Resources, *resources)
			}
			if scale != nil {
				rec.Scale = *scale
			}
			st.OperationSeconds, st.Throttle, st.Retry = opSeconds, throttle, retry
		case "migrate":
			taggable, skipped, opSeconds, throttle, retry := parseMigrateDetail(detail)
			if taggable != nil {
				rec.Resources = mergeResourcesTaggable(rec.Resources, *taggable)
			}
			if skipped != nil {
				rec.Resources = mergeResourcesSkipped(rec.Resources, *skipped)
			}
			st.OperationSeconds, st.Throttle, st.Retry = opSeconds, throttle, retry
		case "test_plan":
			opSeconds, throttle, retry, indexLag := parseTestPlanDetail(detail)
			st.OperationSeconds, st.Throttle, st.Retry = opSeconds, throttle, retry
			if indexLag != nil {
				rec.IndexLagS = indexLag
			}
			if pc := parsePlanCallsDetail(detail); pc != nil {
				rec.PlanCalls = pc
			}
		case "test_apply":
			// Nothing promoted to a ScaleRecord field - see
			// parseTestApplyDetail's own doc comment.
		}
		rec.Stages[id] = st
	}
	if r.DurationS > 0 {
		total := r.DurationS
		rec.TotalSeconds = &total
		rec.UnaccountedSeconds = unaccountedSeconds(total, rec.Stages)
	}
	return rec
}

// BuildScaleRecordFromEstate converts one EstateResult
// (live/gauntlet.json's own `estates` array) into a ScaleRecord, when its
// name and detail text are recognizably a scale-measured run - ok is false
// otherwise (an estate this schema has no scale concept for, e.g. any
// module example that is not terralith-gen's own terralith), and no record
// is fabricated in that case.
func BuildScaleRecordFromEstate(e EstateResult, source string) (ScaleRecord, bool) {
	if e.LastRun == nil {
		return ScaleRecord{}, false
	}
	coldDetail := ""
	if e.LastRun.Detail != nil {
		coldDetail = e.LastRun.Detail["cold_deploy"]
	}
	resources, scale, _, _, _ := parseColdDeployDetail(coldDetail)
	if resources == nil {
		// This estate's cold_deploy sentence names no resource count at
		// all (every module-example estate) - not a scale-measured
		// estate, honestly reported as "nothing to build" rather than an
		// empty/zero-valued record.
		return ScaleRecord{}, false
	}
	rec := ScaleRecord{
		Schema:   ScaleRecordSchema,
		Estate:   e.Name,
		Target:   "floci",
		Scale:    0,
		Commit:   e.LastRun.Commit,
		Date:     e.LastRun.Date,
		Emulator: e.LastRun.Emulator,
		Oracle:   e.LastRun.Oracle,
		Source:   source,
	}
	if scale != nil {
		rec.Scale = *scale
	}
	rec.Resources = &ScaleResources{Total: *resources}
	if migrateDetail, ok := e.LastRun.Detail["migrate"]; ok {
		taggable, _, _, _, _ := parseMigrateDetail(migrateDetail)
		if taggable != nil {
			rec.Resources.Taggable = *taggable
			rec.Resources.Skipped = *resources - *taggable
		}
	}
	// Only the stages THIS run measured belong in a scale record, and
	// LastRun.Seconds is the witness for which those are (issue #1069).
	//
	// EstateResult.Stages is merged across runs by RunEstates (run.go), so
	// a stage this run never reached keeps an older run's verdict. On the
	// board that is right: a stale verdict is still the best thing known
	// about that stage. In a record keyed by (estate, target, SCALE) it is
	// not, because a verdict measured at one size says nothing about
	// another - and the merge is silent, so the record cannot tell the two
	// apart by inspection.
	//
	// The run that forced this was terralith-scale at SCALE=136, 10,069
	// resources: it aborted at test_plan having spoken three stages, into a
	// row carrying eleven more from a scale-1 run eleven days older. Among
	// them was test_apply, which chant-bench scores - so the published row
	// would have claimed choudoufu's apply was verified at ten thousand
	// resources when it was verified at seventy-nine.
	//
	// Seconds became a usable witness only when #1069's fix stopped it
	// being merged too; it now holds exactly the stages this run emitted a
	// duration_s for. A row that recorded no per-stage seconds at all has
	// no witness, and there every stage is kept rather than the record
	// being silently emptied - an older row with nothing to go on is a
	// weaker record, not a false one.
	measured := e.LastRun.Seconds
	for id, verdict := range e.Stages {
		if len(measured) > 0 {
			if _, ok := measured[id]; !ok {
				continue
			}
		}
		st := ScaleStage{Verdict: verdict}
		if e.LastRun.Detail != nil {
			st.Detail = e.LastRun.Detail[id]
		}
		if secs, ok := measured[id]; ok {
			st.Seconds = floatPtr(secs)
		}
		if rec.Stages == nil {
			rec.Stages = map[string]ScaleStage{}
		}
		rec.Stages[id] = st
	}
	if e.LastRun.DurationS > 0 {
		total := e.LastRun.DurationS
		rec.TotalSeconds = &total
		rec.UnaccountedSeconds = unaccountedSeconds(total, rec.Stages)
	}
	return rec, true
}

func mergeResourcesTotal(r *ScaleResources, total int) *ScaleResources {
	if r == nil {
		return &ScaleResources{Total: total}
	}
	r.Total = total
	return r
}

func mergeResourcesTaggable(r *ScaleResources, taggable int) *ScaleResources {
	if r == nil {
		return &ScaleResources{Taggable: taggable}
	}
	r.Taggable = taggable
	return r
}

func mergeResourcesSkipped(r *ScaleResources, skipped int) *ScaleResources {
	if r == nil {
		return &ScaleResources{Skipped: skipped}
	}
	r.Skipped = skipped
	return r
}

// ---------------------------------------------------------------------------
// Loading, upserting and saving the companion artifact
// ---------------------------------------------------------------------------

// LoadScaleArtifact reads live/gauntlet-scale.json, or an empty, correctly-
// versioned ScaleArtifact if the file does not exist yet (the first record
// ever written creates it).
func LoadScaleArtifact(root string) (*ScaleArtifact, error) {
	path := filepath.Join(root, ScaleRecordsPath)
	b, err := os.ReadFile(path) //nolint:gosec // a fixed, repo-relative path
	if err != nil {
		if os.IsNotExist(err) {
			return &ScaleArtifact{Schema: ScaleRecordSchema}, nil
		}
		return nil, err
	}
	var a ScaleArtifact
	if err := json.Unmarshal(b, &a); err != nil {
		return nil, fmt.Errorf("parsing %s: %w", path, err)
	}
	return &a, nil
}

// SaveScaleArtifact writes a to live/gauntlet-scale.json, sorted by
// (Estate, Target, Scale) so a diff shows only what actually changed.
// a.Emulator is stamped fresh from live/floci-image on every call - see its
// own doc comment for why this, like Artifact.Emulator, is always the
// CURRENT pin rather than whatever the caller happened to leave it at.
func SaveScaleArtifact(root string, a *ScaleArtifact) error {
	a.Emulator = emulatorPin(root)
	sortScaleRecords(a.Records)
	b, err := json.MarshalIndent(a, "", "  ")
	if err != nil {
		return err
	}
	b = append(b, '\n')
	return os.WriteFile(filepath.Join(root, ScaleRecordsPath), b, 0o644) //nolint:gosec // a committed artifact, not a secret
}

func sortScaleRecords(recs []ScaleRecord) {
	for i := 1; i < len(recs); i++ {
		for j := i; j > 0 && scaleRecordLess(recs[j], recs[j-1]); j-- {
			recs[j], recs[j-1] = recs[j-1], recs[j]
		}
	}
}

func scaleRecordLess(a, b ScaleRecord) bool {
	if a.Estate != b.Estate {
		return a.Estate < b.Estate
	}
	if a.Target != b.Target {
		return a.Target < b.Target
	}
	return a.Scale < b.Scale
}

// UpsertScaleRecord replaces a.Records' entry sharing rec's (Estate, Target,
// Scale) identity, or appends rec if none does - the row-per-size behavior
// LiveCertResult's own row-per-estate SetLiveCertResult deliberately does
// NOT have (see ScaleRecord's own doc comment).
func (a *ScaleArtifact) UpsertScaleRecord(rec ScaleRecord) {
	for i := range a.Records {
		if a.Records[i].Estate == rec.Estate && a.Records[i].Target == rec.Target && a.Records[i].Scale == rec.Scale {
			a.Records[i] = rec
			return
		}
	}
	a.Records = append(a.Records, rec)
}

// UpsertScaleRecordKeepingCallCounts is UpsertScaleRecord for a caller whose
// source cannot measure PlanCalls or AuditCalls at all - which is every
// caller that rebuilds a record from live/gauntlet.json, because that
// artifact has never held a call count. The rebuilt record wins everywhere
// it has a value; the two call-count fields are filled from the existing
// row when the rebuild has none, and overridden when it has one.
//
// Without this, `gauntlet scale-backfill` silently deleted numbers only
// `gauntlet scale-import-slice` can produce. It did: the terralith-scale
// floci/scale=128 record had cold 21,423 against stock's 17,422 imported,
// and a backfill run seconds later for an unrelated reason left it with no
// call counts and no complaint. A record without plan_calls is a legitimate
// shape, so nothing downstream could have caught it either - the publishing
// side would have gone on validating and simply stopped printing the number.
//
// scaleslice.go already reasoned about this hazard from the other side,
// which is why scale-import-slice merges into an existing row rather than
// replacing it. This is the same care owed in the other direction.
func (a *ScaleArtifact) UpsertScaleRecordKeepingCallCounts(rec ScaleRecord) {
	for i := range a.Records {
		if a.Records[i].Estate != rec.Estate || a.Records[i].Target != rec.Target || a.Records[i].Scale != rec.Scale {
			continue
		}
		if rec.PlanCalls == nil {
			rec.PlanCalls = a.Records[i].PlanCalls
		}
		if rec.AuditCalls == nil {
			rec.AuditCalls = a.Records[i].AuditCalls
		}
		// The numbers are worth nothing without the sentence that says
		// where they came from, and the rebuild has just overwritten
		// Source with its own. Carry that sentence too.
		if rec.CallCountsSource == "" {
			rec.CallCountsSource = a.Records[i].CallCountsSource
		}
		break
	}
	a.UpsertScaleRecord(rec)
}

// ---------------------------------------------------------------------------
// cmdScaleBackfill: `gauntlet scale-backfill [rev...]`
// ---------------------------------------------------------------------------

// cmdScaleBackfill is issue #1051's recovery path: live/gauntlet.json's own
// live_cert array keeps only the LATEST run per estate (LiveCertResult is
// keyed by estate alone - SetLiveCertResult, livecert.go), so every earlier
// scale point terralith-scale.sh ever measured survives only in git
// history, as a row a LATER commit went on to overwrite. This walks the
// revisions named on the command line (HEAD, always, plus whichever past
// revisions the caller names - see this worker's own report for exactly
// which ones issue #1051 asks for), reads live/gauntlet.json AS IT EXISTED
// at each one with `git show`, and upserts a ScaleRecord for every
// live_cert row and (where BuildScaleRecordFromEstate recognizes it)
// `estates` row it finds - never by hand, never by re-typing a number out
// of a commit message, only by parsing the SAME committed JSON a reader
// could open themselves at that revision.
//
// A revision this checkout does not have (a shallow clone, a typo) fails
// the whole run rather than silently skipping it - a backfill that quietly
// drops a point is worse than one that refuses to run at all.
func cmdScaleBackfill(root string, args []string) error {
	revs := append([]string{"HEAD"}, args...)

	sa, err := LoadScaleArtifact(root)
	if err != nil {
		return err
	}
	if sa.Schema == 0 {
		sa.Schema = ScaleRecordSchema
	}

	for i, rev := range revs {
		b, err := gitShowFile(root, rev, ArtifactPath)
		if err != nil {
			return fmt.Errorf("scale-backfill: reading %s at %s: %w", ArtifactPath, rev, err)
		}
		var a Artifact
		if err := json.Unmarshal(b, &a); err != nil {
			return fmt.Errorf("scale-backfill: parsing %s at %s: %w", ArtifactPath, rev, err)
		}
		full, err := resolveRev(root, rev)
		if err != nil {
			return err
		}
		source := fmt.Sprintf("git show %s:%s", full, ArtifactPath)

		for _, lc := range a.LiveCert {
			rec := BuildScaleRecordFromLiveCert(lc, source)
			if rec.Scale == 0 && rec.Resources == nil {
				// Not a scale-measured live_cert row (e.g.
				// reference-ec2-vpc, which has no notion of scale) -
				// nothing to add, and nothing wrong either.
				continue
			}
			if err := ValidateScaleRecord(rec); err != nil {
				return fmt.Errorf("scale-backfill: %s: %w", rev, err)
			}
			sa.UpsertScaleRecordKeepingCallCounts(rec)
			fmt.Printf("scale-backfill: %s live_cert estate=%s target=%s scale=%d at %s\n", rev, rec.Estate, rec.Target, rec.Scale, full)
		}

		// The `estates` array, unlike `live_cert`, is not this backfill's
		// reason for walking history: an EstateResult row IS re-measured in
		// place on every `gauntlet run` (Rebuild, artifact.go), so an old
		// revision's copy is just a stale duplicate of a row HEAD's own
		// Artifact.Estates already carries, at whatever scale that estate's
		// crossing script happens to run at - which for terralith-scale has
		// always been scale=1, never the point of interest here. Reading it
		// only at revs[0] (HEAD, always first - see revs above) keeps this
		// loop from having its floci row's Source/Detail overwritten by
		// whichever PAST revision the caller happened to list last, which
		// upsertion-by-(estate,target,scale) would otherwise do silently.
		if i != 0 {
			continue
		}
		for _, e := range a.Estates {
			rec, ok := BuildScaleRecordFromEstate(e, source)
			if !ok {
				continue
			}
			if err := ValidateScaleRecord(rec); err != nil {
				return fmt.Errorf("scale-backfill: %s: %w", rev, err)
			}
			sa.UpsertScaleRecordKeepingCallCounts(rec)
			fmt.Printf("scale-backfill: %s estates estate=%s target=%s scale=%d at %s\n", rev, rec.Estate, rec.Target, rec.Scale, full)
		}
	}

	if err := SaveScaleArtifact(root, sa); err != nil {
		return err
	}
	fmt.Printf("scale-backfill: wrote %s (%d record(s))\n", ScaleRecordsPath, len(sa.Records))
	return nil
}

// resolveRev returns rev's full commit sha, so a ScaleRecord's Source names
// something a reader can `git show` themselves even when the caller passed
// a short or symbolic rev (HEAD, an abbreviated sha).
func resolveRev(root, rev string) (string, error) {
	cmd := exec.Command("git", "rev-parse", rev)
	cmd.Dir = root
	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("resolving revision %q: %w", rev, err)
	}
	return strings.TrimSpace(string(out)), nil
}
