// Copyright (c) The OpenTofu Authors
// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2023 HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package stamp

// The remainder cohort's slice of internal/live/stamp's three pinned test
// collections: which of the cohort's admitted types carry tags, which do
// not, and the caricature schema each one is checked against. Registered by
// init below; see contributing/LIVE-TABLES.md.
var taggableRemainder = []string{
	// Registry-ratified REMAINDER ratification batch (#40, #44, #65):
	// the long tail of services outside every concurrent batch own
	// scope, verified against the pinned v6.58.0 provider Argument
	// Reference for each. See live/e2e/estates/remainder/README.md.
	"aws_appconfig_application",
	"aws_appconfig_deployment_strategy",
	"aws_appconfig_extension",
	"aws_appsync_api",
	"aws_arcregionswitch_plan",
	"aws_bcmdataexports_export",
	"aws_billing_view",
	"aws_ce_anomaly_monitor",
	"aws_ce_anomaly_subscription",
	"aws_ce_cost_category",
	"aws_chatbot_slack_channel_configuration",
	"aws_cleanrooms_collaboration",
	"aws_cleanrooms_configured_table",
	"aws_cleanrooms_membership",
	"aws_cloud9_environment_ec2",
	"aws_cloudtrail",
	"aws_cloudtrail_event_data_store",
	"aws_codegurureviewer_repository_association",
	"aws_cur_report_definition",
	"aws_datapipeline_pipeline",
	"aws_datazone_domain",
	"aws_detective_graph",
	"aws_dlm_lifecycle_policy",
	"aws_dsql_cluster",
	"aws_dx_connection",
	"aws_dx_gateway",
	"aws_dx_lag",
	"aws_dx_private_virtual_interface",
	"aws_dx_public_virtual_interface",
	"aws_dx_transit_virtual_interface",
	"aws_ec2_instance_connect_endpoint",
	"aws_ec2_local_gateway_route_table",
	"aws_ec2_local_gateway_route_table_virtual_interface_group_association",
	"aws_ec2_local_gateway_route_table_vpc_association",
	"aws_ec2_network_insights_access_scope",
	"aws_ec2_network_insights_analysis",
	"aws_ec2_network_insights_path",
	"aws_ec2_traffic_mirror_filter",
	"aws_ec2_traffic_mirror_session",
	"aws_ec2_traffic_mirror_target",
	"aws_ecs_daemon_task_definition",
	"aws_ecs_express_gateway_service",
	"aws_ecs_task_definition",
	"aws_egress_only_internet_gateway",
	"aws_elb",
	"aws_evidently_project",
	"aws_evidently_segment",
	"aws_fis_experiment_template",
	"aws_fms_resource_set",
	"aws_gamelift_alias",
	"aws_gamelift_build",
	"aws_gamelift_fleet",
	"aws_gamelift_script",
	"aws_glue_data_quality_ruleset",
	"aws_glue_schema",
	"aws_glue_workflow",
	"aws_iam_saml_provider",
	"aws_iam_virtual_mfa_device",
	"aws_imagebuilder_component",
	"aws_imagebuilder_container_recipe",
	"aws_imagebuilder_distribution_configuration",
	"aws_imagebuilder_image",
	"aws_imagebuilder_image_pipeline",
	"aws_imagebuilder_image_recipe",
	"aws_imagebuilder_infrastructure_configuration",
	"aws_imagebuilder_lifecycle_policy",
	"aws_imagebuilder_workflow",
	"aws_inspector_assessment_template",
	"aws_internetmonitor_monitor",
	"aws_invoicing_invoice_unit",
	"aws_kinesis_analytics_application",
	"aws_lb_listener_rule",
	"aws_lb_trust_store",
	"aws_m2_application",
	"aws_m2_environment",
	"aws_mailmanager_rule_set",
	"aws_mailmanager_traffic_policy",
	"aws_msk_replicator",
	"aws_msk_vpc_connection",
	"aws_mwaa_environment",
	"aws_notifications_notification_configuration",
	"aws_notificationscontacts_email_contact",
	"aws_oam_link",
	"aws_oam_sink",
	"aws_observabilityadmin_s3_table_integration",
	"aws_observabilityadmin_telemetry_pipeline",
	"aws_odb_cloud_autonomous_vm_cluster",
	"aws_odb_cloud_exadata_infrastructure",
	"aws_odb_cloud_vm_cluster",
	"aws_odb_network",
	"aws_odb_network_peering_connection",
	"aws_paymentcryptography_key",
	"aws_pinpointsmsvoicev2_configuration_set",
	"aws_pinpointsmsvoicev2_opt_out_list",
	"aws_pinpointsmsvoicev2_phone_number",
	"aws_pinpointsmsvoicev2_pool",
	"aws_prometheus_rule_group_namespace",
	"aws_ram_permission",
	"aws_ram_resource_share",
	"aws_rbin_rule",
	"aws_resiliencehub_resiliency_policy",
	"aws_resiliencehubv2_policy",
	"aws_rolesanywhere_profile",
	"aws_rolesanywhere_trust_anchor",
	"aws_s3_directory_bucket",
	"aws_s3control_bucket",
	"aws_s3files_access_point",
	"aws_s3files_file_system",
	"aws_s3tables_table_bucket",
	"aws_s3vectors_index",
	"aws_s3vectors_vector_bucket",
	"aws_schemas_discoverer",
	"aws_securitylake_data_lake",
	"aws_securitylake_subscriber",
	"aws_service_discovery_http_namespace",
	"aws_service_discovery_public_dns_namespace",
	"aws_service_discovery_service",
	"aws_sesv2_configuration_set",
	"aws_sesv2_dedicated_ip_pool",
	"aws_sesv2_email_identity",
	"aws_sesv2_tenant",
	"aws_shield_protection",
	"aws_ssmcontacts_contact",
	"aws_ssmcontacts_rotation",
	"aws_ssmincidents_replication_set",
	"aws_ssmincidents_response_plan",
	"aws_ssmquicksetup_configuration_manager",
	"aws_verifiedaccess_endpoint",
	"aws_verifiedaccess_instance",
	"aws_verifiedaccess_trust_provider",
	"aws_verifiedpermissions_policy_store",
	"aws_vpc_block_public_access_exclusion",
	"aws_vpc_encryption_control",
	"aws_vpc_route_server",
	"aws_vpc_route_server_endpoint",
	"aws_vpc_route_server_peer",
	"aws_vpn_concentrator",
}

var untaggableRemainder = []string{
	// Registry-ratified REMAINDER ratification batch (#40, #44, #65):
	// the long tail of services outside every concurrent batch's own
	// scope, confirmed against each type's Argument Reference at the
	// pinned v6.58.0 tag to carry no top-level tags argument (or, for
	// the two account-level singletons aws_securityhub_account and
	// aws_securityhub_organization_configuration, no tags argument at
	// all since each imports by the bare AWS account id). See
	// live/e2e/estates/remainder/README.md, "Untaggable types".
	"aws_appconfig_extension_association",
	"aws_appsync_api_cache",
	"aws_appsync_domain_name_api_association",
	"aws_arczonalshift_autoshift_observer_notification_status",
	"aws_arczonalshift_zonal_autoshift_configuration",
	"aws_athena_named_query",
	"aws_autoscaling_group",
	"aws_cloudfront_cache_policy",
	"aws_cloudfront_continuous_deployment_policy",
	"aws_cloudfront_key_group",
	"aws_cloudfront_origin_access_identity",
	"aws_cloudfront_origin_request_policy",
	"aws_cloudfront_public_key",
	"aws_cloudfront_response_headers_policy",
	"aws_devopsguru_resource_collection",
	"aws_efs_mount_target",
	"aws_glue_security_configuration",
	"aws_inspector_assessment_target",
	"aws_kinesis_resource_policy",
	"aws_launch_configuration",
	"aws_macie2_account",
	"aws_msk_cluster_policy",
	"aws_notifications_event_rule",
	"aws_notifications_notification_hub",
	"aws_route53_cidr_collection",
	"aws_route53_resolver_dnssec_config",
	"aws_route53_resolver_query_log_config_association",
	"aws_route53profiles_resource_association",
	"aws_route53recoverycontrolconfig_routing_control",
	"aws_s3control_multi_region_access_point",
	"aws_s3files_file_system_policy",
	"aws_s3files_mount_target",
	"aws_s3tables_table_bucket_policy",
	"aws_s3vectors_vector_bucket_policy",
	"aws_securityhub_account",
	"aws_securityhub_configuration_policy",
	"aws_securityhub_finding_aggregator",
	"aws_securityhub_insight",
	"aws_securityhub_organization_configuration",
	"aws_securityhub_standards_subscription",
	"aws_sesv2_account_vdm_attributes",
	"aws_sfn_alias",
	"aws_shield_proactive_engagement",
	"aws_sns_topic_subscription",
	"aws_ssmcontacts_contact_channel",
	"aws_ssmcontacts_plan",
}

func init() {
	registerCohortStamp(taggableRemainder, untaggableRemainder, func(s testSchemaSource) {
		mergeCohortSchemas(s, testSchemaSource{
			// Registry-ratified REMAINDER ratification batch (#40, #44, #65):
			// caricature schemas for this batch admitted types, taggable per
			// live/survey-full.json own per-type taggable signal. See
			// live/e2e/estates/remainder/README.md.
			"aws_appconfig_application":                   taggedSchema("id", "arn"),
			"aws_appconfig_deployment_strategy":           taggedSchema("id", "arn"),
			"aws_appconfig_extension":                     taggedSchema("id", "arn"),
			"aws_appsync_api":                             taggedSchema("id", "arn"),
			"aws_arcregionswitch_plan":                    taggedSchema("id", "arn"),
			"aws_bcmdataexports_export":                   taggedSchema("id", "arn"),
			"aws_billing_view":                            taggedSchema("id", "arn"),
			"aws_ce_anomaly_monitor":                      taggedSchema("id", "arn"),
			"aws_ce_anomaly_subscription":                 taggedSchema("id", "arn"),
			"aws_ce_cost_category":                        taggedSchema("id", "arn"),
			"aws_chatbot_slack_channel_configuration":     taggedSchema("id", "arn"),
			"aws_cleanrooms_collaboration":                taggedSchema("id", "arn"),
			"aws_cleanrooms_configured_table":             taggedSchema("id", "arn"),
			"aws_cleanrooms_membership":                   taggedSchema("id", "arn"),
			"aws_cloud9_environment_ec2":                  taggedSchema("id", "arn"),
			"aws_cloudtrail":                              taggedSchema("id", "arn"),
			"aws_cloudtrail_event_data_store":             taggedSchema("id", "arn"),
			"aws_codegurureviewer_repository_association": taggedSchema("id", "arn"),
			"aws_cur_report_definition":                   taggedSchema("id", "arn"),
			"aws_datapipeline_pipeline":                   taggedSchema("id", "arn"),
			"aws_datazone_domain":                         taggedSchema("id", "arn"),
			"aws_detective_graph":                         taggedSchema("id", "arn"),
			"aws_dlm_lifecycle_policy":                    taggedSchema("id", "arn"),
			"aws_dsql_cluster":                            taggedSchema("id", "arn"),
			"aws_dx_connection":                           taggedSchema("id", "arn"),
			"aws_dx_gateway":                              taggedSchema("id", "arn"),
			"aws_dx_lag":                                  taggedSchema("id", "arn"),
			"aws_dx_private_virtual_interface":            taggedSchema("id", "arn"),
			"aws_dx_public_virtual_interface":             taggedSchema("id", "arn"),
			"aws_dx_transit_virtual_interface":            taggedSchema("id", "arn"),
			"aws_ec2_instance_connect_endpoint":           taggedSchema("id", "arn"),
			"aws_ec2_local_gateway_route_table":           taggedSchema("id", "arn"),
			"aws_ec2_local_gateway_route_table_virtual_interface_group_association": taggedSchema("id", "arn"),
			"aws_ec2_local_gateway_route_table_vpc_association":                     taggedSchema("id", "arn"),
			"aws_ec2_network_insights_access_scope":                                 taggedSchema("id", "arn"),
			"aws_ec2_network_insights_analysis":                                     taggedSchema("id", "arn"),
			"aws_ec2_network_insights_path":                                         taggedSchema("id", "arn"),
			"aws_ec2_traffic_mirror_filter":                                         taggedSchema("id", "arn"),
			"aws_ec2_traffic_mirror_session":                                        taggedSchema("id", "arn"),
			"aws_ec2_traffic_mirror_target":                                         taggedSchema("id", "arn"),
			"aws_ecs_daemon_task_definition":                                        taggedSchema("id", "arn"),
			"aws_ecs_express_gateway_service":                                       taggedSchema("id", "arn"),
			"aws_ecs_task_definition":                                               taggedSchema("id", "arn"),
			"aws_egress_only_internet_gateway":                                      taggedSchema("id", "arn"),
			"aws_elb":                                                               taggedSchema("id", "arn"),
			"aws_evidently_project":                                                 taggedSchema("id", "arn"),
			"aws_evidently_segment":                                                 taggedSchema("id", "arn"),
			"aws_fis_experiment_template":                                           taggedSchema("id", "arn"),
			"aws_fms_resource_set":                                                  taggedSchema("id", "arn"),
			"aws_gamelift_alias":                                                    taggedSchema("id", "arn"),
			"aws_gamelift_build":                                                    taggedSchema("id", "arn"),
			"aws_gamelift_fleet":                                                    taggedSchema("id", "arn"),
			"aws_gamelift_script":                                                   taggedSchema("id", "arn"),
			"aws_glue_data_quality_ruleset":                                         taggedSchema("id", "arn"),
			"aws_glue_schema":                                                       taggedSchema("id", "arn"),
			"aws_glue_workflow":                                                     taggedSchema("id", "arn"),
			"aws_iam_saml_provider":                                                 taggedSchema("id", "arn"),
			"aws_iam_virtual_mfa_device":                                            taggedSchema("id", "arn"),
			"aws_imagebuilder_component":                                            taggedSchema("id", "arn"),
			"aws_imagebuilder_container_recipe":                                     taggedSchema("id", "arn"),
			"aws_imagebuilder_distribution_configuration":                           taggedSchema("id", "arn"),
			"aws_imagebuilder_image":                                                taggedSchema("id", "arn"),
			"aws_imagebuilder_image_pipeline":                                       taggedSchema("id", "arn"),
			"aws_imagebuilder_image_recipe":                                         taggedSchema("id", "arn"),
			"aws_imagebuilder_infrastructure_configuration":                         taggedSchema("id", "arn"),
			"aws_imagebuilder_lifecycle_policy":                                     taggedSchema("id", "arn"),
			"aws_imagebuilder_workflow":                                             taggedSchema("id", "arn"),
			"aws_inspector_assessment_template":                                     taggedSchema("id", "arn"),
			"aws_internetmonitor_monitor":                                           taggedSchema("id", "arn"),
			"aws_invoicing_invoice_unit":                                            taggedSchema("id", "arn"),
			"aws_kinesis_analytics_application":                                     taggedSchema("id", "arn"),
			"aws_lb_listener_rule":                                                  taggedSchema("id", "arn"),
			"aws_lb_trust_store":                                                    taggedSchema("id", "arn"),
			"aws_m2_application":                                                    taggedSchema("id", "arn"),
			"aws_m2_environment":                                                    taggedSchema("id", "arn"),
			"aws_mailmanager_rule_set":                                              taggedSchema("id", "arn"),
			"aws_mailmanager_traffic_policy":                                        taggedSchema("id", "arn"),
			"aws_msk_replicator":                                                    taggedSchema("id", "arn"),
			"aws_msk_vpc_connection":                                                taggedSchema("id", "arn"),
			"aws_mwaa_environment":                                                  taggedSchema("id", "arn"),
			"aws_notifications_notification_configuration":                          taggedSchema("id", "arn"),
			"aws_notificationscontacts_email_contact":                               taggedSchema("id", "arn"),
			"aws_oam_link":                                                          taggedSchema("id", "arn"),
			"aws_oam_sink":                                                          taggedSchema("id", "arn"),
			"aws_observabilityadmin_s3_table_integration":                           taggedSchema("id", "arn"),
			"aws_observabilityadmin_telemetry_pipeline":                             taggedSchema("id", "arn"),
			"aws_odb_cloud_autonomous_vm_cluster":                                   taggedSchema("id", "arn"),
			"aws_odb_cloud_exadata_infrastructure":                                  taggedSchema("id", "arn"),
			"aws_odb_cloud_vm_cluster":                                              taggedSchema("id", "arn"),
			"aws_odb_network":                                                       taggedSchema("id", "arn"),
			"aws_odb_network_peering_connection":                                    taggedSchema("id", "arn"),
			"aws_paymentcryptography_key":                                           taggedSchema("id", "arn"),
			"aws_pinpointsmsvoicev2_configuration_set":                              taggedSchema("id", "arn"),
			"aws_pinpointsmsvoicev2_opt_out_list":                                   taggedSchema("id", "arn"),
			"aws_pinpointsmsvoicev2_phone_number":                                   taggedSchema("id", "arn"),
			"aws_pinpointsmsvoicev2_pool":                                           taggedSchema("id", "arn"),
			"aws_prometheus_rule_group_namespace":                                   taggedSchema("id", "arn"),
			"aws_ram_permission":                                                    taggedSchema("id", "arn"),
			"aws_ram_resource_share":                                                taggedSchema("id", "arn"),
			"aws_rbin_rule":                                                         taggedSchema("id", "arn"),
			"aws_resiliencehub_resiliency_policy":                                   taggedSchema("id", "arn"),
			"aws_resiliencehubv2_policy":                                            taggedSchema("id", "arn"),
			"aws_rolesanywhere_profile":                                             taggedSchema("id", "arn"),
			"aws_rolesanywhere_trust_anchor":                                        taggedSchema("id", "arn"),
			"aws_s3_directory_bucket":                                               taggedSchema("id", "arn"),
			"aws_s3control_bucket":                                                  taggedSchema("id", "arn"),
			"aws_s3files_access_point":                                              taggedSchema("id", "arn"),
			"aws_s3files_file_system":                                               taggedSchema("id", "arn"),
			"aws_s3tables_table_bucket":                                             taggedSchema("id", "arn"),
			"aws_s3vectors_index":                                                   taggedSchema("id", "arn"),
			"aws_s3vectors_vector_bucket":                                           taggedSchema("id", "arn"),
			"aws_schemas_discoverer":                                                taggedSchema("id", "arn"),
			"aws_securitylake_data_lake":                                            taggedSchema("id", "arn"),
			"aws_securitylake_subscriber":                                           taggedSchema("id", "arn"),
			"aws_service_discovery_http_namespace":                                  taggedSchema("id", "arn"),
			"aws_service_discovery_public_dns_namespace":                            taggedSchema("id", "arn"),
			"aws_service_discovery_service":                                         taggedSchema("id", "arn"),
			"aws_sesv2_configuration_set":                                           taggedSchema("id", "arn"),
			"aws_sesv2_dedicated_ip_pool":                                           taggedSchema("id", "arn"),
			"aws_sesv2_email_identity":                                              taggedSchema("id", "arn"),
			"aws_sesv2_tenant":                                                      taggedSchema("id", "arn"),
			"aws_shield_protection":                                                 taggedSchema("id", "arn"),
			"aws_ssmcontacts_contact":                                               taggedSchema("id", "arn"),
			"aws_ssmcontacts_rotation":                                              taggedSchema("id", "arn"),
			"aws_ssmincidents_replication_set":                                      taggedSchema("id", "arn"),
			"aws_ssmincidents_response_plan":                                        taggedSchema("id", "arn"),
			"aws_ssmquicksetup_configuration_manager":                               taggedSchema("id", "arn"),
			"aws_verifiedaccess_endpoint":                                           taggedSchema("id", "arn"),
			"aws_verifiedaccess_instance":                                           taggedSchema("id", "arn"),
			"aws_verifiedaccess_trust_provider":                                     taggedSchema("id", "arn"),
			"aws_verifiedpermissions_policy_store":                                  taggedSchema("id", "arn"),
			"aws_vpc_block_public_access_exclusion":                                 taggedSchema("id", "arn"),
			"aws_vpc_encryption_control":                                            taggedSchema("id", "arn"),
			"aws_vpc_route_server":                                                  taggedSchema("id", "arn"),
			"aws_vpc_route_server_endpoint":                                         taggedSchema("id", "arn"),
			"aws_vpc_route_server_peer":                                             taggedSchema("id", "arn"),
			"aws_vpn_concentrator":                                                  taggedSchema("id", "arn"),
			"aws_appconfig_extension_association":                                   untaggedSchema("id"),
			"aws_appsync_api_cache":                                                 untaggedSchema("id"),
			"aws_appsync_domain_name_api_association":                               untaggedSchema("id"),
			"aws_arczonalshift_autoshift_observer_notification_status":              untaggedSchema("id"),
			"aws_arczonalshift_zonal_autoshift_configuration":                       untaggedSchema("id"),
			"aws_athena_named_query":                                                untaggedSchema("id"),
			"aws_autoscaling_group":                                                 untaggedSchema("id"),
			"aws_cloudfront_cache_policy":                                           untaggedSchema("id"),
			"aws_cloudfront_continuous_deployment_policy":                           untaggedSchema("id"),
			"aws_cloudfront_key_group":                                              untaggedSchema("id"),
			"aws_cloudfront_origin_access_identity":                                 untaggedSchema("id"),
			"aws_cloudfront_origin_request_policy":                                  untaggedSchema("id"),
			"aws_cloudfront_public_key":                                             untaggedSchema("id"),
			"aws_cloudfront_response_headers_policy":                                untaggedSchema("id"),
			"aws_devopsguru_resource_collection":                                    untaggedSchema("id"),
			"aws_efs_mount_target":                                                  untaggedSchema("id"),
			"aws_glue_security_configuration":                                       untaggedSchema("id"),
			"aws_inspector_assessment_target":                                       untaggedSchema("id"),
			"aws_kinesis_resource_policy":                                           untaggedSchema("id"),
			"aws_launch_configuration":                                              untaggedSchema("id"),
			"aws_macie2_account":                                                    untaggedSchema("id"),
			"aws_msk_cluster_policy":                                                untaggedSchema("id"),
			"aws_notifications_event_rule":                                          untaggedSchema("id"),
			"aws_notifications_notification_hub":                                    untaggedSchema("id"),
			"aws_route53_cidr_collection":                                           untaggedSchema("id"),
			"aws_route53_resolver_dnssec_config":                                    untaggedSchema("id"),
			"aws_route53_resolver_query_log_config_association":                     untaggedSchema("id"),
			"aws_route53profiles_resource_association":                              untaggedSchema("id"),
			"aws_route53recoverycontrolconfig_routing_control":                      untaggedSchema("id"),
			"aws_s3control_multi_region_access_point":                               untaggedSchema("id"),
			"aws_s3files_file_system_policy":                                        untaggedSchema("id"),
			"aws_s3files_mount_target":                                              untaggedSchema("id"),
			"aws_s3tables_table_bucket_policy":                                      untaggedSchema("id"),
			"aws_s3vectors_vector_bucket_policy":                                    untaggedSchema("id"),
			"aws_securityhub_account":                                               untaggedSchema("id"),
			"aws_securityhub_configuration_policy":                                  untaggedSchema("id"),
			"aws_securityhub_finding_aggregator":                                    untaggedSchema("id"),
			"aws_securityhub_insight":                                               untaggedSchema("id"),
			"aws_securityhub_organization_configuration":                            untaggedSchema("id"),
			"aws_securityhub_standards_subscription":                                untaggedSchema("id"),
			"aws_sesv2_account_vdm_attributes":                                      untaggedSchema("id"),
			"aws_sfn_alias":                                                         untaggedSchema("id"),
			"aws_shield_proactive_engagement":                                       untaggedSchema("id"),
			"aws_sns_topic_subscription":                                            untaggedSchema("id"),
			"aws_ssmcontacts_contact_channel":                                       untaggedSchema("id"),
			"aws_ssmcontacts_plan":                                                  untaggedSchema("id"),
		})
	})
}
