// Copyright (c) The OpenTofu Authors
// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2023 HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package stamp

// The issue #245 composite-bucket ratification batch's slice of internal/live/stamp's
// three pinned test collections: which of the batch's admitted types carry tags, which
// do not, and the caricature schema each one is checked against. Taggability for every
// row below is live/survey-full.json's own signals.taggable, read off the real provider
// schema by tools/survey-gen - not a fresh guess. Registered by init below; see
// contributing/LIVE-TABLES.md.
var taggableComposite245 = []string{
	"aws_budgets_budget",
	"aws_cloudwatch_contributor_managed_insight_rule",
	"aws_config_aggregate_authorization",
	"aws_directory_service_region",
	"aws_pinpointsmsvoicev2_sender_id",
	"aws_sagemaker_hub_content_reference",
	"aws_schemas_schema",
}

var untaggableComposite245 = []string{
	"aws_accessanalyzer_archive_rule",
	"aws_amplify_backend_environment",
	"aws_apprunner_custom_domain_association",
	"aws_appstream_user_stack_association",
	"aws_athena_prepared_statement",
	"aws_autoscaling_lifecycle_hook",
	"aws_autoscaling_policy",
	"aws_autoscaling_schedule",
	"aws_cloudfrontkeyvaluestore_key",
	"aws_codecommit_approval_rule_template_association",
	"aws_connect_lambda_function_association",
	"aws_connect_phone_number_contact_flow_association",
	"aws_datazone_asset_type",
	"aws_directory_service_conditional_forwarder",
	"aws_directory_service_trust",
	"aws_ebs_fast_snapshot_restore",
	"aws_fis_target_account_configuration",
	"aws_iot_thing_group_membership",
	"aws_lakeformation_lf_tag",
	"aws_lakeformation_lf_tag_expression",
	"aws_lambda_function_scaling_config",
	"aws_lambda_provisioned_concurrency_config",
	"aws_licensemanager_association",
	"aws_networkmanager_attachment_routing_policy_label",
	"aws_notifications_managed_notification_account_contact_association",
	"aws_notifications_managed_notification_additional_channel_association",
	"aws_notifications_organizational_unit_association",
	"aws_opensearch_authorize_vpc_endpoint_access",
	"aws_opensearch_package_association",
	"aws_organizations_delegated_administrator",
	"aws_pinpointsmsvoicev2_event_destination",
	"aws_ram_resource_association",
	"aws_redshiftserverless_custom_domain_association",
	"aws_resourcegroups_resource",
	"aws_route53_vpc_association_authorization",
	"aws_s3_bucket_intelligent_tiering_configuration",
	"aws_s3control_object_lambda_access_point",
	"aws_s3control_object_lambda_access_point_policy",
	"aws_servicecatalog_budget_resource_association",
	"aws_servicecatalog_tag_option_resource_association",
	"aws_servicequotas_service_quota",
	"aws_ses_identity_policy",
	"aws_sesv2_email_identity_policy",
	"aws_sesv2_tenant_resource_association",
	"aws_ssoadmin_managed_policy_attachment",
	"aws_ssoadmin_region",
	"aws_synthetics_group_association",
	"aws_transfer_access",
	"aws_verifiedaccess_instance_trust_provider_attachment",
	"aws_vpc_security_group_vpc_association",
	"aws_wafv2_web_acl_association",
	"aws_workmail_domain",
}

func init() {
	registerCohortStamp(taggableComposite245, untaggableComposite245, func(s testSchemaSource) {
		mergeCohortSchemas(s, testSchemaSource{
			"aws_budgets_budget":                                                    taggedSchema("account_id", "name"),
			"aws_cloudwatch_contributor_managed_insight_rule":                       taggedSchema("resource_arn", "template_name"),
			"aws_config_aggregate_authorization":                                    taggedSchema("account_id", "authorized_aws_region"),
			"aws_directory_service_region":                                          taggedSchema("directory_id", "region_name"),
			"aws_pinpointsmsvoicev2_sender_id":                                      taggedSchema("sender_id", "iso_country_code"),
			"aws_sagemaker_hub_content_reference":                                   taggedSchema("hub_name", "hub_content_name"),
			"aws_schemas_schema":                                                    taggedSchema("name", "registry_name"),
			"aws_accessanalyzer_archive_rule":                                       untaggedSchema("analyzer_name", "rule_name"),
			"aws_amplify_backend_environment":                                       untaggedSchema("app_id", "environment_name"),
			"aws_apprunner_custom_domain_association":                               untaggedSchema("domain_name", "service_arn"),
			"aws_appstream_user_stack_association":                                  untaggedSchema("user_name", "authentication_type", "stack_name"),
			"aws_athena_prepared_statement":                                         untaggedSchema("workgroup", "name"),
			"aws_autoscaling_lifecycle_hook":                                        untaggedSchema("autoscaling_group_name", "name"),
			"aws_autoscaling_policy":                                                untaggedSchema("autoscaling_group_name", "name"),
			"aws_autoscaling_schedule":                                              untaggedSchema("autoscaling_group_name", "scheduled_action_name"),
			"aws_cloudfrontkeyvaluestore_key":                                       untaggedSchema("key_value_store_arn", "key"),
			"aws_codecommit_approval_rule_template_association":                     untaggedSchema("approval_rule_template_name", "repository_name"),
			"aws_connect_lambda_function_association":                               untaggedSchema("instance_id", "function_arn"),
			"aws_connect_phone_number_contact_flow_association":                     untaggedSchema("phone_number_id", "instance_id", "contact_flow_id"),
			"aws_datazone_asset_type":                                               untaggedSchema("domain_identifier", "name"),
			"aws_directory_service_conditional_forwarder":                           untaggedSchema("directory_id", "remote_domain_name"),
			"aws_directory_service_trust":                                           untaggedSchema("directory_id", "remote_domain_name"),
			"aws_ebs_fast_snapshot_restore":                                         untaggedSchema("availability_zone", "snapshot_id"),
			"aws_fis_target_account_configuration":                                  untaggedSchema("account_id", "experiment_template_id"),
			"aws_iot_thing_group_membership":                                        untaggedSchema("thing_group_name", "thing_name"),
			"aws_lakeformation_lf_tag":                                              untaggedSchema("catalog_id", "key"),
			"aws_lakeformation_lf_tag_expression":                                   untaggedSchema("name", "catalog_id"),
			"aws_lambda_function_scaling_config":                                    untaggedSchema("function_name", "qualifier"),
			"aws_lambda_provisioned_concurrency_config":                             untaggedSchema("function_name", "qualifier"),
			"aws_licensemanager_association":                                        untaggedSchema("resource_arn", "license_configuration_arn"),
			"aws_networkmanager_attachment_routing_policy_label":                    untaggedSchema("core_network_id", "attachment_id"),
			"aws_notifications_managed_notification_account_contact_association":    untaggedSchema("managed_notification_configuration_arn", "contact_identifier"),
			"aws_notifications_managed_notification_additional_channel_association": untaggedSchema("managed_notification_arn", "channel_arn"),
			"aws_notifications_organizational_unit_association":                     untaggedSchema("notification_configuration_arn", "organizational_unit_id"),
			"aws_opensearch_authorize_vpc_endpoint_access":                          untaggedSchema("domain_name", "account"),
			"aws_opensearch_package_association":                                    untaggedSchema("domain_name", "package_id"),
			"aws_organizations_delegated_administrator":                             untaggedSchema("account_id", "service_principal"),
			"aws_pinpointsmsvoicev2_event_destination":                              untaggedSchema("configuration_set_name", "event_destination_name"),
			"aws_ram_resource_association":                                          untaggedSchema("resource_share_arn", "resource_arn"),
			"aws_redshiftserverless_custom_domain_association":                      untaggedSchema("workgroup_name", "custom_domain_name"),
			"aws_resourcegroups_resource":                                           untaggedSchema("group_arn", "resource_arn"),
			"aws_route53_vpc_association_authorization":                             untaggedSchema("zone_id", "vpc_id"),
			"aws_s3_bucket_intelligent_tiering_configuration":                       untaggedSchema("bucket", "name"),
			"aws_s3control_object_lambda_access_point":                              untaggedSchema("account_id", "name"),
			"aws_s3control_object_lambda_access_point_policy":                       untaggedSchema("account_id", "name"),
			"aws_servicecatalog_budget_resource_association":                        untaggedSchema("budget_name", "resource_id"),
			"aws_servicecatalog_tag_option_resource_association":                    untaggedSchema("tag_option_id", "resource_id"),
			"aws_servicequotas_service_quota":                                       untaggedSchema("service_code", "quota_code"),
			"aws_ses_identity_policy":                                               untaggedSchema("identity", "name"),
			"aws_sesv2_email_identity_policy":                                       untaggedSchema("email_identity", "policy_name"),
			"aws_sesv2_tenant_resource_association":                                 untaggedSchema("tenant_name", "resource_arn"),
			"aws_ssoadmin_managed_policy_attachment":                                untaggedSchema("managed_policy_arn", "permission_set_arn", "instance_arn"),
			"aws_ssoadmin_region":                                                   untaggedSchema("instance_arn", "region_name"),
			"aws_synthetics_group_association":                                      untaggedSchema("canary_arn", "group_name"),
			"aws_transfer_access":                                                   untaggedSchema("server_id", "external_id"),
			"aws_verifiedaccess_instance_trust_provider_attachment":                 untaggedSchema("verifiedaccess_instance_id", "verifiedaccess_trust_provider_id"),
			"aws_vpc_security_group_vpc_association":                                untaggedSchema("security_group_id", "vpc_id"),
			"aws_wafv2_web_acl_association":                                         untaggedSchema("web_acl_arn", "resource_arn"),
			"aws_workmail_domain":                                                   untaggedSchema("organization_id", "domain_name"),
		})
	})
}
