// Copyright (c) The OpenTofu Authors
// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2023 HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package stamp

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/intentius/choudoufu/internal/live/flocitest"
	"github.com/intentius/choudoufu/internal/live/identity"
	"github.com/intentius/choudoufu/internal/live/pins"
)

// [taggableAdmittedTypes] and [untaggableAdmittedTypes] are hand-written, and
// they have to be: they are what makes a provider release that adds or
// removes a tags argument fail a test instead of silently changing
// SkipUntaggable behavior. But hand-written and unchecked are different
// things. Every entry's own comment cites live/survey-full.json's
// signals.taggable as where the classification came from, and until now that
// citation was a claim in a comment - a transcription step performed once per
// admission batch, by hand, over dozens of types, with nothing comparing the
// result back to the artifact it claims to come from. The last batch was
// verified twice, by hand, which is the tell.
//
// This closes that loop. The survey artifact is generated by tools/survey-gen
// straight off the pinned provider's GetProviderSchema response, so it is a
// genuinely external answer to "does this type have a settable tags map" -
// not a restatement of these lists, and not something these lists feed.
//
// It is deliberately a cross-check rather than a replacement. Deriving the
// lists from the artifact outright would delete every entry's ratification
// note, which is the evidence a reader needs to know a classification was
// looked at rather than guessed, and it would make
// TestUntaggableTypesMatchLimitationsDoc compare the artifact against a
// rendering of the same artifact. What is wanted is that adding a type to the
// wrong list becomes impossible, and that is what this does.
func TestPinnedTaggabilityMatchesTheSurvey(t *testing.T) {
	survey := readSurveyTaggable(t)

	classified := 0
	for _, tc := range []struct {
		types []string
		want  bool
		list  string
	}{
		{taggableAdmittedTypes, true, "taggableAdmittedTypes"},
		{untaggableAdmittedTypes, false, "untaggableAdmittedTypes"},
	} {
		for _, resourceType := range tc.types {
			got, ok := survey[resourceType]
			if !ok {
				// Not "skip": a pinned type the survey has never heard of
				// means one of the two is talking about a provider the other
				// is not, and silently passing over it is how a check ends up
				// seeing almost nothing.
				t.Errorf("%s pins %s, which live/survey-full.json does not carry at all", tc.list, resourceType)
				continue
			}
			classified++
			if got != tc.want {
				t.Errorf("%s pins %s, but live/survey-full.json's signals.taggable says %v (the provider's own schema, at v%s)",
					tc.list, resourceType, got, pins.AWSProviderVersion)
			}
		}
	}

	// The blindness guard. Every assertion above is inside a loop over the
	// pinned lists, so an empty or mis-parsed survey would produce a clean
	// pass with nothing compared. Both halves of the admission table have to
	// have been reached.
	if classified == 0 {
		t.Fatal("no pinned type was compared against the survey at all; the check is blind")
	}
	if want := len(taggableAdmittedTypes) + len(untaggableAdmittedTypes); classified != want {
		t.Errorf("compared %d pinned types, but %d are pinned", classified, want)
	}

	// And the pinned set has to be the admitted set, or this compares a
	// subset of what ships. TestTaggableSetCoversAdmissionTable owns that
	// equality; this only asserts the two tests are looking at the same
	// population, so a future split of the lists cannot leave this one
	// checking a fragment.
	admitted := 0
	for _, resourceType := range identity.AdmittedTypes() {
		if entry, ok := identity.LookupType(resourceType); ok && entry.RecordBacked {
			// Not AWS resources; they have no tags argument to have or lack.
			// Same exemption TestTaggableSetCoversAdmissionTable makes.
			continue
		}
		admitted++
	}
	if classified != admitted {
		t.Errorf("%d types are pinned and compared here, but the admission table carries %d non-record-backed types; the lists and the table have drifted", classified, admitted)
	}
}

// readSurveyTaggable reads live/survey-full.json's signals.taggable, keyed by
// resource type, and fails rather than degrading if the artifact is missing,
// unparseable, or pinned to a different provider release from the one every
// other measurement in this repository uses.
func readSurveyTaggable(t *testing.T) map[string]bool {
	t.Helper()

	path := filepath.Join(flocitest.RepoRoot(t), "live", "survey-full.json")
	content, err := os.ReadFile(path) //nolint:gosec // a fixed path in the checkout
	if err != nil {
		t.Fatalf("reading %s: %v", path, err)
	}

	var artifact struct {
		Provider        string `json:"provider"`
		ProviderVersion string `json:"provider_version"`
		Types           []struct {
			Type    string `json:"type"`
			Signals struct {
				Taggable bool `json:"taggable"`
			} `json:"signals"`
		} `json:"types"`
	}
	if err := json.Unmarshal(content, &artifact); err != nil {
		t.Fatalf("decoding %s: %v", path, err)
	}
	if artifact.ProviderVersion != pins.AWSProviderVersion {
		t.Fatalf("live/survey-full.json was generated against %s %s, but every measurement here is pinned to %s; regenerate it (just survey-full) before trusting this comparison",
			artifact.Provider, artifact.ProviderVersion, pins.AWSProviderVersion)
	}
	if len(artifact.Types) == 0 {
		t.Fatal("live/survey-full.json carries no type rows")
	}

	out := make(map[string]bool, len(artifact.Types))
	for _, row := range artifact.Types {
		out[row.Type] = row.Signals.Taggable
	}
	return out
}
